### ISSUE TITLE
Some devicelab tests are crashing locally, IosDevice.stopLoggingToSink NoSuchMethodError: The method 'kill' was called on null.

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#84819]
```
dart bin/run.dart -t new_gallery_ios__transition_perf
```
```
ext.cocoonRunTask: (-32000) Server error
NoSuchMethodError: The method 'kill' was called on null.
Receiver: null
Tried calling: kill()
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:63:5)
#1      IosDevice.stopLoggingToSink (package:flutter_devicelab/framework/devices.dart:882:21)
#2      _TaskRunner.run (package:flutter_devicelab/framework/framework.dart:165:24)
<asynchronous suspension>
#3      new _TaskRunner.<anonymous closure> (package:flutter_devicelab/framework/framework.dart:74:33)
<asynchronous suspension>
```
`_loggingProcess` is nullable, regression from https://github.com/flutter/flutter/pull/84008.
