### ISSUE TITLE
On beta channel for web: [cloud_firestore/unknown] NoSuchMethodError: '<Unexpected Null Value>'

### ISSUE THREAD

**Issue by SoftMaster19** [flutter/flutter#75463]
cloud firestore problem. 

Was working in 1.26.0-17.1.pre not working in 1.26.0-17.2.pre

Any access to a snapshot of a document in cloud fire store causes the exception.

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel beta, 1.26.0-17.2.pre, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-US)
    • Flutter version 1.26.0-17.2.pre at /Users/steve/Developer/flutter
    • Framework revision 79b49b9e10 (25 hours ago), 2021-02-03 15:33:39 -0800
    • Engine revision 2c527d6c7e
    • Dart version 2.12.0 (build 2.12.0-259.8.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/steve/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • Chrome (web)      • chrome         • web-javascript • Google Chrome 85.0.4183.102
```

</details>

index.js had these scripts:
```html
<script src="https://www.gstatic.com/firebasejs/7.24.0/firebase-app.js"></script>
<script src="https://www.gstatic.com/firebasejs/7.24.0/firebase-auth.js"></script>
<script src="https://www.gstatic.com/firebasejs/7.24.0/firebase-analytics.js"></script>
<script src="https://www.gstatic.com/firebasejs/7.17.1/firebase-firestore.js">
```
Changing to the latest or earlier (such as 7.20.0) has no effect.

**Comment by SoftMaster19** [comment]
Probably the same as #75466

When I ran flutter downgrade the version obtained was  version 1.25.0-8.3.pre

I can run my program with no problems with that version of the tool.

**Comment by TahaTesser** [comment]
Hi @SoftMaster19 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you
