### ISSUE TITLE
[WEB] NoSuchMethodError: The method 'toFilePath' was called on null.

### ISSUE THREAD

**Issue by AttSee** [flutter/flutter#52947]
Don't work with 1.15.17 to 1.16.1  
It's been experimented.

Downloading Web SDK... 19.0s
Launching lib/main.dart on Chrome in debug mode...

ERROR - 2020-03-20 12:31:23.634307
GET /dwds/src/injected/client.js
Error thrown by handler.
NoSuchMethodError: The method 'toFilePath' was called on null.
Receiver: null
Tried calling: toFilePath()
dart:core Object.noSuchMethod
createInjectedHandler.. (package:dwds/src/handlers/injected_handler.dart:35:39)

flutter doctor -v
Waiting for another flutter command to release the startup lock...
[✓] Flutter (Channel dev, v1.16.1, on Linux, locale en_US.UTF-8)
• Flutter version 1.16.1 at /home/attia/Porgram/flutter
• Framework revision e6b0f5f (33 hours ago), 2020-03-18 21:56:02 -0400
• Engine revision 216c420a2c
• Dart version 2.8.0 (build 2.8.0-dev.15.0 96cf889e6b)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
• Android SDK at /home/attia/Android/Sdk
• Android NDK location not configured (optional; useful for native profiling
support)
• Platform android-29, build-tools 29.0.3
• Java binary at: /home/attia/Porgram/android-studio/jre/bin/java
• Java version OpenJDK Runtime Environment (build
1.8.0_242-release-1644-b3-6222593)
• All Android licenses accepted.

[✓] Chrome - develop for the web
• Chrome at google-chrome

[✓] Android Studio (version 4.0)
• Android Studio at /home/attia/Porgram/android-studio
• Flutter plugin version 44.0.3
• Dart plugin version 193.6494.35
• Java version OpenJDK Runtime Environment (build
1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.43.1)
• VS Code at /usr/share/code
• Flutter extension version 3.8.1

[✓] Connected device (2 available)
• Chrome • chrome • web-javascript • Google Chrome 80.0.3987.149
• Web Server • web-server • web-javascript • Flutter Tools

**Comment by TahaTesser** [comment]
duplicate of [#52914](https://github.com/flutter/flutter/issues/52914)
