### ISSUE TITLE
Error when running Flutter web with `--web-experimental-hot-reload` after upgrading to Flutter 3.32.0 (Hive: `TypeError: dart.nullCheck(...)[$open] is not a function`)

### ISSUE THREAD

**Issue by AliKarimiENT** [flutter/flutter#169222]
### Steps to reproduce

- **Flutter version:** 3.32.0 (channel stable, revision be698c48a6, Dart 3.8.0)
- **Engine revision:** 1881800949
- **DevTools:** 2.45.1
- **OS:** macOS
- **Hive version:** _(please insert exact version here)

1. Upgrade Flutter to version 3.32.0.
2. Ensure `launch.json` contains:
    ```json
    {
      "name": "frontend-app",
      "request": "launch",
      "type": "dart",
      "args": ["--web-experimental-hot-reload"],
      "program": "lib/main.dart"
    }
    ```
3. Run the app with:
    ```
    flutter run -d chrome --web-experimental-hot-reload
    ```
4. Observe the error below.

### Expected results

- The app should run with `--web-experimental-hot-reload` enabled, without error.

### Actual results

Error when running Flutter web with `--web-experimental-hot-reload` after upgrading to Flutter 3.32.0 (Hive: `TypeError: dart.nullCheck(...)[$open] is not a function`)

- The same code works without `--web-experimental-hot-reload`.
- This issue started after upgrading Flutter to 3.32.0.
- Please specify if this is a known incompatibility with Hive and the new Flutter version or if there are any recommended workarounds.

### `main.dart`
```dart
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  setPathUrlStrategy();
  await initializeDependencies();
  await initFirebase();

  await Hive.initFlutter();

  runApp(
    // ...
  );
}
```

### `launch.json`
```json
{
  "name": "frontend-app",
  "request": "launch",
  "type": "dart",
  "args": ["--web-experimental-hot-reload"],
  "program": "lib/main.dart"
}
```

### Logs

<details open><summary>Logs</summary>

```console
[alikarimi@Alis-MacBook-Pro frontend-app % flutter run -d chrome --web-experimental-hot-reload
Launching lib/main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...             13.4s
This app is linked to the debug service: ws://127.0.0.1:63589/caPMdTxuWNw=/ws
Debug service listening on ws://127.0.0.1:63589/caPMdTxuWNw=/ws

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

A Dart VM Service on Chrome is available at: http://127.0.0.1:63589/caPMdTxuWNw=
Starting application from main method in: org-dartlang-app:/web_entrypoint.dart.
The Flutter DevTools debugger and profiler on Chrome is available at: http://127.0.0.1:9102?uri=http://127.0.0.1:63589/caPMdTxuWNw=
TypeError: dart.nullCheck(...)[$open] is not a function
package:hive/src/box_collection/box_collection_stub.dart.lib.js 3328:77           <fn>
dart:sdk_internal 44282:13                                                        <fn>
dart:sdk_internal 44292:7                                                         <fn>
dart:sdk_internal 44240:5                                                         _asyncStartSync
package:hive/src/box_collection/box_collection_stub.dart.lib.js 3366:20           open
package:hive/src/box_collection/box_collection_stub.dart.lib.js 6608:55           <fn>
dart:sdk_internal 44282:13                                                        <fn>
dart:sdk_internal 44292:7                                                         <fn>
dart:sdk_internal 44240:5                                                         _asyncStartSync
package:hive/src/box_collection/box_collection_stub.dart.lib.js 6672:20           [_openBox]
package:hive/src/box_collection/box_collection_stub.dart.lib.js 6694:54           <fn>
dart:sdk_internal 44282:13                                                        <fn>
dart:sdk_internal 44292:7                                                         <fn>
dart:sdk_internal 44240:5                                                         _asyncStartSync
package:hive/src/box_collection/box_collection_stub.dart.lib.js 6706:20           openBox
package:langujet/features/home/presentation/widgets/banner.dart.lib.js 93260:50   <fn>
dart:sdk_internal 44282:13                                                        <fn>
dart:sdk_internal 44292:7                                                         <fn>
dart:sdk_internal 44240:5                                                         _asyncStartSync
package:langujet/features/home/presentation/widgets/banner.dart.lib.js 93278:20   openBox
package:langujet/features/home/presentation/widgets/banner.dart.lib.js 93312:45   <fn>
dart:sdk_internal 44282:13                                                        <fn>
dart:sdk_internal 44292:7                                                         <fn>
dart:sdk_internal 44240:5                                                         _asyncStartSync
package:langujet/features/home/presentation/widgets/banner.dart.lib.js 93325:20   readItem
package:langujet/features/home/presentation/widgets/banner.dart.lib.js 93442:36   <fn>
dart:sdk_internal 44282:13                                                        <fn>
dart:sdk_internal 44292:7                                                         <fn>
dart:sdk_internal 44240:5                                                         _asyncStartSync
package:langujet/features/home/presentation/widgets/banner.dart.lib.js 93451:20   getAccessToken
package:langujet/features/home/presentation/widgets/banner.dart.lib.js 74442:185  <fn>
dart:sdk_internal 44282:13                                                        <fn>
dart:sdk_internal 44292:7                                                         <fn>
dart:sdk_internal 44240:5                                                         _asyncStartSync
package:langujet/features/home/presentation/widgets/banner.dart.lib.js 74458:20   readTokens
package:langujet/main.dart.lib.js 232:185                                         <fn>
dart:sdk_internal 44282:13                                                        <fn>
dart:sdk_internal 44292:7                                                         <fn>
dart:sdk_internal 44259:42                                                        <fn>
dart:sdk_internal 43193:59                                                        runUnary
dart:sdk_internal 35859:26                                                        handleValue
dart:sdk_internal 36558:47                                                        handleValueCallback
dart:sdk_internal 36596:15                                                        _propagateToListeners
dart:sdk_internal 36415:21                                                        [_completeWithValue]
dart:sdk_internal 36461:33                                                        callback
dart:sdk_internal 44642:13                                                        _microtaskLoop
dart:sdk_internal 44649:13                                                        _startMicrotaskLoop
dart:sdk_internal 3792:46                                                         tear
dart:sdk_internal 36899:9                                                         <fn>
TypeError: dart.nullCheck(...)[$open] is not a function
package:hive/src/box_collection/box_collection_stub.dart.lib.js 3328:77           <fn>
dart:sdk_internal 44282:13                                                        <fn>
dart:sdk_internal 44292:7                                                         <fn>
dart:sdk_internal 44240:5                                                         _asyncStartSync
package:hive/src/box_collection/box_collection_stub.dart.lib.js 3366:20           open
package:hive/src/box_collection/box_collection_stub.dart.lib.js 6608:55           <fn>
dart:sdk_internal 44282:13                                                        <fn>
dart:sdk_internal 44292:7                                                         <fn>
dart:sdk_internal 44240:5                                                         _asyncStartSync
package:hive/src/box_collection/box_collection_stub.dart.lib.js 6672:20           [_openBox]
package:hive/src/box_collection/box_collection_stub.dart.lib.js 6694:54           <fn>
dart:sdk_internal 44282:13                                                        <fn>
dart:sdk_internal 44292:7                                                         <fn>
dart:sdk_internal 44240:5                                                         _asyncStartSync
package:hive/src/box_collection/box_collection_stub.dart.lib.js 6706:20           openBox
package:langujet/features/home/presentation/widgets/banner.dart.lib.js 93260:50   <fn>
dart:sdk_internal 44282:13                                                        <fn>
dart:sdk_internal 44292:7                                                         <fn>
dart:sdk_internal 44240:5                                                         _asyncStartSync
package:langujet/features/home/presentation/widgets/banner.dart.lib.js 93278:20   openBox
package:langujet/features/home/presentation/widgets/banner.dart.lib.js 93312:45   <fn>
dart:sdk_internal 44282:13                                                        <fn>
dart:sdk_internal 44292:7                                                         <fn>
dart:sdk_internal 44240:5                                                         _asyncStartSync
package:langujet/features/home/presentation/widgets/banner.dart.lib.js 93325:20   readItem
package:langujet/features/home/presentation/widgets/banner.dart.lib.js 93442:36   <fn>
dart:sdk_internal 44282:13                                                        <fn>
dart:sdk_internal 44292:7                                                         <fn>
dart:sdk_internal 44240:5                                                         _asyncStartSync
package:langujet/features/home/presentation/widgets/banner.dart.lib.js 93451:20   getAccessToken
package:langujet/features/home/presentation/widgets/banner.dart.lib.js 74442:185  <fn>
dart:sdk_internal 44282:13                                                        <fn>
dart:sdk_internal 44292:7                                                         <fn>
dart:sdk_internal 44240:5                                                         _asyncStartSync
package:langujet/features/home/presentation/widgets/banner.dart.lib.js 74458:20   readTokens
package:langujet/main.dart.lib.js 232:185                                         <fn>
dart:sdk_internal 44282:13                                                        <fn>
dart:sdk_internal 44292:7                                                         <fn>
dart:sdk_internal 44259:42                                                        <fn>
dart:sdk_internal 43193:59                                                        runUnary
dart:sdk_internal 35859:26                                                        handleValue
dart:sdk_internal 36558:47                                                        handleValueCallback
dart:sdk_internal 36596:15                                                        _propagateToListeners
dart:sdk_internal 36415:21                                                        [_completeWithValue]
dart:sdk_internal 36461:33                                                        callback
dart:sdk_internal 44642:13                                                        _microtaskLoop
dart:sdk_internal 44649:13                                                        _startMicrotaskLoop
dart:sdk_internal 3792:46              
]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by AliKarimiENT** [comment]
> I've got the same error, it is because I use  if (!Hive.isBoxOpen('MyBoxName'))  , in my data layer,[edit: no... even if I use Hive.openBox('boxname') in the main() diectly, I still get the error]  this issue only uccurs when I use   "--web-experimental-hot-reload" in my vscode config.json, the config is exactly the same as above. when I use regular command run, it works fine, IDK, 

Yes exactly I have the same issue

**Comment by tirth-patel-nc** [comment]
the issue is related to the hive package itself then so you will need to file the issue in dedicated repo.

**Comment by AliKarimiENT** [comment]
> the issue is related to the hive package itself then so you will need to file the issue in dedicated repo.

Yes I reported it to the hive_ce package and updated the fork of the main app.
And they also told us it's related to the flutter 😂😁

**Comment by Rexios80** [comment]
@tirth-patel-nc How is this caused by Hive if the same code runs without hot reload enabled?

**Comment by tirth-patel-nc** [comment]
# Triage Report

I was **not** able to reproduce the issue using the official sample available for [hive_ce_flutter](https://github.com/IO-Design-Team/hive_ce/tree/main/hive_flutter/example/lib) on either the `stable (3.32.0)` or `master (3.33.0-1.0.pre.186)` channels.

<img width="975" alt="Image" src="https://github.com/user-attachments/assets/a9c3c454-d47a-41cb-bd81-c028e511e416" />

<details>
<summary>Code Sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:hive_ce_flutter/hive_flutter.dart';

const counterBox = 'counter';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Hive.initFlutter();
  final box = await Hive.openBox(counterBox);
  if (box.isEmpty) {
    await box.add(0);
  }
  runApp(const MaterialApp(home: HiveCounterApp()));
}

class HiveCounterApp extends StatelessWidget {
  const HiveCounterApp({super.key});

  @override
  Widget build(BuildContext context) {
    final box = Hive.box(counterBox);

    return Scaffold(
      appBar: AppBar(title: const Text('Hive CE Example')),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            const Text('You have pushed the button this many times:'),
            ValueListenableBuilder(
              valueListenable: box.listenable(),
              builder: (context, box, widget) {
                return Text(
                  box.getAt(0).toString(),
                  style: Theme.of(context).textTheme.headlineMedium,
                );
              },
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () => box.putAt(0, box.getAt(0) + 1),
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}
```

</details>

<details>
  <summary>stable (3.32.0) - flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.32.0, on macOS 15.4.1 24E263 darwin-arm64, locale en-IN) [446ms]
    • Flutter version 3.32.0 on channel stable at /Users/tirthpatel/Development/flutter_stable_latest/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision be698c48a6 (34 hours ago), 2025-05-19 12:59:14 -0700
    • Engine revision 1881800949
    • Dart version 3.8.0
    • DevTools version 2.45.1

[✓] Android toolchain - develop for Android devices (Android SDK version 36.0.0) [827ms]
    • Android SDK at /Users/tirthpatel/Library/Android/sdk
    • Platform android-36, build-tools 36.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.6+-13355223-b631.42)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.3) [448ms]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16E140
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [9ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.3) [8ms]
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.6+-13355223-b631.42)

[✓] VS Code (version 1.100.2) [8ms]
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.110.0

[✓] Connected device (2 available) [5.6s]
    • macOS (desktop) • macos  • darwin-arm64   • macOS 15.4.1 24E263 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 136.0.7103.114

[✓] Network resources [1,624ms]
    • All expected network resources are available.

• No issues found!
```

</details>

<details>
  <summary>master (3.33.0-1.0.pre.186) - flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 3.33.0-1.0.pre.186, on macOS 15.4.1 24E263 darwin-arm64, locale en-IN) [2.1s]
    • Flutter version 3.33.0-1.0.pre.186 on channel master at /Users/tirthpatel/Development/flutter_master/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e529d32dbf (76 minutes ago), 2025-05-23 00:15:14 -0400
    • Engine revision e529d32dbf
    • Dart version 3.9.0 (build 3.9.0-161.0.dev)
    • DevTools version 2.46.0

[✓] Android toolchain - develop for Android devices (Android SDK version 36.0.0) [835ms]
    • Android SDK at /Users/tirthpatel/Library/Android/sdk
    • Emulator version 35.4.9.0 (build_id 13025442) (CL:N/A)
    • Platform android-36, build-tools 36.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.6+-13355223-b631.42)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.3) [559ms]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16E140
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [8ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.3) [7ms]
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.6+-13355223-b631.42)

[✓] VS Code (version 1.100.2) [7ms]
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.110.0

[✓] Connected device (2 available) [5.6s]
    • macOS (desktop) • macos  • darwin-arm64   • macOS 15.4.1 24E263 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 136.0.7103.114

[✓] Network resources [1,115ms]
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by AliKarimiENT** [comment]
> # Triage Report
> 
> I was **not** able to reproduce the issue using the official sample available for [hive_ce_flutter](https://github.com/IO-Design-Team/hive_ce/tree/main/hive_flutter/example/lib) on either the `stable (3.32.0)` or `master (3.33.0-1.0.pre.186)` channels.
> 
> <img width="975" alt="Image" src="https://github.com/user-attachments/assets/a9c3c454-d47a-41cb-bd81-c028e511e416" />
> 
> <details>
> <summary>Code Sample</summary>
> 
> ```dart
> import 'package:flutter/material.dart';
> import 'package:hive_ce_flutter/hive_flutter.dart';
> 
> const counterBox = 'counter';
> 
> void main() async {
>   WidgetsFlutterBinding.ensureInitialized();
>   await Hive.initFlutter();
>   final box = await Hive.openBox(counterBox);
>   if (box.isEmpty) {
>     await box.add(0);
>   }
>   runApp(const MaterialApp(home: HiveCounterApp()));
> }
> 
> class HiveCounterApp extends StatelessWidget {
>   const HiveCounterApp({super.key});
> 
>   @override
>   Widget build(BuildContext context) {
>     final box = Hive.box(counterBox);
> 
>     return Scaffold(
>       appBar: AppBar(title: const Text('Hive CE Example')),
>       body: Center(
>         child: Column(
>           mainAxisAlignment: MainAxisAlignment.center,
>           children: [
>             const Text('You have pushed the button this many times:'),
>             ValueListenableBuilder(
>               valueListenable: box.listenable(),
>               builder: (context, box, widget) {
>                 return Text(
>                   box.getAt(0).toString(),
>                   style: Theme.of(context).textTheme.headlineMedium,
>                 );
>               },
>             ),
>           ],
>         ),
>       ),
>       floatingActionButton: FloatingActionButton(
>         onPressed: () => box.putAt(0, box.getAt(0) + 1),
>         tooltip: 'Increment',
>         child: const Icon(Icons.add),
>       ),
>     );
>   }
> }
> ```
> 
> </details>
> 
> <details>
>   <summary>stable (3.32.0) - flutter doctor -v</summary>
> 
> ```
> [✓] Flutter (Channel stable, 3.32.0, on macOS 15.4.1 24E263 darwin-arm64, locale en-IN) [446ms]
>     • Flutter version 3.32.0 on channel stable at /Users/tirthpatel/Development/flutter_stable_latest/flutter
>     • Upstream repository https://github.com/flutter/flutter.git
>     • Framework revision be698c48a6 (34 hours ago), 2025-05-19 12:59:14 -0700
>     • Engine revision 1881800949
>     • Dart version 3.8.0
>     • DevTools version 2.45.1
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 36.0.0) [827ms]
>     • Android SDK at /Users/tirthpatel/Library/Android/sdk
>     • Platform android-36, build-tools 36.0.0
>     • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
>       This is the JDK bundled with the latest Android Studio installation on this machine.
>       To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
>     • Java version OpenJDK Runtime Environment (build 21.0.6+-13355223-b631.42)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 16.3) [448ms]
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Build 16E140
>     • CocoaPods version 1.16.2
> 
> [✓] Chrome - develop for the web [9ms]
>     • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
> 
> [✓] Android Studio (version 2024.3) [8ms]
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build 21.0.6+-13355223-b631.42)
> 
> [✓] VS Code (version 1.100.2) [8ms]
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 3.110.0
> 
> [✓] Connected device (2 available) [5.6s]
>     • macOS (desktop) • macos  • darwin-arm64   • macOS 15.4.1 24E263 darwin-arm64
>     • Chrome (web)    • chrome • web-javascript • Google Chrome 136.0.7103.114
> 
> [✓] Network resources [1,624ms]
>     • All expected network resources are available.
> 
> • No issues found!
> ```
> 
> </details>
> 
> <details>
>   <summary>master (3.33.0-1.0.pre.186) - flutter doctor -v</summary>
> 
> ```
> [✓] Flutter (Channel master, 3.33.0-1.0.pre.186, on macOS 15.4.1 24E263 darwin-arm64, locale en-IN) [2.1s]
>     • Flutter version 3.33.0-1.0.pre.186 on channel master at /Users/tirthpatel/Development/flutter_master/flutter
>     • Upstream repository https://github.com/flutter/flutter.git
>     • Framework revision e529d32dbf (76 minutes ago), 2025-05-23 00:15:14 -0400
>     • Engine revision e529d32dbf
>     • Dart version 3.9.0 (build 3.9.0-161.0.dev)
>     • DevTools version 2.46.0
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 36.0.0) [835ms]
>     • Android SDK at /Users/tirthpatel/Library/Android/sdk
>     • Emulator version 35.4.9.0 (build_id 13025442) (CL:N/A)
>     • Platform android-36, build-tools 36.0.0
>     • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
>       This is the JDK bundled with the latest Android Studio installation on this machine.
>       To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
>     • Java version OpenJDK Runtime Environment (build 21.0.6+-13355223-b631.42)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 16.3) [559ms]
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Build 16E140
>     • CocoaPods version 1.16.2
> 
> [✓] Chrome - develop for the web [8ms]
>     • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
> 
> [✓] Android Studio (version 2024.3) [7ms]
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build 21.0.6+-13355223-b631.42)
> 
> [✓] VS Code (version 1.100.2) [7ms]
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 3.110.0
> 
> [✓] Connected device (2 available) [5.6s]
>     • macOS (desktop) • macos  • darwin-arm64   • macOS 15.4.1 24E263 darwin-arm64
>     • Chrome (web)    • chrome • web-javascript • Google Chrome 136.0.7103.114
> 
> [✓] Network resources [1,115ms]
>     • All expected network resources are available.
> 
> • No issues found!
> ```
> 
> </details>
> 

Let me check with this package 
Because I was using **hive_ce** not **hive_ce_flutter**

**Comment by timmywil** [comment]
Switching to `hive_ce` worked for me. I imagine it would still be nice if things worked with the much more commonly used `hive`, though.

**Comment by Rexios80** [comment]
I was under the impression this issue was with Hive CE. The original Hive uses legacy JS interop so that's probably the issue.
