### ISSUE TITLE
[iOS] Undefined symbols build error after update to 1.17

### ISSUE THREAD

**Issue by iKrupp** [flutter/flutter#57084]
After updating the flutter to version 1.17, I started getting errors during build

Empirically, it was found that with the inclusion of a copied generic config without a flag OTHER_LDFLAG, everything is fine...

I also deleted the file WorkspaceSettings.xcsettings and completed the migration steps to the new xcode  according to this manual:
https://flutter.dev/docs/development/ios-project-migration

Logs
```bash
[12:58:55]: ▸ ❌  Undefined symbols for architecture arm64
[12:58:55]: ▸ > Symbol: _OBJC_CLASS_$_GADUnifiedNativeAd
[12:58:55]: ▸ > Referenced from: objc-class-ref in GoogleAdsProviderImpl.o
[12:58:55]: ▸ ❌  ld: symbol(s) not found for architecture arm64
[12:58:55]: ▸ ❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)
[12:58:55]: ▸ ** ARCHIVE FAILED **
[12:58:55]: ▸ The following build commands failed:
[12:58:55]: ▸ 	Ld DerivedData/Build/Intermediates.noindex/ArchiveIntermediates/development/InstallationBuildProductsLocation/Applications/Runner.app/Runner normal arm64

```

```console
[✓] Flutter (Channel stable, v1.17.0, on Mac OS X 10.15.4 19E287, locale en-GB)
 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.45.0)
[✓] Connected device (1 available)

```

Also we have some manually added dependncies in podfile.
And, in addition, we use our own configuration for assembly (Release-development), which does not appear in the podfile

```
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def parse_KV_file(file, separator='=')
  file_abs_path = File.expand_path(file)
  if !File.exists? file_abs_path
    return [];
  end
  generated_key_values = {}
  skip_line_start_symbols = ["#", "/"]
  File.foreach(file_abs_path) do |line|
    next if skip_line_start_symbols.any? { |symbol| line =~ /^\s*#{symbol}/ }
    plugin = line.split(pattern=separator)
    if plugin.length == 2
      podname = plugin[0].strip()
      path = plugin[1].strip()
      podpath = File.expand_path("#{path}", file_abs_path)
      generated_key_values[podname] = podpath
    else
      puts "Invalid plugin specification: #{line}"
    end
  end
  generated_key_values
end

target 'Runner' do
  use_frameworks!
  use_modular_headers!
  
  # Flutter Pod

  copied_flutter_dir = File.join(__dir__, 'Flutter')
  copied_framework_path = File.join(copied_flutter_dir, 'Flutter.framework')
  copied_podspec_path = File.join(copied_flutter_dir, 'Flutter.podspec')
  unless File.exist?(copied_framework_path) && File.exist?(copied_podspec_path)
    # Copy Flutter.framework and Flutter.podspec to Flutter/ to have something to link against if the xcode backend script has not run yet.
    # That script will copy the correct debug/profile/release version of the framework based on the currently selected Xcode configuration.
    # CocoaPods will not embed the framework on pod install (before any build phases can generate) if the dylib does not exist.

    generated_xcode_build_settings_path = File.join(copied_flutter_dir, 'Generated.xcconfig')
    unless File.exist?(generated_xcode_build_settings_path)
      raise "Generated.xcconfig must exist. If you're running pod install manually, make sure flutter pub get is executed first"
    end
    generated_xcode_build_settings = parse_KV_file(generated_xcode_build_settings_path)
    cached_framework_dir = generated_xcode_build_settings['FLUTTER_FRAMEWORK_DIR'];

    unless File.exist?(copied_framework_path)
      FileUtils.cp_r(File.join(cached_framework_dir, 'Flutter.framework'), copied_flutter_dir)
    end
    unless File.exist?(copied_podspec_path)
      FileUtils.cp(File.join(cached_framework_dir, 'Flutter.podspec'), copied_flutter_dir)
    end
  end

  # Keep pod path relative so it can be checked into Podfile.lock.
  pod 'Flutter', :path => 'Flutter'

  # Plugin Pods

  # Prepare symlinks folder. We use symlinks to avoid having Podfile.lock
  # referring to absolute paths on developers' machines.
  system('rm -rf .symlinks')
  system('mkdir -p .symlinks/plugins')
  plugin_pods = parse_KV_file('../.flutter-plugins')
  plugin_pods.each do |name, path|
    symlink = File.join('.symlinks', 'plugins', name)
    File.symlink(path, symlink)
    pod name, :path => File.join(symlink, 'ios')
  end

  pod 'Google-Mobile-Ads-SDK'
  pod 'TwilioChatClient', '~> 2.3'
  pod 'TwilioAccessManager', '~> 1.1'

end

# Prevent Cocoapods from embedding a second Flutter framework and causing an error with the new Xcode build system.
install! 'cocoapods', :disable_input_output_paths => true

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
```

**Comment by wheying** [comment]
same problem.... Anyone knows the solution or the reason

**Comment by iKrupp** [comment]
@wheying did you remove WorkspaceSettings.xcsettings?

**Comment by wheying** [comment]
My project.pbxproj has been changed: "thin => embed_and_thin"(which key I forget, I reset my project)...
So I have downgraded from 1.17 to v1.12.13+hotfix.9, it works.

**Comment by iKrupp** [comment]
Downgrade is not a good solution :(

**Comment by lyn-euler** [comment]
use new build system resolved it

**Comment by iKrupp** [comment]
In output log i see this line:

```note: Using new build system```

I think it already uses new build system

**Comment by iKrupp** [comment]
I think we have found the key to the problem.

It was really about the legacy build system. In our fastlane script, we manually specified the -UseNewBuildSystem = NO parameter, which is incorrect.

So, summarizing what steps were taken after updating to the new version of flutter.
```
0. Upgraded flutter
1. Updated XCode to 11.4
2. Manual migrated (https://flutter.dev/docs/development/ios-project-migration)
3. Removed WorkspaceSettings.xcsettings (ios/Runner.xcworkspace/xcuserdata/WorkspaceSettings.xcsettings)

---After step 3, everything should probably work already. However, in our case, the problem was still in the fastlane script

4. Remove forcing of legacy build system in fastlane script ( Remove lines which contains '-UseNewBuildSystem=NO')
```

Hope this helps you!

**Comment by iapicca** [comment]
Hi @iKrupp 
your `flutter build ios --verbose` 
and if possible a reproducible minimal code sample.
Thank you

**Comment by iKrupp** [comment]
Hi @iapicca
Problem solved, thanks!
The repair steps I described above.

I will close this issue.
