### ISSUE TITLE
`prepare_package.dart` crashing with `NoSuchMethodError: The method 'start' was called on null`

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#63615]
This crashed on the [dev packaging builder](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8872148853048735808/+/steps/prepare__create_and_publish_a_flutter_archive/0/stdout), caused by https://github.com/flutter/flutter/pull/62710. Note that each packaging build uses the latest version of this script.

It was fixed by https://github.com/flutter/flutter/pull/63608.
