### ISSUE TITLE
error upon trying to accept licenses for custom-installed SDK

### ISSUE THREAD

**Issue by stuart-little** [flutter/flutter#62924]
## Steps to Reproduce

1. clone this repo
2. install SDK command-line tools by unzipping the file available at [developer.android](https://developer.android.com/studio/) (for Linux; I'm on Ubuntu 18.04) to `$HOME/cmdline-tools`. This provides me with an `sdkmanager` executable at `$HOME/cmdline-tools/tools/bin/sdkmanager`
3. prep SDK by mimicking the commands listed in [the file](https://github.com/flutter/flutter/blob/master/dev/bots/download_android_sdk.sh) `dev/bots/download_android_sdk.sh` in this repo:

```
yes | $ANDROID_SDK_ROOT/cmdline-tools/tools/bin/sdkmanager --licenses
$ANDROID_SDK_ROOT/cmdline-tools/tools/bin/sdkmanager tools
$ANDROID_SDK_ROOT/cmdline-tools/tools/bin/sdkmanager platform-tools
$ANDROID_SDK_ROOT/cmdline-tools/tools/bin/sdkmanager  "platforms;android-28" \
    "build-tools;28.0.3" \
    "platforms;android-27" \
    "build-tools;27.0.3" \
    "extras;google;m2repository" \
    "extras;android;m2repository"
```
where for me `ANDROID_SDK_ROOT` is `$HOME/Android`. As far as I can tell, all goes well with these. 

4. run `<path-to-flutter> doctor -v`; this finds `SDK` all right, but cries about licenses (see the output below). I am instructed to run `doctor --android-licenses`. 

5. Finally, this last command produces an error:

```
$ export ANDROID_HOME=~/Android && ~/repos/flutter/bin/flutter doctor --android-licenses
---
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
        at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
        at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
        at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 5 more
```

## Logs

```
```

Output to `<path-to-flutter> doctor -v`:

```
[✓] Flutter (Channel master, 1.21.0-6.0.pre.180, on Linux, locale en_US.UTF-8)
    • Flutter version 1.21.0-6.0.pre.180 at $HOME/repos/flutter
    • Framework revision 428be90768 (3 hours ago), 2020-08-04 14:31:05 -0700
    • Engine revision 033dd45607
    • Dart version 2.10.0 (build 2.10.0-2.0.dev 0f0e04ec3a)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at $HOME/Android
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = $HOME/Android
    • ANDROID_SDK_ROOT = $HOME/Android
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-post-Ubuntu-0ubuntu118.04.1)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.
```

**Comment by jonahwilliams** [comment]
If the Android SDK tools require classes from Java 1.8. Normally this is provided by a JRE downloaded alongside Android Studio, but if you are setting up the SDK yourself, you will need to make sure that JAVA_HOME points to a 1.8 SDK path while running android licenses

**Comment by stuart-little** [comment]
Thank you! Both of these approaches worked on this `Ubuntu 18.0.4` machine:

1. uninstalling `openjdk-11-jre` and installing `openjdk-8-jre`, and
2. keeping both but exporting `JAVA_HOME` to `/usr/lib/jvm/java-1.8.0-openjdk-amd64` before running `flutter doctor --android-licenses`

The `doctor` output looks fine now:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.21.0-6.0.pre.180, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[!] Android Studio (not installed)
[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```
I do have to run it in a terminal where I've exported `JAVA_HOME` to `1.8` though: the issues resurface with `openjdk-11`.

**Comment by jonahwilliams** [comment]
FWIW this is generally an area of the tool I'm working on improving. We shouldn't need to require users uninstall newer Java versions.

**Comment by jonahwilliams** [comment]
Another potential fix is surfacing an env variable just for android tools, falling back to JAVA_HOME as a last resort

**Comment by Calvin-L** [comment]
Hi, first-time Flutter user here. I want to put in a huge vote for this issue: **`flutter doctor` should be updated to check for Java == 1.8**. It should inform the user if an incorrect version was found, and should give some suggestions about what to do.

My experience today (a bad first experience):

1. `echo $JAVA_HOME` --> /Library/Java/JavaVirtualMachines/jdk-15.jdk/Contents/Home
2. `flutter doctor` --> Android license status unknown. Run `flutter doctor --android-licenses` to accept the SDK licenses.
3. `flutter doctor --android-licenses` --> Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
4. (many hours of searching)
5. `/usr/libexec/java_home -v '1.8*'` --> /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home
6. `export JAVA_HOME='/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home'`
7. `flutter doctor --android-licenses`--> works as expected

My experience is very common. Here is an incomplete list of issues filed by users who encountered this same challenge:

https://github.com/flutter/flutter/issues/8438#issuecomment-356440563
#16025
https://github.com/flutter/flutter/issues/16065#issuecomment-391563094
#16280
#16452
https://github.com/flutter/flutter/issues/23732#issuecomment-434267450
https://github.com/flutter/flutter/issues/25753#issuecomment-450568874
#28230
#28504
#31116
https://github.com/flutter/flutter/issues/39823#issuecomment-538989010
#47118
#51155
#51670
https://github.com/flutter/flutter/issues/51712#issuecomment-599653138
#56572
#56778
#56798
#57017
#57372
#59857
#61354
#65414
#66458
#66907
#67050
#67128 
https://stackoverflow.com/questions/46402772/failed-to-install-android-sdk-java-lang-noclassdeffounderror-javax-xml-bind-a/50285218

**Comment by Calvin-L** [comment]
(In the past, `flutter doctor` was altered to check for Java >= 1.8. See issue #5880 and PR #41989. Hopefully the same infrastructure can be re-used to check for Java == 1.8.x.)

**Comment by liudonghua123** [comment]
> Thank you! Both of these approaches worked on this `Ubuntu 18.0.4` machine:
> 
> 1. uninstalling `openjdk-11-jre` and installing `openjdk-8-jre`, and
> 2. keeping both but exporting `JAVA_HOME` to `/usr/lib/jvm/java-1.8.0-openjdk-amd64` before running `flutter doctor --android-licenses`
> 
> The `doctor` output looks fine now:
> 
> ```
> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel master, 1.21.0-6.0.pre.180, on Linux, locale en_US.UTF-8)
> [✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
> [!] Android Studio (not installed)
> [!] Connected device
>     ! No devices available
> 
> ! Doctor found issues in 2 categories.
> ```
> 
> I do have to run it in a terminal where I've exported `JAVA_HOME` to `1.8` though: the issues resurface with `openjdk-11`.

Yes, I can fix it via change the `JAVA_HOME` environment.

```cmd
C:\Users\Liu.D.H>flutter doctor --android-licenses
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
        at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
        at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
        at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 5 more

C:\Users\Liu.D.H>java -version
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.8+10, mixed mode)

C:\Users\Liu.D.H>where java
C:\Program Files\AdoptOpenJDK\jdk-11.0.8.10-hotspot\bin\java.exe
C:\Program Files\Java\jdk1.8.0_191\bin\java.exe

C:\Users\Liu.D.H>set PATH=C:\Program Files\Java\jdk1.8.0_191\bin\;%PATH%

C:\Users\Liu.D.H>where java
C:\Program Files\Java\jdk1.8.0_191\bin\java.exe
C:\Program Files\AdoptOpenJDK\jdk-11.0.8.10-hotspot\bin\java.exe

C:\Users\Liu.D.H>flutter doctor --android-licenses
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
        at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
        at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
        at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 5 more

C:\Users\Liu.D.H>java -version
java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)

C:\Users\Liu.D.H>echo %JAVA_HOME%
C:\Program Files\AdoptOpenJDK\jdk-11.0.8.10-hotspot\

C:\Users\Liu.D.H>set JAVA_HOME=C:\Program Files\Java\jdk1.8.0_191\

C:\Users\Liu.D.H>flutter doctor --android-licenses
All SDK package licenses accepted.======] 100% Computing updates...


C:\Users\Liu.D.H>
```

**Comment by themightychris** [comment]
Until the Android SDK supports java > 1.8, `flutter doctor` needs to handle checking this. It's a guaranteed chokepoint for both new developers and even experienced ones setting up a new machine. The expectation is that `flutter doctor` will tell you if anything is out of order

**Comment by nobody5050** [comment]
Just had this error, solved by downloading the `Android SDK Command-line Tools (latest)` on Android Studio, under `Preferences > Appearance & Behavior > System Settings > Android SDK > SDK Tools` and re-running `flutter doctor --android-licenses`

**Comment by nobody5050** [comment]
IMO downgrading jdk is a bad plan

**Comment by mzubairsaleem** [comment]
This worked for me!

https://github.com/flutter/flutter/issues/56778#issuecomment-834062619
