### ISSUE TITLE
Camera plugin 0.5.8+2 does not compile in Flutter 1.17.4

### ISSUE THREAD

**Issue by leonardoayres** [flutter/flutter#60092]
After update to Flutter 1.17.4 i started to get the error below:

```
Running Gradle task 'assembleDebug'...
E:\Projetos\<my project>\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java:19: error: cannot find symbol
    flutterEngine.getPlugins().add(new io.flutter.plugins.camera.CameraPlugin());
                                                                ^
  symbol:   class CameraPlugin
  location: package io.flutter.plugins.camera
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

Any ideas about whats going on?

Thanks.

**Comment by iapicca** [comment]
Hi @leonardoayres 
testing [camera](https://pub.dev/packages/camera) plugin [example app](https://github.com/flutter/plugins/tree/master/packages/camera/example)
with the latest stable

<details><summary>logs</summary>

```bash
[        ] BUILD SUCCESSFUL in 2m 35s
[        ] 122 actionable tasks: 121 executed, 1 up-to-date
[ +541 ms] Running Gradle task 'assembleDebug'... (completed in 156.3s, longer than expected)
[ +125 ms] calculateSha: LocalDirectory: '/home/francesco/projects/plugins/packages/camera/example/build/app/outputs/apk'/app.apk
[ +132 ms] calculateSha: reading file took 131us
[ +905 ms] calculateSha: computing sha took 905us
[  +12 ms] ✓ Built build/app/outputs/apk/debug/app-debug.apk.
[   +8 ms] executing: /usr/lib/Android/build-tools/29.0.2/aapt dump xmltree /home/francesco/projects/plugins/packages/camera/example/build/app/outputs/apk/app.apk AndroidManifest.xml
[  +37 ms] Exit code 0 from: /usr/lib/Android/build-tools/29.0.2/aapt dump xmltree /home/francesco/projects/plugins/packages/camera/example/build/app/outputs/apk/app.apk AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0" (Raw: "1.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1c
               A: android:compileSdkVersionCodename(0x01010573)="9" (Raw: "9")
               A: package="io.flutter.plugins.cameraexample" (Raw: "io.flutter.plugins.cameraexample")
               A: platformBuildVersionCode=(type 0x10)0x1
               A: platformBuildVersionName=(type 0x4)0x3f800000
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x15
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1c
               E: uses-feature (line=11)
                 A: android:name(0x01010003)="android.hardware.camera" (Raw: "android.hardware.camera")
                 A: android:required(0x0101028e)=(type 0x12)0xffffffff
               E: uses-permission (line=15)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: uses-permission (line=16)
                 A: android:name(0x01010003)="android.permission.CAMERA" (Raw: "android.permission.CAMERA")
               E: uses-permission (line=17)
                 A: android:name(0x01010003)="android.permission.RECORD_AUDIO" (Raw: "android.permission.RECORD_AUDIO")
               E: uses-permission (line=18)
                 A: android:name(0x01010003)="android.permission.ACCESS_NETWORK_STATE" (Raw: "android.permission.ACCESS_NETWORK_STATE")
               E: application (line=20)
                 A: android:label(0x01010001)="camera_example" (Raw: "camera_example")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="io.flutter.app.FlutterApplication" (Raw: "io.flutter.app.FlutterApplication")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=26)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="io.flutter.plugins.cameraexample.EmbeddingV1Activity" (Raw: "io.flutter.plugins.cameraexample.EmbeddingV1Activity")
                   A: android:exported(0x01010010)=(type 0x12)0xffffffff
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x24b4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=34)
                     A: android:name(0x01010003)="io.flutter.app.android.SplashScreenUntilFirstFrame" (Raw: "io.flutter.app.android.SplashScreenUntilFirstFrame")
                     A: android:value(0x01010024)=(type 0x12)0xffffffff
                 E: activity (line=38)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="io.flutter.embedding.android.FlutterActivity" (Raw: "io.flutter.embedding.android.FlutterActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x24b4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: intent-filter (line=45)
                     E: action (line=46)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=48)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=52)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[   +6 ms] Stopping app 'app.apk' on Pixel 3a.
[   +1 ms] executing: /usr/lib/Android/platform-tools/adb -s 965AY0WP5C shell am force-stop io.flutter.plugins.cameraexample
[ +132 ms] executing: /usr/lib/Android/platform-tools/adb -s 965AY0WP5C shell pm list packages io.flutter.plugins.cameraexample
[ +121 ms] Installing APK.
[   +5 ms] executing: /usr/lib/Android/platform-tools/adb version
[  +16 ms] Android Debug Bridge version 1.0.41
           Version 29.0.6-6198805
           Installed as /usr/lib/Android/platform-tools/adb
[   +1 ms] executing: /usr/lib/Android/platform-tools/adb start-server
[  +23 ms] Installing build/app/outputs/apk/app.apk...
[        ] executing: /usr/lib/Android/platform-tools/adb -s 965AY0WP5C install -t -r /home/francesco/projects/plugins/packages/camera/example/build/app/outputs/apk/app.apk
[+4215 ms] Performing Streamed Install
                    Success
[   +1 ms] Installing build/app/outputs/apk/app.apk... (completed in 4.2s)
[  +25 ms] executing: /usr/lib/Android/platform-tools/adb -s 965AY0WP5C shell echo -n fb44cf34e3f8a46bfbc4e37bdf5bd9a4d009c743 > /data/local/tmp/sky.io.flutter.plugins.cameraexample.sha1
[  +39 ms] Pixel 3a startApp
[   +3 ms] executing: /usr/lib/Android/platform-tools/adb -s 965AY0WP5C shell am start -a android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation true --ez enable-dart-profiling true --ez
enable-checked-mode true --ez verify-entry-points true io.flutter.plugins.cameraexample/io.flutter.embedding.android.FlutterActivity
[ +128 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=io.flutter.plugins.cameraexample/io.flutter.embedding.android.FlutterActivity (has extras) }
[        ] Waiting for observatory port to be available...
[+1211 ms] Observatory URL on device: http://127.0.0.1:38153/x8tHRB0o9yE=/
[   +3 ms] executing: /usr/lib/Android/platform-tools/adb -s 965AY0WP5C forward tcp:0 tcp:38153
[  +16 ms] 45699
[        ] Forwarded host port 45699 to device port 38153 for Observatory
[  +20 ms] Connecting to service protocol: http://127.0.0.1:45699/x8tHRB0o9yE=/
[ +520 ms] Successfully connected to service protocol: http://127.0.0.1:45699/x8tHRB0o9yE=/
[  +10 ms] Sending to VM service: getVM({})
[  +10 ms] Result: {type: VM, name: vm, architectureBits: 64, hostCPU: Qualcomm Technologies, Inc SDM670, operatingSystem: android, targetCPU: arm64, version: 2.8.4 (stable) (Wed Jun 3 12:26:04 2020 +0200)
on "android_arm64", _profilerMode: VM, _nativeZoneMemoryUsag...
[   +9 ms] Sending to VM service: getIsolate({isolateId: isolates/878488862615859})
[   +8 ms] Sending to VM service: _flutter.listViews({})
[  +29 ms] Result: {type: Isolate, id: isolates/878488862615859, name: main, number: 878488862615859, _originNumber: 878488862615859, startTime: 1592983927446, _heaps: {new: {type: HeapSpace, name: new,
vmName: Scavenger, collections: 0, avgCollectionPeriodMillis: 0...
[  +15 ms] Result: {type: FlutterViewList, views: [{type: FlutterView, id: _flutterView/0x7c49197620, isolate: {type: @Isolate, fixedId: true, id: isolates/878488862615859, name:
main.dart$main-878488862615859, number: 878488862615859}}]}
[   +7 ms] DevFS: Creating new filesystem on the device (null)
[        ] Sending to VM service: _createDevFS({fsName: example})
[  +38 ms] Result: {type: FileSystem, name: example, uri: file:///data/user/0/io.flutter.plugins.cameraexample/code_cache/exampleKWDBUQ/example/}
[        ] DevFS: Created new filesystem on the device (file:///data/user/0/io.flutter.plugins.cameraexample/code_cache/exampleKWDBUQ/example/)
[   +2 ms] Updating assets
[ +122 ms] Syncing files to device Pixel 3a...
[   +1 ms] Scanning asset files
[   +2 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +1 ms] <- recompile package:camera_example/main.dart dabee1a1-5b87-4639-b952-555b6d921727
[        ] <- dabee1a1-5b87-4639-b952-555b6d921727
[ +281 ms] Updating files
[ +138 ms] DevFS: Sync finished
[   +4 ms] Syncing files to device Pixel 3a... (completed in 426ms)
[   +2 ms] Synced 0.8MB.
[   +4 ms] Sending to VM service: _flutter.listViews({})
[   +8 ms] Result: {type: FlutterViewList, views: [{type: FlutterView, id: _flutterView/0x7c49197620, isolate: {type: @Isolate, fixedId: true, id: isolates/878488862615859, name:
main.dart$main-878488862615859, number: 878488862615859}}]}
[   +2 ms] <- accept
[        ] Connected to _flutterView/0x7c49197620.
[   +4 ms] Flutter run key commands.
[   +5 ms] r Hot reload. 🔥🔥🔥
[   +3 ms] R Hot restart.
[   +1 ms] h Repeat this help message.
[   +1 ms] d Detach (terminate "flutter run" but leave application running).
[   +1 ms] c Clear the screen
[   +1 ms] q Quit (terminate the application on the device).
[        ] An Observatory debugger and profiler on Pixel 3a is available at: http://127.0.0.1:45699/x8tHRB0o9yE=/
[+31966 ms] I/Choreographer( 9837): Skipped 46 frames!  The application may be doing too much work on its main thread.
[   +8 ms] W/Gralloc3( 9837): allocator 3.x is not supported
[+8838 ms] Service protocol connection closed.
[   +2 ms] Lost connection to device.
[   +8 ms] executing: /usr/lib/Android/platform-tools/adb -s 965AY0WP5C forward --list
[  +24 ms] Exit code 0 from: /usr/lib/Android/platform-tools/adb -s 965AY0WP5C forward --list
[        ] 965AY0WP5C tcp:45699 tcp:38153
[   +2 ms] executing: /usr/lib/Android/platform-tools/adb -s 965AY0WP5C forward --remove tcp:45699
[   +8 ms] DevFS: Deleting filesystem on the device (file:///data/user/0/io.flutter.plugins.cameraexample/code_cache/exampleKWDBUQ/example/)
[        ] Sending to VM service: _deleteDevFS({fsName: example})
[ +256 ms] Ignored error while cleaning up DevFS: TimeoutException after 0:00:00.250000: Future not completed
[   +3 ms] executing: /usr/lib/Android/platform-tools/adb -s 965AY0WP5C forward --list
[   +9 ms] Exit code 0 from: /usr/lib/Android/platform-tools/adb -s 965AY0WP5C forward --list
[   +1 ms] "flutter run" took 206,682ms.

```

</details>

<details><summary>doctor</summary>

```console
[✓] Flutter (Channel stable, v1.17.4, on Linux, locale en_US.UTF-8)
    • Flutter version 1.17.4 at /home/francesco/development/flutter
    • Framework revision 1ad9baa8b9 (6 days ago), 2020-06-17 14:41:16 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /usr/lib/Android
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /usr/lib/Android
    • ANDROID_SDK_ROOT = /usr/lib/Android
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_252-8u252-b09-1~18.04-b09)
    • All Android licenses accepted.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] VS Code (version 1.46.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.11.0

[✓] Connected device (1 available)
    • Pixel 3a • 965AY0WP5C • android-arm64 • Android 10 (API 29)

! Doctor found issues in 1 category.
```

</details>

seems to work as intended.

Can you please provideyour `flutter run --verbose`, 
your `pubspec.yaml` 
and a minimal reproducible code sample.
Thank you

**Comment by leonardoayres** [comment]
Thank you @iapicca,

I think this is a kind of echo from another problem related to the new Flutter 1.17.4, the folder access permissions and VS Code.

I've migrated my project to Android Studio and everything is ok, now.

**Comment by TahaTesser** [comment]
@leonardoayres 
Jus tried to reproduce this issue using official [example](https://pub.dev/packages/camera#-example-tab-) on `Channel stable, v1.17.4`, no issues 

<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel stable, v1.17.4, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.17.4 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 1ad9baa8b9 (8 days ago), 2020-06-17 14:41:16 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

 
[✓] Connected device (2 available)            
    • SM M305F      • 32003c30dc19668f          • android-arm64 • Android 10
      (API 29)
    • Taha’s iPhone • 00008020-001059882212002E • ios           • iOS 13.5.1

• No issues found!
``` 

</details> 

given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you
