### ISSUE TITLE
App Crashes in Android

### ISSUE THREAD

**Issue by KarimMohamed2005** [flutter/flutter#40759]
I have problem with my app.
It was working fine, but accidentally without any changes crashes in build and run

# Logs from my device
```
E/AndroidRuntime(28627): FATAL EXCEPTION: main
E/AndroidRuntime(28627): Process: com.example.hadir, PID: 28627
E/AndroidRuntime(28627): java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/util/ArrayMap;
E/AndroidRuntime(28627):        at com.google.firebase.FirebaseApp.<clinit>(com.google.firebase:firebase-common@@17.0.0:147)
E/AndroidRuntime(28627):        at com.google.firebase.provider.FirebaseInitProvider.onCreate(com.google.firebase:firebase-common@@17.0.0:53)
E/AndroidRuntime(28627):        at android.content.ContentProvider.attachInfo(ContentProvider.java:1761)
E/AndroidRuntime(28627):        at android.content.ContentProvider.attachInfo(ContentProvider.java:1730)
E/AndroidRuntime(28627):        at com.google.firebase.provider.FirebaseInitProvider.attachInfo(com.google.firebase:firebase-common@@17.0.0:47)
E/AndroidRuntime(28627):        at android.app.ActivityThread.installProvider(ActivityThread.java:5748)
E/AndroidRuntime(28627):        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5314)
E/AndroidRuntime(28627):        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5254)
E/AndroidRuntime(28627):        at android.app.ActivityThread.access$1500(ActivityThread.java:178)
E/AndroidRuntime(28627):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1609)
E/AndroidRuntime(28627):        at android.os.Handler.dispatchMessage(Handler.java:111)
E/AndroidRuntime(28627):        at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(28627):        at android.app.ActivityThread.main(ActivityThread.java:6102)
E/AndroidRuntime(28627):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(28627):        at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(28627):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1028)
E/AndroidRuntime(28627):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
E/AndroidRuntime(28627): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.util.ArrayMap" on path: DexPathList[[zip file "/data/app/com.flutter.hadir-1/base.apk"],nativeLibraryDirectories=[/data/app/com.flutter.hadir-1/lib/arm64, /vendor/lib64, /system/lib64]]
E/AndroidRuntime(28627):        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
E/AndroidRuntime(28627):        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
E/AndroidRuntime(28627):        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
E/AndroidRuntime(28627):        ... 17 more
E/AndroidRuntime(28627):        Suppressed: java.lang.ClassNotFoundException: android.support.v4.util.ArrayMap
E/AndroidRuntime(28627):                at java.lang.Class.classForName(Native Method)
E/AndroidRuntime(28627):                at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
E/AndroidRuntime(28627):                at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
E/AndroidRuntime(28627):                at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
E/AndroidRuntime(28627):                ... 18 more
E/AndroidRuntime(28627):        Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
E/ActivityManager( 1080): App crashed! Process: com.example.hadir
```

Anyone can help ?

**Comment by janmoppel** [comment]
Hello @KarimMohamed2005 !

Thank you for posting an issue.
Can you please also provide an output of the `flutter doctor -v` command?

Thank you.

**Comment by Pyozer** [comment]
Same issue here.

My `gradle.properties` files has been updated like this when I upgrade Flutter from 1.10.3 to v1.10.5 and run the app.
```
org.gradle.jvmargs=-Xmx1536M
android.useAndroidX=true
android.enableJetifier=trueandroid.enableR8=true
```

I just move `android.enableR8=true` to a new line, like this :
```
org.gradle.jvmargs=-Xmx1536M
android.useAndroidX=true
android.enableJetifier=true
android.enableR8=true
```

After this, no more crash.

**Comment by kroikie** [comment]
@KarimMohamed2005

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/334. Any further collaboration will be done there.

**Comment by kafijunior** [comment]
> Same issue here. (Duplicate of #40656 )
> 
> My `gradle.properties` files has been updated like this when I upgrade Flutter from 1.10.3 to v1.10.5 and run the app.
> 
> ```
> org.gradle.jvmargs=-Xmx1536M
> android.useAndroidX=true
> android.enableJetifier=trueandroid.enableR8=true
> ```
> 
> I just move `android.enableR8=true` to a new line, like this :
> 
> ```
> org.gradle.jvmargs=-Xmx1536M
> android.useAndroidX=true
> android.enableJetifier=true
> android.enableR8=true
> ```
> 
> After this, no more crash.

solved my problem
