### ISSUE TITLE
Build fails after updating to cloud_firestore 0.8.0

### ISSUE THREAD

**Issue by c-born** [flutter/flutter#21543]
## Steps to Reproduce

1. After updating cloud_firestore from 0.7.4 to 0.8.0 by VSCode builds failed (on the BETA channel)
(VSCode -> Start Debugging)
2. Tried a clean and rebuild (flutter clean), no difference
3. Tried with Android Studio instead of VSCode - still fails
4. Updated to DEV Channel. Still fails
5. Updated to Master - still the same
6. Switch back to 0.7.4 - builds and runs. 

## Logs

```
Launching lib\main.dart on SM N910G in debug mode...
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
C:\Users\cborn\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\cloud_firestore-0.8.0\android\src\main\java\io\flutter\plugins\firebase\cloudfirestore\CloudFirestorePlugin.java:159: error: cannot find symbol
        query = query.whereArrayContains(fieldName, value);
                     ^
  symbol:   method whereArrayContains(String,Object)
  location: variable query of type Query
C:\Users\cborn\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\cloud_firestore-0.8.0\android\src\main\java\io\flutter\plugins\firebase\cloudfirestore\CloudFirestorePlugin.java:643: error: cannot find symbol
        return FieldValue.arrayUnion(readValue(buffer));
                         ^
  symbol:   method arrayUnion(Object)
  location: class FieldValue
C:\Users\cborn\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\cloud_firestore-0.8.0\android\src\main\java\io\flutter\plugins\firebase\cloudfirestore\CloudFirestorePlugin.java:645: error: cannot find symbol
        return FieldValue.arrayRemove(readValue(buffer));
                         ^
  symbol:   method arrayRemove(Object)
  location: class FieldValue
Note: C:\Users\cborn\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\cloud_firestore-0.8.0\android\src\main\java\io\flutter\plugins\firebase\cloudfirestore\CloudFirestorePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
3 errors

FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':cloud_firestore:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
* Get more help at https://help.gradle.org
BUILD FAILED in 13s
Gradle build failed: 1
Exited (sigterm)
```

```
[√] Flutter (Channel master, v0.8.1-pre.50, on Microsoft Windows [Version 6.1.7601], locale en-AU)
    • Flutter version 0.8.1-pre.50 at D:\usr_chronos\Sandbox\flutter
    • Framework revision 3c58195350 (2 hours ago), 2018-09-07 09:13:13 +0200
    • Engine revision 58a1894a1c
    • Dart version 2.1.0-dev.3.1.flutter-760a9690c2

[√] Android toolchain - develop for Android devices (Android SDK 27.0.2)
    • Android SDK at D:\Users\cborn\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.2
    • ANDROID_HOME = D:\Users\cborn\AppData\Local\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 28.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] VS Code (version 1.27.1)
    • VS Code at C:\Users\cborn\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.18.0

[√] VS Code, 64-bit edition (version 1.26.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.18.0

[√] Connected devices (1 available)
    • SM N910G • 0ab5d05b • android-arm • Android 6.0.1 (API 23)

• No issues found!
```

**Comment by zoechi** [comment]
Just a guess. You could create a new Flutter project, and compare the build.gradle files (`android/build.gradle` and `android/app/build.gradle`) of the old and new project and update the old accordingly.

**Comment by c-born** [comment]
@zoechi 
Good guess, it gave me a direction to look in!
In order to build originally, I had added to by build.gradle a suggestion given here: https://github.com/flutter/flutter/issues/20486

I removed that code, then the missing symbols were resolved, but the build failed on a dex error.
I then added
```
multiDexEnabled true
```
and my build completed and is running, thank you!
I then created a new project and compared the build.gradle files, there are some changes which I'll try merging into my project tomorrow, as it getting late here now.
I don't know why just updating the plugin version caused the crash, or what I've done to fix it, being somewhat new to this build system, should I close the issue now, or leave it in case others come across it with the update?

**Comment by zoechi** [comment]
Glad to hear!

**Comment by c-born** [comment]
I changed the build.gradle settings in my project to match the ones in the newly created one, basically 
```classpath 'com.android.tools.build:gradle:3.0.1'``` changed to ```3.1.2```, and the two ```androidTestImplementation``` dependencies got a version bump, after that my build failed saying I needed to upgrade gradle from 4.1 to 4.4

I did that in the ```gradle-wrapper.properties``` file as suggested, and the resulting build completed (with a lot more warnings than before) and runs successfully in debug, haven't tried release yet.

I still have to have ```multiDexEnabled true``` to build or it complains about more than 64K methods, which seems strange for a simple 3-page test app?

After all that I can now access ```FieldValue.serverTimestamp()``` from the new plugin, but unfortunately I don't think it does what I had hoped, which was to get the current time on the server as we do in our SQL code! And I haven't been able to figure out how to access ```SnapshotMetadata``` to see if the data I'm getting is fresh or stale (```.fromCache```), so lots to learn!

**Comment by wangvic** [comment]
My android gradle build is working now. However iOS build is still failing on my Mac. Does anyone know how to fix this issue for iOS?

**Comment by zoechi** [comment]
What exactly is the issue on iOS? Any error output?

**Comment by wangvic** [comment]
Flutter beta channel,

Launching lib/main.dart on iPhone X in debug mode...
Starting Xcode build...
Xcode build done.
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **
    
Xcode's output:
.......
.......
 /Users/Vic/Development/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.8.0/ios/Classes/CloudFirestorePlugin.m:50:22: error: no visible @interface for 'FIRQuery' declares the selector 'queryWhereField:arrayContains:'
          query = [query queryWhereField:fieldName arrayContains:value];
                   ~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

.....
.....
    19 warnings and 3 errors generated.
Could not build the application for the simulator.
Error launching application on iPhone X.

**Comment by wangvic** [comment]
Does your iOS build work? Have you tried it?

**Comment by zoechi** [comment]
I think it would be better to create a new issue.
This one is closed and about Android.

**Comment by wangvic** [comment]
Ok. Thanks @zoechi

**Comment by digarahayu** [comment]
The new version of all official Google plugins swaps the use of Android support to use android x instead.
You need to migrate to Android X
how to fix it ??
here the solution

**set minSdk and targetSdk on build.gradle**
```
        minSdkVersion 21
        targetSdkVersion 28
```

and then add
```
android.useAndroidX=true
android.enableJetifier=true
```
**in gradle.properties**

**Comment by iPatel007** [comment]
> 28

also set **compileSdkVersion 28** at **build.gradle**

**Comment by ddkoin** [comment]
C:\Program Files\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_messaging-4.0.0+3\android\src\main\java\io\flutter\plugins\firebasemessaging\FirebaseMessagingPlugin.java:19: error: cannot find symbol
import com.google.firebase.iid.InstanceIdResult;
                              ^
  symbol:   class InstanceIdResult
  location: package com.google.firebase.iid
C:\Program Files\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_messaging-4.0.0+3\android\src\main\java\io\flutter\plugins\firebasemessaging\FirebaseMessagingPlugin.java:120: error: cannot find symbol
              new OnCompleteListener<InstanceIdResult>() {
                                     ^
  symbol:   class InstanceIdResult
  location: class FirebaseMessagingPlugin
C:\Program Files\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_messaging-4.0.0+3\android\src\main\java\io\flutter\plugins\firebasemessaging\FirebaseMessagingPlugin.java:122: error: cannot find symbol
                public void onComplete(@NonNull Task<InstanceIdResult> task) {
                                                     ^
  symbol: class InstanceIdResult
C:\Program Files\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_messaging-4.0.0+3\android\src\main\java\io\flutter\plugins\firebasemessaging\FirebaseMessagingPlugin.java:118: error: cannot find symbol
          .getInstanceId()
          ^
  symbol:   method getInstanceId()
  location: class FirebaseInstanceId


I am  facing the same problem, 

Followed all the recommended procedures but no luck .

Followed procedures. 
1) Flutter clean 
2) flutter packages pub cache repair
3) Restart Android 
4)  Remake emulator 
nothing is working

**Comment by cgbrucezjy** [comment]
> 2\. flutter packages pub cache repair

same here, no luck also followed https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility 
seems like only firebase messaging plugin is giving me issues
