### ISSUE TITLE
cloud_firestore: query returns null (regression in 0.9.6)

### ISSUE THREAD

**Issue by cbenhagen** [flutter/flutter#29423]
This works in `0.9.5+2`
```dart
await Firestore.instance.collection('things').getDocuments();
```

but fails in `0.9.6`

```dart
flutter: Caught error: NoSuchMethodError: The method '[]' was called on null.
Receiver: null
Tried calling: []("documents")
flutter: #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      new QuerySnapshot._ (file:///Users/ben/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.9.6/lib/src/query_snapshot.dart:10:57)
#2      Query.getDocuments (file:///Users/ben/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.9.6/lib/src/query.dart:100:26)
```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.2.1, on Mac OS X 10.14.3 18D109, locale de-CH)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.3)
[✓] VS Code (version 1.31.1)
[✓] Connected device (2 available)

• No issues found!
```

**Comment by FViscardi** [comment]
I can confirm, I'm facing the same issue. It (seems) to work fine on Android, but fails on IOS with the exact same error.

**Comment by collinjackson** [comment]
Please update to 0.9.7 for the fix. Thanks.

**Comment by cbenhagen** [comment]
Thank you for the quick fix @collinjackson! :)

**Comment by kroikie** [comment]
@cbenhagen

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1241. Any further collaboration will be done there.
