### PR TITLE
Revert "[AGP 9] Bumping KGP error minimum to 2.0.0 (#184385)"

### LINKED ISSUE #184384: [AGP 9] Raise KGP Error and Warn Version
To ensure developers can safely migrate to Built-in Kotlin starting AGP 9, we must upgrade the KGP error version (minimum supported version) to KGP 2.0.0 because the `kotlinOptions`{} DSL is deprecated in KGP 2.0.0 can be safely migrated to kotlin.compilerOptions{} DSL [here](https://kotlinlang.org/docs/gradle-compiler-options.html#migrate-from-kotlinoptions-to-compileroptions). 

The warn KGP version was updated to a KGP 2.2.20 because it is a version that is still safe to use the `kotlinOptions`{} DSL 2.2.20. Starting 2.3.0, using `kotlinOptions`{} DSL results in a compilation error [here](https://youtrack.jetbrains.com/issue/KT-76720). The goal is to rasie the KGP warn version such that we can also raise the AGP and Gradle warn version in preparation for AGP 9.

The error and warn dependencies of AGP and Gradle had to be raised accordingly and were dictated by KGP [here](https://kotlinlang.org/docs/gradle-configure-project.html#apply-the-plugin).

### PR DESCRIPTION
**Pull request by jason-simmons**
Reverts: flutter/flutter#184385

Initiated by: jason-simmons

Reason for reverting: This is causing errors in the `build_android_host_app_with_module_source` integration test.

Example: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20build_android_host_app_with_module_source/7845/overview

https://github.com/flutter/flutter/blob/master/dev/integration_tests/pure_android_host_apps/host_app_kotlin_gradle_dsl/gradle/libs.versions.toml needs to be updated.

Original PR Author: jesswrd

Reviewed By: {gmackall}

This change reverts the following previous change:
Bumped KGP error and warn versions to support Built-in Kotlin migration. AGP and Gradle error and warn versions had to be bumped as a result of bumping KGP error and warn versions.

This will be CP'ed to beta and stable.

Fixes https://github.com/flutter/flutter/issues/184384
Addresses https://github.com/flutter/flutter/issues/181557

### CODE REVIEW

**Comment by reidbaker** [comment]
I have filed https://github.com/flutter/flutter/issues/184456 and am marking those tests as skipped. The failure is that this test needs a higher agp version.
