### ISSUE TITLE
Compilation error after upgrading Flutter from 1.0.0 to 1.2.1

### ISSUE THREAD

**Issue by Jardo-51** [flutter/flutter#30879]
## Steps to Reproduce

My application had no problem compiling with Flutter 1.0.0. But when I upgraded Flutter to 1.2.1 (using `flutter upgrade`), I get the following compilation error:  

```
error: cannot access NonNull
  class file for androidx.annotation.NonNull not found
  Consult the following stack trace for details.
  com.sun.tools.javac.code.Symbol$CompletionFailure: class file for androidx.annotation.NonNull not found

1 error
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
Finished with error: Gradle task assembleDebug failed with exit code 1
```
The app is migrated to AndroidX. I also tried Flutter version 1.4.9 with the same result. After downgrading back to 1.0.0, I can compile my app again.

```
flutter doctor -v
[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17763.379], locale sk-SK)
    • Flutter version 1.2.1 at D:\programs\flutter
    • Framework revision 8661d8aecd (8 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\jardo\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!
```

**Comment by MichaelMarner** [comment]
Have you followed the documentation for upgrading your Android project structure to work with Android X?

https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility

**Comment by TikoZiko** [comment]
Had the same problem and the document worked with me. Thanx

**Comment by escamoteur** [comment]
Hi, sorry for the delay, I just want to check if you could solve this problem.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
