### ISSUE TITLE
Flutter Doctor: Does anyone know hot to solve this issue: When I run flutter doctor the following message is displayed: Cannot execute C:\jdk-15_windows-x64_bin\jdk-15\bin\bin\java to determine the version

### ISSUE THREAD

**Issue by cmatosdiaz** [flutter/flutter#68439]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

**Comment by ufolux** [comment]
Can you make sure if that is the correct path where your java installed？

**Comment by iapicca** [comment]
@cmatosdiaz 
please provide your full `flutter doctor -v` and any other related log

**Comment by cmatosdiaz** [comment]
Thanks.  I realized it was not been added correctly to the environment variables. But now I have other several issues:
These are the logs:
Flutter (Channel stable, 1.22.1, on Microsoft Windows [Version 10.0.19041.572], locale en-US)
    • Flutter version 1.22.1 at C:\src\flutter
    • Framework revision f30b7f4db9 (10 days ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\albap\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Java\jdk-15\bin\java
    • Java version Java(TM) SE Runtime Environment (build 15+36-1562)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[!] Connected device
    ! Device R58M54BDN5K is not authorized.
      You might need to check your device for an authorization dialog.

For the _license unknown_ issue, I already ran the " flutter doctor --android-licenses" command and returns the following log:

Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
        at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
        at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
        at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:606)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 5 more

I also installed the Android Studio and set my android device (usb driver included).  I don't know what else to do.

If you can shed me some light I'll be very grateful.

**Comment by flameyee** [comment]
I bang in the same problem after I updated Android Studio to 4.10

**Comment by sidrao2006** [comment]
Possible duplicate of #67986

**Comment by ufolux** [comment]
Seems like a problem caused by high JDK version. JDK 8 might work properly with Android SDK.
I got this one which may provide useful information: 
https://stackoverflow.com/questions/46402772/failed-to-install-android-sdk-java-lang-noclassdeffounderror-javax-xml-bind-a

**Comment by pedromassangocode** [comment]
Hi @https://github.com/flutter/flutter/issues/57372
I see there's an open issue addressing the case you described.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
