### ISSUE TITLE
alert() method doesn't work in WebView

### ISSUE THREAD

**Issue by yumi0629** [flutter/flutter#30358]
I use the plugin ```webview_flutter``` to load a html page below:
```
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport"
        content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <title>Amaze UI 在线调试</title>
  <link rel="stylesheet" href="http://cdn.amazeui.org/amazeui/2.5.0/css/amazeui.min.css"/>
</head>
<body>
  <button onclick="alert(123456)">alert</button>
<script src="http://code.jquery.com/jquery-2.1.4.min.js"></script>
<script src="http://cdn.amazeui.org/amazeui/2.5.0/js/amazeui.min.js"></script>
</body>
</html>
```
But when I click the button "alert", the alert dialog doesn't show in Flutter. I open the html in Chrome, everything works well.

Does alert() method not support in Flutter?

output of ```flutter doctor -v```:

[✓] Flutter (Channel beta, v1.3.8, on Mac OS X 10.13.6 17G65, locale zh-Hans-CN)
    • Flutter version 1.3.8 at /Users/yumi/Library/Android/flutter
    • Framework revision e5b1ed7a7f (4 weeks ago), 2019-03-06 14:23:37 -0800
    • Engine revision f4951df193
    • Dart version 2.2.1 (build 2.2.1-dev.0.0 571ea80e11)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/yumi/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/yumi/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.3
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)

[✓] Connected device (2 available)
    • M5 Note  • 621QECQP4P2HM    • android-arm64 • Android 7.0 (API 24)
    • VKY AL00 • WJX7N17815008179 • android-arm64 • Android 7.0 (API 24)

**Comment by ushang000** [comment]
are u solve it ? alert & confirm can not work

**Comment by xuyu461989426** [comment]
alert&confirm currently are not supported in webview_flutter , if u want it working , you must rebuild  webview_flutter  on native platform library or  don't  use alert in html(use self-build alert instead)

**Comment by jerryzhoujw** [comment]
You can use
```
flutter_webview_plugin:
    git:
      ref: "dev/fix_alert_not_work_in_webview"
      url: "https://github.com/jerryzhoujw/flutter_webview_plugin"
      source: git
```
this as temp in `pubspec.yaml` before merge [PR](https://github.com/fluttercommunity/flutter_webview_plugin/pull/522)

**Comment by escamoteur** [comment]
Hi, there is a PR on the way you can follow it here https://github.com/fluttercommunity/flutter_webview_plugin/pull/522

**Comment by iapicca** [comment]
Hi @yumi0629 
are you referring to the first party plugin [webview_flutter](https://pub.dev/packages/webview_flutter) or the third party [flutter_webview_plugin](https://pub.dev/packages/flutter_webview_plugin)?
If the latter you may want to open an issue in the dedicated [github](https://github.com/fluttercommunity/flutter_webview_plugin/issue), otherwise,
if you are still experiencing the issue with the latest stable version of Flutter
please provide your update `flutter doctor -v` 
and your `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post a reproducible minimal code sample
or the steps to reproduce the problem.
Thank you

**Comment by simpleblack** [comment]
When i using alert, I had a good experience.

```dart
onPageFinished: (url) async {
  try {
    var javascript = '''
      window.alert = function (e){
        Alert.postMessage(e);
      }
    ''';
    await _webViewController?.evaluateJavascript(javascript);
  } catch (_) {}
  setState(() {
     isLoading = false;
   });
},
```

```dart
JavascriptChannel(
  name: 'Alert',
  onMessageReceived: (JavascriptMessage message) {
    // TODO popup
  },
 )
```

**Comment by deandreamatias** [comment]
> When i using alert, I had a good experience.
> 
> ```dart
> onPageFinished: (url) async {
>   try {
>     var javascript = '''
>       window.alert = function (e){
>         Alert.postMessage(e);
>       }
>     ''';
>     await _webViewController?.evaluateJavascript(javascript);
>   } catch (_) {}
>   setState(() {
>      isLoading = false;
>    });
> },
> ```
> 
> ```dart
> JavascriptChannel(
>   name: 'Alert',
>   onMessageReceived: (JavascriptMessage message) {
>     // TODO popup
>   },
>  )
> ```

What is your configuration?
You try whit popup directly in web site?

**Comment by simpleblack** [comment]
@deandreamatias 
Reconfigure alert on your website to use as channel.

**Comment by deandreamatias** [comment]
> @deandreamatias
> Reconfigure alert on your website to use as channel.

The website isn't mine :/

**Comment by simpleblack** [comment]
@deandreamatias
It's okay if it's not my website.

It is important to reconstruct `window.alert`
```dart
var javascript = '''
  window.alert = function (str){
    Alert.postMessage(str);
  }
''';
await _webViewController?.evaluateJavascript(javascript);
```

Example Code
```dart
WebView(
  initialUrl: 'https://flutter.dev',
  javascriptMode: JavascriptMode.unrestricted,
  onWebViewCreated: (controller) {
    _webViewController = controller;
  },
  onPageFinished: (url) async {
    try {
      var javascript = '''
            window.alert = function (str){
              Alert.postMessage(str);
            }
          ''';
      await _webViewController?.evaluateJavascript(javascript);
    } catch (_) {}

    try {
      var testAlert = '''
            alert('Test alert Message');
          ''';
      await _webViewController?.evaluateJavascript(testAlert);
    } catch (_) {}
  },
  javascriptChannels: Set.from(
    [
      JavascriptChannel(
        name: 'Alert',
        onMessageReceived: (JavascriptMessage message) {
          // alert message = Test alert Message
          print(message.message)
          // TODO popup
        },
      )
    ],
  ),
),
```

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Comment by andynvt** [comment]
> When i using alert, I had a good experience.
> 
> ```dart
> onPageFinished: (url) async {
>   try {
>     var javascript = '''
>       window.alert = function (e){
>         Alert.postMessage(e);
>       }
>     ''';
>     await _webViewController?.evaluateJavascript(javascript);
>   } catch (_) {}
>   setState(() {
>      isLoading = false;
>    });
> },
> ```
> 
> ```dart
> JavascriptChannel(
>   name: 'Alert',
>   onMessageReceived: (JavascriptMessage message) {
>     // TODO popup
>   },
>  )
> ```

Thank you, you save my life

**Comment by lizhuoyuan** [comment]
> ```dart
> evaluateJavascript
> ```

hello , my controller does not have evaluateJavascript . 
I used the last version.

**Comment by shinriyo** [comment]
@andynvt wow!! it is good ida.
but, confirm can't get return value.

```
window.confirm = function(str) {
  if (typeof Confirm !== 'undefined') {
    Confirm.postMessage(str);
  }
};
```

```
    return JavascriptChannel(
      name: 'Confirm',
      onMessageReceived: (JavascriptMessage message) async {
    return showDialog<bool>(
      context: context,
      builder: (_) {
        return AlertDialog(
          content: Text(message.message),
          actions: <Widget>[
            FlatButton(
              child: Text("Cancel"),
              onPressed: () {
                Navigator.pop(context, false);
              },
            ),
            FlatButton(
              child: Text("OK"),
              onPressed: () {
                Navigator.pop(context, true);
              },
            ),
          ],
        );
      },
    );
  
        // true / false
        print(a);
      },
    );
```

**Comment by jasxir** [comment]
As this issue is currently the top search result in Google regarding this issue.
I'm updating the solution here for anyone who comes here for an answer.

Now it's working on Flutter 1.22.6
I was searching for why I couldn't select text in the webview, and I found the solution below.
This also solves the confirm/alert dialog issue.

Sorry don't remeber the original issue/ticket where I found the solution. If anyone finds please link below.

Thanks,
Hope this helps.

```
@override
void initState() {
  super.initState();
  if (Platform.isAndroid) WebView.platform = SurfaceAndroidWebView();
}
```

**Comment by stuartmorgan** [comment]
It's not clear to me why this was closed, since the description was clear about what the issue is and that it was with `webview_flutter`; re-opening, but updating labels per the comment above to indicate that this only happens with Virtual Display.

**Comment by danagbemava-nc** [comment]
I can confirm that the issue still persists on the latest `master 2.5.0-6.0.pre.21` and `stable 2.2.3`
on both `android` and `ios` with `webview_flutter: ^2.0.10`.

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 2.5.0-6.0.pre.21, on macOS 11.5.1 20G80 darwin-arm, locale en-GH)
    • Flutter version 2.5.0-6.0.pre.21 at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 40e8620a27 (3 hours ago), 2021-08-06 09:14:50 +0430
    • Engine revision 431ac604da
    • Dart version 2.14.0 (build 2.14.0-383.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.58.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64  • Android
      12 (API 31) (emulator)
    • iPhone 12 (mobile)          • F2592D43-5FE3-46BB-8A2B-A38BA468DCE9 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)                • chrome                               • web-javascript • Google
      Chrome 92.0.4515.131

• No issues found!
```


```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.1 20G80 darwin-arm, locale en-GH)
    • Flutter version 2.2.3 at /Users/nexus/dev/sdks/flutter
    • Framework revision f4abaa0735 (5 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.58.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64  • Android
      12 (API 31) (emulator)
    • iPhone 12 (mobile)          • F2592D43-5FE3-46BB-8A2B-A38BA468DCE9 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)                • chrome                               • web-javascript • Google
      Chrome 92.0.4515.131

• No issues found!
```
</details>

<details>
<summary>Sample code for reference</summary>

```dart
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  void initState() {
    super.initState();

    // enable hybrid composition
    if (Platform.isAndroid) WebView.platform = SurfaceAndroidWebView();
  }

  final String _html = """
  <!DOCTYPE html>
  <html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport"
        content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>Amaze UI</title>
    <link rel="stylesheet" href="http://cdn.amazeui.org/amazeui/2.5.0/css/amazeui.min.css"/>
  </head>
  <body>
    <button onclick="alert(123456)">alert</button>
  <script src="http://code.jquery.com/jquery-2.1.4.min.js"></script>
  <script src="http://cdn.amazeui.org/amazeui/2.5.0/js/amazeui.min.js"></script>
  </body> 
  </html>
  """;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: WebView(
        initialUrl: 'flutter.dev',
        onWebViewCreated: (WebViewController controller) {
          controller.loadUrl(
            Uri.dataFromString(_html, mimeType: 'text/html').toString(),
          );
        },
      ),
    );
  }
}

```
</details>

**Comment by pheebeeadej** [comment]
> 

worked for me. thanks

**Comment by pheebeeadej** [comment]
> As this issue is currently the top search result in Google regarding this issue. I'm updating the solution here for anyone who comes here for an answer.
> 
> Now it's working on Flutter 1.22.6 I was searching for why I couldn't select text in the webview, and I found the solution below. This also solves the confirm/alert dialog issue.
> 
> Sorry don't remeber the original issue/ticket where I found the solution. If anyone finds please link below.
> 
> Thanks, Hope this helps.
> 
> ```
> @override
> void initState() {
>   super.initState();
>   if (Platform.isAndroid) WebView.platform = SurfaceAndroidWebView();
> }
> ```

this solution worked for me thanks.

**Comment by ameenbadri7** [comment]
```
@override
void initState() {
  super.initState();
  if (Platform.isAndroid) WebView.platform = SurfaceAndroidWebView();
}
```

fix my problem .. thanks

**Comment by BuildAppEasy** [comment]
Does this only fix for android? In iOS the alert still not popping up.

**Comment by mdeandrea-mrmilu** [comment]
In my Flutter web app (running in Chrome with Flutter 2.10.5), this alert did not appear and I found this in the console log:
> [Intervention] Blocked attempt to show a 'beforeunload' confirmation panel for a frame that never had a user gesture since its load. https://chromestatus.com/feature/5082396709879808

Maybe is related

**Comment by mgj** [comment]
webview_flutter will not display alert() on iOS because the package does not implement an ios-specific runJavaScriptAlertPanelWithMessage function.

For it to work it needs to implement something like this: https://github.com/fluttercommunity/flutter_webview_plugin/pull/522

Any existing setting or setting `WebView.platform` will be insufficient.

**Comment by esenpi** [comment]
For anyone who is searching on Google for something like "JavaScript not working on iOS Webview with Flutter," you may have encountered the same issue as me. I was testing if JavaScript was working by using the most simple way with "alert('test');" but it didn't work. Therefore, I concluded that JavaScript might be blocked in WebViews on iOS devices. However, the true answer is that this plugin simply does not support the alert() function. (╯°□°)╯︵ ┻━┻ ︵ 
So if you're testing if JavaScript is working or not, don't use alert() to get the answer. Surprisingly, alert() does work on Android devices.

**Comment by ostup17** [comment]
Hello everyone, to this day the problem is relevant on the iPhone. `alert()` not showing

**Comment by ostup17** [comment]
Hello everyone, to this day the problem is relevant on the iPhone. `alert()` not showing

**Comment by dam-ease** [comment]
I am able to reproduce this issue on the latest `master` and `stable` channels using the latest version of the `webview_flutter` package (`webview_flutter: ^4.2.0`).

<details><summary>Code Sample</summary>
<p>

```dart
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  late final WebViewController _webViewController;

  @override
  void initState() {
    super.initState();
    _webViewController = WebViewController()
      ..loadRequest(Uri.dataFromString(_html, mimeType: 'text/html'));
  }

  final String _html = """
  <!DOCTYPE html>
  <html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport"
        content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>Amaze UI</title>
    <link rel="stylesheet" href="http://cdn.amazeui.org/amazeui/2.5.0/css/amazeui.min.css"/>
  </head>
  <body>
    <button onclick="alert(123456)">alert</button>
  <script src="http://code.jquery.com/jquery-2.1.4.min.js"></script>
  <script src="http://cdn.amazeui.org/amazeui/2.5.0/js/amazeui.min.js"></script>
  </body> 
  </html>
  """;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: WebViewWidget(controller: _webViewController),
    );
  }
}

``` 

</p>
</details> 


<details> <summary> flutter doctor -v </summary>

```bash
[✓] Flutter (Channel master, 3.11.0-2.0.pre.55, on macOS 13.3 22E252 darwin-arm64, locale en-NG)
    • Flutter version 3.11.0-2.0.pre.55 on channel master at /Users/dammya/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 835b892d7f (12 days ago), 2023-05-07 01:30:22 +0530
    • Engine revision 23f730efbf
    • Dart version 3.1.0 (build 3.1.0-83.0.dev)
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/dammya/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • ANDROID_HOME = /Users/dammya/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.78.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] VS Code (version 1.78.0)
    • VS Code at /Users/dammya/.Trash/Visual Studio Code 20.07.05.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (4 available)
    • sdk gphone arm64 (mobile)  • emulator-5554                        • android-arm64  • Android 11 (API 30) (emulator)
    • iPhone 14 Pro Max (mobile) • D7F3302D-D66F-4B89-B8CF-DBEE1CDB5449 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 13.3 22E252 darwin-arm64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 113.0.5672.126

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```
```bash
[✓] Flutter (Channel stable, 3.10.1, on macOS 13.3 22E252 darwin-arm64, locale en-NG)
    • Flutter version 3.10.1 on channel stable at /Users/dammya/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d3d8effc68 (31 hours ago), 2023-05-16 17:59:05 -0700
    • Engine revision b4fb11214d
    • Dart version 3.0.1
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/dammya/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • ANDROID_HOME = /Users/dammya/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.78.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] VS Code (version 1.78.0)
    • VS Code at /Users/dammya/.Trash/Visual Studio Code 20.07.05.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (4 available)
    • sdk gphone arm64 (mobile)  • emulator-5554                        • android-arm64  • Android 11 (API 30) (emulator)
    • iPhone 14 Pro Max (mobile) • D7F3302D-D66F-4B89-B8CF-DBEE1CDB5449 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 13.3 22E252 darwin-arm64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 113.0.5672.126

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```
</details>

**Comment by ntaworking** [comment]
This problem still existing in 2023 ??? The alert not show on iOS.

**Comment by stuartmorgan** [comment]
For anyone interested in working on this, the approach we would want to take is to delegate the alert information the plugin client via a Dart callback, rather than implementing a specific native UI. (If someone wants native UI, then can then implement that callback by calling a plugin that shows native dialogs.)

**Comment by tomonori-sakieda-iplug** [comment]
We are considering moving to another package because of this problem.
When do you expect this issue to be resolved?
