### ISSUE TITLE
Packages roller blocked on JS interop errors

### ISSUE THREAD

**Issue by stuartmorgan-g** [flutter/flutter#190355]
The flutter/flutter -> flutter/packages roller is currently blocked on JS interop errors. I've bisected it down to https://github.com/flutter/packages/pull/12328 which is [this Dart roll](https://github.com/flutter/flutter/pull/190158). I'm not familiar enough with the internals of JS interop to know what the solution is here to unblock the roller.

```
Target dart2js failed: ProcessException: Process exited abnormally with exit code 1:
../packages/camera/camera_web/lib/src/pkg_web_tweaks.dart:47:20:
Error: The '@JS' annotation on an extension type constructor has no effect.
  external factory WebTweakMediaSettingsRange({num max, num min, num step});
                   ^
../packages/camera/camera_web/lib/src/pkg_web_tweaks.dart:67:20:
Error: The '@JS' annotation on an extension type constructor has no effect.
  external factory WebTweakMediaTrackConstraints({JSAny zoom, ConstrainBoolean torch});
                   ^
Error: Compilation failed.
```

As usual with flutter/packages, if at all possible we want a solution that is compatible with both `stable` and `master`.

**Comment by stuartmorgan-g** [comment]
FYI @mboetger as this week's gardener, as this still isn't resolved.

**Comment by mdebbar** [comment]
I assume you meant @mdebbar not @mboetger :)

**Comment by stuartmorgan-g** [comment]
No, I wanted the current flutter/packages gardener to be aware of this blocking issue that had carried over from the previous week.
