### ISSUE TITLE
AudioPlayer.java:6: error: package android.support.annotation does not exist

### ISSUE THREAD

**Issue by elmarou** [flutter/flutter#34609]
i working with fluttery_audio : 0.0.4 
i have this error 
***haw can i fix this !***
```dart 
C:\flutter\.pub-cache\hosted\pub.dartlang.org\fluttery_audio-0.0.4\android\src\main\java\io\fluttery\flutteryaudio\AudioPlayer.java:6: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
                                 ^
C:\flutter\.pub-cache\hosted\pub.dartlang.org\fluttery_audio-0.0.4\android\src\main\java\io\fluttery\flutteryaudio\AudioVisualizer.java:5: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
```
