### PR TITLE
Flutter 1.22.0-12.2.pre Framework cherrypicks

### PR DESCRIPTION
**Pull request by christopherfujino**
## Scheduled Cherrypicks

* Engine cherrypicks
  * https://github.com/flutter/engine/pull/21366
  * https://github.com/flutter/engine/commit/f763b5b9b936872bc6c84b4395286ce684e3b431
* Deprecate VelocityTracker default constructor and added VelocityTracker.withKind constructor
  * https://github.com/flutter/flutter/issues/66070
  * https://github.com/flutter/flutter/commit/b1d17c914dec8e09cf2cec5351afeef2996ff89e
  * Author @jonahwilliams, original approver @goderbauer 
* NoSuchMethodError: The method 'cancel' was called on null
  * https://github.com/flutter/flutter/issues/65903
  * https://github.com/flutter/flutter/commit/6acea15f220a35498736111f2b7fbfbd41580ad9
  * Author @jonahwilliams, original approvers @jmagman & @christopherfujino 
* "print" statements do not work with iOS 13.7 physical device
  * https://github.com/flutter/flutter/issues/65519
  * https://github.com/flutter/flutter/commit/658e6c8a8d7739140fc06d29f26e595ecaa2d6ff
  * Author @jmagman, original approvers @jonahwilliams

### CODE REVIEW

**Review by jmagman — APPROVED** [review]
#65519 LGTM

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Review by goderbauer — APPROVED** [review]
LGTM
