### ISSUE TITLE
reportFullyDrawn seems to require extra permissions on some API levels

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#46172]
I happened to test something on API 19 today, which is the first API level where `Activity.reportFullyDrawn` was supported.  I ended up with a stack trace saying I didn't have `android.permissions.UPDATE_DEVICE_STATS`.  This is documented as not being for use by third party apps.  Adding it to my manifest made the crash go away.

We may want to either remove the `reportFullyDrawn` line and just let users do it when they think it's right, or raise the API level to something safer.

/cc @matthew-carroll @xster

**Comment by xster** [comment]
copy pasting previous comment from @skreborn

> There's a StackOverflow issue (https://stackoverflow.com/questions/39828918/is-there-a-workaround-for-method-reportfullydrawn). This is a known bug and there was an attempt to remove the permission requirement (https://android-review.googlesource.com/c/platform/frameworks/base/+/100800), but the changes were abandoned after Lollipop because usage stats were now measured in a different way. Unfortunately, it looks like we'll just have to catch that exception and handle it, because there's no other way around.

We should just exclude API 19 from this code path

**Comment by RadianEleven** [comment]
How do i add it to manifest?

**Comment by dnfield** [comment]
The permission for the manifest is one that is marked as being for internal usage, unfortunately (`android.permissions.UPDATE_DEVICE_STATS`).  I'm not sure your app would be accepted with it in there.

You can _probably_ work around this by subclassing FlutterActivity and overriding `onFlutterUiDisplayed` to call `super` in a `try/catch` block.  Or, you can build your own local engine with the linked pull request that fixed this in the engine.

Unfortunately, this bug is very specific to API 19.

**Comment by RadianEleven** [comment]
The thing is i'm not using AVD, i am using my phone and it is still not working.

**Comment by RadianEleven** [comment]
Syncing files to device GT I9195...
I/flutter ( 6001): APP SRATED
E/flutter ( 6001): [ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(39)] java.lang.SecurityException: uid 10178 does not have android.permission.UPDATE_DEVICE_STATS.
E/flutter ( 6001): 	at android.os.Parcel.readException(Parcel.java:1465)
E/flutter ( 6001): 	at android.os.Parcel.readException(Parcel.java:1419)
E/flutter ( 6001): 	at android.app.ActivityManagerProxy.reportActivityFullyDrawn(ActivityManagerNative.java:5581)
E/flutter ( 6001): 	at android.app.Activity.reportFullyDrawn(Activity.java:1561)
E/flutter ( 6001): 	at io.flutter.embedding.android.FlutterActivity.onFlutterUiDisplayed(FlutterActivity.java:942)
E/flutter ( 6001): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate$1.onFlutterUiDisplayed(FlutterActivityAndFragmentDelegate.java:90)
E/flutter ( 6001): 	at io.flutter.embedding.android.FlutterView$2.onFlutterUiDisplayed(FlutterView.java:119)
E/flutter ( 6001): 	at io.flutter.embedding.engine.FlutterJNI.onFirstFrame(FlutterJNI.java:262)
E/flutter ( 6001): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter ( 6001): 	at android.os.MessageQueue.next(MessageQueue.java:138)
E/flutter ( 6001): 	at android.os.Looper.loop(Looper.java:131)
E/flutter ( 6001): 	at android.app.ActivityThread.main(ActivityThread.java:5593)
E/flutter ( 6001): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/flutter ( 6001): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/flutter ( 6001): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
E/flutter ( 6001): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
E/flutter ( 6001): 	at dalvik.system.NativeStart.main(Native Method)
E/flutter ( 6001): 
F/flutter ( 6001): [FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(111)] Check failed: CheckException(env). 
Lost connection to device.
Could not update files on device: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:64797/JBYtxBQqy84=/

**Comment by RadianEleven** [comment]
that is what errors i get

**Comment by RadianEleven** [comment]
I added the permission to my xml, still not working

**Comment by dnfield** [comment]
Right - that permission is actually an Android internal one, and there's a bug with `reportFullyDrawn` in API 19 that causes it to be requested - but there's no way to grant it.

**Comment by nicodoss** [comment]
Hi, i have the same problem, my app crash on kitkat vesion after upgrade my flutter version to 1.12.13 ,so just want to know if we fix the problem to redownload it(flutter).

**Comment by elmissouri16** [comment]
same issue for me  is there any update on this  ??

**Comment by chenshuiluke** [comment]
Is there no fix for this?

**Comment by dnfield** [comment]
Is the workaround from https://github.com/flutter/flutter/issues/46172#issuecomment-567200119 not working for you?

**Comment by elmissouri16** [comment]
@dnfield  honestly I dint know how to implement it if you can guide will be great thank you

**Comment by dnfield** [comment]
Open MainActivity.kt and add the following:

```kt
    override fun onFlutterUiDisplayed() {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
            reportFullyDrawn();
        }
    }
```

to `class MainActivity: FlutterActivity() {`.

If it's java, do the Java equivalent:

```java
@Override
  public void onFlutterUiDisplayed() {
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
      reportFullyDrawn();
    }
  }
```

**Comment by elmissouri16** [comment]
@dnfield thanks for the help i manage to get work with thats

**Comment by RadianEleven** [comment]
It still doesnt work

**Comment by digitalindiaapps** [comment]
### it gives error 
****
Activity.kt: (16, 38): Unresolved reference: Build

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugKotlin'.
> Compilation error. See log for more details

**Comment by dnfield** [comment]
You're missing an `import android.os.Build `

**Comment by HiPipilu** [comment]
> Open MainActivity.kt and add the following:
> 
> ```kotlin
>     override fun onFlutterUiDisplayed() {
>         if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
>             reportFullyDrawn();
>         }
>     }
> ```
> 
> to `class MainActivity: FlutterActivity() {`.
> 
> If it's java, do the Java equivalent:
> 
> ```java
> @Override
>   public void onFlutterUiDisplayed() {
>     if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
>       reportFullyDrawn();
>     }
>   }
> ```

It work,thank you

**Comment by manglide** [comment]
> Open MainActivity.kt and add the following:
> 
> ```kotlin
>     override fun onFlutterUiDisplayed() {
>         if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
>             reportFullyDrawn();
>         }
>     }
> ```
> 
> to `class MainActivity: FlutterActivity() {`.
> 
> If it's java, do the Java equivalent:
> 
> ```java
> @Override
>   public void onFlutterUiDisplayed() {
>     if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
>       reportFullyDrawn();
>     }
>   }
> ```

This works thanks.

**Comment by RadianEleven** [comment]
it doesnt recognize the repoftFullyDrawn function
