### ISSUE TITLE
iOS build is crashing when trying to use cloud_functions in combination with cloud_firestore and/or firebase_database

### ISSUE THREAD

**Issue by MartinRippel** [flutter/flutter#21885]
I want to use the Firebase plugins `cloud_functions`, `cloud_firestore` and `firebase_database` in my new Flutter project. When trying to build the project for an simulated iPhone 7 Plus the Xcode build crashes. When only using the `cloud_functions` plugin but not `cloud_functions` and/or `cloud_firestore` it works fine. It also works fine when only using `cloud_firestore` and/or `firebase_database` but not `cloud_functions`. In fact the build only crashes when I combine `cloud_functions` with one or both of the other plugins.
I could not find any info regarding this problem so far, so maybe you can help me with this.

## Steps to Reproduce

1. Create a new flutter project
2. Get an `GoogleService-Info.plist` file for your Firebase project and include it in Xcode as Firebase is telling you
3. Add the following dependencies to the file `pubspec.yaml` inside the new project:
`firebase_core: ^0.2.5`
`cloud_firestore: ^0.8.0`
`firebase_auth: ^0.5.20`
`firebase_database: ^1.0.4`
`cloud_functions: ^0.0.4`
![pubspec_yaml](https://user-images.githubusercontent.com/31508956/45571007-206ca980-b865-11e8-898d-51ed44c83716.jpg)
4. Run the command `flutter packages get`
5. Start the project with the command `flutter run` to start the project
The app will try to start the app, before the build finally fails.

## Logs
When running the command `flutter run --verbose` the output is as follows. Here as pdf because the output is to long for GitHub to handle (only 65536 characters are allowed):
[Flutter run output.pdf](https://github.com/flutter/flutter/files/2384653/Flutter.run.output.pdf)

Alternatively here is the version for the command `flutter run`:
```
$ flutter run -d A0C8531C-54C8-447E-9BDF-4EDAA3FA7DC6
Launching lib/main.dart on iPhone 7 Plus in debug mode...
Starting Xcode build...                                          
Xcode build done.                                            2.2s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **
    
Xcode's output:
↳
    In file included from /Users/martinrippel/Documents/Development/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_functions-0.0.4/ios/Classes/CloudFunctionsPlugin.m:5:
    In file included from /Users/martinrippel/Documents/Development/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_functions-0.0.4/ios/Classes/CloudFunctionsPlugin.h:1:
    In file included from /Users/martinrippel/Documents/Development/test/flutter_tests/ios/Pods/Headers/Public/Flutter/Flutter/Flutter.h:40:
    In file included from /Users/martinrippel/Documents/Development/test/flutter_tests/ios/Pods/Headers/Public/Flutter/Flutter/FlutterAppDelegate.h:11:
    /Users/martinrippel/Documents/Development/test/flutter_tests/ios/Pods/Headers/Public/Flutter/Flutter/FlutterPlugin.h:100:42: warning: 'UIUserNotificationSettings' is only available on iOS 8.0 or newer [-Wunguarded-availability]
        didRegisterUserNotificationSettings:(UIUserNotificationSettings*)notificationSettings;
                                             ^
    In module 'UIKit' imported from /Users/martinrippel/Documents/Development/test/flutter_tests/ios/Pods/Target Support Files/cloud_functions/cloud_functions-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.4.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIUserNotificationSettings.h:43:12: note: 'UIUserNotificationSettings' has been explicitly marked partial here
    @interface UIUserNotificationSettings : NSObject
               ^
    In file included from /Users/martinrippel/Documents/Development/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_functions-0.0.4/ios/Classes/CloudFunctionsPlugin.m:5:
    In file included from /Users/martinrippel/Documents/Development/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_functions-0.0.4/ios/Classes/CloudFunctionsPlugin.h:1:
    In file included from /Users/martinrippel/Documents/Development/test/flutter_tests/ios/Pods/Headers/Public/Flutter/Flutter/Flutter.h:40:
    In file included from /Users/martinrippel/Documents/Development/test/flutter_tests/ios/Pods/Headers/Public/Flutter/Flutter/FlutterAppDelegate.h:11:
    /Users/martinrippel/Documents/Development/test/flutter_tests/ios/Pods/Headers/Public/Flutter/Flutter/FlutterPlugin.h:99:1: note: annotate 'application:didRegisterUserNotificationSettings:' with an availability attribute to silence this warning
    - (void)application:(UIApplication*)application
    ^
    /Users/martinrippel/Documents/Development/test/flutter_tests/ios/Pods/Headers/Public/Flutter/Flutter/FlutterPlugin.h:115:44: warning: 'UIBackgroundFetchResult' is only available on iOS 7.0 or newer [-Wunguarded-availability]
              fetchCompletionHandler:(void (^)(UIBackgroundFetchResult result))completionHandler;
                                               ^
    In module 'UIKit' imported from /Users/martinrippel/Documents/Development/test/flutter_tests/ios/Pods/Target Support Files/cloud_functions/cloud_functions-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.4.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIApplication.h:76:29: note: 'UIBackgroundFetchResult' has been explicitly marked partial here
    typedef NS_ENUM(NSUInteger, UIBackgroundFetchResult) {
                                ^
    In file included from /Users/martinrippel/Documents/Development/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_functions-0.0.4/ios/Classes/CloudFunctionsPlugin.m:5:
    In file included from /Users/martinrippel/Documents/Development/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_functions-0.0.4/ios/Classes/CloudFunctionsPlugin.h:1:
    In file included from /Users/martinrippel/Documents/Development/test/flutter_tests/ios/Pods/Headers/Public/Flutter/Flutter/Flutter.h:40:
    In file included from /Users/martinrippel/Documents/Development/test/flutter_tests/ios/Pods/Headers/Public/Flutter/Flutter/FlutterAppDelegate.h:11:
    /Users/martinrippel/Documents/Development/test/flutter_tests/ios/Pods/Headers/Public/Flutter/Flutter/FlutterPlugin.h:113:1: note: annotate 'application:didReceiveRemoteNotification:fetchCompletionHandler:' with an availability attribute to silence this warning
    - (BOOL)application:(UIApplication*)application
    ^
    /Users/martinrippel/Documents/Development/test/flutter_tests/ios/Pods/Headers/Public/Flutter/Flutter/FlutterPlugin.h:168:49: warning: 'UIBackgroundFetchResult' is only available on iOS 7.0 or newer [-Wunguarded-availability]
        performFetchWithCompletionHandler:(void (^)(UIBackgroundFetchResult result))completionHandler;
                                                    ^
    In module 'UIKit' imported from /Users/martinrippel/Documents/Development/test/flutter_tests/ios/Pods/Target Support Files/cloud_functions/cloud_functions-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.4.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIApplication.h:76:29: note: 'UIBackgroundFetchResult' has been explicitly marked partial here
    typedef NS_ENUM(NSUInteger, UIBackgroundFetchResult) {
                                ^
    In file included from /Users/martinrippel/Documents/Development/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_functions-0.0.4/ios/Classes/CloudFunctionsPlugin.m:5:
    In file included from /Users/martinrippel/Documents/Development/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_functions-0.0.4/ios/Classes/CloudFunctionsPlugin.h:1:
    In file included from /Users/martinrippel/Documents/Development/test/flutter_tests/ios/Pods/Headers/Public/Flutter/Flutter/Flutter.h:40:
    In file included from /Users/martinrippel/Documents/Development/test/flutter_tests/ios/Pods/Headers/Public/Flutter/Flutter/FlutterAppDelegate.h:11:
    /Users/martinrippel/Documents/Development/test/flutter_tests/ios/Pods/Headers/Public/Flutter/Flutter/FlutterPlugin.h:167:1: note: annotate 'application:performFetchWithCompletionHandler:' with an availability attribute to silence this warning
    - (BOOL)application:(UIApplication*)application
    ^
    /Users/martinrippel/Documents/Development/test/flutter_tests/ios/Pods/Headers/Public/Flutter/Flutter/FlutterPlugin.h:176:27: warning: 'NSUserActivity' is only available on iOS 8.0 or newer [-Wunguarded-availability]
        continueUserActivity:(NSUserActivity*)userActivity
                              ^
    In module 'Foundation' imported from /Users/martinrippel/Documents/Development/test/flutter_tests/ios/Pods/Headers/Public/Flutter/Flutter/FlutterBinaryMessenger.h:8:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.4.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSUserActivity.h:17:12: note: 'NSUserActivity' has been explicitly marked partial here
    @interface NSUserActivity : NSObject
               ^
    In file included from /Users/martinrippel/Documents/Development/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_functions-0.0.4/ios/Classes/CloudFunctionsPlugin.m:5:
    In file included from /Users/martinrippel/Documents/Development/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_functions-0.0.4/ios/Classes/CloudFunctionsPlugin.h:1:
    In file included from /Users/martinrippel/Documents/Development/test/flutter_tests/ios/Pods/Headers/Public/Flutter/Flutter/Flutter.h:40:
    In file included from /Users/martinrippel/Documents/Development/test/flutter_tests/ios/Pods/Headers/Public/Flutter/Flutter/FlutterAppDelegate.h:11:
    /Users/martinrippel/Documents/Development/test/flutter_tests/ios/Pods/Headers/Public/Flutter/Flutter/FlutterPlugin.h:175:1: note: annotate 'application:continueUserActivity:restorationHandler:' with an availability attribute to silence this warning
    - (BOOL)application:(UIApplication*)application
    ^
    In file included from /Users/martinrippel/Documents/Development/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_functions-0.0.4/ios/Classes/CloudFunctionsPlugin.m:5:
    In file included from /Users/martinrippel/Documents/Development/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_functions-0.0.4/ios/Classes/CloudFunctionsPlugin.h:1:
    In file included from /Users/martinrippel/Documents/Development/test/flutter_tests/ios/Pods/Headers/Public/Flutter/Flutter/Flutter.h:50:
    /Users/martinrippel/Documents/Development/test/flutter_tests/ios/Pods/Headers/Public/Flutter/Flutter/FlutterPluginAppLifeCycleDelegate.h:70:42: warning: 'UIUserNotificationSettings' is only available on iOS 8.0 or newer [-Wunguarded-availability]
        didRegisterUserNotificationSettings:(UIUserNotificationSettings*)notificationSettings;
                                             ^
    In module 'UIKit' imported from /Users/martinrippel/Documents/Development/test/flutter_tests/ios/Pods/Target Support Files/cloud_functions/cloud_functions-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.4.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIUserNotificationSettings.h:43:12: note: 'UIUserNotificationSettings' has been explicitly marked partial here
    @interface UIUserNotificationSettings : NSObject
               ^
    In file included from /Users/martinrippel/Documents/Development/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_functions-0.0.4/ios/Classes/CloudFunctionsPlugin.m:5:
    In file included from /Users/martinrippel/Documents/Development/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_functions-0.0.4/ios/Classes/CloudFunctionsPlugin.h:1:
    In file included from /Users/martinrippel/Documents/Development/test/flutter_tests/ios/Pods/Headers/Public/Flutter/Flutter/Flutter.h:50:
    /Users/martinrippel/Documents/Development/test/flutter_tests/ios/Pods/Headers/Public/Flutter/Flutter/FlutterPluginAppLifeCycleDelegate.h:69:1: note: annotate 'application:didRegisterUserNotificationSettings:' with an availability attribute to silence this warning
    - (void)application:(UIApplication*)application
    ^
    /Users/martinrippel/Documents/Development/test/flutter_tests/ios/Pods/Headers/Public/Flutter/Flutter/FlutterPluginAppLifeCycleDelegate.h:83:44: warning: 'UIBackgroundFetchResult' is only available on iOS 7.0 or newer [-Wunguarded-availability]
              fetchCompletionHandler:(void (^)(UIBackgroundFetchResult result))completionHandler;
                                               ^
    In module 'UIKit' imported from /Users/martinrippel/Documents/Development/test/flutter_tests/ios/Pods/Target Support Files/cloud_functions/cloud_functions-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.4.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIApplication.h:76:29: note: 'UIBackgroundFetchResult' has been explicitly marked partial here
    typedef NS_ENUM(NSUInteger, UIBackgroundFetchResult) {
                                ^
    In file included from /Users/martinrippel/Documents/Development/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_functions-0.0.4/ios/Classes/CloudFunctionsPlugin.m:5:
    In file included from /Users/martinrippel/Documents/Development/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_functions-0.0.4/ios/Classes/CloudFunctionsPlugin.h:1:
    In file included from /Users/martinrippel/Documents/Development/test/flutter_tests/ios/Pods/Headers/Public/Flutter/Flutter/Flutter.h:50:
    /Users/martinrippel/Documents/Development/test/flutter_tests/ios/Pods/Headers/Public/Flutter/Flutter/FlutterPluginAppLifeCycleDelegate.h:81:1: note: annotate 'application:didReceiveRemoteNotification:fetchCompletionHandler:' with an availability attribute to silence this warning
    - (void)application:(UIApplication*)application
    ^
    /Users/martinrippel/Documents/Development/test/flutter_tests/ios/Pods/Headers/Public/Flutter/Flutter/FlutterPluginAppLifeCycleDelegate.h:139:49: warning: 'UIBackgroundFetchResult' is only available on iOS 7.0 or newer [-Wunguarded-availability]
        performFetchWithCompletionHandler:(void (^)(UIBackgroundFetchResult result))completionHandler;
                                                    ^
    In module 'UIKit' imported from /Users/martinrippel/Documents/Development/test/flutter_tests/ios/Pods/Target Support Files/cloud_functions/cloud_functions-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.4.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIApplication.h:76:29: note: 'UIBackgroundFetchResult' has been explicitly marked partial here
    typedef NS_ENUM(NSUInteger, UIBackgroundFetchResult) {
                                ^
    In file included from /Users/martinrippel/Documents/Development/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_functions-0.0.4/ios/Classes/CloudFunctionsPlugin.m:5:
    In file included from /Users/martinrippel/Documents/Development/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_functions-0.0.4/ios/Classes/CloudFunctionsPlugin.h:1:
    In file included from /Users/martinrippel/Documents/Development/test/flutter_tests/ios/Pods/Headers/Public/Flutter/Flutter/Flutter.h:50:
    /Users/martinrippel/Documents/Development/test/flutter_tests/ios/Pods/Headers/Public/Flutter/Flutter/FlutterPluginAppLifeCycleDelegate.h:138:1: note: annotate 'application:performFetchWithCompletionHandler:' with an availability attribute to silence this warning
    - (BOOL)application:(UIApplication*)application
    ^
    /Users/martinrippel/Documents/Development/test/flutter_tests/ios/Pods/Headers/Public/Flutter/Flutter/FlutterPluginAppLifeCycleDelegate.h:147:27: warning: 'NSUserActivity' is only available on iOS 8.0 or newer [-Wunguarded-availability]
        continueUserActivity:(NSUserActivity*)userActivity
                              ^
    In module 'Foundation' imported from /Users/martinrippel/Documents/Development/test/flutter_tests/ios/Pods/Headers/Public/Flutter/Flutter/FlutterBinaryMessenger.h:8:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.4.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSUserActivity.h:17:12: note: 'NSUserActivity' has been explicitly marked partial here
    @interface NSUserActivity : NSObject
               ^
    In file included from /Users/martinrippel/Documents/Development/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_functions-0.0.4/ios/Classes/CloudFunctionsPlugin.m:5:
    In file included from /Users/martinrippel/Documents/Development/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_functions-0.0.4/ios/Classes/CloudFunctionsPlugin.h:1:
    In file included from /Users/martinrippel/Documents/Development/test/flutter_tests/ios/Pods/Headers/Public/Flutter/Flutter/Flutter.h:50:
    /Users/martinrippel/Documents/Development/test/flutter_tests/ios/Pods/Headers/Public/Flutter/Flutter/FlutterPluginAppLifeCycleDelegate.h:146:1: note: annotate 'application:continueUserActivity:restorationHandler:' with an availability attribute to silence this warning
    - (BOOL)application:(UIApplication*)application
    ^
    In file included from /Users/martinrippel/Documents/Development/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_functions-0.0.4/ios/Classes/CloudFunctionsPlugin.m:8:
    In file included from /Users/martinrippel/Documents/Development/test/flutter_tests/ios/Pods/Headers/Private/Firebase/Firebase.h:26:
    In file included from /Users/martinrippel/Documents/Development/test/flutter_tests/ios/Pods/Headers/Private/FirebaseDatabase/FirebaseDatabase.h:20:
    /Users/martinrippel/Documents/Development/test/flutter_tests/ios/Pods/Headers/Private/FirebaseDatabase/FIRDatabase.h:154:1: error: property with 'retain (or strong)' attribute must be of object type
    @property (nonatomic, strong) dispatch_queue_t callbackQueue;
    ^
    In file included from /Users/martinrippel/Documents/Development/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_functions-0.0.4/ios/Classes/CloudFunctionsPlugin.m:8:
    In file included from /Users/martinrippel/Documents/Development/test/flutter_tests/ios/Pods/Headers/Private/Firebase/Firebase.h:34:
    In file included from /Users/martinrippel/Documents/Development/test/flutter_tests/ios/Pods/Headers/Private/FirebaseFirestore/FirebaseFirestore.h:25:
    /Users/martinrippel/Documents/Development/test/flutter_tests/ios/Pods/Headers/Private/FirebaseFirestore/FIRFirestoreSettings.h:42:1: error: property with 'retain (or strong)' attribute must be of object type
    @property(nonatomic, strong) dispatch_queue_t dispatchQueue;
    ^
    /Users/martinrippel/Documents/Development/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_functions-0.0.4/ios/Classes/CloudFunctionsPlugin.m:55:35: warning: null passed to a callee that requires a non-null argument [-Wnonnull]
                        [FlutterError errorWithCode:nil message:error.localizedDescription details:nil];
                                      ^             ~~~
    /Users/martinrippel/Documents/Development/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_functions-0.0.4/ios/Classes/CloudFunctionsPlugin.m:36:30: warning: 'objectForKeyedSubscript:' is only available on iOS 6.0 or newer [-Wunguarded-availability]
        NSString *functionName = call.arguments[@"functionName"];
                                 ^~~~
    In module 'Foundation' imported from /Users/martinrippel/Documents/Development/test/flutter_tests/ios/Pods/Headers/Public/Flutter/Flutter/FlutterBinaryMessenger.h:8:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.4.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSDictionary.h:50:1: note: 'objectForKeyedSubscript:' has been explicitly marked partial here
    - (nullable ObjectType)objectForKeyedSubscript:(KeyType)key API_AVAILABLE(macos(10.8), ios(6.0), watchos(2.0), tvos(9.0));
    ^
    /Users/martinrippel/Documents/Development/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_functions-0.0.4/ios/Classes/CloudFunctionsPlugin.m:36:30: note: enclose 'objectForKeyedSubscript:' in an @available check to silence this warning
        NSString *functionName = call.arguments[@"functionName"];
                                 ^~~~
    /Users/martinrippel/Documents/Development/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_functions-0.0.4/ios/Classes/CloudFunctionsPlugin.m:37:28: warning: 'objectForKeyedSubscript:' is only available on iOS 6.0 or newer [-Wunguarded-availability]
        NSObject *parameters = call.arguments[@"parameters"];
                               ^~~~
    In module 'Foundation' imported from /Users/martinrippel/Documents/Development/test/flutter_tests/ios/Pods/Headers/Public/Flutter/Flutter/FlutterBinaryMessenger.h:8:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.4.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSDictionary.h:50:1: note: 'objectForKeyedSubscript:' has been explicitly marked partial here
    - (nullable ObjectType)objectForKeyedSubscript:(KeyType)key API_AVAILABLE(macos(10.8), ios(6.0), watchos(2.0), tvos(9.0));
    ^
    /Users/martinrippel/Documents/Development/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_functions-0.0.4/ios/Classes/CloudFunctionsPlugin.m:37:28: note: enclose 'objectForKeyedSubscript:' in an @available check to silence this warning
        NSObject *parameters = call.arguments[@"parameters"];
                               ^~~~
    /Users/martinrippel/Documents/Development/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_functions-0.0.4/ios/Classes/CloudFunctionsPlugin.m:51:56: warning: 'objectForKeyedSubscript:' is only available on iOS 6.0 or newer [-Wunguarded-availability]
                                              @"details" : error.userInfo[FIRFunctionsErrorDetailsKey]
                                                           ^~~~~
    In module 'Foundation' imported from /Users/martinrippel/Documents/Development/test/flutter_tests/ios/Pods/Headers/Public/Flutter/Flutter/FlutterBinaryMessenger.h:8:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.4.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSDictionary.h:50:1: note: 'objectForKeyedSubscript:' has been explicitly marked partial here
    - (nullable ObjectType)objectForKeyedSubscript:(KeyType)key API_AVAILABLE(macos(10.8), ios(6.0), watchos(2.0), tvos(9.0));
    ^
    /Users/martinrippel/Documents/Development/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_functions-0.0.4/ios/Classes/CloudFunctionsPlugin.m:51:56: note: enclose 'objectForKeyedSubscript:' in an @available check to silence this warning
                                              @"details" : error.userInfo[FIRFunctionsErrorDetailsKey]
                                                           ^~~~~
    12 warnings and 2 errors generated.
Could not build the application for the simulator.
Error launching application on iPhone 7 Plus.
```

The command `flutter analyse` produces the following output:
```
Analyzing flutter_tests...                                       
No issues found! (ran in 1.0s)
```

The command `flutter doctor -v` produces this result:
```
[✓] Flutter (Channel beta, v0.7.3, on Mac OS X 10.13.6 17G2307, locale en-DE)
    • Flutter version 0.7.3 at /Users/martinrippel/Documents/Development/flutter
    • Framework revision 3b309bda07 (2 weeks ago), 2018-08-28 12:39:24 -0700
    • Engine revision af42b6dc95
    • Dart version 2.1.0-dev.1.0.flutter-ccb16f7282

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.2)
    • Android SDK at /Users/martinrippel/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.27.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.18.0

[✓] Connected devices (1 available)
    • iPhone 7 Plus • A0C8531C-54C8-447E-9BDF-4EDAA3FA7DC6 • ios • iOS 11.4 (simulator)

• No issues found!
```

Many thanks in advance for your help.

**Comment by evelyne24** [comment]
Maybe be similar to #21866 ?

**Comment by MartinRippel** [comment]
I have to add, that I am using Xcode Version 9.4.1 and the iPhone 7 Plus simulator is running iOS 11.4

**Comment by zoechi** [comment]
Please try

```
cd ios
rm -rf Podfile.lock Pods
pod repo update
flutter clean
flutter run
```

als try commenting in/out `use_frameworks!` in `Podfile`

**Comment by MartinRippel** [comment]
Thank you for your answer zoechi. Unfortunately both of your proposed solutions have not worked for me.
Currently I am using the following versions of Flutter and Cocoapods:
```
$ flutter --version
Flutter 0.7.3 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 3b309bda07 (3 weeks ago) • 2018-08-28 12:39:24 -0700
Engine • revision af42b6dc95
Tools • Dart 2.1.0-dev.1.0.flutter-ccb16f7282
$ pod --version
1.5.3
```
Maybe this info could help solving the problem.

Please also find the new console output (`use_frameworks!` is activated):
```
Launching lib/main.dart on iPhone 7 Plus in debug mode...
Running pod install...                                      12.1s
Starting Xcode build...
Xcode build done.                                           13.2s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    /Users/martinrippel/Documents/Development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.2.5/ios/Classes/FirebaseCorePlugin.m:13:17: warning: property 'dictionary' requires method 'dictionary' to be defined - use @dynamic or provide a method implementation in this category [-Wobjc-property-implementation]
    @implementation FIROptions (FLTFirebaseCorePlugin)
                    ^
    /Users/martinrippel/Documents/Development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.2.5/ios/Classes/FirebaseCorePlugin.m:10:46: note: property declared here
    @property(readonly, nonatomic) NSDictionary *dictionary;
                                                 ^
    1 warning generated.
    While building module 'FirebaseDatabase' imported from /Users/martinrippel/Documents/Development/test/flutter_tests/ios/Pods/Headers/Public/Firebase/Firebase.h:26:
    In file included from <module-includes>:1:
    In file included from /Users/martinrippel/Documents/Development/test/flutter_tests/ios/Pods/Target Support Files/FirebaseDatabase/FirebaseDatabase-umbrella.h:13:
    /Users/martinrippel/Documents/Development/test/flutter_tests/ios/Pods/FirebaseDatabase/Firebase/Database/Public/FIRDatabase.h:154:1: error: property with 'retain (or strong)' attribute must be of object type
    @property (nonatomic, strong) dispatch_queue_t callbackQueue;
    ^
    1 error generated.
    In file included from /Users/martinrippel/Documents/Development/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_functions-0.0.4/ios/Classes/CloudFunctionsPlugin.m:8:
    /Users/martinrippel/Documents/Development/test/flutter_tests/ios/Pods/Headers/Public/Firebase/Firebase.h:26:13: fatal error: could not build module 'FirebaseDatabase'
        #import <FirebaseDatabase/FirebaseDatabase.h>
         ~~~~~~~^
    2 errors generated.
Could not build the application for the simulator.
Error launching application on iPhone 7 Plus.
```

**Comment by unknownzebra** [comment]
I'm having this exact problem. It first occurred when I updated cloud_functions from 0.0.2 to 0.0.4.

@MartinRippel Were you able to fix this issue?
