### ISSUE TITLE
Local Auth Android Plugin does not work with flutter 3.29+

### ISSUE THREAD

**Issue by derekpitts28** [flutter/flutter#166062]
### Steps to reproduce

Use the local auth plugin on a project with flutter 3.29.

### Expected results

Build without error.

### Actual results

Plugin will fail with error:

```
/Users/derekpitts/.pub-cache/hosted/pub.dev/local_auth_android-1.0.38/android/src/main/java/io/flutter/plugins/localauth/LocalAuthPlugin.java:79: error: cannot find symbol
  public static void registerWith(@NonNull PluginRegistry.Registrar registrar) {
                                                         ^
  symbol:   class Registrar
  location: interface PluginRegistry
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':local_auth_android:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

### Code sample

NA

### Screenshots or Video

NA

### Logs

<details open><summary>Logs</summary>

```console
/Users/derekpitts/.pub-cache/hosted/pub.dev/local_auth_android-1.0.38/android/src/main/java/io/flutter/plugins/localauth/LocalAuthPlugin.java:79: error: cannot find symbol
  public static void registerWith(@NonNull PluginRegistry.Registrar registrar) {
                                                         ^
  symbol:   class Registrar
  location: interface PluginRegistry
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':local_auth_android:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.29.2, on macOS 14.7.4 23H420 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.97.2)
[✓] Connected device (7 available)
[✓] Network resources

• No issues found!

```

</details>

**Comment by maheshj01** [comment]
> /Users/derekpitts/.pub-cache/hosted/pub.dev/local_auth_android-1.0.38/android/src/main/java/io/flutter/plugins/localauth/LocalAuthPlugin.java:79: error: cannot find symbol
  public static void registerWith(@NonNull PluginRegistry.Registrar registrar) {
  
@derekpitts28 from your logs it seems flutter tool is not fetching the latest package the current version of the android plugin is  `local_auth_android: ^1.0.48` 

Run

```
flutter pub upgrade
flutter pub get
flutter run
```

And this should resolve the issue
