### ISSUE TITLE
[Android] Flutter 3.35.1 cannot customize the version code during compilation.

### ISSUE THREAD

**Issue by mumu-lhl** [flutter/flutter#173917]
### Steps to reproduce

Add this code to `build.gradle.kts`:

```kotlin
val abiCodes = mapOf("x86_64" to 1, "armeabi-v7a" to 2, "arm64-v8a" to 3, "universal" to 4)

androidComponents {
    onVariants { variant ->

        variant.outputs.forEach { output ->
            val name = output.filters.find { it.filterType == ABI }?.identifier

            val baseAbiCode = abiCodes[name ?: "universal"]
            if (baseAbiCode != null) {
                output.versionCode.set(output.versionCode.get() * 10000 + baseAbiCode * 1000)
            }
        }
    }
}
```

It works fine in Flutter 3.32.X, but not in 3.35.X. This issue is suspected to be caused by #169816.

### Expected results

Version code for each arch:

* `x86_64` - XX1000
* `armeabi-v7a` - XX2000
* `arm64-v8a` - XX3000
* `universal` - XX4000

Since the format XX[version code] is required by F-Droid, I hope there is a solution that can achieve this.

### Actual results

Version code for each arch:

* `x86_64` - 40xx
* `armeabi-v7a` - 10XX
* `arm64-v8a` - 20XX

### Code sample

Same as above.

### Flutter Doctor output

It doesn't matter.

**Comment by tirth-patel-nc** [comment]
@mumu-lhl thanks for the report. I added the snippet in build.gradle.kts (both project and app level) but ran into errors for both 3.32 & 3.35. Could you please share a proper runnable snippet and any missing steps/config so we can verify on our end? Since you confirmed it’s a regression, we’d like to reproduce it correctly.

```console
tirthpatel@Tirths-MacBook-Pro au18 % flutter build apk --split-per-abi 
e: file:///Users/tirthpatel/au18/android/app/build.gradle.kts:52:63: Unresolved reference: ABI

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/tirthpatel/au18/android/app/build.gradle.kts' line: 52

* What went wrong:
Script compilation error:

  Line 52:             val name = output.filters.find { it.filterType == ABI }?.identifier
                                                                         ^ Unresolved reference: ABI

1 error

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 1s
Running Gradle task 'assembleRelease'...                         1,640ms
Gradle task assembleRelease failed with exit code 1
tirthpatel@Tirths-MacBook-Pro au18 % 
```

also please confirm whether #62005 is somewhat related to your case or not.

**Comment by mumu-lhl** [comment]
Here's my build.gralde.kts https://github.com/mumu-lhl/Ciyue/blob/main/android/app/build.gradle.kts 

#62005 seems to have a slightly similar problem to this one.

**Comment by tirth-patel-nc** [comment]
@mumu-lhl thanks for the file. The missing part was adding the **import**, using the correct **build command,** (`flutter build apk --split-per-abi`) and verifying with **aapt dump badging**. Please include such crucial details in reports.

Thanks for the report. Seeing the same behaviour with latest SDK versions.

```
stable : 3.35.1
master : 3.33.0-1.0.pre-1468
beta   : 3.36.0-0.1.pre
```

<details>
<summary>build.gradle.kts</summary>

```gradle.kts
import com.android.build.api.variant.FilterConfiguration.FilterType.*

plugins {
    id("com.android.application")
    id("kotlin-android")
    // The Flutter Gradle Plugin must be applied after the Android and Kotlin Gradle plugins.
    id("dev.flutter.flutter-gradle-plugin")
}

android {
    namespace = "com.example.au19"
    compileSdk = flutter.compileSdkVersion
    ndkVersion = flutter.ndkVersion

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_11.toString()
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId = "com.example.au19"
        // You can update the following values to match your application needs.
        // For more information, see: https://flutter.dev/to/review-gradle-config.
        minSdk = flutter.minSdkVersion
        targetSdk = flutter.targetSdkVersion
        versionCode = flutter.versionCode
        versionName = flutter.versionName
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig = signingConfigs.getByName("debug")
        }
    }
}

flutter {
    source = "../.."
}

val abiCodes = mapOf("x86_64" to 1, "armeabi-v7a" to 2, "arm64-v8a" to 3, "universal" to 4)

androidComponents {
    onVariants { variant ->

        variant.outputs.forEach { output ->
            val name = output.filters.find { it.filterType == ABI }?.identifier

            val baseAbiCode = abiCodes[name ?: "universal"]
            if (baseAbiCode != null) {
                output.versionCode.set(output.versionCode.get() * 10000 + baseAbiCode * 1000)
            }
        }
    }
}
```

</details>

### Output: 3.32.8

```console
tirthpatel@Tirths-MacBook-Pro au19 % ~/Library/Android/sdk/build-tools/36.0.0/aapt dump badging ~/au19/build/app/outputs/flutter-apk/app-x86_64-release.apk | grep versionCode
package: name='com.example.au19' versionCode='11000' versionName='1.0.0' platformBuildVersionName='15' platformBuildVersionCode='35' compileSdkVersion='35' compileSdkVersionCodename='15'
tirthpatel@Tirths-MacBook-Pro au19 % ~/Library/Android/sdk/build-tools/36.0.0/aapt dump badging ~/au19/build/app/outputs/flutter-apk/app-arm64-v8a-release.apk | grep versionCode
package: name='com.example.au19' versionCode='13000' versionName='1.0.0' platformBuildVersionName='15' platformBuildVersionCode='35' compileSdkVersion='35' compileSdkVersionCodename='15'
tirthpatel@Tirths-MacBook-Pro au19 % ~/Library/Android/sdk/build-tools/36.0.0/aapt dump badging ~/au19/build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk | grep versionCode
package: name='com.example.au19' versionCode='12000' versionName='1.0.0' platformBuildVersionName='15' platformBuildVersionCode='35' compileSdkVersion='35' compileSdkVersionCodename='15'
```

### Output: 3.35.1, 3.33.0-1.0.pre-1468, 3.36.0-0.1.pre

```console
tirthpatel@Tirths-MacBook-Pro au19 % ~/Library/Android/sdk/build-tools/36.0.0/aapt dump badging ~/au19/build/app/outputs/flutter-apk/app-x86_64-release.apk | grep versionCode   
package: name='com.example.au19' versionCode='4001' versionName='1.0.0' platformBuildVersionName='16' platformBuildVersionCode='36' compileSdkVersion='36' compileSdkVersionCodename='16'
tirthpatel@Tirths-MacBook-Pro au19 % ~/Library/Android/sdk/build-tools/36.0.0/aapt dump badging ~/au19/build/app/outputs/flutter-apk/app-arm64-v8a-release.apk | grep versionCode  
package: name='com.example.au19' versionCode='2001' versionName='1.0.0' platformBuildVersionName='16' platformBuildVersionCode='36' compileSdkVersion='36' compileSdkVersionCodename='16'
tirthpatel@Tirths-MacBook-Pro au19 % ~/Library/Android/sdk/build-tools/36.0.0/aapt dump badging ~/au19/build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk | grep versionCode
package: name='com.example.au19' versionCode='1001' versionName='1.0.0' platformBuildVersionName='16' platformBuildVersionCode='36' compileSdkVersion='36' compileSdkVersionCodename='16'
```

**Comment by Predidit** [comment]
Seems that the fix havn't been cherry picked to stable channel.

This is a severe issue. Given that the v3.37 release is not expected for some time, could a fix be backported to v3.35.3?

**Comment by tirth-patel-nc** [comment]
It has been CP'd to 3.35.2 http://github.com/flutter/flutter/blob/master/CHANGELOG.md#3352

**Comment by gmackall** [comment]
> Seems that the fix havn't been cherry picked to stable channel.
> 
> This is a severe issue. Given that the v3.37 release is not expected for some time, could a fix be backported to v3.35.3?

This seems like a reasonable request to me, will get it cherry picked.

**Comment by gmackall** [comment]
The bot doesn't seem to be working, will do it manually tomorrow.

**Comment by gmackall** [comment]
Cherry picks have landed

**Comment by adil192** [comment]
> Cherry picks have landed

Am I correct in thinking app devs still need to wait for Flutter 3.35.3 to release?

**Comment by tirth-patel-nc** [comment]
Correct @adil192

**Comment by adil192** [comment]
I added some logs and it looks like Flutter isn't respecting the `output.versionCode` I set. It's adding an extra 1000 after I already set the versionCode to contain the abiCode.

With this gradle codeblock as shown below, Flutter changes my versionCode from 1111011 to 1112011.
If I remove this codeblock, Flutter changes the version code from 111101 to 112101.



```gradle
val abiCodes = mapOf("armeabi-v7a" to 1, "arm64-v8a" to 2, "x86_64" to 3)
androidComponents {
    onVariants { variant ->
        variant.outputs.forEach { output ->
            val abi = output.filters.find { it.filterType.name == "ABI" }?.identifier
            val abiCode = abiCodes[abi]
            print("abi=$abi, abiCode=$abiCode, output.versionCode=${output.versionCode.get()}, flutter.versionCode=${flutter.versionCode}\n")
            if (abiCode != null) {
                print("Found ABI $abi, setting version code to ${flutter.versionCode * 10 + abiCode}\n")
                output.versionCode.set(flutter.versionCode * 10 + abiCode)
            }
            print("Output: ${output}\n\n")
        }
    }
}
```
```console
➜  ricochlime git:(main) ✗ flutter build apk --split-per-abi --target-platform="android-arm"
//...
abi=armeabi-v7a, abiCode=1, output.versionCode=111101, flutter.versionCode=111101
Found ABI armeabi-v7a, setting version code to 1111011
Output: VariantOutputImpl(versionCode=property(java.lang.Integer, fixed(class java.lang.Integer, 1111011)), versionName=property(java.lang.String, map(java.lang.String provider(?) check-type())), enabled=property(java.lang.Boolean, fixed(class java.lang.Boolean, true)), variantOutputConfiguration=VariantOutputConfigurationImpl(isUniversal=false, filters=[FilterConfiguration(filterType=ABI, identifier=armeabi-v7a)]), baseName=armeabi-v7a-debug, fullName=armeabi-v7aDebug, outputFileName=property(java.lang.String, map(java.lang.String map(extension 'base' property 'archivesName') check-type())))

abi=armeabi-v7a, abiCode=1, output.versionCode=111101, flutter.versionCode=111101
Found ABI armeabi-v7a, setting version code to 1111011
Output: VariantOutputImpl(versionCode=property(java.lang.Integer, fixed(class java.lang.Integer, 1111011)), versionName=property(java.lang.String, map(java.lang.String provider(?) check-type())), enabled=property(java.lang.Boolean, fixed(class java.lang.Boolean, true)), variantOutputConfiguration=VariantOutputConfigurationImpl(isUniversal=false, filters=[FilterConfiguration(filterType=ABI, identifier=armeabi-v7a)]), baseName=armeabi-v7a-release, fullName=armeabi-v7aRelease, outputFileName=property(java.lang.String, map(java.lang.String map(extension 'base' property 'archivesName') check-type())))

abi=armeabi-v7a, abiCode=1, output.versionCode=111101, flutter.versionCode=111101
Found ABI armeabi-v7a, setting version code to 1111011
Output: VariantOutputImpl(versionCode=property(java.lang.Integer, fixed(class java.lang.Integer, 1111011)), versionName=property(java.lang.String, map(java.lang.String provider(?) check-type())), enabled=property(java.lang.Boolean, fixed(class java.lang.Boolean, true)), variantOutputConfiguration=VariantOutputConfigurationImpl(isUniversal=false, filters=[FilterConfiguration(filterType=ABI, identifier=armeabi-v7a)]), baseName=armeabi-v7a-profile, fullName=armeabi-v7aProfile, outputFileName=property(java.lang.String, map(java.lang.String map(extension 'base' property 'archivesName') check-type())))

Font asset "MaterialIcons-Regular.otf" was tree-shaken, reducing it from 1645184 to 1312 bytes (99.9% reduction). Tree-shaking can be disabled by providing the --no-tree-shake-icons flag when building your app.
Running Gradle task 'assembleRelease'...                            5.1s
✓ Built build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk (17.9MB)

➜  ricochlime git:(main) ✗ ~/Android/Sdk/build-tools/35.0.0/aapt dump badging build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
package: name='com.adilhanney.ricochlime' versionCode='1112011' versionName='1.11.10' platformBuildVersionName='16' platformBuildVersionCode='36' compileSdkVersion='36' compileSdkVersionCodename='16'
//...
```

Without this fixed, I can't publish my app to F-Droid (https://github.com/adil192/ricochlime/issues/63): `ERROR: Could not build app com.adilhanney.ricochlime: Unexpected version/version code in output; APK: '1.11.10' / '1112011',  Expected: '1.11.10' / '1111011'`

**Comment by rusty-snake** [comment]
I can confirm the behavior @adil192 sees. ~~Flutter 3.35.3 honors `output.versionCode.set()`. However it has a **undocumented breaking-change**, `flutter.versionCode` now contains a modified (#49544) value rather than the original value from pubspec.yaml.~~ Flutter 3.35.3 still adds it own opinion with `--split-per-abi` and forces this opinion on all apps that previously workaround this (#49544) or had a different/custom opinion.

**Comment by rusty-snake** [comment]
From https://github.com/flutter/flutter/blame/3.35.3/packages/flutter_tools/gradle/src/main/kotlin/FlutterPlugin.kt#L637-L640:

```kts
output.versionCodeOverride = abiVersionCode * 1000 + (
    versionCodeIfPresent
        ?: variant.mergedFlavor.versionCode as Int
)
```

`versionCodeIfPresent` was added in Flutter 3.35.3 to "fix" this issue. In order to fix this issue without introducing a **breaking-change**, the fix should have been to use `versionCodeIfPresent` w/o modifying it like:

```kts
output.versionCodeOverride = versionCodeIfPresent ?: abiVersionCode * 1000 + (variant.mergedFlavor.versionCode as Int)
```

**Comment by ImranR98** [comment]
Yes it's still broken, this issue should be re-opened.

**Comment by mboetger** [comment]
@gmackall - this was re-opened.  Can you take a look?

**Comment by gmackall** [comment]
> From https://github.com/flutter/flutter/blame/3.35.3/packages/flutter_tools/gradle/src/main/kotlin/FlutterPlugin.kt#L637-L640:
> 
> output.versionCodeOverride = abiVersionCode * 1000 + (
>     versionCodeIfPresent
>         ?: variant.mergedFlavor.versionCode as Int
> )
> `versionCodeIfPresent` was added in Flutter 3.35.3 to "fix" this issue. In order to fix this issue without introducing a **breaking-change**, the fix should have been to use `versionCodeIfPresent` w/o modifying it like:
> 
> output.versionCodeOverride = versionCodeIfPresent ?: abiVersionCode * 1000 + (variant.mergedFlavor.versionCode as Int)

Running @adil192 s code snippet on 3.29.3 and on master I see the same outputs:
```
mackall-macbookpro:versioncoderoundtwo mackall$ /Users/mackall/Library/Android/sdk/cmdline-tools/latest/bin/apkanalyzer manifest version-code build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk && /Users/mackall/Library/Android/sdk/cmdline-tools/latest/bin/apkanalyzer manifest version-code build/app/outputs/flutter-apk/app-arm64-v8a-release.apk && /Users/mackall/Library/Android/sdk/cmdline-tools/latest/bin/apkanalyzer manifest version-code build/app/outputs/flutter-apk/app-x86_64-release.apk
1011
2011
4011
```
Indicating this is not a breaking change (though it is different from the broken behavior on 3.32, see https://github.com/flutter/flutter/issues/169790). I also see the same outputs on this version for the snippet being used to modify [version codes here](https://github.com/ImranR98/Obtainium/blob/main/android/app/build.gradle.kts#L87-L99)

Is this different from what you see? (any of @ImranR98 , @rusty-snake , or @adil192 feel free to reply!) If so can you confirm this is not a breaking change but instead a return to https://github.com/flutter/flutter/issues/49544? If so feel free to follow up on that issue, and if not let me know what I'm missing

**Comment by adil192** [comment]
@gmackall Thanks for investigating. I see the same with a minimal example. I looked some more into it and it seems unrelated to Flutter 3.35, but rather in my switch from groovy to kotlin gradle files.

The solution was just to switch back to the older `android.applicationVariants` api. I [tried it before](https://github.com/adil192/ricochlime/issues/63#issuecomment-3258102753) but it didn't work for some reason, but it's working now...
```kts
val abiCodes = mapOf("armeabi-v7a" to 1, "arm64-v8a" to 2, "x86_64" to 3)
android.applicationVariants.configureEach {
    val variant = this
    variant.outputs.forEach { output ->
        val abiVersionCode = abiCodes[output.filters.find { it.filterType == "ABI" }?.identifier]
        if (abiVersionCode != null) {
            (output as ApkVariantOutputImpl).versionCodeOverride = variant.versionCode * 10 + abiVersionCode
        }
    }
}
```

**Comment by gmackall** [comment]
@adil192 Glad to hear you see the same.

I'm going to close this again for now based on that. @ImranR98 and @rusty-snake feel free to follow up if you still feel this behavior is broken in comparison to how it functioned on 3.29.
