### PR TITLE
Rewire all Dart entrypoints when the Dart plugin registrant is used.

### LINKED ISSUE #91841: Multiple entry-points in same Dart file is broken
### Steps to reproduce

Create the following Dart program:

```dart
import 'package:flutter/widgets.dart';

@pragma('vm:entry-point')
void main() {
  runApp(ColoredBox(color: Color(0xffcc0000)));
}

@pragma('vm:entry-point')
void entryPoint() {
  runApp(ColoredBox(color: Color(0xff00cc00)));
}
```

... then override `getDartEntrypointFunctionName` in the Android `MainActivity`, like so:

```kotlin
import io.flutter.embedding.android.FlutterActivity

class MainActivity: FlutterActivity() {
  override fun getDartEntrypointFunctionName(): String {
    return "entryPoint"
  }
}
```

... then run the app on an Android device.

### Expected behavior

You expect `entryPoint()` to be run as the program's entry-point, yielding a green screen.

### Actual behavior

The app fails to start, with the following error:

```
E/flutter (16188): [ERROR:flutter/shell/common/shell.cc(103)] Dart Unhandled Exception: NoSuchMethodError: No top-level getter 'entryPoint' declared.
E/flutter (16188): Receiver: top-level
E/flutter (16188): Tried calling: entryPoint, stack trace: #0      NoSuchMethodError._throwNew (dart:core-patch/errors_patch.dart:214:5)
E/flutter (16188): 
E/flutter (16188): [ERROR:flutter/runtime/dart_isolate.cc(727)] Could not resolve main entrypoint function.
E/flutter (16188): [ERROR:flutter/runtime/dart_isolate.cc(195)] Could not run the run main Dart entrypoint.
E/flutter (16188): [ERROR:flutter/runtime/runtime_controller.cc(415)] Could not create root isolate.
E/flutter (16188): [ERROR:flutter/shell/common/shell.cc(588)] Could not launch engine with configuration.
```

## Notes

This scenario has been created in https://github.com/tvolkert/entrypoint

## Culprit

This appears to have been introduced by https://github.com/flutter/flutter/pull/79669

### PR DESCRIPTION
**Pull request by blasten**
Fixes https://github.com/flutter/flutter/issues/91841
Fixes https://github.com/flutter/flutter/issues/91832

### CODE REVIEW

**Review by zanderso — APPROVED** [review]
This is much simpler =)
