### ISSUE TITLE
[pigeon] Explicitly wrap `EncodableMap` in `EncodableValue` in C++ generated code

### ISSUE THREAD

**Issue by HakkyuKim** [flutter/flutter#111722]
## Overview

`EncodableValue` overrides conversion constructor from `std::variant` to avoid implicit conversion: https://github.com/flutter/engine/blob/93da4784765158a89e269cdea36b2ba7fab85a27/shell/platform/common/client_wrapper/include/flutter/encodable_value.h#L190-L199.

Although MSVC compiler chooses a different constructor, it seems reasonable to use the API the intended way, for example `camera.cpp` in `camera_windows` plugin: https://github.com/flutter/plugins/blob/5159d5ec00478950a8ce24945a73a9567e4b9aaa/packages/camera/camera_windows/windows/camera.cpp#L156-L161.

## Proposal
Explicitly calling EncodableValue constructor in:
- https://github.com/flutter/packages/blob/6bd9c7fdbd5ae053706b5ae7b64b62ea4f4b44b9/packages/pigeon/lib/cpp_generator.dart#L568
- https://github.com/flutter/packages/blob/6bd9c7fdbd5ae053706b5ae7b64b62ea4f4b44b9/packages/pigeon/lib/cpp_generator.dart#L639
- https://github.com/flutter/packages/blob/6bd9c7fdbd5ae053706b5ae7b64b62ea4f4b44b9/packages/pigeon/lib/cpp_generator.dart#L657
- https://github.com/flutter/packages/blob/6bd9c7fdbd5ae053706b5ae7b64b62ea4f4b44b9/packages/pigeon/lib/cpp_generator.dart#L661

Fix to:
```dart
indent.writeln('flutter::EncodableValue(reply(wrapped));');
```

- https://github.com/flutter/packages/blob/6bd9c7fdbd5ae053706b5ae7b64b62ea4f4b44b9/packages/pigeon/lib/cpp_generator.dart#L124-L125

Fix to:
```dart
indent.writeln(
    'WriteValue(flutter::EncodableValue(std::any_cast<${customClass.name}>(*custom_value).ToEncodableMap()), stream);');
```

**Comment by stuartmorgan** [comment]
> ```dart
> indent.writeln('flutter::EncodableValue(reply(wrapped));');
> ```

`reply` is a function. I assume you meant to wrap `wrapped` here, not `reply(wrapped)`?

I'm not actually sure why it's compiling without this, so I think we can just call this a bug rather than a proposal.

(I assume you're filing this because it's not working in your fork; what's the compiler there? clang, or something else?)

**Comment by HakkyuKim** [comment]
> reply is a function. I assume you meant to wrap wrapped here, not reply(wrapped)?

Oh right, it's a mistake.

(I assume you're filing this because it's not working in your fork; what's the compiler there? clang, or something else?)

The compiler is clang++ (llvm-10).

**Comment by swift-kim** [comment]
@stuartmorgan Hi. The bug can be reproduced with this simple example:

```cpp
#include <map>
#include <variant>

class EncodableValue;

using EncodableMap = std::map<EncodableValue, EncodableValue>;
using EncodableValueVariant = std::variant<std::monostate, EncodableMap>;

class EncodableValue : public EncodableValueVariant {
 public:
  using super = EncodableValueVariant;
  using super::super;
  using super::operator=;

  explicit EncodableValue() = default;

  template <class T>
  constexpr explicit EncodableValue(T&& t) noexcept : super(t) {}
};

void MyFunction(EncodableValue value) {}

int main() {
    EncodableMap map;
    MyFunction(map);

    return 0;
}
```

This code compiles well with MSVC 19 (on Windows) and GCC 9.3 (on Linux), but not with Clang (I tried Clang 10, 11, and 15).

Developer Command Prompt for VS 2019:
```sh
$ cl /std:c++17 main.cc

```

Linux:
```sh
$ g++ -std=c++17 main.cc

$ clang-15 -std=c++17 -lstdc++ main.cc
main.cc:25:5: error: no matching function for call to 'MyFunction'
    MyFunction(map);
    ^~~~~~~~~~
main.cc:21:6: note: candidate function not viable: no known conversion from 'EncodableMap' (aka 'map<EncodableValue, EncodableValue>') to 'EncodableValue' for 1st argument
void MyFunction(EncodableValue value) {}
     ^
1 error generated.
```

A copy constructor must explicitly be used to suppress the error.

```patch
 int main() {
     EncodableMap map;
-    MyFunction(map);
+    MyFunction(EncodableValue(map));

     return 0;
 }
```

**Comment by stuartmorgan** [comment]
> The bug can be reproduced with this simple example

Yes, I understand the bug. As I said above, I don't actually know why it compiles in the non-clang compilers in the first place (since EncodableValue intentionally avoids having implicit conversion constructors).

> A copy constructor must explicitly be used to suppress the error.

That's not a copy constructor, since `EncodableMap` isn't an `EncodableValue`—in retrospect, `EncodableMap` and `EncodableList` were probably not the best names for the aliases.

**Comment by swift-kim** [comment]
I tried the latest release of pigeon (4.2.13) but https://github.com/flutter/packages/pull/2745 doesn't seem to be a relevant fix for this bug. I think @stuartmorgan is already aware of the issue.

https://github.com/flutter/packages/pull/2745#discussion_r1044655791

https://github.com/flutter/packages/pull/2745#discussion_r1046638393

```sh
src/messages.cc:424:13: error: no matching function for call to object of type 'const flutter::MessageReply<flutter::EncodableValue>' (aka 'const function<void (const flutter::EncodableValue&)>')
            reply(wrapped);
            ^~~~~
std_function.h:579:12: note: candidate function not viable: no known conversion from 'flutter::EncodableList' (aka 'vector<flutter::EncodableValue>') to 'const flutter::EncodableValue' for 1st argument
      _Res operator()(_ArgTypes... __args) const;
```

**Comment by tarrinneal** [comment]
@swift-kim Nice catch, I'll check that bug out and get it fixed.

**Comment by swift-kim** [comment]
@tarrinneal The code compiled well with pigeon 4.2.14. Thank you very much!

**Comment by tarrinneal** [comment]
> @tarrinneal The code compiled well with pigeon 4.2.14. Thank you very much!

Awesome @swift-kim. Thanks for bringing it to our attention!
