### ISSUE TITLE
WorkManager is not initialized properly

### ISSUE THREAD

**Issue by atleugim** [flutter/flutter#81442]
When i run my app the debugger console throws an exception related with workmanager, like this.

**FATAL EXCEPTION: main**
```
E/AndroidRuntime(18384): Process: com.google.android.apps.walletnfcrel, PID: 18384
E/AndroidRuntime(18384): java.lang.RuntimeException: Unable to create application com.google.commerce.tapandpay.android.application.TapAndPayApplication: java.lang.IllegalStateException: WorkManager is not initialized properly.  You have explicitly disabled WorkManagerInitializer in your manifest, have not manually called WorkManager#initialize at this point, and your Application does not implement Configuration.Provider.

I'm working on the latest stable version (2.0.5) with sound null-safety
**_Here is my flutter doctor -v_**

$ flutter doctor -v
[√] Flutter (Channel stable, 2.0.5, on Microsoft Windows [VersiÃ³n 10.0.19042.631], locale es-CO)
    • Flutter version 2.0.5 at C:\flutter
    • Framework revision adc687823a (12 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\MyUser\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.55.2)
    • VS Code at C:\Users\MyUser\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[√] Connected device (2 available)
    • Redmi Note 9 Pro (mobile) • d0a82e4e • android-arm64  • Android 10 (API 29)
    • Chrome (web)              • chrome   • web-javascript • Google Chrome 90.0.4430.93

• No issues found!


**_And the packages i use_**
http: ^0.13.1
share: ^2.0.1
cached_network_image: ^3.0.0
google_fonts: ^2.0.0
url_launcher: ^6.0.3

```

**Comment by darshankawar** [comment]
@atleugim 
Can you try `flutter clean` and then `flutter run` to see if it resolves your issue ?
Thanks.

**Comment by atleugim** [comment]
@darshankawar 
I do that everytime i run project, the issue is still there.

**Comment by darshankawar** [comment]
@atleugim 
Can you also try `flutter pub cache repair' ?
If issue still persists, can you provide complete `pubspec.yaml` ?

**Comment by atleugim** [comment]
@darshankawar 

I've made the `flutter pub cache repair` but te issue is still there

This is my  **pubspec.yaml**

```
name: myproject
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  http: ^0.13.1
  share: ^2.0.1
  cached_network_image: ^3.0.0
  google_fonts: ^2.0.0
  url_launcher: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/backgrounds/
```

**Comment by darshankawar** [comment]
@atleugim 
Can you try by removing the third party plugin `cached_network_image` and see if it helps ?

Also, can you confirm there isn't workmanager related code in your project, specially in manifest file inside `Android` folder ?

**Comment by atleugim** [comment]
@darshankawar 

I removed the  ` cached_network_image` plugin,
and in my AndroidManifest.xml file I haven't made any change

The problem is still there, but it appears randomly.

PD:  I use a physical device to test the app, the model is a Xiaomi Redmi Note 9 Pro,
Will it be related to this problem?

**Comment by darshankawar** [comment]
@atleugim 
Don't think it'd be device specific. Please share your `manifest` file.
Thanks.

**Comment by atleugim** [comment]
Here´s my AndroidManifest.xml

[AndroidManifest.txt](https://github.com/flutter/flutter/files/6445013/AndroidManifest.txt)

**Comment by atleugim** [comment]
Here's my AndroidManifest.xml

<manifest
  xmlns:android="http://schemas.android.com/apk/res/android"
  package="dev.atleugim.ffmaster">

  <uses-permission android:name="android.permission.INTERNET"/>

  <application
    android:label="FFMaster"
    android:icon="@mipmap/ic_launcher">

    <activity
      android:name=".MainActivity"
      android:launchMode="singleTop"
      android:screenOrientation="portrait"
      android:theme="@style/LaunchTheme"
      android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
      android:hardwareAccelerated="true"
      android:windowSoftInputMode="adjustResize">

      <meta-data
        android:name="io.flutter.embedding.android.NormalTheme"
        android:resource="@style/NormalTheme"
      />
      <meta-data
        android:name="io.flutter.embedding.android.SplashScreenDrawable"
        android:resource="@drawable/launch_background"
      />
      <intent-filter>
        <action android:name="android.intent.action.MAIN"/>
        <category android:name="android.intent.category.LAUNCHER"/>
      </intent-filter>
    </activity>
    
    <meta-data
      android:name="flutterEmbedding"
      android:value="2"
    />
  </application>

</manifest>

**Comment by atleugim** [comment]
Here´s my AndroidManifest.xml

[AndroidManifest.txt](https://github.com/flutter/flutter/files/6445017/AndroidManifest.txt)

**Comment by darshankawar** [comment]
@atleugim 
Does it also occur with new project using `flutter create` ? If not, can you compare the files / settings of new project vs your project and see what's missing / changed ?

**Comment by atleugim** [comment]
@darshankawar 

I tested on a new project with no dependencies, and only changed the android:label in the AndroidManifest.xml File

`FATAL EXCEPTION: main
E/AndroidRuntime(10559): Process: com.google.android.apps.walletnfcrel, PID: 10559
E/AndroidRuntime(10559): java.lang.RuntimeException: Unable to create application com.google.commerce.tapandpay.android.application.TapAndPayApplication: java.lang.IllegalStateException: WorkManager is not initialized properly.  You have explicitly disabled WorkManagerInitializer in your manifest, have not manually called WorkManager#initialize at this point, and your Application does not implement Configuration.Provider.
E/AndroidRuntime(10559): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6587)
E/AndroidRuntime(10559): 	at android.app.ActivityThread.access$1400(ActivityThread.java:224)
E/AndroidRuntime(10559): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1887)
E/AndroidRuntime(10559): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(10559): 	at android.os.Looper.loop(Looper.java:224)
E/AndroidRuntime(10559): 	at android.app.ActivityThread.main(ActivityThread.java:7562)
E/AndroidRuntime(10559): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(10559): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
E/AndroidRuntime(10559): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
E/AndroidRuntime(10559): Caused by: java.lang.IllegalStateException: WorkManager is not initialized properly.  You have explicitly disabled WorkManagerInitializer in your manifest, have not manually called WorkManager#initialize at this point, and your Application does not implement Configuration.Provider.
E/AndroidRuntime(10559): 	at androidx.work.impl.WorkManagerImpl.getInstance(WorkManagerImpl.java:40)
E/AndroidRuntime(10559): 	at com.google.commerce.tapandpay.android.application.TapAndPayApplication.onCreate(TapAndPayApplication.java:46)
E/AndroidRuntime(10559): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1190)
E/AndroidRuntime(10559): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6582)
E/AndroidRuntime(10559): 	... 8 more
`

The issue is there

**Comment by darshankawar** [comment]
@atleugim 
Thanks for digging in. What was the earlier `label` value and what did you changed it to ?

**Comment by atleugim** [comment]
@darshankawar 

Yes, that's the label I'm referring to.
The original was as the name of the project "bookstore" and I changed it to "Bookstore Preview".

That's the only modification I have done, I have not installed any package.

But the change of the label can be seen, since at the moment of executing the debugger the app is installed with that new name.

**Comment by darshankawar** [comment]
@atleugim 
I am wondering if space between your updated label is causing it.
Can you try in singular `BookstorePreview` and check ?

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
