### ISSUE TITLE
Flutter Engine compile error in MacOS 13.0.1 

### ISSUE THREAD

**Issue by xiaoxiaowesley** [flutter/flutter#115351]
After I upgrade my macOS version to 13.0.1. Can't compile the engine successfully.

OS: macOS 13.0.1 (22A400)
Xcode:14.0.1

## Steps to Reproduce

1. Upgrade to macOS 13.0.1 (22A400)
2. Compile the engine with command  `./flutter/tools/gn --runtime-mode=release  --ios  --ios-cpu=arm64  --bitcode
  && ninja -j 8 -C out/ios_release`
3. Error happened
```
FAILED: clang_x64/obj/third_party/libpng/libpng.pngread.o 
clang -MD -MF clang_x64/obj/third_party/libpng/libpng.pngread.o.d -DUSE_OPENSSL=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -D_LIBCPP_DISABLE_AVAILABILITY=1 -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -I../.. -Iclang_x64/gen -I../../third_party/libcxx/include -I../../third_party/libcxxabi/include -I../../third_party/libpng -I../../third_party/zlib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.sdk -mmacosx-version-min=10.11.0 -fno-strict-aliasing -fstack-protector-all -fembed-bitcode -arch x86_64 -fcolor-diagnostics -Wall -Wextra -Wendif-labels -Werror -Wno-missing-field-initializers -Wno-unused-parameter -Wunguarded-availability -Wno-deprecated-declarations -fvisibility=hidden -stdlib=libc++ -Wstring-conversion -Wnewline-eof -O2 -fno-ident -g2 -std=c99  -c ../../third_party/libpng/pngread.c -o clang_x64/obj/third_party/libpng/libpng.pngread.o
../../third_party/libpng/pngread.c:3455:26: error: variable 'row' set but not used [-Werror,-Wunused-but-set-variable]
               png_bytep row = png_voidcast(png_bytep, display->first_row);
                         ^
1 error generated.
```

I found something difference in comparing the `libpng.ninja` between two macOS vesions.

#### libpng.ninja in macOS 12
```
defines = -DPNG_ARM_NEON_OPT=2 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0
include_dirs = -I../.. -Igen -I../../third_party/libpng -I../../third_party/zlib
asmflags = -fno-strict-aliasing -fembed-bitcode -arch arm64 -fcolor-diagnostics
cflags = -fno-strict-aliasing
-fembed-bitcode
-arch arm64
-fcolor-diagnostics
-Wall -Wextra -Wendif-labels
-Werror
-Wno-missing-field-initializers
-Wno-unused-parameter
-Wunguarded-availability
-Wno-deprecated-declarations
-fvisibility=hidden
-stdlib=libc++
-Wstring-conversion
-Wnewline-eof
-Os -fno-ident -flto -g2
cflags_c = -Wno-unused-but-set-variable -Wno-sign-compare -std=c99
root_out_dir = .
target_out_dir = obj/third_party/libpng
target_output_name = libpng
```

Value `clags_c` will add flags `-Wno-unused-but-set-variable` in macOS12.

#### libpng.ninja in macOS  13.0.1 
```
defines = -DPNG_ARM_NEON_OPT=2 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0
include_dirs = -I../.. -Igen -I../../third_party/libpng -I../../third_party/zlib
asmflags = -fno-strict-aliasing -fembed-bitcode -arch arm64 -fcolor-diagnostics
cflags = -fno-strict-aliasing -fembed-bitcode -arch arm64 -fcolor-diagnostics -Wall -Wextra -Wendif-labels -Werror -Wno-missing-field-initializers -Wno-unused-parameter -Wunguarded-availability -Wno-deprecated-declarations -fvisibility=hidden -stdlib=libc++ -Wstring-conversion -Wnewline-eof -Os -fno-ident -flto -g2
cflags_c = -Wno-sign-compare -std=c99
root_out_dir = .
target_out_dir = obj/third_party/libpng
target_output_name = libpng
```
Value `clags_c`  **won't**  add flags `-Wno-unused-but-set-variable` in macOS 13.

I searched all the places where  `clags_c` appeared. No explicitly add `-Wno-unused-but-set-variable` in bitcode mode.

Can anyone help?

**Comment by huycozy** [comment]
Hi @xiaoxiaowesley 
Please provide the information indicated below:
- Can you compile the engine successfully before on macOS 12?
- Did you make any modifications to the engine that you built?
- Which engine hash are you building at?

**Comment by huycozy** [comment]
Hi @xiaoxiaowesley 
Please provide the information indicated below:
- Can you compile the engine successfully on macOS 12?
- Did you make any modifications to the engine that you built?
- Which engine hash are you building at?

**Comment by xiaoxiaowesley** [comment]
> 

Q: "Can you compile the engine successfully on macOS 12?"
A: YES. I

Q: "Did you make any modifications to the engine that you built?"
A: Nope. I have several mac devices. I tested on different OS versions (12 ,13 ) Macs in the same engine code. macOS 13 did fail.

Q: "Which engine hash are you building at?"
A: 3.3.0

**Comment by moffatman** [comment]
I have had this issue for some time, I have had to add a few changes when compiling specifically for arm64 simulator. Mostly adding `(void)x;` when it complains that `x` is an unused variable.

**Comment by huycozy** [comment]
Thanks! Labeling the issue for further investigation from the team.

**Comment by knopp** [comment]
> I have had this issue for some time, I have had to add a few changes when compiling specifically for arm64 simulator. Mostly adding `(void)x;` when it complains that `x` is an unused variable.

Same thing here. I think the reason for this is that iOS builds don't use the bundled clang toolchain, but a system one (which produces different warnings). I'm not sure why this doesn't show on CI, might be just a different XCode version.

**Comment by jmagman** [comment]
@jason-simmons do you know if there's a way to add to `clags_c` when building a third_party target?  Or is the right thing to do to patch https://flutter.googlesource.com/third_party/libpng to fix the warnings?

**Comment by jmagman** [comment]
It was removed:
```
gn: error: unrecognized arguments: --bitcode
```
@xiaoxiaowesley what Flutter commit are you on?  Can you try on top of tree, does it work without `--bitcode`?

**Comment by xiaoxiaowesley** [comment]
> 
Work for me without `--bitcode`?

I use flutter 3.3.0 which engine.git 's commit is from  https://github.com/flutter/flutter/blob/3.3.8/bin/internal/engine.version
