### PR TITLE
Starts using the `--source` flag to compile the dart registrant.

### LINKED ISSUE #91841: Multiple entry-points in same Dart file is broken
### Steps to reproduce

Create the following Dart program:

```dart
import 'package:flutter/widgets.dart';

@pragma('vm:entry-point')
void main() {
  runApp(ColoredBox(color: Color(0xffcc0000)));
}

@pragma('vm:entry-point')
void entryPoint() {
  runApp(ColoredBox(color: Color(0xff00cc00)));
}
```

... then override `getDartEntrypointFunctionName` in the Android `MainActivity`, like so:

```kotlin
import io.flutter.embedding.android.FlutterActivity

class MainActivity: FlutterActivity() {
  override fun getDartEntrypointFunctionName(): String {
    return "entryPoint"
  }
}
```

... then run the app on an Android device.

### Expected behavior

You expect `entryPoint()` to be run as the program's entry-point, yielding a green screen.

### Actual behavior

The app fails to start, with the following error:

```
E/flutter (16188): [ERROR:flutter/shell/common/shell.cc(103)] Dart Unhandled Exception: NoSuchMethodError: No top-level getter 'entryPoint' declared.
E/flutter (16188): Receiver: top-level
E/flutter (16188): Tried calling: entryPoint, stack trace: #0      NoSuchMethodError._throwNew (dart:core-patch/errors_patch.dart:214:5)
E/flutter (16188): 
E/flutter (16188): [ERROR:flutter/runtime/dart_isolate.cc(727)] Could not resolve main entrypoint function.
E/flutter (16188): [ERROR:flutter/runtime/dart_isolate.cc(195)] Could not run the run main Dart entrypoint.
E/flutter (16188): [ERROR:flutter/runtime/runtime_controller.cc(415)] Could not create root isolate.
E/flutter (16188): [ERROR:flutter/shell/common/shell.cc(588)] Could not launch engine with configuration.
```

## Notes

This scenario has been created in https://github.com/tvolkert/entrypoint

## Culprit

This appears to have been introduced by https://github.com/flutter/flutter/pull/79669

### PR DESCRIPTION
**Pull request by gaaclarke**
The hack we did previously to shadow the main entrypoint wasn't working on release builds.  Now that Dart supports the `--source` flag we can avoid shadowing main which fixes the issue and is a more clear solution.

fixes https://github.com/flutter/flutter/issues/91841

companion engine pr: https://github.com/flutter/engine/pull/31418

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by gaaclarke** [comment]
This is the error the plugin_test is experiencing:
```
[plugin_test] [STDOUT] ══════════════════════════════╡ ••• Test app ••• ╞══════════════════════════════
[plugin_test] [STDOUT] 
[plugin_test] [STDOUT] Executing "/Users/aaclarke/dev/flutter/bin/flutter test" in "/var/folders/2y/72984f4n0r7fskhjt3qctglw00915v/T/flutter_devicelab_plugin_test.x3USf3/plugintestapp" with environment {BOT: true, LANG: en_US.UTF-8}
[plugin_test] [STDOUT] stdout: 
[plugin_test] [STDOUT] stdout: 00:00 +0: loading /private/var/folders/2y/72984f4n0r7fskhjt3qctglw00915v/T/flutter_devicelab_plugin_test.x3USf3/plugintestapp/test/widget_test.dart                                                    
[plugin_test] [STDOUT] stdout: 00:01 +0: loading /private/var/folders/2y/72984f4n0r7fskhjt3qctglw00915v/T/flutter_devicelab_plugin_test.x3USf3/plugintestapp/test/widget_test.dart                                                    
[plugin_test] [STDOUT] stdout: 00:02 +0: loading /private/var/folders/2y/72984f4n0r7fskhjt3qctglw00915v/T/flutter_devicelab_plugin_test.x3USf3/plugintestapp/test/widget_test.dart                                                    
[plugin_test] [STDOUT] stdout: 00:03 +0: loading /private/var/folders/2y/72984f4n0r7fskhjt3qctglw00915v/T/flutter_devicelab_plugin_test.x3USf3/plugintestapp/test/widget_test.dart                                                    Shell: [ERROR:flutter/runtime/dart_isolate.cc(142)] Could not prepare isolate.
[plugin_test] [STDOUT] stdout: Shell: [ERROR:flutter/runtime/runtime_controller.cc(381)] Could not create root isolate.
[plugin_test] [STDOUT] stdout: Shell: [ERROR:flutter/shell/common/shell.cc(580)] Could not launch engine with configuration.
```

**Comment by gaaclarke** [comment]
I've reproduced the problem locally.  If you go into one of the generated projects in a `plugin_test` then run `flutter run` the app runs fine.  But if you run `flutter test` the `Could not prepare isolate.` error happens.  There is something peculiar with the `flutter test` flow.

**Comment by gaaclarke** [comment]
Hey @blasten , I'm having a problem with this working with `flutter test`.   I get an error when launching the isolate "Could not prepare isolate".  I looked at the original PR for dart registrants and didn't see an obvious place where this could affect `flutter test`.  I'm not well versed in the `flutter test` flow.  Do you know offhand why it might be broken?  I'm looking into it but I was hoping maybe you could save me some time and point me in the right direction.

**Comment by gaaclarke** [comment]
I tracked down why `flutter test` is failing, it's here: https://github.com/gaaclarke/engine/blob/9f99d99628ee4a658f4fff206f588592278ed6b0/runtime/dart_isolate.cc#L528
```c++
  if (Dart_IsNull(Dart_RootLibrary())) {
    return false;
  }
```

According to the documentation this means:
`If the root script has not yet been set for the current isolate, this function returns Dart_Null()`

I'm not sure why `flutter test` is different in this respect from `flutter run`.

**Comment by gaaclarke** [comment]
`Dart_IsNull(Dart_RootLibrary())` because `Dart_IsNull(Dart_LoadLibraryFromKernel())` here: https://github.com/gaaclarke/engine/blob/9f99d99628ee4a658f4fff206f588592278ed6b0/runtime/dart_isolate.cc#L561

**Comment by gaaclarke** [comment]
Here is the verbose log for `flutter test`.  The compilation step wasn't affected by the addition of `--source` but there is something happening with `generated_main.dart` after compilation:
```
[  +11 ms] /Users/aaclarke/dev/engine/src/out/host_debug_unopt/dart-sdk/bin/dart --disable-dart-dev
/Users/aaclarke/dev/engine/src/out/host_debug_unopt/dart-sdk/bin/snapshots/frontend_server.dart.snapshot --sdk-root
/Users/aaclarke/dev/engine/src/out/host_debug_unopt/flutter_patched_sdk/ --incremental --no-print-incremental-dependencies
--target=flutter --debugger-module-names --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill
/var/folders/2y/72984f4n0r7fskhjt3qctglw00915v/T/flutter_tools.NlMem0/flutter_test_compiler.NjBxz3/output.dill --packages
/private/var/folders/2y/72984f4n0r7fskhjt3qctglw00915v/T/flutter_devicelab_plugin_test.iFhDRT/plugintestapp/.dart_tool/package_config.j
son -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --initialize-from-dill
/private/var/folders/2y/72984f4n0r7fskhjt3qctglw00915v/T/flutter_devicelab_plugin_test.iFhDRT/plugintestapp/build/test_cache/build/c075
001b96339384a97db4862b8ab8db.cache.dill.track.dill
[  +21 ms] <- compile
file:///private/var/folders/2y/72984f4n0r7fskhjt3qctglw00915v/T/flutter_devicelab_plugin_test.iFhDRT/plugintestapp/.dart_tool/flutter_b
uild/generated_main.dart
[ +728 ms] <- accept
```

**Comment by gaaclarke** [comment]
Commenting out this line gives us the fix we need: https://github.com/flutter/flutter/blob/0ce527eb91a37ef31b60ed6d4a9613310f2107d4/packages/flutter_tools/lib/src/compile.dart#L642

Looks like there is another flow through compilation I missed.

**Comment by gaaclarke** [comment]
I'm not sure if we are experiencing flakes or failures from the PR.

`Mac plugin_lint_mac` is failing because it can't find a simulator, sounds like an infra failure.
`Mac dart_plugin_registry_test` is failing but there is no assertion being printed out to stdout.  It's unclear why it failed.
`customer_testing-linux` timed out

**Comment by gaaclarke** [comment]
Okay, I've shook out all the analysis errors.  The Mac dart_plugin_registry_test is legitimately broken.  When run locally the app appears but the test doesn't complete.

**Comment by gaaclarke** [comment]
This looks like it's going to need to require an engine change since we'll have to look up the plugin registrant in a different way now.

File: dev/devicelab/bin/tasks/entrypoint_dart_registrant.dart [hunk 1]
```diff
@@ -0,0 +1,12 @@
+// Copyright 2014 The Flutter Authors. All rights reserved.
```
Comment (gaaclarke) [inline dev/devicelab/bin/tasks/entrypoint_dart_registrant.dart:1]: Don't I need to register this task somewhere?  I'm not sure what the latest rules are, it used to be in the infra repo but I know they wanted to move it.

File: dev/devicelab/lib/tasks/entrypoint_dart_registrant.dart [hunk 2]
```diff
@@ -0,0 +1,106 @@
...
+    await stdoutSub.cancel();
+    process.stdin.write('q');
+    await process.stdin.flush();
+    process.kill(ProcessSignal.sigint);
+    return entrypoint;
+  });
+  if (entrypoint.contains('$_messagePrefix $_entrypointName')) {
+    return TaskResult.success(null);
+  } else {
+    return TaskResult.failure(entrypoint);
```
Comment (blasten) [inline dev/devicelab/lib/tasks/entrypoint_dart_registrant.dart:90]: nit: error message could be more informative

File: packages/flutter_tools/test/general.shard/dart_plugin_test.dart [hunk 3]
```diff
@@ -701,206 +701,6 @@ void main() {
...
-          '    (entrypoint.main as _NullaryFunction)();\n'
-          '  }\n'
-          '}\n',
-        );
-      }, overrides: <Type, Generator>{
-        FileSystem: () => fs,
-        ProcessManager: () => FakeProcessManager.any(),
-      });
-
-      testUsingContext('Rewires entrypoints', () async {
```
Comment (blasten) [inline packages/flutter_tools/test/general.shard/dart_plugin_test.dart:807]: is this test no longer valid?

File: packages/flutter_tools/lib/src/flutter_plugins.dart [hunk 4]
```diff
@@ -754,18 +750,6 @@ $_dartPluginRegisterWith
       {{/windows}}
     }
   }
-
-}
-
-typedef _UnaryFunction = dynamic Function(List<String> args);
-typedef _NullaryFunction = dynamic Function();
-
-void main(List<String> args) {
```
Comment (blasten) [inline packages/flutter_tools/lib/src/flutter_plugins.dart:763]: nice

File: packages/flutter_tools/test/general.shard/test/test_compiler_test.dart [hunk 5]
```diff
@@ -152,12 +152,12 @@ environment:
...
       .childDirectory('flutter_build')
-      .childFile('generated_main.dart');
+      .childFile('dart_plugin_registrant.dart');
 
     expect(generatedMain, exists);
     expect(
-      generatedMain.readAsLinesSync(),
-      contains("import 'test/foo.dart' as entrypoint;")
+      generatedMain.readAsStringSync(),
+      contains('APlugin.registerWith();')
```
Comment (blasten) [inline packages/flutter_tools/test/general.shard/test/test_compiler_test.dart:160]: this could be the entire content

File: dev/devicelab/bin/tasks/entrypoint_dart_registrant.dart (hunk 1 above)
Comment (blasten) [reply dev/devicelab/bin/tasks/entrypoint_dart_registrant.dart:1]: In ci.yaml. e.g. https://github.com/flutter/flutter/blob/533a5dde96b35798c501811f3ba378b53bc4b7e4/.ci.yaml#L2523-L2544

Comment (gaaclarke) [reply dev/devicelab/bin/tasks/entrypoint_dart_registrant.dart:1]: thanks!

File: .ci.yaml [hunk 6]
```diff
@@ -2454,6 +2454,29 @@ targets:
       - bin/**
       - .ci.yaml
 
+  - name: Mac entrypoint_dart_registrant
+    recipe: devicelab/devicelab_drone
+    timeout: 60
```
Comment (CaseyHillers) [inline .ci.yaml:2459]: Per the frameworks flaky test policy, you need to add bringup: true to not block the tree. The bot will then mark this as blocking once it has enough data.

You also need to add a TESTOWNERS line

File: packages/flutter_tools/test/general.shard/dart_plugin_test.dart (hunk 3 above)
Comment (gaaclarke) [reply packages/flutter_tools/test/general.shard/dart_plugin_test.dart:807]: That's right.  The git diff is goofy but the result is removing one test.  We don't rewire entrypoints anymore.

File: .ci.yaml (hunk 6 above)
Comment (gaaclarke) [reply .ci.yaml:2459]: done

File: dev/devicelab/lib/tasks/entrypoint_dart_registrant.dart (hunk 2 above)
Comment (gaaclarke) [reply dev/devicelab/lib/tasks/entrypoint_dart_registrant.dart]: done

File: packages/flutter_tools/test/general.shard/test/test_compiler_test.dart (hunk 5 above)
Comment (gaaclarke) [reply packages/flutter_tools/test/general.shard/test/test_compiler_test.dart:160]: I tried to keep the scope similar to what was there before.  Asserting the whole content while being more exact is more fragile, that's why I chose just to assert the `registerWith` call.

**Review by blasten — APPROVED** [review]
LGTM

**Comment by gaaclarke** [comment]
Thanks @blasten, just a reminder to everyone that this can't land until the engine PR lands.

**Review by CaseyHillers — APPROVED** [review]
ci.yaml lgtm
