### ISSUE TITLE
[firebase_messaging] iOS build fails since 2.0.3

### ISSUE THREAD

**Issue by derTuca** [flutter/flutter#24512]
Running `flutter build ios` fails with the following log on versions 2.0.3 and 2.1 (works fine on 2.0.2):

```
Building com.app.app for device (ios-release)...
Automatically signing iOS for device deployment using specified development team
in Xcode project: XXXXXXXXXXX
Running pod install...                                      14.8s
Starting Xcode build...                                          
Xcode build done.                                            3.9s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    /Users/alex/dev/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messagin
    g-2.1.0/ios/Classes/FirebaseMessagingPlugin.m:79:33: error: type-id cannot
    have a name
            instanceIDWithHandler:^(FIRInstanceIDResult *_Nullable
            instanceIDResult,
                                    ^~~~~~~~~~~~~~~~~~~
    /Users/alex/dev/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messagin
    g-2.1.0/ios/Classes/FirebaseMessagingPlugin.m:79:53: error: expected ')'
            instanceIDWithHandler:^(FIRInstanceIDResult *_Nullable
            instanceIDResult,
                                                        ^
    /Users/alex/dev/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messagin
    g-2.1.0/ios/Classes/FirebaseMessagingPlugin.m:79:32: note: to match this '('
            instanceIDWithHandler:^(FIRInstanceIDResult *_Nullable
            instanceIDResult,
                                   ^
    /Users/alex/dev/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messagin
    g-2.1.0/ios/Classes/FirebaseMessagingPlugin.m:79:31: warning: type specifier
    missing, defaults to 'int' [-Wimplicit-int]
            instanceIDWithHandler:^(FIRInstanceIDResult *_Nullable
            instanceIDResult,
                                  ^
    /Users/alex/dev/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messagin
    g-2.1.0/ios/Classes/FirebaseMessagingPlugin.m:81:15: error: use of
    undeclared identifier 'error'
              if (error != nil) {
                  ^
    /Users/alex/dev/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messagin
    g-2.1.0/ios/Classes/FirebaseMessagingPlugin.m:82:63: error: use of
    undeclared identifier 'error'
                NSLog(@"getToken, error fetching instanceID: %@", error);
                                                                  ^
    /Users/alex/dev/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messagin
    g-2.1.0/ios/Classes/FirebaseMessagingPlugin.m:85:20: error: use of
    undeclared identifier 'instanceIDResult'
                result(instanceIDResult.token);
                       ^
    /Users/alex/dev/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messagin
    g-2.1.0/ios/Classes/FirebaseMessagingPlugin.m:79:9: error: no visible
    @interface for 'FIRInstanceID' declares the selector
    'instanceIDWithHandler:'
            instanceIDWithHandler:^(FIRInstanceIDResult *_Nullable
            instanceIDResult,
            ^~~~~~~~~~~~~~~~~~~~~
    /Users/alex/dev/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messagin
    g-2.1.0/ios/Classes/FirebaseMessagingPlugin.m:99:11: warning: incompatible
    integer to pointer conversion initializing 'BOOL *' (aka 'bool *') with an
    expression of type 'BOOL' (aka 'bool') [-Wint-conversion]
        BOOL *value = [[FIRMessaging messaging] isAutoInitEnabled];
              ^       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    2 warnings and 6 errors generated.

Encountered error while building for device.
```

`flutter doctor -v` output:
```
[✓] Flutter (Channel beta, v0.11.3, on Mac OS X 10.14.1 18B75, locale en-RO)
    • Flutter version 0.11.3 at /Users/alex/dev/flutter
    • Framework revision 72bf075e8d (9 days ago), 2018-11-09 20:36:17 -0800
    • Engine revision 5646e86a6f
    • Dart version 2.1.0 (build 2.1.0-dev.9.3 9c07fb64c4)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/alex/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/alex/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 30.0.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.2.5)
    • IntelliJ at /Users/alex/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 30.0.2
    • Dart plugin version 182.5124

[✓] VS Code (version 1.29.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.20.0

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

**Comment by derTuca** [comment]
Yes, I have run flutter clean beforehand.

**Comment by alexeylanars** [comment]
I have the same issue. Added `firebase_messaging: ^2.1.0`.

**Comment by derTuca** [comment]
The `pod update` did the trick, thanks.

**Comment by kroikie** [comment]
@derTuca

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/573. Any further collaboration will be done there.
