### ISSUE TITLE
After updating the xcode to 16, i am not able to build the app

### ISSUE THREAD

**Issue by rajatsingh0406** [flutter/flutter#156204]
### Steps to reproduce

1. Updated the xcode.
2. trying to build the app but i am getting error.

### Expected results

The app should build in ios

### Actual results

The app is not build

### Code sample

<details open><summary>Code sample</summary>

```dart
[4]: Mac Designed for iPad (mac-designed-for-ipad)
Please choose one (or "q" to quit): 2
Launching lib/main.dart on Abhinav’s iPhone in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: 22LR5PHG5J
Running Xcode build...                                                  
Xcode build done.                                           16.5s
Failed to build iOS app
Could not build the precompiled application for the device.
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    Writing result bundle at path:
        /var/folders/wp/czy2ky5553vgdmg6s67j0w_c0000gn/T/flutter_tools.oDn0XW/flutter_ios_build_temp_dirlcd5Vh/temporary_xcresult_bundle

    /Users/abhinav/.pub-cache/hosted/pub.dev/url_launcher_ios-6.3.0/ios/url_launcher_ios/Sources/url_launcher_ios/Launcher.swift:22:1: error: type 'UIApplication' does not conform to protocol 'Launcher'
    extension UIApplication: Launcher {}
    ^
    UIKit.UIApplication:24:15: note: candidate has non-matching type '(URL, [UIApplication.OpenExternalURLOptionsKey : Any], (@MainActor @Sendable (Bool) -> Void)?) -> Void'
        open func open(_ url: URL, options: [UIApplication.OpenExternalURLOptionsKey : Any] = [:], completionHandler completion: (@MainActor @Sendable (Bool) -> Void)? = nil)
                  ^
    /Users/abhinav/.pub-cache/hosted/pub.dev/url_launcher_ios-6.3.0/ios/url_launcher_ios/Sources/url_launcher_ios/Launcher.swift:22:1: note: add stubs for conformance
    extension UIApplication: Launcher {}
    ^
    /Users/abhinav/Documents/Flutter Project/pmg-app/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but the range of supported deployment target versions is 12.0 to 18.0.99.
    (in target 'permission_handler_apple-permission_handler_apple_privacy' from project 'Pods')
    /Users/abhinav/Documents/Flutter Project/pmg-app/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but the range of supported deployment target versions is 12.0 to 18.0.99.
    (in target 'flutter_local_notifications-flutter_local_notifications_privacy' from project 'Pods')
    /Users/abhinav/Documents/Flutter Project/pmg-app/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but the range of supported deployment target versions is 12.0 to 18.0.99.
    (in target 'SwiftyGif-SwiftyGif' from project 'Pods')
    /Users/abhinav/Documents/Flutter Project/pmg-app/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but the range of supported deployment target versions is 12.0 to 18.0.99.
    (in target 'SDWebImage-SDWebImage' from project 'Pods')
    /Users/abhinav/Documents/Flutter Project/pmg-app/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but the range of supported deployment target versions is 12.0 to 18.0.99.
    (in target 'PromisesObjC-FBLPromises_Privacy' from project 'Pods')
    /Users/abhinav/Documents/Flutter Project/pmg-app/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 12.0 to 18.0.99.
    (in target 'GTMSessionFetcher-GTMSessionFetcher_Full_Privacy' from project 'Pods')
    /Users/abhinav/Documents/Flutter Project/pmg-app/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 12.0 to 18.0.99.
    (in target 'GTMSessionFetcher-GTMSessionFetcher_Core_Privacy' from project 'Pods')
    /Users/abhinav/Documents/Flutter Project/pmg-app/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but the range of supported deployment target versions is 12.0 to 18.0.99.
    (in target 'AppAuth-AppAuthCore_Privacy' from project 'Pods')```

</details>


### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>


### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.2, on macOS 15.0 24A335 darwin-arm64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.92.2)
[✓] Connected device (4 available)
    ! Error: Browsing on the local area network for Mohit’s iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @rajatsingh0406, this has been fixed in `url_launcher_ios: 6.3.1`. Kindly run `flutter pub upgrade` to upgrade your dependency to `6.3.1`. 

Closing this as a duplicate of https://github.com/flutter/flutter/issues/155306

**Comment by rajatsingh0406** [comment]
Running Xcode build...                                                  
Xcode build done.                                           37.5s
Failed to build iOS app
Could not build the precompiled application for the device.
Swift Compiler Error (Xcode): Method does not override any method from its superclass
/Users/abhinav/.pub-cache/hosted/pub.dev/flutter_inappwebview-5.8.0/ios/Classes/InAppWebView/InAppWebView.swift:1225:25



now getting this issues

**Comment by danagbemava-nc** [comment]
Kindly report that on the flutter_inappwebview plugin repo

**Comment by hpelitebook745G2** [comment]
What worked for me:
1. `flutter pub upgrade`
2. upgraded `url_launcher` to `6.3.1` from `6.2.5`

**Comment by ridefox-abarbosa** [comment]
### My solution
1. `Flutter pub upgrade`
2. Upgrade `url_launcher` to `6.3.1`
3. If you run into the issue @rajatsingh0406 experienced update `flutter_inappwebview` to its latest version (`6.1.5`)
4. If you experience a `firebase_database` error go to Xcode => Runner => Build Settings and put "Allow Non-modular Includes In Framework Modules" to "yes"
![Screenshot 2024-10-17 at 11 08 14 AM](https://github.com/user-attachments/assets/9d7f06ae-a8dc-4d38-bd49-25b646133aa6)
