### ISSUE TITLE
error: cannot find symbol   private SizeFCompat calculateTargetSize

### ISSUE THREAD

**Issue by tony123S** [flutter/flutter#136021]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Flutter version
3.13.4

image_picker version
1.0.4

### Actual results

```
C:\xxx\nick_\AppData\Local\Pub\Cache\hosted\pub.dev\image_picker_android-0.8.8+1\android\src\main\java\io\flutter\plugins\imagepicker\ImageResizer.java:13: error: cannot find symbol
import androidx.core.util.SizeFCompat;
                         ^
  symbol:   class SizeFCompat
  location: package androidx.core.util
C:\Users\xxx\AppData\Local\Pub\Cache\hosted\pub.dev\image_picker_android-0.8.8+1\android\src\main\java\io\flutter\plugins\imagepicker\ImageResizer.java:84: error: cannot find symbol
  private SizeFCompat calculateTargetSize(
          ^
  symbol:   class SizeFCompat
  location: class ImageResizer
C:\Users\xxx\AppData\Local\Pub\Cache\hosted\pub.dev\image_picker_android-0.8.8+1\android\src\main\java\io\flutter\plugins\imagepicker\ImageResizer.java:148: error: cannot find symbol
  private SizeFCompat readFileDimensions(String path) {
```

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

I got this error after update flutter version to 3.13.4

**Comment by danagbemava-nc** [comment]
Hi @tony123S, can you try clearing your pub cache and running flutter pub get and running your app again to see if you still face this issue?

**Comment by tony123S** [comment]
I did, but still same

> Hi @tony123S, can you try clearing your pub cache and running flutter pub get and running your app again to see if you still face this issue?

**Comment by danagbemava-nc** [comment]
Hi @tony123S, do you have this issue with a new project or it is only with your existing project? 

Can you also try the solutions in https://stackoverflow.com/questions/66305553/error-cannot-find-symbol-when-building-for-android-in-flutter to see if any of them help?

This is more of an issue with your local cache. I run the image_picker example but I could not reproduce the issue

**Comment by tony123S** [comment]
Is on my existing project. I have clean cache multiple time, still facing this issue

**Comment by danagbemava-nc** [comment]
Hi @tony123S, this is a bit extreme but can you try deleting your cache folder manually or running flutter pub cache repair to see if it makes any difference?
