### ISSUE TITLE
8578 Shader compilation error

### ISSUE THREAD

**Issue by lamikam100** [flutter/flutter#33018]
Just had flutter upgrade to v1.6.0.   Tried to run the following app at:  https://github.com/Ethiel97/flutter_login_ui

Keep getting this error.  Also happens with other apps.

An Observatory debugger and profiler on Android SDK built for x86 is available at: http://127.0.0.1:62618/faH79RFHh9E=/
For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".
D/EGL_emulation( 8578): eglMakeCurrent: 0xe3505420: ver 3 0 (tinfo 0xe3503700)
I/Choreographer( 8578): Skipped 37 frames!  The application may be doing too much work on its main thread.
D/EGL_emulation( 8578): eglMakeCurrent: 0xe52e1d00: ver 3 0 (tinfo 0xcb117830)
D/EGL_emulation( 8578): eglCreateContext: 0xe35054e0: maj 3 min 0 rcv 3
D/EGL_emulation( 8578): eglMakeCurrent: 0xe35054e0: ver 3 0 (tinfo 0xe3503700)
D/EGL_emulation( 8578): eglMakeCurrent: 0xe52e1d00: ver 3 0 (tinfo 0xcb117830)
D/EGL_emulation( 8578): eglMakeCurrent: 0xe35054e0: ver 3 0 (tinfo 0xe3503700)
D/skia    ( 8578): Shader compilation error
D/skia    ( 8578): ------------------------
D/skia    ( 8578): Errors:
D/skia    ( 8578):
D/skia    ( 8578): Shader compilation error
D/skia    ( 8578): ------------------------
D/skia    ( 8578): Errors:
D/skia    ( 8578):
D/skia    ( 8578): Shader compilation error
D/skia    ( 8578): ------------------------
D/skia    ( 8578): Errors:

**Comment by SvenSchoene** [comment]
Can't believe we both posted this in the exact same three minute window: https://github.com/flutter/flutter/issues/33019 😆

**Comment by jason-simmons** [comment]
Looks like this happened on an emulator.  What kind of desktop hardware was the emulator running on?

**Comment by lamikam100** [comment]
x64 windows 10 enterprise.     Let me know if I need to dump and other logs, etc.  Thanks

**Comment by SvenSchoene** [comment]
For me:
- Windows 10 Pro
- Intel i7-7700K @ 4.20GHz
- 32 GB Ram
- 2x Geforce 1080 GTX in SLI

**Comment by DanTup** [comment]
I see this too running my tiler example app [tiler](https://github.com/DanTup/tiler) on the Android emulator (created by `flutter emulator --create`).

- Windows 10 Pro Version 10.0.17763 Build 17763
- Intel(R) Core(TM) i5-4430 CPU @ 3.00GHz, 3001 Mhz, 4 Core(s), 4 Logical Processor(s)
- 16 GB RAM
- NVIDIA GeForce GTX 1060 6GB

**Comment by voivoed** [comment]
I only started seeing that error after the last flutter update a couple days ago. Happens intermittently, on different emulators.

Windows 10 Home
10.0.17134 Build 17134
Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz, 3192 Mhz, 6 Core(s), 12 Logical Processor(s)
16 GB RAM
NVIDIA GeForce GTX 1070

**Comment by alexjuniodev** [comment]
Same specs as yours and same error. What a coincidence 

Windows 10 Home
10.0.17134 Build 17134
Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz, 3192 Mhz, 6 Core(s), 12 Logical Processor(s)
16 GB RAM
NVIDIA GeForce GTX **1060**

**Comment by iplash** [comment]
Same specs as yours and same error. 
I used stable version to resolve this issue and  the current stable version is 1.5.4

**Comment by rjzg85** [comment]
Same error here, using windows 10 as well, is there any update on this? thanks

**Comment by cfreemoser** [comment]
Same error here, using windows 10. However, seems to work if graphics hardware acceleration is disabled.

**Comment by icatalud** [comment]
Same problem.

Windows 10 Home
10.0.17134 Build 17134
Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz, 2701 Mhz, 2 Core(s), 4 Logical Processor(s)
8 GB RAM

**Comment by erfanasg** [comment]
same problem

flutter 1.7 stable
win 10 pro x64
8 gb ram
i7 6820HQ


hope that someone from flutter team check this problem out!

**Comment by tuomohopia** [comment]
I'm hitting this too on Android Emulator. My app shows up either totally black or white, showing nothing else on the screen.

`flutter doctor -v` output:
```
[√] Flutter (Channel stable, v1.7.8+hotfix.3, on Microsoft Windows [Version 10.0.17763.615], locale fi-FI)
    • Flutter version 1.7.8+hotfix.3 at D:\dev\flutter
    • Framework revision b712a172f9 (4 days ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\user\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\user\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] VS Code, 64-bit edition (version 1.36.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.2.0

[√] Connected device (1 available)
    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 9 (API 28) (emulator)

• No issues found!

```

**Comment by tuomohopia** [comment]
@cfreemoser seems to be right, it works on my emulator if graphics hardware acceleration is disabled.

**Comment by Oyeng** [comment]
@tuomohopia @cfreemoser how did u disabled graphics hardware acceleration? they said that u cannot disabled it anymore in windows 10.

**Comment by cfreemoser** [comment]
@Oyeng you can disable it while creating the emulator. There is an option to select whenever host GPU or software emulation should be used.

**Comment by udithv** [comment]
I deleted the emulator created a new one and it worked for me. But I can't  seem to create emulators from vscode since the last update.

**Comment by TylerHorn** [comment]
Same issue, started when using emulator with Hyper-V

| Environment Info | Version |
| :------------------: | :-------: |
| Flutter | v1.7.8+hotfix.3 |
| Windows 10 Enterprise | 1809 |
| Intel i7 | 8750H @ 2.20GHz |
| 32GB RAM |
| Nvidia GTX | 1060 Max-Q |

was initially having issues with system crashes when running the emulator because I have Hyper-V enabled. I use Docker regularly so turning it off wasn't an option, I started the emulator from the command line using 
```console
emulator @avdname -feature WindowsHypervisorPlatform.
```

**Comment by MHShetty** [comment]
Even I am facing the same issue.
I think this issue probably occurred because I closed Android Studio as 'pub upgrade' (while upgrading to 1.7.8) took more than 2 hours to execute.

After executing flutter doctor -v,

[√] Flutter (Channel stable, v1.7.8+hotfix.4, on Microsoft Windows [Version 10.0.17134.407], locale en-IN)
    • Flutter version 1.7.8+hotfix.4 at C:\src\flutter
    • Framework revision 20e59316b8 (9 days ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0-rc2)
    • Android SDK at C:\Users\admin\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0-rc2
    • ANDROID_HOME = C:\Users\admin\AppData\Local\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 36.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] VS Code (version 1.34.0)
    • VS Code at C:\Users\admin\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.26.0

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

• No issues found!

**Comment by jason-simmons** [comment]
The change in the error message started with https://github.com/google/skia/commit/5e7fbfd9b0d6737e08ee9d8861c30ebc244396df

In the past the engine and Skia have logged errors involving the persistent shader cache when running in Android emulators on Windows (https://github.com/flutter/flutter/issues/24058, https://github.com/flutter/flutter/issues/22732).

At one point the engine had disabled the persistent cache to work around this, but it's currently enabled (https://github.com/flutter/engine/commit/2f87713d4074afe4970ae55256100b50819d5315).

For now, you can work around this by using the `--enable-software-rendering` flag in `flutter run` or by disabling hardware acceleration in the emulator.

**Comment by matanshukry** [comment]
@jason-simmons are there any drawbacks to it? can I assume from the errors that hardware acceleration won't work anyway so there's no loss in disabling hardware acceleration?

**Comment by anihow** [comment]
Hi,
I am facing the same issue of shadder compilation error even though it is not effecting my test application.

Below are the logs:
D/skia    ( 8762): Shader compilation error                                                                        
D/skia    ( 8762): ------------------------                                                                        
D/skia    ( 8762): Errors:                                                                                         
D/skia    ( 8762):                                                                                                 
D/skia    ( 8762): Shader compilation error                                                                        
D/skia    ( 8762): ------------------------                                                                        
D/skia    ( 8762): Errors:                                                                                         
D/skia    ( 8762):                                                                                                 
D/skia    ( 8762): Shader compilation error                                                                        
D/skia    ( 8762): ------------------------                                                                        
D/skia    ( 8762): Errors:                                                                                         
D/skia    ( 8762):                                                                                                 
D/skia    ( 8762): Shader compilation error                                                                        
D/skia    ( 8762): ------------------------                                                                        
D/skia    ( 8762): Errors:                                                                                         
D/skia    ( 8762):                                                                                                 
D/skia    ( 8762): Shader compilation error                                                                        
D/skia    ( 8762): ------------------------                                                                        
D/skia    ( 8762): Errors:                                                                                         
D/skia    ( 8762):                                                                                                 
D/skia    ( 8762): Shader compilation error                                                                        
D/skia    ( 8762): ------------------------                                                                        
D/skia    ( 8762): Errors:                                                                                         
D/skia    ( 8762):                                                                    

Please let me know of any suggestions?

**Comment by vimalmistry** [comment]
Same error here. Is anyone have solution? I am using Mac.

**Comment by EmadKaizen** [comment]
The same error appears when starting debugging.

[√] Flutter (Channel beta, v1.8.3, on Microsoft Windows [Version 10.0.17763.678], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
[√] Android Studio (version 3.4)
[√] IntelliJ IDEA Community Edition (version 2019.1)
[√] VS Code (version 1.37.1)
[√] Connected device (1 available)

• No issues found!

**Comment by byshy** [comment]
I just solved my issue, I created a directory called assets, then defined assets in my pubspec.yaml as follows: 
assets:
    - images/assets
whereas it should be:
assets:
    - assets/
maybe this will help
also don't forget to add the '/' cause it also got me

**Comment by klokoleva** [comment]
same problem too, if click images from  gallery, still error

**Comment by bsangamesh** [comment]
I had the same issue but, when I restarted my application, am not seeing any issues.

**Comment by Yann39** [comment]
Same problem here for few days now since I updated flutter.
Error still occurs when setting Emulated Performance Graphics to "hardware" or "software".
Flutter doctor does not find any disease.

Flutter 1.8.3, Dart 2.5.0, emulator Android API 28
Windows 10 Pro up to date
i9 7900X
32Go DDR4
GTX 1080 Ti

**Comment by klokoleva** [comment]
Im already solved,

1 check your connection [!important] 
- opened project in vs code, go to terminal and type flutter clean,
- delete development apps in the emulator,
 
2  if number 1 not work, just creating new project and running,
    if can running, number 1 project has something wrong happen

**Comment by mdhvkothari** [comment]
The same problem any solution?

**Comment by Shahineven** [comment]
i didnt use any gallery image or anything  .. just plain , a simple demo code from flutter.dev 

D/skia    (13527): Shader compilation error
D/skia    (13527): ------------------------
D/skia    (13527): Errors:
D/skia    (13527):
D/skia    (13527): Shader compilation error
D/skia    (13527): ------------------------
D/skia    (13527): Errors:
D/skia    (13527):
D/skia    (13527): Shader compilation error
D/skia    (13527): ------------------------
D/skia    (13527): Errors:
D/skia    (13527):
D/skia    (13527): Shader compilation error
D/skia    (13527): ------------------------
D/skia    (13527): Errors:
D/skia    (13527):
D/skia    (13527): Shader compilation error
D/skia    (13527): ------------------------
D/skia    (13527): Errors:
D/skia    (13527):
D/skia    (13527): Shader compilation error
D/skia    (13527): ------------------------
D/skia    (13527): Errors:
D/skia    (13527):
D/skia    (13527): Shader compilation error
D/skia    (13527): ------------------------
D/skia    (13527): Errors:
D/skia    (13527):
D/skia    (13527): Shader compilation error
D/skia    (13527): ------------------------
D/skia    (13527): Errors:
D/skia    (13527):
D/skia    (13527): Shader compilation error
D/skia    (13527): ------------------------
D/skia    (13527): Errors:
D/skia    (13527):
D/skia    (13527): Shader compilation error
D/skia    (13527): ------------------------
D/skia    (13527): Errors:
D/skia    (13527):
D/skia    (13527): Shader compilation error
D/skia    (13527): ------------------------
D/skia    (13527): Errors:
D/skia    (13527):
D/skia    (13527): Shader compilation error
D/skia    (13527): ------------------------
D/skia    (13527): Errors:
D/skia    (13527):
D/skia    (13527): Shader compilation error
D/skia    (13527): ------------------------
D/skia    (13527): Errors:
D/skia    (13527):
D/EGL_emulation(13527): eglMakeCurrent: 0xe1b023c0: ver 3 1 (tinfo 0xe1b003c0)
D/eglCodecCommon(13527): setVertexArrayObject: set vao to 0 (0) 10 0
D/skia    (13527): Shader compilation error
D/skia    (13527): ------------------------
D/skia    (13527): Errors:
D/skia    (13527):
D/skia    (13527): Shader compilation error
D/skia    (13527): ------------------------
D/skia    (13527): Errors:
D/skia    (13527):
D/skia    (13527): Shader compilation error
D/skia    (13527): ------------------------
D/skia    (13527): Errors:
D/skia    (13527):
D/skia    (13527): Shader compilation error
D/skia    (13527): ------------------------
D/skia    (13527): Errors:
D/skia    (13527):
D/skia    (13527): Shader compilation error
D/skia    (13527): ------------------------
D/skia    (13527): Errors:
D/skia    (13527):
D/skia    (13527): Shader compilation error
D/skia    (13527): ------------------------
D/skia    (13527): Errors:
D/skia    (13527):
D/skia    (13527): Shader compilation error
D/skia    (13527): ------------------------
D/skia    (13527): Errors:
D/skia    (13527):

how to solve this ?
does it affect in any major thing  ?

**Comment by buster95** [comment]
> The change in the error message started with [google/skia@5e7fbfd](https://github.com/google/skia/commit/5e7fbfd9b0d6737e08ee9d8861c30ebc244396df)
> 
> In the past the engine and Skia have logged errors involving the persistent shader cache when running in Android emulators on Windows (#24058, #22732).
> 
> At one point the engine had disabled the persistent cache to work around this, but it's currently enabled ([flutter/engine@2f87713](https://github.com/flutter/engine/commit/2f87713d4074afe4970ae55256100b50819d5315)).
> 
> For now, you can work around this by using the `--enable-software-rendering` flag in `flutter run` or by disabling hardware acceleration in the emulator.

thanks @jason-simmons problem disappeared, i only added software rendering flag in file launch.json for vscode
![image](https://user-images.githubusercontent.com/15637669/65835510-592ac580-e2a4-11e9-9c88-efc8e5e3a96b.png)

**Comment by OmarAbdo** [comment]
same issue 
D/skia    ( 4714): Errors:
D/skia    ( 4714):
D/skia    ( 4714): Shader compilation error
D/skia    ( 4714): ------------------------

**Comment by buster95** [comment]
> same issue
> D/skia ( 4714): Errors:
> D/skia ( 4714):
> D/skia ( 4714): Shader compilation error
> D/skia ( 4714): ------------------------

@OmarAbdo you can use this method, but when you use another components like webview for embedded page, application is crashed

> > The change in the error message started with [google/skia@5e7fbfd](https://github.com/google/skia/commit/5e7fbfd9b0d6737e08ee9d8861c30ebc244396df)
> > In the past the engine and Skia have logged errors involving the persistent shader cache when running in Android emulators on Windows (#24058, #22732).
> > At one point the engine had disabled the persistent cache to work around this, but it's currently enabled ([flutter/engine@2f87713](https://github.com/flutter/engine/commit/2f87713d4074afe4970ae55256100b50819d5315)).
> > For now, you can work around this by using the `--enable-software-rendering` flag in `flutter run` or by disabling hardware acceleration in the emulator.
> 
> thanks @jason-simmons problem disappeared, i only added software rendering flag in file launch.json for vscode
> ![image](https://user-images.githubusercontent.com/15637669/65835510-592ac580-e2a4-11e9-9c88-efc8e5e3a96b.png)

**Comment by ad-on-is** [comment]
I've found, that when you try to access an image, that doesn't exist, it throws that exact same error in the emulator, and crashes it. While on a real device (in my case, OnePlus 6T), the app just works.

`Image.asset('assets/images/${item.image}.png', height: 50, color: Theme.of(context).textTheme.display3.color)`

In this case `item.image` was `""`, which resulted in fetching `assets/images/.png`.

Hope this helps ;-)

**Comment by buster95** [comment]
> I've found, that when you try to access an image, that doesn't exist, it throws that exact same error in the emulator, and crashes it. While on a real device (in my case, OnePlus 6T), the app just works.
> 
> `Image.asset('assets/images/${item.image}.png', height: 50, color: Theme.of(context).textTheme.display3.color)`
> 
> In this case `item.image` was `""`, which resulted in fetching `assets/images/.png`.
> 
> Hope this helps ;-)

that's correct problem only appear when you use a emulator, in physical devices problem is not showing

**Comment by Talha089** [comment]
Same here,
Windows 10
Dell core i7, 7thGeneration
Nvidia GTX
![image](https://user-images.githubusercontent.com/37252998/67087981-75dc5e00-f1bd-11e9-8693-8a4264741204.png)

**Comment by hasen6** [comment]
People keep talking about images but I get the same error with Custom Painter. I'm using Mac with the Android emulator.

**Comment by harunayyildiz** [comment]
Launching lib\main.dart on Android SDK built for x86 64 in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...
Built build\app\outputs\apk\debug\app-debug.apk.
Syncing files to device Android SDK built for x86 64...
D/skia    ( 4990): Shader compilation error
D/skia    ( 4990): ------------------------
D/skia    ( 4990): Errors:
D/skia    ( 4990): 
I/Choreographer( 4990): Skipped 116 frames!  The application may be doing too much work on its main thread.
D/skia    ( 4990): Shader compilation error
D/skia    ( 4990): ------------------------
D/skia    ( 4990): Errors:
D/skia    ( 4990): 
D/EGL_emulation( 4990): eglMakeCurrent: 0x713e6586b860: ver 3 0 (tinfo 0x713e50620580)
D/skia    ( 4990): Shader compilation error
D/skia    ( 4990): ------------------------
D/skia    ( 4990): Errors:
D/skia    ( 4990): 
D/skia    ( 4990): Shader compilation error
D/skia    ( 4990): ------------------------
D/skia    ( 4990): Errors:
D/skia    ( 4990): 
D/skia    ( 4990): Shader compilation error
D/skia    ( 4990): ------------------------
D/skia    ( 4990): Errors:
D/skia    ( 4990): 
D/skia    ( 4990): Shader compilation error
D/skia    ( 4990): ------------------------
D/skia    ( 4990): Errors:
D/skia    ( 4990): 
D/skia    ( 4990): Shader compilation error
D/skia    ( 4990): ------------------------
D/skia    ( 4990): Errors:
D/skia    ( 4990): 
D/skia    ( 4990): Shader compilation error
D/skia    ( 4990): ------------------------
D/skia    ( 4990): Errors:
D/skia    ( 4990): 
D/skia    ( 4990): Shader compilation error
D/skia    ( 4990): ------------------------
D/skia    ( 4990): Errors:
D/skia    ( 4990): 
D/skia    ( 4990): Shader compilation error
D/skia    ( 4990): ------------------------
D/skia    ( 4990): Errors:
D/skia    ( 4990): 
D/skia    ( 4990): Shader compilation error
D/skia    ( 4990): ------------------------
D/skia    ( 4990): Errors:
D/skia    ( 4990): 
D/skia    ( 4990): Shader compilation error
D/skia    ( 4990): ------------------------
D/skia    ( 4990): Errors:
D/skia    ( 4990): 
D/skia    ( 4990): Shader compilation error
D/skia    ( 4990): ------------------------
D/skia    ( 4990): Errors:
D/skia    ( 4990): 
D/EGL_emulation( 4990): eglMakeCurrent: 0x713e63efa5e0: ver 3 0 (tinfo 0x713e63f65e80)
D/skia    ( 4990): Shader compilation error
D/skia    ( 4990): ------------------------
D/skia    ( 4990): Errors:
D/skia    ( 4990): 
D/skia    ( 4990): Shader compilation error
D/skia    ( 4990): ------------------------
D/skia    ( 4990): Errors:
D/skia    ( 4990): 
D/skia    ( 4990): Shader compilation error
D/skia    ( 4990): ------------------------
D/skia    ( 4990): Errors:
D/skia    ( 4990): 
D/skia    ( 4990): Shader compilation error
D/skia    ( 4990): ------------------------
D/skia    ( 4990): Errors:
D/skia    ( 4990): 
D/skia    ( 4990): Shader compilation error
D/skia    ( 4990): ------------------------
D/skia    ( 4990): Errors:
D/skia    ( 4990): 
D/skia    ( 4990): Shader compilation error
D/skia    ( 4990): ------------------------
D/skia    ( 4990): Errors:
D/skia    ( 4990): 
E/flutter ( 4990): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: HandshakeException: Connection terminated during handshake

**Comment by harunayyildiz** [comment]
Help?

**Comment by giaur500** [comment]
So, your solution is to disable hw acceleration and kill emulator performance - simple make emulator unusable. Are you kidding me?

**Comment by liyuqian** [comment]
Even the simplest Flutter app needs to compile some Skia shaders so it's expected to have no difference between complex apps and simple apps. To fix this, we need to first reproduce the error. @jason-simmons : during your investigation of https://github.com/flutter/flutter/issues/33018#issuecomment-517055562, have you reproduced this on any Linux, Mac, or Windows Android emulators locally?

**Comment by AnshulAggarwal15** [comment]
This issue was opened on May,2019 and in feb,2020 I am still facing same issue on AVD on Win 10

**Comment by liyuqian** [comment]
I've bisected this issue down to a single engine roll with many Skia rolls: https://github.com/flutter/flutter/commit/c27d10bf464500ef4e1792e9aa57128c1b281d2f

CC @brianosman from Skia team for further triaging.

AFAIK, this issue is only about having excessive error messages. There are no actual rendering artifacts, performance regressions, or crashes. And this issue seems to only manifest on Windows 10 Android simulators with hardware acceleration turned on.

**Comment by giaur500** [comment]
> And this issue seems to only manifest on Windows 10 Android simulators with hardware acceleration turned on.

Not only Windows 10, I've seen it on Linux

**Comment by brianosman** [comment]
@liyuqian That range includes https://skia-review.googlesource.com/c/skia/+/211361, which changed how Skia reports shader compile errors. Previously, we always printed messages with SkDebugf. After that CL, GrContextOptions has a ShaderErrorHandler pointer, so that clients can intercept and handle errors however they want. The default implementation still just prints the errors with SkDebugf. I've looked at the code again, and I don't see how that CL would have changed anything (as far as reporting new or different errors).

Given that the output has no shader text and no errors, I'm not sure which call to the reporter is failing. There are only three sites in Skia (within Flutter) that can report errors: one in GrGLProgramBuilder, two in GrGLShaderStringBuilder: https://source.chromium.org/search?q=compileError&sq=&ss=chromium%2Fchromium%2Fsrc:third_party%2Fskia%2F&originalUrl=https:%2F%2Fcs.chromium.org%2F

Flutter could supply a custom ShaderErrorHandler, but I'd really like to know the situation where we're reporting an error with no shader text and no errors. If you have a way to repro this, we can insert some additional output at each of those call-sites to help track it down.

**Comment by liyuqian** [comment]
@brianosman Here's the simple way to reproduce the error (I only confirmed reproduction on Windows because I don't have access to my Linux desktop now as I'm quarantined at home for 2 weeks)

1. Start an Android simulator with hardware acceleration turned on
1. Check out Flutter version https://github.com/flutter/flutter/commit/c27d10bf464500ef4e1792e9aa57128c1b281d2f
1. `cd examples/flutter_gallery/`
1. `flutter run --trace-startup`
1. `flutter run --trace-startup` again and you should see the error

Please feel free to tweak the Skia code, recompile the Flutter engine and run `flutter run --trace-startup --local-engine=...` to conduct more experiments.

**Comment by kcprabase** [comment]
> Im already solved,
> 
> 1 check your connection [!important]
> 
> * opened project in vs code, go to terminal and type flutter clean,
> * delete development apps in the emulator,
> 
> 2 if number 1 not work, just creating new project and running,
> if can running, number 1 project has something wrong happen

This worked for my case. Error appeared in new project running on Android P. Windows 10 64 bit

**Comment by superern** [comment]
> > Im already solved,
> > 1 check your connection [!important]
> > 
> > * opened project in vs code, go to terminal and type flutter clean,
> > * delete development apps in the emulator,
> > 
> > 2 if number 1 not work, just creating new project and running,
> > if can running, number 1 project has something wrong happen
> 
> This worked for my case. Error appeared in new project running on Android P. Windows 10 64 bit

Somehow it worked on my side also, 

- `removed `/ `uninstall `the app in emulator

- `flutter clean`

- `run` again

**Comment by liyuqian** [comment]
> This worked for my case. Error appeared in new project running on Android P. Windows 10 64 bit

@kcprabase : do you mean "Error appeared" or "Error disappeared"?

@superern : can you please confirm that this issue is solved on the newest Flutter version by following https://github.com/flutter/flutter/issues/33018#issuecomment-599539090 ? If so, I think I can close this issue.

**Comment by buster95** [comment]
Problem dissapear for me on new versions

**Comment by vinay-khatri** [comment]
fresh installation of latest android studio today. And i am getting this error on first build ever. Issue is not solved. using amd ryzen 2500u laptop.

**Comment by FranciscoDevPy** [comment]
Hola a todos!!
Yo he usado el comando **flutter clean** y los errores han desaparecido
Hi everyone I have used the command  **flutter clean** and it worked

**Comment by FredCof** [comment]
### Maybe no proven solution
> I think, u should used hot reload in Flutter development. And in the same time, u exit your application in emulator, then u reopen your application to continue developing. 

command ***`flutter clean`*** can solve the problem. It will clean flutter builded. Then start debugging again.

**Comment by TheBrown** [comment]
I found out that some Emulator just doesn't have google play service.
To solve the problems just easily recreate the android emulator to consist with google play service

**Comment by bhagyashreeHebbar** [comment]
Solved.
Clearing the flutter build cache resolved the issue.
->To do this open the project in vs code, go to terminal execute the command "flutter clean"

**Comment by eyoeldefare** [comment]
Flutter clean worked for me too as one of the superman guy above me mentioned.

**Comment by Ali7med** [comment]
just terminal execute the command "flutter clean" ,
its worked !!!

**Comment by MrDevo** [comment]
> just terminal execute the command "flutter clean" ,
> its worked !!!

Thank youuuuuu!!!
