### ISSUE TITLE
`-[FlutterMetalLayerTest testDealloc]` is failing on Xcode 16 beta 5: `((weakLayer) == nil) failed`

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#152990]
```
 Test Case '-[FlutterMetalLayerTest testDealloc]' started.
 /../../../flutter/shell/platform/darwin/ios/framework/Source/FlutterMetalLayerTest.mm:290: error: -[FlutterMetalLayerTest testDealloc] : ((weakLayer) == nil) failed: "<FlutterMetalLayer: 0x1120ba3a0>"
```
Run in CI in https://github.com/flutter/engine/pull/53790
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8740291695932872753/+/u/test:_Tests_for_ios_debug_unopt_sim/stdout

Test introduced in https://github.com/flutter/engine/pull/54119

**Comment by sethladd** [comment]
Thanks for the catch!

**Comment by jmagman** [comment]
cc @knopp in case you have bandwidth to check this out before I do.

**Comment by knopp** [comment]
Sure, I tale a look. I think one invocation of `CFRunLoopRunInMode` with `returnAfterSourceHandled` might be too optimistic, there can be other things scheduled.

**Comment by knopp** [comment]
I can confirm the test is flaky on iOS 18, the problem disappears if I pump the run loop more than once. Will have PR in a bit.

**Comment by jmagman** [comment]
@knopp Thanks, confirmed the test passes on your fix:

```
 Test Case '-[FlutterMetalLayerTest testDealloc]' started.
 Test Case '-[FlutterMetalLayerTest testDealloc]' passed (0.012 seconds)
```
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8740148292697675889/+/u/test:_Tests_for_ios_debug_unopt_sim/stdout

https://github.com/flutter/engine/pull/53790/checks?check_run_id=28533193334
