### PR TITLE
Identify and re-throw our dependency checking errors in `flutter.groovy`

### PR DESCRIPTION
**Pull request by gmackall**
The application of the `dependency_version_checker` gradle plugin is wrapped in a try catch, which prevented blocking the build in https://github.com/flutter/flutter/pull/149204. This pr re-throws the errors we intended to throw.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[Data Driven Fixes]: https://github.com/flutter/flutter/wiki/Data-driven-Fixes

### CODE REVIEW

File: packages/flutter_tools/gradle/src/main/groovy/flutter.groovy [hunk 1]
```diff
@@ -340,10 +340,26 @@ class FlutterPlugin implements Plugin<Project> {
                         "packages", "flutter_tools", "gradle", "src", "main", "kotlin",
                         "dependency_version_checker.gradle.kts")
                 project.apply from: dependencyCheckerPluginPath
-            } catch (Exception ignored) {
+            } catch (Exception e) {
+                // If the exception was thrown by us in the dependency version checker plugin then
```
Comment (reidbaker) [inline packages/flutter_tools/gradle/src/main/groovy/flutter.groovy:344]: This is a bit gross as any change to that message would cause this unrelated code to fail. 

Can you modify the exception to have a root class maybe and catch that root class and rethrow?

**Review by reidbaker — CHANGES_REQUESTED** [review]

File: packages/flutter_tools/gradle/src/main/groovy/flutter.groovy (hunk 1 above)
Comment (bartekpacia) [reply packages/flutter_tools/gradle/src/main/groovy/flutter.groovy:344]: name idea: `DependencyValidationException` :P

Comment (gmackall) [reply packages/flutter_tools/gradle/src/main/groovy/flutter.groovy:344]: Yeah, I agree it's pretty gross. 

The reason I wrote it this way is that I thought at first that any exception class I wrote for use in the kotlin side (where we throw) wouldn't resolve in the groovy side (where we catch). But I think I'm mistaken about that, it just gets wrapped in a `GradleException`, so I'll still have to dig in like I am here, but won't have to rely on error message at least

Comment (gmackall) [reply packages/flutter_tools/gradle/src/main/groovy/flutter.groovy:343]: Ok, this is still gross but hopefully less so.

I've made changes so that we have a `DependencyValidationException` defined in `flutter.groovy`, and then we throw that from within the kotlin file. We still catch broadly, because Gradle wraps our exception in a couple others, but now we test for that error class with `instanceof`.

**Review by bartekpacia — APPROVED** [review]

File: packages/flutter_tools/gradle/src/main/groovy/flutter.groovy [hunk 2]
```diff
@@ -340,10 +339,27 @@ class FlutterPlugin implements Plugin<Project> {
                         "packages", "flutter_tools", "gradle", "src", "main", "kotlin",
                         "dependency_version_checker.gradle.kts")
                 project.apply from: dependencyCheckerPluginPath
-            } catch (Exception ignored) {
+            } catch (Exception e) {
```
Comment (reidbaker) [inline packages/flutter_tools/gradle/src/main/groovy/flutter.groovy:342]: Why can't we do something like the suggestion below this comment with multiple catch blocks? Is is a quirk of throwing an exception from kotlin to groovy? 
```suggestion
            } catch (DependencyValidationException e) {
              // Rethrow 
            } catch (Exception e) {
              // eat exception Do other code path. 
            }
```

Comment (gmackall) [reply packages/flutter_tools/gradle/src/main/groovy/flutter.groovy:342]: > Is is a quirk of throwing an exception from kotlin to groovy?

Yes, that is correct. The `DependencyValidationException` gets wrapped in a couple of `GradleException`s

Comment (bartekpacia) [reply packages/flutter_tools/gradle/src/main/groovy/flutter.groovy:342]: I think when the Gradle plugin is fully rewritten to Kotlin, then we'll no longer have to depend on such hacks, right?

**Review by reidbaker — APPROVED** [review]

File: packages/flutter_tools/gradle/src/main/groovy/flutter.groovy (hunk 2 above)
Comment (gmackall) [reply packages/flutter_tools/gradle/src/main/groovy/flutter.groovy:342]: Correct. I also haven't looked too far into this, but I think when the full re-write happens it can also be done in actual Kotlin source, and not Kotlin script (I believe AGP is written this way https://android.googlesource.com/platform/tools/base/+/1839aa23b8dc562005e2f0f0cc8e8b4c5caa37d0/build-system/gradle-core/src/main/java/com/android/build/gradle/internal/utils/agpVersionChecker.kt#58)

Comment (bartekpacia) [reply packages/flutter_tools/gradle/src/main/groovy/flutter.groovy:342]: Yes, that's my understanding as well (Kotlin "proper" instead of kts). Sweet!

**Comment by gmackall** [comment]
Reason for revert: Long spam in certain circumstances:

```
e: /Users/mackall/development/flutter/flutter/packages/flutter_tools/gradle/src/main/kotlin/dependency_version_checker.gradle.kts:238:23: Unresolved reference: DependencyValidationException
e: /Users/mackall/development/flutter/flutter/packages/flutter_tools/gradle/src/main/kotlin/dependency_version_checker.gradle.kts:263:23: Unresolved reference: DependencyValidationException
e: /Users/mackall/development/flutter/flutter/packages/flutter_tools/gradle/src/main/kotlin/dependency_version_checker.gradle.kts:288:23: Unresolved reference: DependencyValidationException
e: /Users/mackall/development/flutter/flutter/packages/flutter_tools/gradle/src/main/kotlin/dependency_version_checker.gradle.kts:313:23: Unresolved reference: DependencyValidationException
Warning: Flutter was unable to detect project Gradle, Java, AGP, and KGP versions. Skipping dependency version checking. Error was: org.gradle.internal.exceptions.LocationAwareException: Script '/Users/mackall/development/flutter/flutter/packages/flutter_tools/gradle/src/main/kotlin/dependency_version_checker.gradle.kts' line: 238
Script compilation errors:

  Line 238:                 throw DependencyValidationException(errorMessage)
                                  ^ Unresolved reference: DependencyValidationException

  Line 263:                 throw DependencyValidationException(errorMessage)
                                  ^ Unresolved reference: DependencyValidationException

  Line 288:                 throw DependencyValidationException(errorMessage)
                                  ^ Unresolved reference: DependencyValidationException

  Line 313:                 throw DependencyValidationException(errorMessage)
                                  ^ Unresolved reference: DependencyValidationException
```
