### ISSUE TITLE
Failed assertion: line 263 pos 16: I/flutter (20345): 'child == null || indexOf(child) > index': is not true.

### ISSUE THREAD

**Issue by NitinSharma639** [flutter/flutter#34915]
I am loading images from network in ListView. When I push new widget using 

 ```
Navigator.push(
                     context,
                     MaterialPageRoute(
                         builder: (context) => ImageFullscreenWidget(record.image) )
```

When user tap on first image it works fine but if user tap on third image and come back to same screen it shows error which is following

```
2019-06-22 13:52:34.989 27339-3661/com.infinitytechniques.justlaugh I/flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
2019-06-22 13:52:34.990 27339-3661/com.infinitytechniques.justlaugh I/flutter: The following assertion was thrown building
2019-06-22 13:52:34.990 27339-3661/com.infinitytechniques.justlaugh I/flutter: RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#72621](state:
2019-06-22 13:52:34.990 27339-3661/com.infinitytechniques.justlaugh I/flutter: RawGestureDetectorState#86f18(gestures: [vertical drag], behavior: opaque)):
2019-06-22 13:52:34.990 27339-3661/com.infinitytechniques.justlaugh I/flutter: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 263 pos 16:
2019-06-22 13:52:34.990 27339-3661/com.infinitytechniques.justlaugh I/flutter: 'child == null || indexOf(child) > index': is not true.
2019-06-22 13:52:34.990 27339-3661/com.infinitytechniques.justlaugh I/flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
2019-06-22 13:52:34.990 27339-3661/com.infinitytechniques.justlaugh I/flutter: more information in this error message to help you determine and fix the underlying cause.
2019-06-22 13:52:34.990 27339-3661/com.infinitytechniques.justlaugh I/flutter: In either case, please report this assertion by filing a bug on GitHub:
2019-06-22 13:52:34.990 27339-3661/com.infinitytechniques.justlaugh I/flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
2019-06-22 13:52:34.990 27339-3661/com.infinitytechniques.justlaugh I/flutter: When the exception was thrown, this was the stack:
2019-06-22 13:52:34.990 27339-3661/com.infinitytechniques.justlaugh I/flutter: #2      RenderSliverMultiBoxAdaptor._debugVerifyChildOrder (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:263:16)
2019-06-22 13:52:34.990 27339-3661/com.infinitytechniques.justlaugh I/flutter: #3      RenderSliverMultiBoxAdaptor.debugChildIntegrityEnabled=.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:238:14)
2019-06-22 13:52:34.990 27339-3661/com.infinitytechniques.justlaugh I/flutter: #4      RenderSliverMultiBoxAdaptor.debugChildIntegrityEnabled= (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:240:6)
2019-06-22 13:52:34.990 27339-3661/com.infinitytechniques.justlaugh I/flutter: #5      SliverMultiBoxAdaptorElement.performRebuild (package:flutter/src/widgets/sliver.dart:1148:20)
2019-06-22 13:52:34.990 27339-3661/com.infinitytechniques.justlaugh I/flutter: #6      SliverMultiBoxAdaptorElement.update (package:flutter/src/widgets/sliver.dart:1084:7)
2019-06-22 13:52:34.990 27339-3661/com.infinitytechniques.justlaugh I/flutter: #7      Element.updateChild (package:flutter/src/widgets/framework.dart:2844:15)
2019-06-22 13:52:34.990 27339-3661/com.infinitytechniques.justlaugh I/flutter: #8      SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4979:14)
2019-06-22 13:52:34.990 27339-3661/com.infinitytechniques.justlaugh I/flutter: #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2844:15)
2019-06-22 13:52:34.990 27339-3661/com.infinitytechniques.justlaugh I/flutter: #10     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4697:32)
2019-06-22 13:52:34.990 27339-3661/com.infinitytechniques.justlaugh I/flutter: #11     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5088:17)
2019-06-22 13:52:34.990 27339-3661/com.infinitytechniques.justlaugh I/flutter: #12     _ViewportElement.update (package:flutter/src/widgets/viewport.dart:192:11)
2019-06-22 13:52:34.990 27339-3661/com.infinitytechniques.justlaugh I/flutter: #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2844:15)
2019-06-22 13:52:34.990 27339-3661/com.infinitytechniques.justlaugh I/flutter: #14     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4979:14)
2019-06-22 13:52:34.990 27339-3661/com.infinitytechniques.justlaugh I/flutter: #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2844:15)
2019-06-22 13:52:34.990 27339-3661/com.infinitytechniques.justlaugh I/flutter: #16     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4979:14)
2019-06-22 13:52:34.990 27339-3661/com.infinitytechniques.justlaugh I/flutter: #17     Element.updateChild (package:flutter/src/widgets/framework.dart:2844:15)
2019-06-22 13:52:34.990 27339-3661/com.infinitytechniques.justlaugh I/flutter: #18     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4979:14)
2019-06-22 13:52:34.990 27339-3661/com.infinitytechniques.justlaugh I/flutter: #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2844:15)
2019-06-22 13:52:34.990 27339-3661/com.infinitytechniques.justlaugh I/flutter: #20     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4979:14)
2019-06-22 13:52:34.990 27339-3661/com.infinitytechniques.justlaugh I/flutter: #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2844:15)
2019-06-22 13:52:34.991 27339-3661/com.infinitytechniques.justlaugh I/flutter: #22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3846:16)
2019-06-22 13:52:34.991 27339-3661/com.infinitytechniques.justlaugh I/flutter: #23     Element.rebuild (package:flutter/src/widgets/framework.dart:3656:5)
2019-06-22 13:52:34.991 27339-3661/com.infinitytechniques.justlaugh I/flutter: #24     StatefulElement.update (package:flutter/src/widgets/framework.dart:3990:5)
2019-06-22 13:52:34.991 27339-3661/com.infinitytechniques.justlaugh I/flutter: #25     Element.updateChild (package:flutter/src/widgets/framework.dart:2844:15)
2019-06-22 13:52:34.991 27339-3661/com.infinitytechniques.justlaugh I/flutter: #26     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4979:14)
2019-06-22 13:52:34.991 27339-3661/com.infinitytechniques.justlaugh I/flutter: #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2844:15)
2019-06-22 13:52:34.991 27339-3661/com.infinitytechniques.justlaugh I/flutter: #28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3846:16)
2019-06-22 13:52:34.991 27339-3661/com.infinitytechniques.justlaugh I/flutter: #29     Element.rebuild (package:flutter/src/widgets/framework.dart:3656:5)
2019-06-22 13:52:34.991 27339-3661/com.infinitytechniques.justlaugh I/flutter: #30     ProxyElement.update (package:flutter/src/widgets/framework.dart:4102:5)
2019-06-22 13:52:34.991 27339-3661/com.infinitytechniques.justlaugh I/flutter: #31     Element.updateChild (package:flutter/src/widgets/framework.dart:2844:15)
2019-06-22 13:52:34.991 27339-3661/com.infinitytechniques.justlaugh I/flutter: #32     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4979:14)
2019-06-22 13:52:34.991 27339-3661/com.infinitytechniques.justlaugh I/flutter: #33     Element.updateChild (package:flutter/src/widgets/framework.dart:2844:15)
2019-06-22 13:52:34.991 27339-3661/com.infinitytechniques.justlaugh I/flutter: #34     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4979:14)
2019-06-22 13:52:34.991 27339-3661/com.infinitytechniques.justlaugh I/flutter: #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2844:15)
2019-06-22 13:52:34.991 27339-3661/com.infinitytechniques.justlaugh I/flutter: #36     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4979:14)
2019-06-22 13:52:34.991 27339-3661/com.infinitytechniques.justlaugh I/flutter: #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2844:15)
2019-06-22 13:52:34.991 27339-3661/com.infinitytechniques.justlaugh I/flutter: #38     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4979:14)
2019-06-22 13:52:34.991 27339-3661/com.infinitytechniques.justlaugh I/flutter: #39     Element.updateChild (package:flutter/src/widgets/framework.dart:2844:15)
2019-06-22 13:52:34.991 27339-3661/com.infinitytechniques.justlaugh I/flutter: #40     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3846:16)
2019-06-22 13:52:34.991 27339-3661/com.infinitytechniques.justlaugh I/flutter: #41     Element.rebuild (package:flutter/src/widgets/framework.dart:3656:5)
2019-06-22 13:52:34.991 27339-3661/com.infinitytechniques.justlaugh I/flutter: #42     StatelessElement.update (package:flutter/src/widgets/framework.dart:3892:5)
2019-06-22 13:52:34.991 27339-3661/com.infinitytechniques.justlaugh I/flutter: #43     Element.updateChild (package:flutter/src/widgets/framework.dart:2844:15)
2019-06-22 13:52:34.991 27339-3661/com.infinitytechniques.justlaugh I/flutter: #44     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3846:16)
2019-06-22 13:52:34.991 27339-3661/com.infinitytechniques.justlaugh I/flutter: #45     Element.rebuild (package:flutter/src/widgets/framework.dart:3656:5)
2019-06-22 13:52:34.991 27339-3661/com.infinitytechniques.justlaugh I/flutter: #46     StatefulElement.update (package:flutter/src/widgets/framework.dart:3990:5)
2019-06-22 13:52:34.991 27339-3661/com.infinitytechniques.justlaugh I/flutter: #47     Element.updateChild (package:flutter/src/widgets/framework.dart:2844:15)
2019-06-22 13:52:34.991 27339-3661/com.infinitytechniques.justlaugh I/flutter: #48     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3846:16)
2019-06-22 13:52:34.991 27339-3661/com.infinitytechniques.justlaugh I/flutter: #49     Element.rebuild (package:flutter/src/widgets/framework.dart:3656:5)
2019-06-22 13:52:34.991 27339-3661/com.infinitytechniques.justlaugh I/flutter: #50     StatefulElement.update (package:flutter/src/widgets/framework.dart:3990:5)
2019-06-22 13:52:34.991 27339-3661/com.infinitytechniques.justlaugh I/flutter: #51     Element.updateChild (package:flutter/src/widgets/framework.dart:2844:15)
2019-06-22 13:52:34.991 27339-3661/com.infinitytechniques.justlaugh I/flutter: #52     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3846:16)
2019-06-22 13:52:34.991 27339-3661/com.infinitytechniques.justlaugh I/flutter: #53     Element.rebuild (package:flutter/src/widgets/framework.dart:3656:5)
2019-06-22 13:52:34.991 27339-3661/com.infinitytechniques.justlaugh I/flutter: #54     ProxyElement.update (package:flutter/src/widgets/framework.dart:4102:5)
2019-06-22 13:52:34.991 27339-3661/com.infinitytechniques.justlaugh I/flutter: #55     Element.updateChild (package:flutter/src/widgets/framework.dart:2844:15)
2019-06-22 13:52:34.991 27339-3661/com.infinitytechniques.justlaugh I/flutter: #56     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3846:16)
2019-06-22 13:52:34.992 27339-3661/com.infinitytechniques.justlaugh I/flutter: #57     Element.rebuild (package:flutter/src/widgets/framework.dart:3656:5)
2019-06-22 13:52:34.992 27339-3661/com.infinitytechniques.justlaugh I/flutter: #58     StatelessElement.update (package:flutter/src/widgets/framework.dart:3892:5)
2019-06-22 13:52:34.992 27339-3661/com.infinitytechniques.justlaugh I/flutter: #59     Element.updateChild (package:flutter/src/widgets/framework.dart:2844:15)
2019-06-22 13:52:34.992 27339-3661/com.infinitytechniques.justlaugh I/flutter: #60     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3846:16)
2019-06-22 13:52:34.992 27339-3661/com.infinitytechniques.justlaugh I/flutter: #61     Element.rebuild (package:flutter/src/widgets/framework.dart:3656:5)
2019-06-22 13:52:34.992 27339-3661/com.infinitytechniques.justlaugh I/flutter: #62     StatefulElement.update (package:flutter/src/widgets/framework.dart:3990:5)
2019-06-22 13:52:34.992 27339-3661/com.infinitytechniques.justlaugh I/flutter: #63     Element.updateChild (package:flutter/src/widgets/framework.dart:2844:15)
2019-06-22 13:52:34.992 27339-3661/com.infinitytechniques.justlaugh I/flutter: #64     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3846:16)
2019-06-22 13:52:34.992 27339-3661/com.infinitytechniques.justlaugh I/flutter: #65     Element.rebuild (package:flutter/src/widgets/framework.dart:3656:5)
2019-06-22 13:52:34.992 27339-3661/com.infinitytechniques.justlaugh I/flutter: #66     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2314:33)
2019-06-22 13:52:34.992 27339-3661/com.infinitytechniques.justlaugh I/flutter: #67     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:700:20)
2019-06-22 13:52:34.992 27339-3661/com.infinitytechniques.justlaugh I/flutter: #68     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:285:5)
2019-06-22 13:52:34.992 27339-3661/com.infinitytechniques.justlaugh I/flutter: #69     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1012:15)
2019-06-22 13:52:34.992 27339-3661/com.infinitytechniques.justlaugh I/flutter: #70     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:952:9)
2019-06-22 13:52:34.992 27339-3661/com.infinitytechniques.justlaugh I/flutter: #71     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:864:5)
2019-06-22 13:52:34.992 27339-3661/com.infinitytechniques.justlaugh I/flutter: #75     _invoke (dart:ui/hooks.dart:220:10)
2019-06-22 13:52:34.992 27339-3661/com.infinitytechniques.justlaugh I/flutter: #76     _drawFrame (dart:ui/hooks.dart:178:3)
2019-06-22 13:52:34.992 27339-3661/com.infinitytechniques.justlaugh I/flutter: (elided 5 frames from class _AssertionError and package dart:async)
2019-06-22 13:52:34.992 27339-3661/com.infinitytechniques.justlaugh I/flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
2019-06-22 13:52:35.213 27339-3661/com.infinitytechniques.justlaugh I/flutter: Another exception was thrown: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 263 pos 16: 'child == null || indexOf(child) > index': is not true.
2019-06-22 13:52:35.256 27339-3661/com.infinitytechniques.justlaugh I/flutter: Another exception was thrown: Duplicate GlobalKey detected in widget tree.
2019-06-22 13:52:35.581 27339-3661/com.infinitytechniques.justlaugh I/flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4243 pos 14: '_dependents.isEmpty': is not true.
2019-06-22 13:52:35.605 27339-3661/com.infinitytechniques.justlaugh I/flutter: Another exception was thrown: Duplicate GlobalKey detected in widget tree.
2019-06-22 13:52:35.871 27339-3661/com.infinitytechniques.justlaugh I/flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 5067 pos 12: '_children.contains(child)': is not true.
2019-06-22 13:52:35.910 27339-3661/com.infinitytechniques.justlaugh I/flutter: Another exception was thrown: NoSuchMethodError: The getter 'userGestureInProgress' was called on null.
2019-06-22 13:52:35.937 27339-3661/com.infinitytechniques.justlaugh I/flutter: Another exception was thrown: Duplicate GlobalKey detected in widget tree.
```

**Comment by totalerex** [comment]
I started to observe the same issue after updating Flutter to 1.7.4 (wanted to have android easy bundles build), but reverted to Flutter 1.5.8 - there is no such issue

**Comment by MisterJimson** [comment]
Also seeing this in 1.7

**Comment by MisterJimson** [comment]
For me this seemed to be related to duplicate keys in a list. Removing the dupes fixed the issue.

**Comment by totalerex** [comment]
> For me this seemed to be related to duplicate keys in a list. Removing the dupes fixed the issue.

Thank you! 
In my case it was related to duplicates in page storage keys.

**Comment by alex7egli** [comment]
I had a similar issue that was caused by duplicate keys as well.

**Comment by tavindersingh** [comment]
I have the save issue with listview. When I scroll down and scroll up then I get the red widget error.
I am using the following code.
return MultiProvider(
      providers: [
        ChangeNotifierProvider(
          create: (_) => AccountProvider(),
        )
      ],
      child: Consumer<AccountProvider>(
        builder: (context, accountProvider, _) {
          return Scaffold(
            appBar: AppBar(
              title: Text('Quiz-o-Mania'),
              bottom: PreferredSize(
                preferredSize: Size.fromHeight(48),
                child: StreamBuilder<User>(
                  stream: accountProvider.user.asStream(),
                  builder: (context, snapshot) {
                    if (snapshot.hasData) {
                      return UserDetailHeaderWidget(
                        accountProvider: accountProvider,
                        user: snapshot.data,
                      );
                    } else {
                      return Container();
                    }
                  },
                ),
              ),
            ),
            body: Container(
              padding: EdgeInsets.all(AppConstant.PADDING_M),
              child: Column(
                children: <Widget>[
                  Expanded(
                    child: StreamBuilder<List<Contest>>(
                      stream: _contestStreamController.stream,
                      builder: (context, snapshot) {
                        switch (snapshot.connectionState) {
                          case ConnectionState.none:
                            return Text(
                                'Cannot connect to server. Please try again later.');
                          case ConnectionState.waiting:
                            return Center(
                              child: CircularProgressIndicator(),
                            );
                          case ConnectionState.active:
                          case ConnectionState.done:
                            return ListView.builder(
                              itemCount: 15,
                              itemBuilder: (context, index) {
                                Contest contest = snapshot.data[index % 2];
                                return StreamBuilder<User>(
                                  stream: accountProvider.user.asStream(),
                                  builder: (context, snapshot) {
                                    if (snapshot.hasData) {
                                      return ContestListItemWidget(
                                        contest: contest,
                                        user: snapshot.data,
                                      );
                                    } else {
                                      // return ContestListItemWidget(
                                      //   contest: contest,
                                      //   user: User(),
                                      // );
                                      return Container();
                                    }
                                  },
                                );
                              },
                            );
                          default:
                            return Container();
                        }
                      },
                    ),
                  ),
                ],
              ),
            ),
          );
        },
      ),
    );

**Comment by Anilkhanna** [comment]
I also had a similar issue that was caused by duplicate keys as well.

**Comment by shredding** [comment]
Can someone enlighten me what duplicate keys in a list means?

**Comment by itssasanka** [comment]
Same here, the issue went away as soon as I eliminated duplicate keys within my widgets.
@shredding 
It basically means that some widgets you could be using in a `ListView`, `Column`, `GridView`, etc. have duplicate `key` attributes.

https://api.flutter.dev/flutter/widgets/Widget/key.html

**Comment by cheenuthor** [comment]
faced this issue in **listView**

how to fix it?

**Comment by mohamedbenalima** [comment]
can anyone tell us what's  duplicate keys ?

**Comment by markusaksli-nc** [comment]
All of these issues have to do with either duplicate [GlobalKey](https://api.flutter.dev/flutter/widgets/GlobalKey-class.html)s

> You cannot simultaneously include two widgets in the tree with the same global key. Attempting to do so will assert at runtime.

or duplicate [Key](https://api.flutter.dev/flutter/foundation/Key-class.html)s.

> Keys must be unique amongst the Elements with the same parent.

Most of these issues can be solved by checking your GlobalKey or Key setting logic. Remember that even if you have multiples of the same widget in a list, they cannot have the same keys. Consider using the list length or item index to generate different keys.

If you are not manually setting keys for the widgets in your list, please switch to the latest version of flutter (eg. dev or master) and provide a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) and your `flutter doctor -v` to demonstrate the issue.

@NitinSharma639 Can you confirm that the issue persists on the latest master and your key setting logic isn't at fault for generating multiple widgets with the same key?

**Comment by markusaksli-nc** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

Thanks for your contribution.

**Comment by wangkaibule** [comment]
> Can someone enlighten me what duplicate keys in a list means?

Try restart your app instead, rather than reload
