### ISSUE TITLE
flutter gallery fails to run in --preview-dart-2 mode

### ISSUE THREAD

**Issue by aam** [flutter/flutter#15368]
With dart roll (https://github.com/flutter/engine/pull/4767) running flutter gallery in `--preview-dart-2` mode fails:
```
Launching lib/main.dart on iPhone X in debug mode...
Running Xcode clean...                                       1.1s
Starting Xcode build...                                          
 ├─Assembling Flutter resources...                       -
 5.4s
 └─Compiling, linking and signing...                  6.0s
Xcode build done                                            13.2s
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following NoSuchMethodError was thrown building
_OverlayEntry-[LabeledGlobalKey<_OverlayEntryState>#0e6f9](state: _OverlayEntryState#85633):
Class 'RenderStack' has no instance setter '_firstChild'.
Receiver: Instance of 'RenderStack'
Tried calling: _firstChildInstance of 'RenderIgnorePointer'

When the exception was thrown, this was the stack:
#0      Object.noSuchMethod (dart:core/object_patch.dart:46:5)
#1      _RenderStack&RenderBox&ContainerRenderObjectMixin._insertIntoChildList (package:flutter/src/rendering/object.dart:2727:7)
#2      _RenderStack&RenderBox&ContainerRenderObjectMixin.insert (package:flutter/src/rendering/object.dart:2766:5)
#3      MultiChildRenderObjectElement.insertChildRenderObject (package:flutter/src/widgets/framework.dart:4697:18)
#4      RenderObjectElement.attachRenderObject (package:flutter/src/widgets/framework.dart:4492:35)
#5      RenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4262:5)
#6      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4632:11)
#7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#8      Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#10     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#11     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#12     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752:11)
#13     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#15     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4738:32)
#16     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#17     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#18     _TheatreElement.mount (package:flutter/src/widgets/overlay.dart:493:16)
#19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#20     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#22     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#23     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#24     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752:11)
#25     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#27     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#29     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#30     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#31     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#32     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#33     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#34     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4633:14)
#35     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#36     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#38     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#39     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#40     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752:11)
#41     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#42     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#43     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#44     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4633:14)
#45     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#46     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#47     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4633:14)
#48     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#49     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#50     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#51     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#52     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#53     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752:11)
#54     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#55     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#56     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#57     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#58     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#59     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#60     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#61     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#62     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#63     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#64     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#65     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#66     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#67     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#68     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#69     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#70     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#71     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#72     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#73     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#74     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#75     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#76     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#77     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#78     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#79     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#80     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#81     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#82     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#83     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#84     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#85     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#86     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#87     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4633:14)
#88     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#89     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#90     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#91     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#92     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#93     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#94     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#95     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#96     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#97     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#98     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#99     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#100    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#101    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#102    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#103    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#104    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#105    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#106    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#107    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#108    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#109    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#110    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#111    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#112    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#113    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#114    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#115    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#116    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#117    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#118    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#119    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#120    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#121    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#122    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#123    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752:11)
#124    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#125    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#126    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#127    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#128    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#129    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#130    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#131    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#132    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#133    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#134    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#135    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#136    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752:11)
#137    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#138    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#139    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#140    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
[VERBOSE-2:dart_error.cc(16)] Unhandled exception:
'package:flutter/src/widgets/framework.dart': Failed assertion: line 2209 pos 20: '_debugCurrentBuildTarget == context': is not true.
#0      _AssertionError._doThrowNew (dart:core/errors_patch.dart)
#1      _AssertionError._throwNew (dart:core/errors_patch.dart:33:5)
#2      BuildOwner.buildScope.<anonymous closure> (package:flutter/src/widgets/framework.dart)
#3      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2213:12)
#4      RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:768:13)
#5      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:657:7)
#6      runApp (package:flutter/src/widgets/binding.dart:699:7)
#7      main (file:///Users/aam/projects/flutter/test_root6/flutter/flutter/examples/flutter_gallery/lib/main.dart:13:3)
#8      _startIsolate.<<…>
Syncing files to device iPhone X...                              
#141    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#142    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#143    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#144    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#145    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#146    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#147    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#148    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#149    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#150    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#151    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#152    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#153    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#154    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#155    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#156    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#157    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#158    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#159    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#160    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#161    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752:11)
#162    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#163    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#164    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#165    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#166    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#167    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#168    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#169    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#170    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#171    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#172    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#173    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#174    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752:11)
#175    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#176    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#177    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#178    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#179    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#180    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#181    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752:11)
#182    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#183    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#184    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#185    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:852:16)
#186    RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:823:5)
#187    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:769:17)
#188    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2205:19)
#189    RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:768:13)
#190    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:657:7)
#191    runApp (package:flutter/src/widgets/binding.dart:699:7)
#192    main (file:///Users/aam/projects/flutter/test_root6/flutter/flutter/examples/flutter_gallery/lib/main.dart:13:3)
#193    _startIsolate.<anonymous closure> (dart:isolate/isolate_patch.dart:279:19)
#194    _RawReceivePortImpl._handleMessage (dart:isolate/isolate_patch.dart:165:12)
════════════════════════════════════════════════════════════════════════════════════════════════════
Another exception was thrown: NoSuchMethodError: Class 'RenderStack' has no instance setter '_firstChild'.
```

**Comment by aam** [comment]
cc @peter-ahe-google @jensjoha

**Comment by aam** [comment]
quickly ran bisect, which shows that this was introduced in 9f56e283721ce7809f028680133484a6b24f9202 https://dart-review.googlesource.com/45021.

Hope this helps

**Comment by jensjoha** [comment]
This was fixed in https://github.com/dart-lang/sdk/commit/290c576264faa096a0b3206c71b2435309d9f904.

**Comment by mraleph** [comment]
@aam can you confirm that the issue is fixed? I closing this - please reopen if it is not.

**Comment by aam** [comment]
@mraleph yes, it was fixed(all preview-dart-2 flutter roll tests which relied on running flutter gallery in preview-dart-2 mode passed too).
