### ISSUE TITLE
Dart static type context signature crash in 1.17

### ISSUE THREAD

**Issue by dvird** [flutter/flutter#56479]
Hi guys, since updating to 1.17 I'm getting this error:
Doctor all good.
Tried clean, delete derived data, reinstall flutter

```
 Unhandled exception:
    NoSuchMethodError: The getter 'enclosingLibrary' was called on null.
    Receiver: null
    Tried calling: enclosingLibrary
    #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
    #1      new StaticTypeContext (package:kernel/type_environment.dart:763:27)
    #2      _TreeShakerPass1.staticTypeContext (package:vm/transformations/type_flow/transformer.dart:752:30)
    #3      _TreeShakerPass1._fixArgumentEvaluationOrder (package:vm/transformations/type_flow/transformer.dart:1007:41)
    #4      _TreeShakerPass1.visitConstructorInvocation (package:vm/transformations/type_flow/transformer.dart:1170:22)
    #5      ConstructorInvocation.accept (package:kernel/ast.dart:3964:44)
    #6      Field.transformChildren (package:kernel/ast.dart:1862:33)
    #7      _TreeShakerPass1.visitField (package:vm/transformations/type_flow/transformer.dart:903:16)
    #8      Field.accept (package:kernel/ast.dart:1847:40)
    #9      transformList (package:kernel/ast.dart:8700:27)
    #10     _TreeShakerPass1.visitClass (package:vm/transformations/type_flow/transformer.dart:856:5)
    #11     Class.accept (package:kernel/ast.dart:1375:38)
    #12     transformList (package:kernel/ast.dart:8700:27)
    #13     Library.transformChildren (package:kernel/ast.dart:627:5)
    #14     Transformer.defaultTreeNode (package:kernel/visitor.dart:650:10)
    #15     TreeVisitor.visitLibrary (package:kernel/visitor.dart:254:35)
    #16     Library.accept (package:kernel/ast.dart:609:38)
    #17     transformList (package:kernel/ast.dart:8700:27)
    #18     Component.transformChildren (package:kernel/ast.dart:8516:5)
    #19     _TreeShakerPass1.transform (package:vm/transformations/type_flow/transformer.dart:764:15)
    #20     TreeShaker.transformComponent (package:vm/transformations/type_flow/transformer.dart:582:12)
    #21     transformComponent (package:vm/transformations/type_flow/transformer.dart:76:7)
    #22     runGlobalTransformations (package:vm/kernel_front_end.dart:425:5)
    #23     compileToKernel (package:vm/kernel_front_end.dart:336:11)
    <asynchronous suspension>
    #24     FrontendCompiler.compile.<anonymous closure> (package:frontend_server/frontend_server.dart:510:54)
    #25     new Future.<anonymous closure> (dart:async/future.dart:176:37)
    #26     _rootRun (dart:async/zone.dart:1180:38)
    #27     _CustomZone.run (dart:async/zone.dart:1077:19)
    #28     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
    #29     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
    #30     _rootRun (dart:async/zone.dart:1184:13)
    #31     _CustomZone.run (dart:async/zone.dart:1077:19)
    #32     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1003:23)
    #33     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
    #34     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
    #35     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
    #36     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

    Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
    build failed.
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description

```

**Comment by mraleph** [comment]
Looks like it is caused by the dart-lang/sdk@a67aac8c6a4d88b055cc5bc4773ddc48afdfce61 - `visitField` should be setting `currentMember` but it does not. 

/cc @mkustermann @alexmarkov 

The bug is affecting one of the fields in one of your classes which has initialiser invoking a constructor which has optional parameters - unfortunately it is unclear to me if there is an easy way to locate which field in one of you classes is affected. There is no information about this in stack trace, and unfortunately I don't think we have any debug logging that would allow us to pinpoint it.

/cc @pcsosinski

**Comment by alexmarkov** [comment]
This crash started to happen since tree-shaker started converting optional parameters to required (since https://github.com/dart-lang/sdk/commit/a67aac8c6a4d88b055cc5bc4773ddc48afdfce61 or more earlier commit https://github.com/dart-lang/sdk/commit/9ab51b8012ea82c345a80e905e376d6d37e17481 which was reverted). Crash could happen when tree shaker converts optional parameters to required parameters in a call inside field initializer.

https://dart-review.googlesource.com/c/sdk/+/146980 should fix this bug.

**Comment by dvird** [comment]
Guys, it's on the stable channel.. what can we do? ive tried to downgrade but the command not working.

**Comment by ayush221b** [comment]
cc @Hixie

**Comment by pcsosinski** [comment]
what command are you trying to run to downgrade?

**Comment by dvird** [comment]
flutter downgrade

**Comment by dvird** [comment]
run 'flutter version v1.12.13+hotfix.9' to downgrade it back.
I also have other problem on ios

**Comment by tvolkert** [comment]
@dvird we're looking to issue a stable update (`1.17.1`) to fix this.

**Comment by dvird** [comment]
Great, thanks :) how long you estimate it's going to take for you?

**Comment by tvolkert** [comment]
No definitive timeline since it has to go through testing, and we're looking for other candidate fixes to bundle with it.  But as soon as we can 🙂

**Comment by pcsosinski** [comment]
@franklinyow we'll need this for 1.18 beta as well @athomas

**Comment by franklinyow** [comment]
@mkustermann   Can you start a merge request issue for [stable](https://github.com/dart-lang/sdk/issues/new?title=%5BCP%5DPlease%20merge%20%23HASH%20into%20%5Bstable%5D%20channel&labels=merge-to-stable,cherry-pick-review&body=%2A%2Acommit%28s%29+to+merge%2A%2A%3A+COMMIT-HASH%0A%0A%2A%2Amerge+instructions%2A%2A%3A+clean+merge+or+patch+CL%0A%0A%2A%2Areason%2A%2A%3A+Brief+description+of+the+problem+and+impact,+link+to+original+issue(s).%0A%0A%2Fcc+%40dgrove+%40kevmoo+%40mit-mit+%40whesse+%40athomas+%40vsmenon+%40franklinyow%0A%0A--------%0AThank+you+for+filing+a+cherrypick+request%2C+please%3A%0A++%2A+fill+in+the+data+above%0A++%2A+set+a+milestone,+and+area+label+%28e.g.+area-dart2js+for+a+dart2js+fix%29,+and+%E2%80%9Dmerge-to-stable%E2%80%9D+label+%0A++%2A+attempt+to+do+the+merge+%28%60git+checkout+origin%2Fstable%3B+git+cherry-pick+HASH%60%29+to+ensure+the+merge+instructions+are+accurate.%0A++%2A+delete+this+comment+and+examples+%3A%29%0A%0AEXAMPLE+1%3A%0A%3E+%2A%2Acommit+to+merge%2A%2A%3A+a7e511f+%28Should+match+the+hash+in+the+title.+It%27s+OK+to+have+more+than+one+commit%2C+but+please+explain.%29%0A%3E%0A%3E+%2A%2Amerge+instructions%2A%2A%3A+merges+cleanly+in+%60origin%2Fstable%60%0A%3E%0A%3E+%2A%2Areason%2A%2A%3A+fixes+bug+with+nsm-forwarders+with+named+arguments.+Affects+customers+unit+tests+that+use+mockito.%0A%0AEXAMPLE+2%3A%0A%3E+%2A%2Acommit+to+merge%2A%2A%3A+a7e511f%0A%3E%0A%3E+%2A%2Amerge+instructions%2A%2A%3A+patch+%5BCL%2Fxyz%5D%28link%29+%28merge+had+conflicts%2C+CL+resolves+them%29.%0A%3E%0A%3E+%2A%2Areason%2A%2A%3A+fixes+bug+with+nsm-forwarders+with+named+arguments.+Affects+%3E+customers+unit+tests+that+use+mockito.)

**Comment by mkustermann** [comment]
I've filed a cherry-pick request for stable: https://github.com/dart-lang/sdk/issues/41816

**Comment by xster** [comment]
https://dart-review.googlesource.com/c/sdk/+/146980 doesn't look like there's anything iOS specific is there?

**Comment by alexmarkov** [comment]
@xster The bug and the fix are not iOS specific.

**Comment by pcsosinski** [comment]
CP'd into dart

**Comment by tvolkert** [comment]
Should this be closed now?

**Comment by alexmarkov** [comment]
Yes, the fix was rolled into Flutter.
