### ISSUE TITLE
apk from "flutter run --release" does not crash, but apk from "flutter build apk" crashes

### ISSUE THREAD

**Issue by bhan** [flutter/flutter#48015]
I am developing on an OSX 10.14.6 Macbook Pro with the following Flutter version:

Flutter 1.12.13+hotfix.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 27321ebbad (3 weeks ago) • 2019-12-10 18:15:01 -0800
Engine • revision 2994f7e1e6
Tools • Dart 2.7.0

I'm running into an issue where my app crashes when I install the APK from "flutter build apk" or "flutter build apk --target-platform android-arm64". 

However, the app doesn't crash when the APK is installed through "flutter run --release". I've also re-installed the same APK installed through "flutter run --release" and the app works fine (Xiaomi has a share app feature where I can send the raw APK for the app).

The problem isn't unique to my Xiaomi 9 Pro 5G. It happens on all Android devices I've tested.

The APK that works is here: https://cdn.qianmaschool.com/test/base.apk

And the APK that crashes is here: https://cdn.qianmaschool.com/test/test.apk

I unzipped the two and it seems like the major difference is the classes.dex file for the APK that works is larger.

The app crashes with this error:
<img width="931" alt="1" src="https://user-images.githubusercontent.com/1280879/71620299-33df8780-2c04-11ea-9f8a-14298cf24c7a.png">
<img width="926" alt="2" src="https://user-images.githubusercontent.com/1280879/71620304-36da7800-2c04-11ea-969f-e31ca17df0f3.png">
<img width="926" alt="3" src="https://user-images.githubusercontent.com/1280879/71620309-39d56880-2c04-11ea-807c-ee234ef7864b.png">
<img width="926" alt="4" src="https://user-images.githubusercontent.com/1280879/71620310-3cd05900-2c04-11ea-8185-fcc986cfb2d4.png">

Here are two videos comparing the non-crashing and crashing apks: 
[screencaps.zip](https://github.com/flutter/flutter/files/4012570/screencaps.zip)

The crash is related to a third party SDK that uses JNI, and it seems like the "flutter build apk" version cannot find the methods called by that SDK, whereas the "flutter run --release" version can. The third party SDK is accessed through a plugin.

Here is my project structure (the plugin is under the plugins/speech directory):
<img width="356" alt="screenshot" src="https://user-images.githubusercontent.com/1280879/71620529-5de57980-2c05-11ea-928c-2f56989ae7f4.png">

[android_directory_build.gradle.zip]
(https://github.com/flutter/flutter/files/4012578/android_directory_build.gradle.zip)

[plugin_directory_build.gradle.zip](https://github.com/flutter/flutter/files/4012579/plugin_directory_build.gradle.zip)

Any tips as to why these two release APKs would have different behavior? Thanks!

**Comment by VladyslavBondarenko** [comment]
Hi @bhan 
Could you provide your `flutter build apk --verbose`?
Please, paste logs in text form instead of attaching pictures
Thank you

**Comment by bhan** [comment]
Hi @VladyslavBondarenko . Thank you for the quick response, and happy new year!

I ran `flutter clean` and have attached the output of `flutter build apk --verbose`. Let me know if you need anything else.

[build.log](https://github.com/flutter/flutter/files/4013864/build.log)

**Comment by bitsydarel** [comment]
Maybe running, try the following workaround:
flutter clean
flutter create .
flutter build apk —verbose

**Comment by Samuramu** [comment]
I also have this problem. Pre-launch tests on Google Play console also crash on all devices.

**Comment by bhan** [comment]
@bitsydarel Thanks for the suggestion, but the crashing behavior is the same. Does that workaround work for some related issue?

**Comment by bhan** [comment]
> I also have this problem. Pre-launch tests on Google Play console also crash on all devices.

@Samuramu When does your app crash during pre-launch tests? Mine only crashes when trying to execute a specific method in a third party library that uses JNI.

**Comment by bhan** [comment]
@VladyslavBondarenko I've just tried the beta and master channels with the same crashing behavior. Any suggestions for next steps?

**Comment by bhan** [comment]
@VladyslavBondarenko changing the flutter channel back to `v1.9.1-hotfixes` gets rid of the crashing issue, so this bug seems to be something introduced between `v1.9.1-hotfixes` and the current `stable` branch.

**Comment by VladyslavBondarenko** [comment]
Thanks for the comment, @bhan 
I'm glad you managed with it

**Comment by VladyslavBondarenko** [comment]
Possibly related to [#48039](https://github.com/flutter/flutter/issues/48039)

**Comment by bhan** [comment]
@VladyslavBondarenko Is there a plan to fix this on `master`?

**Comment by danydev** [comment]
I'm having the same exact problem. In my case the library using JNI was Tesseract used in java code (with Tesseract4Android java library).
Everything works correctly with `flutter run --release` but as soon as I produce a fat apk with `flutter build apk` I got `java.lang.NoClassDefFoundError: com.googlecode.tesseract.android.TessBaseAPI`.
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57, locale en-IT)
```
I just tried to change flutter channel to `v1.9.1-hotfixes` as adviced by @bhan and the apk works correctly.

**Comment by bhan** [comment]
The result of the `git bisect` is:

```0df1594ba263493937e3e4d5d2c5062a7ecc6c71 is the first bad commit
commit 0df1594ba263493937e3e4d5d2c5062a7ecc6c71
Author: Emmanuel Garcia <egarciad@google.com>
Date:   Mon Sep 16 15:27:05 2019 -0700

    Enable the resource shrinker (#40610)

:040000 040000 0be7e0248eda99952fb64ec5954755fd4eccda3f 4a469f256c53003a919e0ff1cdb2681de05ede5f M   dev
:040000 040000 ff8d46de9aa05cd222e9241b34e159b24337c3a5 973da718eed6faaf69a05134ccc81867fa2208f8 M   packages
```
@danydev Can you compare the APKs generated from `commit 26bb93145f2b2f395f524593e1e12f052558cc45` (the one before the `git bisect bad` result) and `commit 0df1594ba263493937e3e4d5d2c5062a7ecc6c71`?

@blasten @VladyslavBondarenko This commit seems to have introduced an issue with Java Native Interface linking.

**Comment by blasten** [comment]
Thanks for filing this bug.

Which 3P SDK are you using?  We enabled R8 by default for release builds. As a result, all JNI methods must be annotated with the `@Keep` annotation, so R8 doesn't delete them.

You can also use `flutter build apk --no-shrink` to disable R8.

Let me know if this answer the question and if so, consider closing the bug.

**Comment by blasten** [comment]
Here's more about `@Keep`: https://developer.android.com/reference/android/support/annotation/Keep

**Comment by bhan** [comment]
@blasten Thanks for the response and workaround.

I will follow up with our third party library provider so that they add the `@Keep` annotation to avoid deletion by R8.

I guess the remaining worry I have is that this behavior is only reproducible with `flutter build apk` and not `flutter run --release`. Not coming from a native Android developer background, there was no easy way for me to figure out through the error logs to disable R8 or to add the `@Keep` annotation.

Is there any way to make it easier for developers to figure out how to solve this issue on their own?

**Comment by Gaoxichao** [comment]
我有同样的问题，楼主知道怎么解决吗？我的貌似也是升级版本后就这样了，直接run可以，但是build出来的就闪退，好像是so架构兼容问题，找了很多解决办法没有解决。

**Comment by bhan** [comment]
> 我有同样的问题，楼主知道怎么解决吗？我的貌似也是升级版本后就这样了，直接run可以，但是build出来的就闪退，好像是so架构兼容问题，找了很多解决办法没有解决。

@Gaoxichao 你好。可以用blasten提出的解决方案，就是`flutter build apk`加上`--no-shrink`关掉R8，之后编译都用`flutter build apk --no-shrink`。如果你能改相关的Java代码也可以在方法上加上 @Keep 防止R8删除你需要的方法，这样就不用加`--no-shrink`了。

问题出现是由于新的flutter的stable版本默认开启了R8，而R8有时会错误地判断一个方法没有被调用，然后把它删除，导致你调用的时候找不到方法然后闪退。

这些上面都有解释，如果需要翻译建议用谷歌翻译的中国网站 translate.google.cn ，目前在国内还没有被封。

**Comment by Gaoxichao** [comment]
谢谢，不过跟我的好像不一样，我的问题更准确来说，是build release后，libflutter.so会缺少，我现在试着降级flutter版本试试。

**Comment by Gaoxichao** [comment]
> > 我有同样的问题，楼主知道怎么解决吗？我的貌似也是升级版本后就这样了，直接run可以，但是build出来的就闪退，好像是so架构兼容问题，找了很多解决办法没有解决。
> 
> @Gaoxichao 你好。可以试试`blasten`提出的解决方案，就是`flutter build apk`加上`--no-shrink`关掉R8，之后编译都用`flutter build apk --no-shrink`。如果你能改相关的Java代码也可以在方法上加上 `@Keep` 防止R8删除你需要的方法，这样就不用加`--no-shrink`了。
> 
> 问题出现是由于新的flutter的stable版本默认开启了R8，而R8有时会错误地判断一个方法没有被调用，然后把它删除，导致因为调用一个不存在的方法闪退。
> 
> 上面有更详细的解释，如果需要翻译建议用谷歌翻译的中国网站 translate.google.cn ，目前在国内还没有被封。

谢谢，不过跟我的好像不一样，我的问题更准确来说，是build release后，libflutter.so会缺少，我现在试着降级flutter版本试试。

**Comment by bhan** [comment]
@Gaoxichao `flutter build apk --no-shrink` 打的包的libflutter.so也会缺少吗？

**Comment by Gaoxichao** [comment]
> @Gaoxichao `flutter build apk --no-shrink` 打的包的libflutter.so也会缺少吗？
> 
> 如果不好使，我建议在你的flutter SDK文件夹里用 `git bisect` (http://www.ruanyifeng.com/blog/2018/12/git-bisect.html) 找到具体是哪个`commit`之后会出现你的问题。

谢谢，我觉得问题可能是出现在新版本本身，或是我电脑flutter环境导致（这个问题我有在其他issues看见过，很大可能是这两个原因）。降级到flutter 1.9版本后，好像解决了此问题。

**Comment by zanderso** [comment]
The action item here seems to be to make both of these commands behave the same way. Assigning to @blasten to look into that.

**Comment by BaptisteOue** [comment]
Hi,

I am facing the same issue (flutter run --relase works as expected but building and installing the app makes it crash) and the --no-shrink option did indeed fix it. But is it the final fix ? I mean while it seems to work, having to test first without the --no-shrink options, launch the app, see if it crashes and if it does rebuild with the --no-shrink, is kind of a weird way of developping ... But maybe did I miss something ?

Thanks in advance for your response.

**Comment by danydev** [comment]
@BaptisteOue the "final fix" is to make `flutter run --relase` crash just like `flutter build` and then understanding in your specific case which class is missing, and fixing it (either by using `@Keep` or changing the `proguard` file . For example I opened a bug on the external library I was using (see above)

**Comment by BaptisteOue** [comment]
@danydev Thanks, I got it.
Not really sur if it's relevant but in my particular case `flutter run --release` launch the app and it does not crash. But `flutter build` **do not** crash either, it build the app and I can then `flutter install` as usual. That's when I open it on the device that it crashes (while with `flutter run --release` the app is working).

**Comment by danydev** [comment]
What you describe is expected. When I said "`flutter run --relase ` should crash just like `flutter build`", I actually meant "`flutter run --relase` should crash just like it crashes at runtime if you install & run the app produced with `flutter build`"

**Comment by MichalMisiaszek** [comment]
I can't run Release version of app on the device at all, the Debug version works like charm.

**Comment by MichalMisiaszek** [comment]
flutter run --release is crashing too without any error on console :(

**Comment by NedWilbur** [comment]
`flutter build apk --no-shrink` resolved issue for me. Pubspec dependencies can be found here: [pubspec.txt](https://github.com/flutter/flutter/files/4101252/pubspec.txt)

**Comment by manburenshenglu** [comment]
flutter build apk --no-shrink resolved issue for me。tks

**Comment by NedWilbur** [comment]
@manburenshenglu Note, while this resolved it, you should not release without shrinking. This should just hint to you that something is being shrunk that should not. 

For me, it was the `https://pub.dev/packages/flutter_local_notifications` package and missing a required proguard rule `-keep class com.dexterous.** { *; }`. 

Hope this helps.

**Comment by tharinduprabath** [comment]
I'm not added internet permission to manifest file. After adding it works.

**Comment by prinzpiuz** [comment]
mine also fixed by running `flutter build apk --split-per-abi --no-shrink`

**Comment by blasten** [comment]
I'm going to close this issue. If you are using a plugin that doesn't work with R8, I'd suggest filing a new issue for that individual plugin.

The Android Gradle plugin will make R8 the default in an upcoming release. At that point, we will remove the `--no-shrink` option since it won't have any effect.
