### PR TITLE
Replace CocoaPods deprecated `exists?` with `exist?`

### LINKED ISSUE #147041: [Regression] Cocoapods shows "undefined method `exists?' for File:Class" error
### Steps to reproduce

This bug is back in 

```
$ flutter --version
Flutter 3.22.0-14.0.pre.33 • channel master • https://github.com/flutter/flutter.git
Framework • revision 12d54de962 (2 hours ago) • 2024-04-19 03:10:34 -0400
Engine • revision 25d773ea90
Tools • Dart 3.5.0 (build 3.5.0-76.0.dev) • DevTools 2.35.0-dev.8
```

* https://github.com/flutter/flutter/issues/141167
* https://github.com/flutter/flutter/issues/118295

(I can't reopen my original bug)

It was re-introduced by https://github.com/flutter/flutter/commit/6d19fa3bfa2beee81ee2730dc9aae241b051857c, 12 hours ago.

It's called `exist?` since Ruby 2.2 and the deprecated `exists?` method was removed in Ruby 3.2. And Cocoapods installed by Homebrew uses Ruby 3.3, so it crashes.

### Expected results

it should work

### Actual results

it doesn't

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

### PR DESCRIPTION
**Pull request by vashworth**
Fixes https://github.com/flutter/flutter/issues/147041.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[Data Driven Fixes]: https://github.com/flutter/flutter/wiki/Data-driven-Fixes

### CODE REVIEW

**Comment by vashworth** [comment]
@stuartmorgan Can you also test-exempt? Existing integration tests validate it does not break anything, but unfortunately can't test that it fixes since we don't have a newer version of Ruby.

**Comment by stuartmorgan** [comment]
test-exempt: code refactor with no semantic change

**Review by stuartmorgan-g — APPROVED** [review]
LGTM
