### ISSUE TITLE
Error when Upgrade Camera plugin version to 0.7.0+1 

### ISSUE THREAD

**Issue by Sathi789888** [flutter/flutter#74966]
I'm upgrade the camera plugin version to 0.7.0+1 at runtime  I have two errors to stop application

error: cannot find symbol
    if (VERSION.SDK_INT >= VERSION_CODES.R) {
                                        ^
  symbol:   variable R
  location: class VERSION_CODES

and

error: cannot find symbol
      return activity.getDisplay();
                     ^
  symbol:   method getDisplay()
  location: variable activity of type Activity

**Comment by TahaTesser** [comment]
Hi @Sathi789888 
I see there's an open issue addressing the case you described. https://github.com/flutter/flutter/issues/74915
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
