### ISSUE TITLE
Stable hotfix bad merge

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#85664]
in the PR https://github.com/flutter/engine/pull/27081 I cherrypicked https://github.com/flutter/engine/pull/26628, but I merged it incorrectly, and it lead to the following compilation failure:

```
../../flutter/shell/platform/android/io/flutter/plugin/editing/InputConnectionAdaptor.java:48: error: cannot find symbol
  private final KeyboardManager keyboardManager;
                ^
  symbol:   class KeyboardManager
  location: class InputConnectionAdaptor
1 error
```

https://ci.chromium.org/p/flutter/builders/try/Linux%20Host%20Engine/24238?

**Comment by christopherfujino** [comment]
Closed in https://github.com/flutter/engine/pull/27087
