### ISSUE TITLE
Shader compilation error on windows 8

### ISSUE THREAD

**Issue by reddream** [flutter/flutter#107219]
How to make the app build from flutter work correctly on windows 8 ? I only created a simple app ,but it does not look good.

## Steps to Reproduce

1. Create a test app using flutter create testapp --platforms=windows8
2. Build the app using fluter build windows
3. Copy the testapp\build\windows\runner\Release folder into my windows8 which version is 6.2 (internal version 9200)
4. Run this app in windows8

**Expected results:** 
It is ok on windows 10.
![runnormal](https://user-images.githubusercontent.com/293340/177729149-1e13dbdf-02af-4d0c-b4c2-305c207b6def.png)

**Actual results:** 
on windows 8:
![runerror](https://user-images.githubusercontent.com/293340/177727068-2d878cd4-5993-4f73-8752-e9e5f5d6d513.png)

I got the error logs on console window:
------------------------
   1    // Vertex SKSL
   2    uniform float4 sk_RTAdjust;uniform float3x3 ulocalMatrix_S0;in float2 in
Position;in half4 inColor;in float4 inCircleEdge;out float4 vinCircleEdge_S0;out
 half4 vinColor_S0;void main() {// Primitive Processor CircleGeometryProcessor
   3    vinCircleEdge_S0 = inCircleEdge;vinColor_S0 = inColor;float2 _tmp_0_inPo
sition = inPosition;float2 _tmp_1_inPosition = float3x2(ulocalMatrix_S0) * inPos
ition.xy1;
   4    sk_Position = _tmp_0_inPosition.xy01;}
   5    // Fragment SKSL
   6    in float4 vinCircleEdge_S0;in half4 vinColor_S0;out half4 sk_FragColor;
   7    void main() {// Stage 0, CircleGeometryProcessor
   8    float4 circleEdge;circleEdge = vinCircleEdge_S0;half4 outputColor_S0;out
putColor_S0 = vinColor_S0;float d = length(circleEdge.xy);half distanceToOuterEd
ge = half(circleEdge.z * (1.0 - d));half edgeAlpha = saturate(distanceToOuterEdg
e);half4 outputCoverage_S0 = half4(edgeAlpha);{ // Xfer Processor: Porter Duff
   9    sk_FragColor = outputColor_S0 * outputCoverage_S0;}}
  10    // Vertex GLSL
  11    #version 300 es
  12
  13    precision mediump float;
  14    precision mediump sampler2D;
  15    uniform highp vec4 sk_RTAdjust;
  16    uniform highp mat3 ulocalMatrix_S0;
  17    in highp vec2 inPosition;
  18    in mediump vec4 inColor;
  19    in highp vec4 inCircleEdge;
  20    out highp vec4 vinCircleEdge_S0;
  21    out mediump vec4 vinColor_S0;
  22    void main() {
  23        vinCircleEdge_S0 = inCircleEdge;
  24        vinColor_S0 = inColor;
  25        highp vec2 _tmp_0_inPosition = inPosition;
  26        gl_Position = vec4(_tmp_0_inPosition, 0.0, 1.0);
  27        gl_Position = vec4(gl_Position.xy * sk_RTAdjust.xz + gl_Position.ww
* sk_RTAdjust.yw, 0.0, gl_Position.w);
  28    }
  29
  30    // Fragment GLSL
  31    #version 300 es
  32
  33    precision mediump float;
  34    precision mediump sampler2D;
  35    out mediump vec4 sk_FragColor;
  36    in highp vec4 vinCircleEdge_S0;
  37    in mediump vec4 vinColor_S0;
  38    void main() {
  39        highp vec4 circleEdge;
  40        circleEdge = vinCircleEdge_S0;
  41        mediump vec4 outputColor_S0;
  42        outputColor_S0 = vinColor_S0;
  43        highp float d = length(circleEdge.xy);
  44        mediump float distanceToOuterEdge = circleEdge.z * (1.0 - d);
  45        mediump float edgeAlpha = clamp(distanceToOuterEdge, 0.0, 1.0);
  46        mediump vec4 outputCoverage_S0 = vec4(edgeAlpha);
  47        {
  48            sk_FragColor = outputColor_S0 * outputCoverage_S0;
  49        }
  50    }
  51
  52
Errors:
link failed but did not provide an info log
Shader compilation error

<details>
<summary>Code sample</summary>
this is my code:
[testapp.zip](https://github.com/flutter/flutter/files/9061768/testapp.zip)

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by iapicca** [comment]
isn't the lowest supported version `windows 10`?

**Comment by reddream** [comment]
> isn't the lowest supported version `windows 10`?

The testapp runs correctly on windows 7 and windows 8.1.   But this issue happend on windows 8.

**Comment by maheshmnj** [comment]
Hi @reddream, Thanks for filing the issue. Unfortunately, I do not have a windows 8 to verify the issue. Could you please share what version of flutter are you using by running `flutter doctor -v`?

Also there is an open proposal to switch to a standard bundle for app distribution  https://github.com/flutter/flutter/issues/63672  I believe this should help resolve such issues in the future.

**Comment by reddream** [comment]
> Hi @reddream, Thanks for filing the issue. Unfortunately, I do not have a windows 8 to verify the issue. Could you please share what version of flutter are you using by running `flutter doctor -v`?
> 
> Also there is an open proposal to switch to a standard bundle for app distribution #63672 I believe this should help resolve such issues in the future.

Thank you for your response.
I develop the app on windows 10 with flutter 3.0.4 stable version. Then I deploy it on other windows.  It works fine on windows  7 and windows 8.1 .  The issue is on Windows 8(mainversion 6.2, internal version 9200).  
  This is the one of my dev env(I have 2 dev env, another one uses vs2019 . The versions of flutter are the same) below:
     
<img width="705" alt="flutterdoctor" src="https://user-images.githubusercontent.com/293340/177784948-396d4187-dc3f-413e-8dd5-5a67e94646df.png">

I also found that vcruntime library does not work on testapp I deploy on windows 8.  Although vcruntime dlls are in system32,  I analyzed testapp.exe throgh Dependency Walker showing the runtime140_1.dll missing.

**Comment by maheshmnj** [comment]
Labeling this issue for further investigation from the team.

**Comment by gspencergoog** [comment]
What is the hardware that Windows 8 is running on? And what is the graphics card?

cc @chinmaygarde

**Comment by cwangfr** [comment]
I have same error on win7, use J1900 cpu. But not every start app crash, There is about a 30% chance of crashing

**Comment by iapicca** [comment]
@gspencergoog 
does flutter even support windows 8 as a target?
for development [supports windows10 or later ](https://docs.flutter.dev/get-started/install/windows/desktop#operating-system) only
