### ISSUE TITLE
3.44.0 breaks native compilation of plugins on Windows ARM

### ISSUE THREAD

**Issue by Adam-Langley** [flutter/flutter#186836]
### Steps to reproduce

1. install Flutter SDK 3.44.0 on a Windows/ARM64 machine (I'm using Parallels on a M4 Max Macbook Pro)
2. write a simple application that uses native plugins, examples of plugins which will no longer compile are 
  1. syncfusion_pdfviewer_windows
  2. desktop_webview_window

Note: downgrading to 3.41.9 resolves the issue.

### Expected results

Program should compile and run just fine.

### Actual results

Program fails to compile - fails with multiple linking errors "error LNK2019: unresolved external symbol"

### Code sample

-

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```
Launching lib\main.dart on Windows in debug mode...
web_view.obj : error LNK2019: unresolved external symbol CreateCoreWebView2EnvironmentWithOptions referenced in function "public: __cdecl webview_window::WebView::WebView(class std::shared_ptr<class flutter::MethodChannel<class flutter::EncodableValue> >,__int64,class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> >,class std::function<void __cdecl(long)>)" (??0WebView@webview_window@@QEAA@V?$shared_ptr@V?$MethodChannel@VEncodableValue@flutter@@@flutter@@@std@@_JV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@3@V?$function@$$A6AXJ@Z@3@@Z) [C:\Users\<USER>\source\repos\<REPO>\src\<APP>\build\windows\arm64\plugins\desktop_webview_window\desktop_webview_window_plugin.vcxproj]
web_view_window_plugin.obj : error LNK2019: unresolved external symbol GetAvailableCoreWebView2BrowserVersionString referenced in function "bool __cdecl `anonymous namespace'::IsWebViewRuntimeAvailable(void)" (?IsWebViewRuntimeAvailable@?A0x9ea8913d@@YA_NXZ) [C:\Users\<USER>\source\repos\<REPO>\src\<APP>\build\windows\arm64\plugins\desktop_webview_window\desktop_webview_window_plugin.vcxproj]
C:\Users\<USER>\source\repos\<REPO>\src\<APP>\windows\flutter\ephemeral\.plugin_symlinks\desktop_webview_window\windows\libs\x64\Webview2Loader.dll.lib : warning LNK4272: library machine type 'x64' conflicts with target machine type 'ARM64' [C:\Users\<USER>\source\repos\<REPO>\src\<APP>\build\windows\arm64\plugins\desktop_webview_window\desktop_webview_window_plugin.vcxproj]
C:\Users\<USER>\source\repos\<REPO>\src\<APP>\build\windows\arm64\plugins\desktop_webview_window\Debug\desktop_webview_window_plugin.dll : fatal error LNK1120: 2 unresolved externals [C:\Users\<USER>\source\repos\<REPO>\src\<APP>\build\windows\arm64\plugins\desktop_webview_window\desktop_webview_window_plugin.vcxproj]
pdfviewer.obj : error LNK2019: unresolved external symbol FPDF_InitLibraryWithConfig referenced in function "class std::shared_ptr<class pdfviewer::PdfDocument> __cdecl pdfviewer::initializePdfRenderer(class std::vector<unsigned char,class std::allocator<unsigned char> >,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)" (?initializePdfRenderer@pdfviewer@@YA?AV?$shared_ptr@VPdfDocument@pdfviewer@@@std@@V?$vector@EV?$allocator@E@std@@@3@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@3@1@Z) [C:\Users\<USER>\source\repos\<REPO>\src\<APP>\build\windows\arm64\plugins\syncfusion_pdfviewer_windows\syncfusion_pdfviewer_windows_plugin.vcxproj]
pdfviewer.obj : error LNK2019: unresolved external symbol FPDF_LoadDocument referenced in function "public: __cdecl pdfviewer::PdfDocument::PdfDocument(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)" (??0PdfDocument@pdfviewer@@QEAA@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@00@Z) [C:\Users\<USER>\source\repos\<REPO>\src\<APP>\build\windows\arm64\plugins\syncfusion_pdfviewer_windows\syncfusion_pdfviewer_windows_plugin.vcxproj]
pdfviewer.obj : error LNK2019: unresolved external symbol FPDF_LoadMemDocument64 referenced in function "public: __cdecl pdfviewer::PdfDocument::PdfDocument(class std::vector<unsigned char,class std::allocator<unsigned char> >,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)" (??0PdfDocument@pdfviewer@@QEAA@V?$vector@EV?$allocator@E@std@@@std@@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@3@1@Z) [C:\Users\<USER>\source\repos\<REPO>\src\<APP>\build\windows\arm64\plugins\syncfusion_pdfviewer_windows\syncfusion_pdfviewer_windows_plugin.vcxproj]
pdfviewer.obj : error LNK2019: unresolved external symbol FPDF_CloseDocument referenced in function "void __cdecl pdfviewer::closePdfDocument(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)" (?closePdfDocument@pdfviewer@@YAXV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) [C:\Users\<USER>\source\repos\<REPO>\src\<APP>\build\windows\arm64\plugins\syncfusion_pdfviewer_windows\syncfusion_pdfviewer_windows_plugin.vcxproj]
syncfusion_pdfviewer_windows_plugin.obj : error LNK2019: unresolved external symbol FPDF_GetPageCount referenced in function "void __cdecl pdfviewer::InitializePdfRenderer(class flutter::MethodCall<class flutter::EncodableValue> const &,class std::unique_ptr<class flutter::MethodResult<class flutter::EncodableValue>,struct std::default_delete<class flutter::MethodResult<class flutter::EncodableValue> > >)" (?InitializePdfRenderer@pdfviewer@@YAXAEBV?$MethodCall@VEncodableValue@flutter@@@flutter@@V?$unique_ptr@V?$MethodResult@VEncodableValue@flutter@@@flutter@@U?$default_delete@V?$MethodResult@VEncodableValue@flutter@@@flutter@@@std@@@std@@@Z) [C:\Users\<USER>\source\repos\<REPO>\src\<APP>\build\windows\arm64\plugins\syncfusion_pdfviewer_windows\syncfusion_pdfviewer_windows_plugin.vcxproj]
syncfusion_pdfviewer_windows_plugin.obj : error LNK2019: unresolved external symbol FPDF_LoadPage referenced in function "void __cdecl pdfviewer::GetPagesHeight(class flutter::MethodCall<class flutter::EncodableValue> const &,class std::unique_ptr<class flutter::MethodResult<class flutter::EncodableValue>,struct std::default_delete<class flutter::MethodResult<class flutter::EncodableValue> > >)" (?GetPagesHeight@pdfviewer@@YAXAEBV?$MethodCall@VEncodableValue@flutter@@@flutter@@V?$unique_ptr@V?$MethodResult@VEncodableValue@flutter@@@flutter@@U?$default_delete@V?$MethodResult@VEncodableValue@flutter@@@flutter@@@std@@@std@@@Z) [C:\Users\<USER>\source\repos\<REPO>\src\<APP>\build\windows\arm64\plugins\syncfusion_pdfviewer_windows\syncfusion_pdfviewer_windows_plugin.vcxproj]
syncfusion_pdfviewer_windows_plugin.obj : error LNK2019: unresolved external symbol FPDF_GetPageWidthF referenced in function "void __cdecl pdfviewer::GetPagesWidth(class flutter::MethodCall<class flutter::EncodableValue> const &,class std::unique_ptr<class flutter::MethodResult<class flutter::EncodableValue>,struct std::default_delete<class flutter::MethodResult<class flutter::EncodableValue> > >)" (?GetPagesWidth@pdfviewer@@YAXAEBV?$MethodCall@VEncodableValue@flutter@@@flutter@@V?$unique_ptr@V?$MethodResult@VEncodableValue@flutter@@@flutter@@U?$default_delete@V?$MethodResult@VEncodableValue@flutter@@@flutter@@@std@@@std@@@Z) [C:\Users\<USER>\source\repos\<REPO>\src\<APP>\build\windows\arm64\plugins\syncfusion_pdfviewer_windows\syncfusion_pdfviewer_windows_plugin.vcxproj]
syncfusion_pdfviewer_windows_plugin.obj : error LNK2019: unresolved external symbol FPDF_GetPageHeightF referenced in function "void __cdecl pdfviewer::GetPagesHeight(class flutter::MethodCall<class flutter::EncodableValue> const &,class std::unique_ptr<class flutter::MethodResult<class flutter::EncodableValue>,struct std::default_delete<class flutter::MethodResult<class flutter::EncodableValue> > >)" (?GetPagesHeight@pdfviewer@@YAXAEBV?$MethodCall@VEncodableValue@flutter@@@flutter@@V?$unique_ptr@V?$MethodResult@VEncodableValue@flutter@@@flutter@@U?$default_delete@V?$MethodResult@VEncodableValue@flutter@@@flutter@@@std@@@std@@@Z) [C:\Users\<USER>\source\repos\<REPO>\src\<APP>\build\windows\arm64\plugins\syncfusion_pdfviewer_windows\syncfusion_pdfviewer_windows_plugin.vcxproj]
syncfusion_pdfviewer_windows_plugin.obj : error LNK2019: unresolved external symbol FPDF_RenderPageBitmap referenced in function "void __cdecl pdfviewer::GetPdfPageImage(class flutter::MethodCall<class flutter::EncodableValue> const &,class std::unique_ptr<class flutter::MethodResult<class flutter::EncodableValue>,struct std::default_delete<class flutter::MethodResult<class flutter::EncodableValue> > >)" (?GetPdfPageImage@pdfviewer@@YAXAEBV?$MethodCall@VEncodableValue@flutter@@@flutter@@V?$unique_ptr@V?$MethodResult@VEncodableValue@flutter@@@flutter@@U?$default_delete@V?$MethodResult@VEncodableValue@flutter@@@flutter@@@std@@@std@@@Z) [C:\Users\<USER>\source\repos\<REPO>\src\<APP>\build\windows\arm64\plugins\syncfusion_pdfviewer_windows\syncfusion_pdfviewer_windows_plugin.vcxproj]
syncfusion_pdfviewer_windows_plugin.obj : error LNK2019: unresolved external symbol FPDF_RenderPageBitmapWithMatrix referenced in function "void __cdecl pdfviewer::GetPdfPageTileImage(class flutter::MethodCall<class flutter::EncodableValue> const &,class std::unique_ptr<class flutter::MethodResult<class flutter::EncodableValue>,struct std::default_delete<class flutter::MethodResult<class flutter::EncodableValue> > >)" (?GetPdfPageTileImage@pdfviewer@@YAXAEBV?$MethodCall@VEncodableValue@flutter@@@flutter@@V?$unique_ptr@V?$MethodResult@VEncodableValue@flutter@@@flutter@@U?$default_delete@V?$MethodResult@VEncodableValue@flutter@@@flutter@@@std@@@std@@@Z) [C:\Users\<USER>\source\repos\<REPO>\src\<APP>\build\windows\arm64\plugins\syncfusion_pdfviewer_windows\syncfusion_pdfviewer_windows_plugin.vcxproj]
syncfusion_pdfviewer_windows_plugin.obj : error LNK2019: unresolved external symbol FPDF_ClosePage referenced in function "void __cdecl pdfviewer::GetPagesHeight(class flutter::MethodCall<class flutter::EncodableValue> const &,class std::unique_ptr<class flutter::MethodResult<class flutter::EncodableValue>,struct std::default_delete<class flutter::MethodResult<class flutter::EncodableValue> > >)" (?GetPagesHeight@pdfviewer@@YAXAEBV?$MethodCall@VEncodableValue@flutter@@@flutter@@V?$unique_ptr@V?$MethodResult@VEncodableValue@flutter@@@flutter@@U?$default_delete@V?$MethodResult@VEncodableValue@flutter@@@flutter@@@std@@@std@@@Z) [C:\Users\<USER>\source\repos\<REPO>\src\<APP>\build\windows\arm64\plugins\syncfusion_pdfviewer_windows\syncfusion_pdfviewer_windows_plugin.vcxproj]
syncfusion_pdfviewer_windows_plugin.obj : error LNK2019: unresolved external symbol FPDFBitmap_Create referenced in function "void __cdecl pdfviewer::GetPdfPageImage(class flutter::MethodCall<class flutter::EncodableValue> const &,class std::unique_ptr<class flutter::MethodResult<class flutter::EncodableValue>,struct std::default_delete<class flutter::MethodResult<class flutter::EncodableValue> > >)" (?GetPdfPageImage@pdfviewer@@YAXAEBV?$MethodCall@VEncodableValue@flutter@@@flutter@@V?$unique_ptr@V?$MethodResult@VEncodableValue@flutter@@@flutter@@U?$default_delete@V?$MethodResult@VEncodableValue@flutter@@@flutter@@@std@@@std@@@Z) [C:\Users\<USER>\source\repos\<REPO>\src\<APP>\build\windows\arm64\plugins\syncfusion_pdfviewer_windows\syncfusion_pdfviewer_windows_plugin.vcxproj]
syncfusion_pdfviewer_windows_plugin.obj : error LNK2019: unresolved external symbol FPDFBitmap_FillRect referenced in function "void __cdecl pdfviewer::GetPdfPageImage(class flutter::MethodCall<class flutter::EncodableValue> const &,class std::unique_ptr<class flutter::MethodResult<class flutter::EncodableValue>,struct std::default_delete<class flutter::MethodResult<class flutter::EncodableValue> > >)" (?GetPdfPageImage@pdfviewer@@YAXAEBV?$MethodCall@VEncodableValue@flutter@@@flutter@@V?$unique_ptr@V?$MethodResult@VEncodableValue@flutter@@@flutter@@U?$default_delete@V?$MethodResult@VEncodableValue@flutter@@@flutter@@@std@@@std@@@Z) [C:\Users\<USER>\source\repos\<REPO>\src\<APP>\build\windows\arm64\plugins\syncfusion_pdfviewer_windows\syncfusion_pdfviewer_windows_plugin.vcxproj]
syncfusion_pdfviewer_windows_plugin.obj : error LNK2019: unresolved external symbol FPDFBitmap_GetBuffer referenced in function "void __cdecl pdfviewer::GetPdfPageImage(class flutter::MethodCall<class flutter::EncodableValue> const &,class std::unique_ptr<class flutter::MethodResult<class flutter::EncodableValue>,struct std::default_delete<class flutter::MethodResult<class flutter::EncodableValue> > >)" (?GetPdfPageImage@pdfviewer@@YAXAEBV?$MethodCall@VEncodableValue@flutter@@@flutter@@V?$unique_ptr@V?$MethodResult@VEncodableValue@flutter@@@flutter@@U?$default_delete@V?$MethodResult@VEncodableValue@flutter@@@flutter@@@std@@@std@@@Z) [C:\Users\<USER>\source\repos\<REPO>\src\<APP>\build\windows\arm64\plugins\syncfusion_pdfviewer_windows\syncfusion_pdfviewer_windows_plugin.vcxproj]
syncfusion_pdfviewer_windows_plugin.obj : error LNK2019: unresolved external symbol FPDFBitmap_Destroy referenced in function "void __cdecl pdfviewer::GetPdfPageImage(class flutter::MethodCall<class flutter::EncodableValue> const &,class std::unique_ptr<class flutter::MethodResult<class flutter::EncodableValue>,struct std::default_delete<class flutter::MethodResult<class flutter::EncodableValue> > >)" (?GetPdfPageImage@pdfviewer@@YAXAEBV?$MethodCall@VEncodableValue@flutter@@@flutter@@V?$unique_ptr@V?$MethodResult@VEncodableValue@flutter@@@flutter@@U?$default_delete@V?$MethodResult@VEncodableValue@flutter@@@flutter@@@std@@@std@@@Z) [C:\Users\<USER>\source\repos\<REPO>\src\<APP>\build\windows\arm64\plugins\syncfusion_pdfviewer_windows\syncfusion_pdfviewer_windows_plugin.vcxproj]
C:\Users\<USER>\source\repos\<REPO>\src\<APP>\windows\flutter\ephemeral\.plugin_symlinks\syncfusion_pdfviewer_windows\windows\include\pdfium\x64\lib\pdfium.dll.lib : warning LNK4272: library machine type 'x64' conflicts with target machine type 'ARM64' [C:\Users\<USER>\source\repos\<REPO>\src\<APP>\build\windows\arm64\plugins\syncfusion_pdfviewer_windows\syncfusion_pdfviewer_windows_plugin.vcxproj]
C:\Users\<USER>\source\repos\<REPO>\src\<APP>\build\windows\arm64\plugins\syncfusion_pdfviewer_windows\Debug\syncfusion_pdfviewer_windows_plugin.dll : fatal error LNK1120: 15 unresolved externals [C:\Users\<USER>\source\repos\<REPO>\src\<APP>\build\windows\arm64\plugins\syncfusion_pdfviewer_windows\syncfusion_pdfviewer_windows_plugin.vcxproj]
Error: Build process failed.
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.44.0, on Microsoft Windows [Version 10.0.26200.8457], locale en-NZ)
[√] Windows Version (Windows 11 or higher, 25H2, 2009)
[√] Android toolchain - develop for Android devices (Android SDK version 36.1.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Professional 2022 17.14.18 (October 2025))
[√] Connected device (3 available)
[√] Network resources

• No issues found!
```

</details>

**Comment by suryaKommana2662** [comment]
Thanks for the detailed report and reproduction steps.

The logs show an architecture mismatch during native plugin linking:
> library machine type 'x64' conflicts with target machine type 'ARM64'

Since this works on Flutter 3.41.9 but fails on 3.44.0, we need to determine whether this is:
> a regression in Flutter’s Windows ARM64 tooling, or
> caused by plugins that currently include only x64 native binaries.

Could you please also confirm:
> Whether a newly created Flutter app without any plugins builds successfully on ARM64.
> Whether the issue still occurs with a minimal sample app using only one affected plugin.

**Comment by stuartmorgan-g** [comment]
Those plugins don't appear to support Windows arm64; https://github.com/MixinNetwork/flutter-plugins/tree/main/packages/desktop_webview_window/windows for instance clearly includes x64 binaries but no arm64 binaries.

**Comment by Adam-Langley** [comment]
Hi @suryaKommana2662 

In response to your questions

1. Whether a newly created Flutter app without any plugins builds successfully on ARM64. **YES**
2. Whether the issue still occurs with a minimal sample app using only one affected plugin. **YES**

debug output from minimal example

> flutter create testapp
> flutter pub add desktop_webview_window
> flutter run

```

Launching lib\main.dart on Windows in debug mode...
web_view.obj : error LNK2019: unresolved external symbol CreateCoreWebView2EnvironmentWithOptions referenced in function "public: __cdecl webview_window::WebView::WebView(class std::shared_ptr<class flutter::MethodChannel<class flutter::EncodableValue> >,__int64,class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> >,class std::function<void __cdecl(long)>)" (??0WebView@webview_window@@QEAA@V?$shared_ptr@V?$MethodChannel@VEncodableValue@flutter@@@flutter@@@std@@_JV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@3@V?$function@$$A6AXJ@Z@3@@Z) [C:\Users\adam\Downloads\test\test\build\windows\arm64\plugins\desktop_webview_window\desktop_webview_window_plugin.vcxproj]
web_view_window_plugin.obj : error LNK2019: unresolved external symbol GetAvailableCoreWebView2BrowserVersionString referenced in function "bool __cdecl `anonymous namespace'::IsWebViewRuntimeAvailable(void)" (?IsWebViewRuntimeAvailable@?A0x3b47ead8@@YA_NXZ) [C:\Users\adam\Downloads\test\test\build\windows\arm64\plugins\desktop_webview_window\desktop_webview_window_plugin.vcxproj]
C:\Users\adam\Downloads\test\test\windows\flutter\ephemeral\.plugin_symlinks\desktop_webview_window\windows\libs\x64\Webview2Loader.dll.lib : warning LNK4272: library machine type 'x64' conflicts with target machine type 'ARM64' [C:\Users\adam\Downloads\test\test\build\windows\arm64\plugins\desktop_webview_window\desktop_webview_window_plugin.vcxproj]
C:\Users\adam\Downloads\test\test\build\windows\arm64\plugins\desktop_webview_window\Debug\desktop_webview_window_plugin.dll : fatal error LNK1120: 2 unresolved externals [C:\Users\adam\Downloads\test\test\build\windows\arm64\plugins\desktop_webview_window\desktop_webview_window_plugin.vcxproj]
```

@stuartmorgan-g 
Yes this probably is a dup - however to be clear - the exact same application, build on another platform, and transferred to the win-arm machine will run - it simply will not compile on the win-arm machine.
This is a sohwstopper because I have this application in production, customers are using it on Windows/arm machines, and I need to debug to repro issues on customer configurations.
I get that those plugins are not arm specific, however they do run just fine on win-arm, I can only assume emulation is occuring.
This issue only occurs after upgrade to latest version of flutter. Thanks.

**Comment by stuartmorgan-g** [comment]
> the exact same application, build on another platform, and transferred to the win-arm machine will run

That's expected. Building an x64 app with x64-only libraries will give you an x64 build, and Windows on arm64 will run x64 apps.

> it simply will not compile on the win-arm machine

Because it's trying to do an arm64 build. You cannot build an arm64 application by linking to x64 libraries.

> I get that those plugins are not arm specific

It's not a question of being "arm specific". They use precompiled libraries that are x64 only.

Plugins don't have to be arm-specific to work in an arm build, but they can't have been set up to *only* work in an x64 build like those have.
