### ISSUE TITLE
RangeError: Value not in range

### ISSUE THREAD

**Issue by yantao608** [flutter/flutter#49989]
## Steps to Reproduce

I got this crash on crash collect server and I can't reproduce this on my iPhone.
through the server logs we can see，when this crash occur , the next crash log is 

```bash
NoSuchMethodError: The method 'findRenderObject' was called on null.\
Receiver: null\
Tried calling: findRenderObject()\
#0 EditableTextState._onCursorColorTick (package:flutter/src/widgets/editable_text.dart:1347)\
#1_AnimationController&Animation&AnimationEagerListenerMixin&AnimationLocalListenersMixin.notifyListeners (package:flutter/src/animation/listener_helpers.dart:126)\
#2 AnimationController.set:value (package:flutter/src/animation/animation_controller.dart:351)\
#3 EditableTextState._startCursorTimer (package:flutter/src/widgets/editable_text.dart:1274)\
```

```bash
RangeError: Value not in range: 8\
#0 _StringBase.substring (dart:core-patch/string_patch.dart:386)\
#1 TextRange.textInside (package:flutter/src/services/text_editing.dart:72)\
#2 EditableTextState.buildTextSpan (package:flutter/src/widgets/editable_text.dart:1475)\
#3 EditableTextState.build.<anonymous closure> (package:flutter/src/widgets/editable_text.dart:1422)\
#4 ScrollableState.build (package:flutter/src/widgets/scrollable.dart:584)\
#5 StatefulElement.build (package:flutter/src/widgets/framework.dart:3825)\
#6 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3739)\
#7 Element.rebuild (package:flutter/src/widgets/framework.dart:3565)\
#8 StatefulElement.update (package:flutter/src/widgets/framework.dart:3894)\
#9 Element.updateChild (package:flutter/src/widgets/framework.dart:2753)\
#10 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750)\
#11 Element.rebuild (package:flutter/src/widgets/framework.dart:3565)\
#12 BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2278)\
#13 _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:700)\
#14 _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286)\
#15 _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1012)\
#16 _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:952)\
#17 _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:864)\
#18 FrameMetrics._handleDrawFrame (package:mt_flutter_route/monitor/fps/frame_metrics.dart:42)\
#19 FrameMetrics._handleDrawFrame (package:flutter_metrics_plugin/metrics/frame_metrics.dart:42)\
#20 _rootRun (dart:async/zone.dart:1124)\
#21 _CustomZone.run (dart:async/zone.dart:1021)\
#22 _CustomZone.runGuarded (dart:async/zone.dart:923)\
#23 _invoke (dart:ui/hooks.dart:219)\
#24 _drawFrame (dart:ui/hooks.dart:178)\
```

```console
[✓] Flutter (Channel v1.5.4-hotfixes, v1.5.4-hotfix.2-pre.1, on
    Mac OS X 10.14.6 18G87, locale zh-Hans-CN)
    • Flutter version 1.5.4-hotfix.2-pre.1 at
      /Users/yantao/flutter
    • Framework revision 953bbe2ccd (9 months ago), 2019-05-02
      09:59:16 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)
```

**Comment by iapicca** [comment]
Hi @yantao608 
your full `flutter run --verbose` 
and a reproducible minimal code sample.

I see you are using an old version of flutter
if you decide to upgrade you may want to run
`flutter channel stable`
`flutter upgrade --force`
`flutter pub cache repair`
`cd <YOUR APP FOLDER>`
`flutter clean`

thank you

**Comment by yantao608** [comment]
> Hi @yantao608
> your full `flutter run --verbose`
> and a reproducible minimal code sample.
> 
> I see you are using an old version of flutter
> if you decide to upgrade you may want to run
> `flutter channel stable`
> `flutter upgrade --force`
> `flutter pub cache repair`
> `cd <YOUR APP FOLDER>`
> `flutter clean`
> 
> thank you

thank you for your reply, the main code is 
```
  Widget _buildCenterContainer() {
    this._controller.text = provider.currentReason.reason;
      return Container(
        margin: EdgeInsets.only(top: 10),
        child: TextField(
          controller: _controller,
          maxLines: null,
          keyboardType: TextInputType.text,
          autofocus: true,
          maxLength: 150,
          onEditingComplete: () {
            FocusScope.of(context).requestFocus(FocusNode());
          },
          decoration: InputDecoration(
              border: InputBorder.none,
              hintText: 'xxxxxxxx',
              hintStyle: TextStyle(color: ColorUtil.scGrey25Color),
              contentPadding: EdgeInsets.fromLTRB(20.0, 10.0, 20.0, 5.0)
          ),
        )
      );
  }
```
but this crash occured accidentally，I can't reproduce it。

We will update flutter version to 1.9.1 next month。

**Comment by iapicca** [comment]
Hi @yantao608 
please note that the current stable version is `1.12.13`
let me know if you are experiencing the issue following [this](https://github.com/flutter/flutter/issues/49989#issuecomment-581286828)
Thank you

**Comment by gitfornncn** [comment]
Same problem. flutter version is 1.12.13 + hotfix.7.

I used the official component of flui  https://www.flui.xin/widgets/label.html#flmarqueelabel .
Frequent refresh hotreload. cmd+s.i got the erroor.

NoSuchMethodError: The method 'findRenderObject' was called on null.

**Comment by iapicca** [comment]
Hi @yantao608 
if you are experiencing this issue with the 3rd party plugin [flui](https://github.com/Rannie/flui/issues)
you may want to open an issue in the dedicated [github](https://github.com/Rannie/flui/issues) 

otherwise could you please provide a reproducible minimal code sample?
thank you

**Comment by yantao608** [comment]
> Hi @yantao608
> please note that the current stable version is `1.12.13`
> let me know if you are experiencing the issue following [this](https://github.com/flutter/flutter/issues/49989#issuecomment-581286828)
> Thank you

YES，I know that the current stable Version is `1.12.13`. 
But my team has a strategy,  don't follow stable version so quickly.
Now I close this issue , 
after we update the flutter version to 1.12.13 . if still has this crash, can open it again.
Thank you

**Comment by iapicca** [comment]
Hi @yantao608 
updating your framework to the latest stable 
is **not** considered a must,
on the other hand is hard to keep track if a problem
has been fixed in subsequent stable releases,
in your case 3 of them (1.7..., 1.9..., 1.12...);
`update => cache repair => flutter clean`
it's just a way to check that,

I don't mean in anyway to push you or your team 
to change your legitimate strategy.

Moreover, in your specific case
the issue might not be w/ Flutter at all,
as I pointed out [here](https://github.com/flutter/flutter/issues/49989#issuecomment-583369395).

If you could provide a minimal code sample I'd be happy to help.
Thank you

**Comment by TahaTesser** [comment]
Hi @yantao608 

Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Comment by PacteraWangCong** [comment]
Hi @TahaTesser  @ianloic   same problem  https://github.com/flutter/flutter/issues/58565

**Comment by LongCatIsLooong** [comment]
I suspect this is a direct cause of https://github.com/flutter/flutter/issues/33730. Reopening for investigation.

**Comment by LongCatIsLooong** [comment]
FYI, I added a few more asserts to catch the `RangeError` early, but there's no direct evidence that `RangeError` you are seeing is caused by the framework. The new asserts should be able to provide much more helpful stack traces if this happens again.

**Comment by sudha-anecure** [comment]
Hi - we got this error from a user using our app built on 1.22.0 version of flutter. Here is the stack trace reported on crahslytics from the screen. This is a screen where the user is shown a single text field to enter his username. I assume he tried to select a portion of the text using touch and faced this error.

Error:
RangeError: Value not in range: 19
Stack trace:
#0      _StringBase.substring (dart:core-patch/string_patch.dart:393)
#1      _selectionAwareTextManipulation (package:flutter/src/services/text_formatter.dart:416)
#2      FilteringTextInputFormatter.formatEditUpdate (package:flutter/src/services/text_formatter.dart:220)
#3      EditableTextState._formatAndSetValue (package:flutter/src/widgets/editable_text.dart:2142)
#4      EditableTextState.textEditingValue= (package:flutter/src/widgets/editable_text.dart:2310)
#5      TextSelectionOverlay._handleSelectionHandleChanged (package:flutter/src/widgets/text_selection.dart:601)
#6      TextSelectionOverlay._buildHandle.<anonymous closure> (package:flutter/src/widgets/text_selection.dart:532)
#7      _TextSelectionHandleOverlayState._handleDragUpdate (package:flutter/src/widgets/text_selection.dart:697)
#8      DragGestureRecognizer._checkUpdate.<anonymous closure> (package:flutter/src/gestures/monodrag.dart:431)
#9      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183)
#10     DragGestureRecognizer._checkUpdate (package:flutter/src/gestures/monodrag.dart:431)
#11     DragGestureRecognizer.handleEvent (package:flutter/src/gestures/monodrag.dart:286)
#12     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:77)
#13     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:122)
#14     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377)
#15     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120)
#16     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106)
#17     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:358)
#18     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:338)
#19     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:267)
#20     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:295)
#21     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:240)
#22     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:213)
#23     _rootRunUnary (dart:async/zone.dart:1206)
#24     _CustomZone.runUnary (dart:async/zone.dart:1100)
#25     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005)
#26     _invoke1 (dart:ui/hooks.dart:265)
#27     _dispatchPointerDataPacket (dart:ui/hooks.dart:174)
Device parameters:
id: QP1A.190711.020
androidId: c4b9bef95b366509
board: dandelion
bootloader: unknown
brand: Redmi
device: dandelion
display: QP1A.190711.020
fingerprint: Redmi/dandelion_global/dandelion:10/QP1A.190711.020/V12.0.6.0.QCDMIXM:user/release-keys
hardware: mt6762
host: c3-miui-ota-bd145.bj
isPhysicalDevice: true
manufacturer: Xiaomi
model: M2006C3LG
product: dandelion_global
tags: release-keys
type: user
versionBaseOs: 
versionCodename: REL
versionIncremental: V12.0.6.0.QCDMIXM
versionPreviewSdk: 0
versionRelease: 10
versionSdk: 29
versionSecurityPatch: 2020-09-01
Application parameters:
version: 2.5.1
environment: ApplicationProfile.release
Custom parameters:


The above is the only information I have since this is on a production device of an end user.

Can you please reopen this issue and see if you can fix?

**Comment by LongCatIsLooong** [comment]
@sudha-anecure this seems to be a different issue. Could you open a new issue for it?

**Comment by sudha-anecure** [comment]
Thank you for the response. I have opened #70257
