### ISSUE TITLE
[google_maps_flutter] google_maps_flutter_ios native-test fails on iOS 26.4/26.5 simulators via CLI, passes in Xcode

### ISSUE THREAD

**Issue by preethi0228-git** [flutter/flutter#185205]
### Steps to reproduce

1. Clone flutter/packages
2. Navigate to google_maps_flutter_ios example
3. Run:
   dart run script/tool/bin/flutter_plugin_tools.dart native-test --ios --packages=google_maps_flutter_ios

- Reproduced on:
  - iOS 26.4 simulator 
  - iOS 26.5 simulator 

- Works correctly when run via Xcode on the same simulators / real device

### Expected results

Build and tests should pass as they do in Xcode.

### Actual results

Build is failing with which the tests are not executed.

**Note** : Issue repro on both Master and Stable channels too

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

[google_maps_ios_test.log](https://github.com/user-attachments/files/26823427/google_maps_ios_test.log)

[google_maps_ios_test.ios26.4.log](https://github.com/user-attachments/files/26823439/google_maps_ios_test.ios26.4.log)

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

Flutter (Channel master, 3.44.0-1.0.pre-133, on macOS 26.5 25F5053d darwin-arm64, locale en-US) [1,625ms]
    • Flutter version 3.44.0-1.0.pre-133 on channel master at /Users/preethikandukuri/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 02da4c69f0 (4 hours ago), 2026-04-17 16:26:17 +0900
    • Engine revision 02da4c69f0
    • Dart version 3.13.0 (build 3.13.0-27.0.dev)
    • DevTools version 2.57.0
    • Feature flags: enable-web, enable-linux-desktop, enable-macos-desktop, enable-windows-desktop, enable-android,
      enable-ios, cli-animations, enable-native-assets, enable-swift-package-manager, omit-legacy-version-file,
      enable-lldb-debugging, enable-uiscene-migration, enable-riscv64

[✓] Android toolchain - develop for Android devices (Android SDK version 37.0.0) [1,756ms]
    • Android SDK at /Users/preethikandukuri/Library/Android/sdk
    • Emulator version 36.5.10.0 (build_id 15081367) (CL:N/A)
    • Platform android-37.0, build-tools 37.0.0
    • ANDROID_HOME = /Users/preethikandukuri/Library/Android/sdk
    • Java binary at: /Applications/Android Studio panda4 rc1.app/Contents/jbr/Contents/Home/bin/java
      This JDK is specified in your Flutter configuration.
      To change the current JDK, run: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.10+-117844308-b1163.108)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 26.5) [903ms]
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Build 17F5022i
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [4ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Connected device (2 available) [6.0s]
    • macOS (desktop) • macos  • darwin-arm64   • macOS 26.5 25F5053d darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 147.0.7727.101

[✓] Network resources [484ms]
    • All expected network resources are available.

**Comment by mbcorona** [comment]
Hi @preethi0228-git 
Thanks for providing the logs.

Routing to team-ecosystem to evaluate the plugin's dependencies and compiler flags for compatibility with upcoming Xcode releases.

**Comment by jmagman** [comment]
```
GMUHeatmapTileLayer.m:345:78: error: bitwise operation between different enumeration types ('enum CGBitmapInfo' and 'enum CGImageAlphaInfo') [-Werror,-Wenum-enum-conversion]
  345 |                                       colorSpaceRef, kCGBitmapByteOrder32Big | kCGImageAlphaLast,
      |                                                      ~~~~~~~~~~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~
1 error generated.
```

Essentially a duplicate of https://github.com/flutter/flutter/issues/184470, but I wonder why it wasn't excluded from native-test and still failed after https://github.com/flutter/packages/pull/11480. Maybe passing in `--packages=google_maps_flutter_ios` overrides the exclusion.

**Comment by jmagman** [comment]
Ah, I see, CI knows to pass in `--xcode-warnings-exceptions=script/configs/xcode_warnings_exceptions.yaml`

https://github.com/flutter/packages/blob/4a2091d89f77d4c202d6c6a9b541a42c954fbfff/.ci/targets/ios_platform_tests.yaml#L29
@preethi0228-git can you update your test scripts to match the exclusions in that ios_platform_tests.yaml files? For example:
`drive-examples --ios --exclude=script/configs/exclude_integration_ios.yaml`
https://github.com/flutter/packages/blob/4a2091d89f77d4c202d6c6a9b541a42c954fbfff/.ci/targets/ios_platform_tests.yaml#L39
