### ISSUE TITLE
ImagePicker doesn't work with flutter 3.29

### ISSUE THREAD

**Issue by derekpitts28** [flutter/flutter#166029]
### Steps to reproduce

Add the library to any project running flutter 3.29+ you will get the following error:

```
/Users/derekpitts/.pub-cache/hosted/pub.dev/image_picker_android-0.8.12+1/android/src/main/java/io/flutter/plugins/imagepicker/ImagePickerPlugin.java:188: error: cannot find symbol
      @NonNull io.flutter.plugin.common.PluginRegistry.Registrar registrar) {
                                                      ^
  symbol:   class Registrar
  location: interface PluginRegistry
```

See this related article https://benamorn.medium.com/today-i-learned-after-upgrading-to-flutter-3-29-0-7c7ab1a97975

### Expected results

It works.

### Actual results

Build error.

### Code sample

No code sample needed.

### Screenshots or Video

NA

### Logs

<details open><summary>Logs</summary>

```console
/Users/derekpitts/.pub-cache/hosted/pub.dev/image_picker_android-0.8.12+1/android/src/main/java/io/flutter/plugins/imagepicker/ImagePickerPlugin.java:188: error: cannot find symbol
      @NonNull io.flutter.plugin.common.PluginRegistry.Registrar registrar) {
                                                      ^
  symbol:   class Registrar
  location: interface PluginRegistry
/Users/derekpitts/.pub-cache/hosted/pub.dev/image_picker_android-0.8.12+1/android/src/main/java/io/flutter/plugins/imagepicker/ImagePickerPlugin.java:257: error: cannot find symbol
      final PluginRegistry.Registrar registrar,
                          ^
  symbol:   class Registrar
  location: interface PluginRegistry
/Users/derekpitts/.pub-cache/hosted/pub.dev/image_picker_android-0.8.12+1/android/src/main/java/io/flutter/plugins/imagepicker/ImagePickerPlugin.java:120: error: cannot find symbol
        final PluginRegistry.Registrar registrar,
                            ^
  symbol:   class Registrar
  location: interface PluginRegistry
3 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':image_picker_android:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --info option to get more log output.
> Run with --scan to get full insights.

BUILD FAILED in 10s
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.29.2, on macOS 14.7.4 23H420 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.97.2)
[✓] Connected device (6 available)
[✓] Network resources

• No issues found!

```

</details>

**Comment by darshankawar** [comment]
> image_picker_android-0.8.12+1/

This plugin version is not latest. The current version is 0.8.12+22, so you need to run `flutter pub upgrade` which should resolve the issue.
Closing for now. If you disagree or above command doesn't resolve it, write in comments and I'll reopen it.

**Comment by derekpitts28** [comment]
@darshankawar  image_picker_android-0.8.12+1 is part of ImagePIcker 1.1.2. I don't believe doing a flutter pub upgrade will help.

**Comment by darshankawar** [comment]
@derekpitts28 
Can you provide pubspec.lock ?

**Comment by wdtheprovider** [comment]
I'm getting the same issue

**Comment by wagner1343** [comment]
This is still an issue, it's possible to work around this by adding an override to your pubspec.yaml file like so:
```yaml
dependency_overrides:
  image_picker_android: 0.8.12+22
```
