### ISSUE TITLE
Build Error when updated Xcode to 14.2

### ISSUE THREAD

**Issue by ohm1998** [flutter/flutter#82030]
I always face build issues whenever i upgrade my Xcode version. Following error has occurred currently :

`/Users/apple/Desktop/dt2/ios/Pods/RealmSwift/RealmSwift/Combine.swift:38:40: error: 'Identifiable' is only available in application extensions for iOS 13 or newer
    public protocol ObjectKeyIdentifiable: Identifiable, Object {`

Is it related to flutter or some package?
