### ISSUE TITLE
`SHARD=tool_tests ./bin/cache/dart-sdk/bin/dart ./dev/bots/test.dart ` fails when run locally

### ISSUE THREAD

**Issue by rmacnak-google** [flutter/flutter#23109]
```
09:30 +755 ~1 -1: test/integration/flutter_attach_test.dart: attached process can hot reload [E]                                                                                                       
  Received app.stop event while waiting for app.started event.
  
  
  dart:async                                _Completer.completeError
  test/integration/test_driver.dart 333:18  FlutterTestDriver._waitFor.<fn>
  ===== asynchronous gap ===========================
  dart:async                                _asyncThenWrapperHelper
  test/integration/test_driver.dart         FlutterTestDriver._waitFor.<fn>
  ===== asynchronous gap ===========================
  dart:async                                _StreamImpl.listen
  test/integration/test_driver.dart 313:26  FlutterTestDriver._waitFor
  ===== asynchronous gap ===========================
  dart:async                                _asyncThenWrapperHelper
  test/integration/test_driver.dart         FlutterTestDriver._setupProcess
  test/integration/test_driver.dart 60:11   FlutterTestDriver.run
  
  Received app.stop event while waiting for app.debugPort event.
  
  
  dart:async                                _Completer.completeError
  test/integration/test_driver.dart 333:18  FlutterTestDriver._waitFor.<fn>
  ===== asynchronous gap ===========================
  dart:async                                _asyncThenWrapperHelper
  test/integration/test_driver.dart         FlutterTestDriver._waitFor.<fn>
  ===== asynchronous gap ===========================
  dart:async                                _StreamImpl.listen
  test/integration/test_driver.dart 313:26  FlutterTestDriver._waitFor
  ===== asynchronous gap ===========================
  dart:async                                _asyncThenWrapperHelper
  test/integration/test_driver.dart         FlutterTestDriver._setupProcess
  test/integration/test_driver.dart 60:11   FlutterTestDriver.run
  
  NoSuchMethodError: The getter 'exitCode' was called on null.
  Receiver: null
  Tried calling: exitCode
  dart:core                                 Object.noSuchMethod
  test/integration/test_driver.dart 189:18  FlutterTestDriver.detach
  ===== asynchronous gap ===========================
  dart:async                                _AsyncAwaitCompleter.completeError
  test/integration/test_driver.dart         FlutterTestDriver.detach
  ```
And 11 other similar failures.

**Comment by DanTup** [comment]
Looks like this roll that saw these failures was reverted by @dnfield in #23170. I did run with this version of the engine locally anyway but I had different failures to those in the related issue, mine are all timeouts at 40 seconds waiting for the isolate to pause after a hot reload:

```

[{"id":1,"method":"app.restart","params":{"appId":"79529336-1f6a-413d-a3db-c16640c5f345","fullRestart":false,"pause":false}}]
[{"event":"app.progress","params":{"appId":"79529336-1f6a-413d-a3db-c16640c5f345","id":"1","progressId":"hot.reload","message":"Initializing hot reload..."}}]
[{"event":"app.progress","params":{"appId":"79529336-1f6a-413d-a3db-c16640c5f345","id":"2","progressId":null,"message":"Syncing files to device Flutter test device..."}}]

Compiler message:
lib/main.dart:1: Warning: Interpreting this as package URI, 'package:test/main.dart'.
[{"event":"app.progress","params":{"appId":"79529336-1f6a-413d-a3db-c16640c5f345","id":"2","progressId":null,"finished":true}}]
topLevelFunction
[{"event":"app.progress","params":{"appId":"79529336-1f6a-413d-a3db-c16640c5f345","id":"1","progressId":"hot.reload","finished":true}}]
Reloaded 0 of 415 libraries in 497ms.
[{"id":1,"result":{"code":0,"message":"Reloaded 0 of 415 libraries"}}]

{"jsonrpc":"2.0","method":"getIsolate","id":13,"params":{"isolateId":"isolates/1001534799"}}
{"jsonrpc":"2.0", "result":{"type":"Isolate","fixedId":true,"id":"isolates\/1001534799","name":"main.dart:main()","number":"1001534799","_originNumber":"1001534799","startTime":1539760172239,"_heaps":{"new":{"type":"HeapSpace","name":"new","vmName":"Scavenger","collections":1,"avgCollectionPeriodMillis":4630.190000,"used":454640,"capacity":2097152,"external":7440,"time":0.000399},"old":{"type":"HeapSpace","name":"old","vmName":"PageSpace","collections":3,"used":26364480,"capacity":26673152,"external":0,"time":0.031044,"avgCollectionPeriodMillis":1543.399000}},"runnable":true,"livePorts":0,"pauseOnExit":false,"_isReloading":false,"pauseEvent":{"type":"Event","kind":"Resume",/*...*/,"id":13}
Waiting for isolate to pause
{"jsonrpc":"2.0","method":"streamListen","id":14,"params":{"streamId":"Debug"}}
{"jsonrpc":"2.0","method":"getIsolate","id":15,"params":{"isolateId":"isolates/1001534799"}}
{"jsonrpc":"2.0","id":14,"result":{"type":"Success"}}
{"jsonrpc":"2.0", "result":{"type":"Isolate","fixedId":true,"id":"isolates\/1001534799","name":"main.dart:main()","number":"1001534799","_originNumber":"1001534799","startTime":1539760172239,"_heaps":{"new":{"type":"HeapSpace","name":"new","vmName":"Scavenger","collections":1,"avgCollectionPeriodMillis":4641.687000,"used":464192,"capacity":2097152,"external":7536,"time":0.000399},"old":{"type":"HeapSpace","name":"old","vmName":"PageSpace","collections":3,"used":26364480,"capacity":26673152,"external":0,"time":0.031044,"avgCollectionPeriodMillis":1547.231667}},"runnable":true,"livePorts":0,"pauseOnExit":false,"_isReloading":false,"pauseEvent":{"type":"Event","kind":"Resume",/*...*/,"id":15}
```

The isolate PauseEvent is set to `Resume` after the reload and a pause event never comes through. On the surface, this seems like a valid failure.

@rmacnak-google LMK if you think there is something wrong with the tests and plan to re-land this and I can do some more digging. Otherwise, if there was an issue with that roll, should this issue be closed?

**Comment by DanTup** [comment]
I landed a PR that should improve the logging when this happens. If you can still repro locally, could you paste the new output?

**Comment by timsneath** [comment]
@rmacnak-google are you OK if we close this? Looks like the issue is stale at this time?

**Comment by pedromassangocode** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
