### PR TITLE
Consolidate ascii spinner stop in devtools activation

### LINKED ISSUE #75677: NoSuchMethodError: The method 'cancel' was called on null at AnsiSpinner.finish
beta crasher:
```
NoSuchMethodError: The method 'cancel' was called on null.
Receiver: null
Tried calling: cancel()
  | at Object.noSuchMethod | (object_patch.dart:54)
  | at AnsiSpinner.finish | (logger.dart:952)
  | at Status.stop | (logger.dart:775)
  | at AnsiStatus.stop | (logger.dart:1030)
  | at DevtoolsServerLauncher._activateDevTools | (devtools_launcher.dart:167)
  | at <asynchronous gap> | (async)
  | at DevtoolsServerLauncher.launch | (devtools_launcher.dart:71)
  | at <asynchronous gap> | (async)
  | at DevtoolsServerLauncher.serve | (devtools_launcher.dart:176)
  | at <asynchronous gap> | (async)
...
```
https://crash.corp.google.com/browse?q=product_name%3D%27Flutter_Tools%27+AND+product.Version%3D%27beta%2F1.26.0-17.3.pre%27+AND+stable_signature%3D%27NoSuchMethodError+at+Object.noSuchMethod+at+dart%3Acore-patch%2Fobject_patch.dart-44ba5769%27

### PR DESCRIPTION
**Pull request by jmagman**
`status.stop()` in `catch` was throwing because the timer was already stopped and nulled out.  Consolidate the status `stop` calls into one `finally` block.

Introduced in #73366
Fixes https://github.com/flutter/flutter/issues/75677

### CODE REVIEW

**Review by jonahwilliams — COMMENTED** [review]
We really need to make the BufferLogger spinners hit this same assert

**Review by jonahwilliams — APPROVED** [review]
LGTM

The devtools launcher is somewhat standalone, could we write a test with this using a fake logger?

**Comment by jmagman** [comment]
> We really need to make the BufferLogger spinners hit this same assert

That's a good idea.

> The devtools launcher is somewhat standalone, could we write a test with this using a fake logger?

There are already tests that exercise the exception case https://github.com/flutter/flutter/blob/f2bb39d6b622b5517eb516e1e8b1eda99eb363df/packages/flutter_tools/test/general.shard/devtools_launcher_test.dart#L206

The `status.stop()` in the catch throws the `The method 'cancel' was called on null` seen in the crashes. 
https://github.com/flutter/flutter/blob/021311ed8a2c182d3237330e5d8ae4c4937b3d76/packages/flutter_tools/lib/src/devtools_launcher.dart#L155-L168

So the original exception caught could be:
1. `pub global activate` succeeds, `status.stop()` is called, then `_persistentToolState.lastDevToolsActivationTime = DateTime.now()` throws? I don't see how though, the persisting config seems fine.
https://github.com/flutter/flutter/blob/73506f36f7d8ecc9b18d3b98f1e09ed7f97edce1/packages/flutter_tools/lib/src/persistent_tool_state.dart#L148-L150

2.`pub global activate` fails, `status.cancel()` is called, and `_logger.printError('Error running pub global activate devtools:\n${_devToolsActivateProcess.stderr}')` throws.  I don't see how that could be either.

Let me think about how to test this by simulating either one or two.
