### ISSUE TITLE
Flutter tools support for packaging/linking to native libraries

### ISSUE THREAD

**Issue by sjindel-google** [flutter/flutter#33227]
We want to enable Flutter apps and plugins to bind to native (C/C++) libraries directly via the Dart FFI. This requires support from Flutter tools. There are four categories of use cases we'd like to enable:

0. A Flutter plugin wants to interact with a native library which should be available on the target device (e.g. Android Audio).

1. A Flutter app wants to ship business logic written in C/C++ (e.g. some add-to-app scenarios).

2. A Flutter plugin wants to ship a prebuilt native library (.so on Android or .framework on iOS) within its package (e.g. closed-source or vendored plugins like Realm).

3. A Flutter plugin wants to ship source code within its package which should be compiled by the client developer.

We should also keep in mind support for desktop, server and non-Flutter use cases (which also broadly fall into the above categories).

**Comment by sjindel-google** [comment]
I've identified how all four use cases can be solved within the existing Gradle/Cocoa Pods systems for Flutter on Android, iOS and MacOS.

Both systems have first-class support for "native" (C/C++) dependencies, both in source and binary forms. There is nothing special which needs to be done to make these usable from the FFI, but I've written an overview of the solutions as a [Wiki page](https://github.com/flutter/flutter/wiki/Binding-to-native-code-via-FFI)

We don't have a story for packaging native code inside Dart packages independently of Flutter yet.

**Comment by hanabi1224** [comment]
@sjindel-google Thanks for the wiki, I'm able to invoke native libraries via dart:ffi on both android and IOS. In IOS case, I was using a statically linked library built from rust-lang, and on dart side, I was able to get the handle with DynamicLibrary.process(), the only problem I have is, DynamicLibrary.process is on flutter dev channel only which I'm not fully confident to take as a hard dependency,  is there roadmap on when DynamicLibrary.process will be shipped to stable / beta channel? Thanks in advance!

**Comment by sjindel-google** [comment]
@hanabi1224 `DynamicLibrary.process` is here to stay and will be included whenever Flutter ships their next release.

I believe it's already available on their dev channel.

**Comment by zean00** [comment]
@hanabi1224 Do you mind share the detail of your configuration? I have similar case, I have library built from rust, and I'm successfully test it on dart VM. But still have no clue how to integrate it with flutter on Android and iOS as there no much detailed documentation available at the moment. If you write you step on your blog or anywhere, or if you follow someone's step, please share it. Thanks

**Comment by hanabi1224** [comment]
@zean00 Basically, you just build .so and .a libs for android and ios respectively following https://github.com/kennytm/rust-ios-android . Note that you don't really need to write JNI wrappers for android when you only load it from dart, and on IOS, write .h and .m files invoke any dummy FFI functions otherwise xcode will be smart enough to drop the .a file.
On dart side, use ffi.open('libxxx.so') for android and use ffi.process() to get the handle

**Comment by zean00** [comment]
Thanks @hanabi1224 . It is working now :)

**Comment by sjindel-google** [comment]
I've added a walkthrough to the wiki page: https://github.com/flutter/flutter/wiki/Binding-to-native-code-via-FFI

This illustrates how to add the C/C++ sources directly so they will be compiled for the correct architecture for the end application.

Please don't upload `.so` or `.a` files directly to Flutter plugins on Pub: it's a security hazard and it can cause compatibility issues.

**Comment by stuartmorgan** [comment]
Could you elaborate on what you mean when you say "plugin"? Currently 'Flutter plugin' tends to refer to the thing created by `flutter create --template=plugin`, which uses method channels to communicate using APIs that differ by platform. I wouldn't expect any of that plumbing/boilerplate to be relevant to the FFI use case. (I.e., step 1 of what's currently on the wiki doesn't seem like what we would want the solution to be.)

It might be helpful to come up with a different term for an FFI-based package, or at least distinguish clearly (e.g., a method-channel plugin vs. an FFI plugin)

**Comment by sjindel-google** [comment]
I would also like to have a different template for an FFI-based package, but the plugin system actually provides a lot of useful plumbing besides method channels.

1. Including "native" code: the FFI can also bind to Swift, Objective-C and Java (via JNI).

2. Compilation & linking: the plugin system ensures that C/C++ is compiled with the correct compiler (NDK on Android and Xcode on iOS) and ABI for the target system and that the result of compilation (static or dynamic library) is in the system linker's path at runtime.

3. Code signing: on iOS and MacOS, the plugin system (via Xcode) ensures that the results of compilation are signed appropriately.

4. Architecture selection: the plugin system generates fat files on Darwin and the JNI-libs directory structure on Android so the correct version of the native library is loaded at runtime and others can be stripped by the App or Play store.

**Comment by jaumard** [comment]
So we have already a way to include native libraries into a plugin/package to be deployed in pub ? 

Something like: 

```
native_libraries:
 platform:
    android:
        assets/binary/android.so
    ios:
        assets/binary/ios.so
    macos:
        assets/binary/macos.so

``` 
And they flutter is configuring native projects to include them automatically. 

That would be super useful instead of asking packages user to deal with native binaries. Because most of the time they don't know how/what to do with them.

**Comment by vaind** [comment]
What about a Dart library wrapping a C library using FFI. The C library is pre-compiled and available for "all" platforms, desktop as well as Android/iOS.
How can this be distributed to be consumable for both flutter & dart "other/server" apps?

I've been able to manually create a flutter app example that depends on the dart-library but I had to add an `implementation` dependency on the `aar` package directly to the example/app/build.gradle. Is there a way this dependency could be specified within the dart-library/flutter-plugin so that its users wouldn't need to take do it manually (especially, because the version of the `aar` dependency is different than the dart-lib/flutter-plugin).

I've tried to do it [here](https://github.com/objectbox/objectbox-dart/commit/cc507cf471b55b7ff3d22cc8f26fc456e2e97c56) by "converting" the dart-library to a flutter-package (running `flutter create --template=plugin` on the existing folder) but the original example doesn't work, after I've moved the dependency into dart-library/flutter-plugin `android/build.gradle`

**Comment by baldemir** [comment]
Hello @hanabi1224 I'm trying to use my Go library in Flutter. I'm exporting framework thanks to gomobile. And after that i'm including .framework file in xcode project. When I try to call lookup function after DynamicLibrary.process() it gives the error `[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: Invalid argument(s): Failed to lookup symbol (dlsym(RTLD_DEFAULT, increment): symbol not found)` 

Do you have an idea how I can solve it? There is no problem in lookup when i try ffi with native C code.

**Comment by hanabi1224** [comment]
@baldemir Sorry, not very familiar with golang :(

**Comment by hanabi1224** [comment]
@sjindel-google Due to https://github.com/flutter/flutter/issues/39916 , do you think it's good idea to put up a WARNING if ppl use ffi features to build IOS apps? Or can you please suggest some workaround?

**Comment by mit-mit** [comment]
cc @dcharkes

**Comment by vaind** [comment]
> I've been able to manually create a flutter app example that depends on the dart-library but I had to add an `implementation` dependency on the `aar` package directly to the example/app/build.gradle. Is there a way this dependency could be specified within the dart-library/flutter-plugin so that its users wouldn't need to take do it manually (especially, because the version of the `aar` dependency is different than the dart-lib/flutter-plugin).
> 
> I've tried to do it [here](https://github.com/objectbox/objectbox-dart/commit/cc507cf471b55b7ff3d22cc8f26fc456e2e97c56) by "converting" the dart-library to a flutter-package (running `flutter create --template=plugin` on the existing folder) but the original example doesn't work, after I've moved the dependency into dart-library/flutter-plugin `android/build.gradle`

I was able to get this working, see https://github.com/objectbox/objectbox-dart/pull/79 if you're interested. In short, I was missing the following declaration in the library's pubspec.yaml:
```
flutter:
  plugin:
    android:
```

**Comment by hanabi1224** [comment]
The document does not seems to cover how to integrate prebuilt statically linked library (libxxx.a) on IOS, where I actually had some problem.  Everything work fine with debug build (flutter run --debug), however, in release build (flutter run --release),  it complains symbol(from libxxx.a) not found. I guess it's some build args that strip the symbol, can you please give some hints on it?  Thanks in advance!

**Comment by dcharkes** [comment]
We recently updated the documentation for non-prebuilt (including the source in Xcode) statically linked libraries, see the discussion on https://github.com/dart-lang/ffi/issues/28#issuecomment-562238818. If I run the example from the tutorial (native add), which is a non-prebuilt statically linked library, it works both with `flutter run --debug` and `flutter run --release` when statically linking the symbol into the app.

Note that we had to add the source code in the Xcode project to get it statically linked in. However, that was the same for both debug and release modes.

Can you provide a minimal example where `flutter run --release` doesn't work with a prebuilt library? (P.s. feel free to open a new specific issue instead of making this thread longer, and cc me.)

**Comment by hanabi1224** [comment]
@dcharkes  Sure! Please use [this example project](https://github.com/hanabi1224/flutter_native_extensions/tree/master/src/compression/flutter_native_compression/example)  it will print a version number from native code when there's no error
I did not commit the statically link library to the repo, you can download from here and place it under [{plugin}/ios](https://github.com/hanabi1224/flutter_native_extensions/tree/master/src/compression/flutter_native_compression/ios) folder manually

**Comment by dcharkes** [comment]
I'm able to reproduce the error on `--release`.

`Failed to lookup symbol (dlsym(RTD_DEFAULT, ffi_lz4_version_string): symbol not found)`.

I'm not very familiar with the XCode setup of Flutter projects, but it looks like the `flutter_native_compression` is only included in `Development`.

<img width="269" alt="Screenshot 2019-12-18 at 10 52 47" src="https://user-images.githubusercontent.com/3601775/71075674-c738a780-2184-11ea-98e1-7d9aa26016c9.png">

I'll dig a bit deeper.

**Comment by dcharkes** [comment]
cc Flutter tools team: @jonahwilliams @jmagman

**Comment by hanabi1224** [comment]
@dcharkes just FYI, when I use the (native) symbol from obj-c / swift code, everthing works, I can confirm that the library is linked, but the symbols are not accessible from dart VM in release build

**Comment by dcharkes** [comment]
In that case, it might be related to https://github.com/flutter/flutter/issues/46887 (dart_api.h symbols not visible in release).

**Comment by jmagman** [comment]
> cc Flutter tools team: @jonahwilliams @jmagman

After I added the libdart_native_compression.a and podspec from [Archive.zip](https://github.com/flutter/flutter/files/3974889/Archive.zip) the [example project](https://github.com/hanabi1224/flutter_native_extensions/tree/master/src/compression/flutter_native_compression/example) built in Xcode in Debug and Release.

I was also able to use it in the Runner app.
```swift
import flutter_native_compression
...
let test = ffi_lz4_version_number();
```
```
(lldb) p test
(Int32) $R0 = 10902
```
I was a bit surprised `ffi_lz4_version_number()` didn't need an `extern` in that header, that could be causing other issues if the symbol needs to be used elsewhere.

Was there something else you needed us to look at, @dcharkes?

**Comment by dcharkes** [comment]
> After I added the libdart_native_compression.a and podspec from Archive.zip the example project built in Xcode in Debug and Release.

Hm, if I run it with `flutter run --release`, it doesn't find the symbol. How exactly did you run in release mode @jmagman? With that command? From XCode?

**Comment by jmagman** [comment]
@dcharkes I unzipped and copied the contents of [Archive.zip](https://github.com/flutter/flutter/files/3974889/Archive.zip) to `flutter_native_extensions/src/compression/flutter_native_compression/ios`, which adds libdart_native_compression.a as a vendored library.

I did hit a cached module problem at some point and had to delete ~/Library/Developer/Xcode/DerivedData.

It then compiled in Xcode in Debug and Release, `flutter build ios` and `flutter run --release`

**Comment by hanabi1224** [comment]
@jmagman Did you run it in emulator or real device?  In real device, I always see (only in release build) error message of 'symbol not found'. And I believe @dcharkes had the same experience, thanks!

**Comment by jmagman** [comment]
> @jmagman Did you run it in emulator or real device? In real device, I always see (only in release build) error message of 'symbol not found'. And I believe @dcharkes had the same experience, thanks!

@hanabi1224 Sorry I totally missed this question.
I just tried again.  I just ran `flutter run --release` from `examples` and it launched on my real device. 
 I also ran `example/ios/Runner.xcworkspace` in Release mode on a real device from Xcode.

Are you sure you unarchived libdart_native_compression.a AND the podspec to the right place?

**Comment by hanabi1224** [comment]
@jmagman That is strange, I always have the same problem that flutter run --debug works (which confirms environment setup is corrent) but flutter run --release does not,  can you please also attach your flutter / OSX / Xcode version?

**Comment by jmagman** [comment]
```
[✓] Flutter (Channel master, v1.14.2-pre.49, on Mac OS X 10.15.2 19C57, locale en-US)
    • Flutter version 1.14.2-pre.49 at /Users/m/Projects/flutter
    • Framework revision 9301a86a86 (4 days ago), 2020-01-17 15:28:01 -0800
    • Engine revision 6f37b7357e
    • Dart version 2.8.0 (build 2.8.0-dev.3.0 f96c48307d)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/m/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Users/m/Applications/Xcode_11-3.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (1 available)
    • iPhone • d83d5bc53967baa0ee18626ba87b6254b2ab5418 • ios • iOS 13.3

• No issues found!
```

**Comment by jmagman** [comment]
```
s.public_header_files = 'Classes**/*.h'
```
podspec change from your Archive was important...

**Comment by hanabi1224** [comment]
@jmagman Hmmm, I have the same OSX version. I updated xcode to latest 11.3.1 and use flutter master channel but still no good. Regarding podspec change, it's included otherwise flutter run --debug won't work either.  My verification steps are always 1. flutter run --debug works 2.  flutter run --release

**Comment by bltavares** [comment]
I've tried to include a static lib as part of the plugin, but I could not make it work on the Simulator either, running with `flutter run --debug`.

On the plugin `.podspec` freshly generated from the plugin template I've included the following:

```ruby
  s.static_framework = true
  s.vendored_libraries = "**/*.a"
```

Then I added the compiled archive inside the `my_plugin/ios/libs` folder. After a `pod install` on `my_plugin/example/ios`, I can see that the library was included as part of the linking process:

<img width="264" alt="image" src="https://user-images.githubusercontent.com/109474/74206748-71035480-4c5b-11ea-906f-bf832cba04a8.png">

On XCode, navigating to `Pods > Target Support Files > Pods-Runner.debug.cxconfig` I can see that the library has been added to the linking variable:

<img width="687" alt="image" src="https://user-images.githubusercontent.com/109474/74206791-af007880-4c5b-11ea-91dd-28c47cb67174.png">

The code compiles, but clicking the button leads to a failed lookup on the symbol. This is the same code that works on Android, so I kept investigating.

```
[VERBOSE-2:dart_isolate.cc(813)] Unhandled exception:
Invalid argument(s): Failed to lookup symbol (dlsym(RTLD_DEFAULT, colmeia_dat1_sync): symbol not found)
```

The file was generated with `lipo`. Looking at `libcolmeia_dat1_ffi.a` the symbol is defined:

```sh
$ lipo -info libcolmeia_dat1_ffi.a
Architectures in the fat file: libcolmeia_dat1_ffi.a are: x86_64 arm64

$ strings libcolmeia_dat1_ffi.a | grep 'colmeia_da1_sync` # shows up
$ otool -tV libcolmeia_dat1_ffi.a | grep "colmeia_dat1_sync:" # shows up
```

But looking at the generated frameworks and app, I can't find any of the symbols. I think this is something about how iOS deals with static and dynamic frameworks on the same build. I would expect it to fail during linking phase. That is how far I've investigated.

```sh
otool -tV example/build/ios/Debug-iphonesimulator/Runner.app/Runner | grep "colmeia_da1_sync" # nothing shows up.
strings  example/build/ios/Debug-iphonesimulator/Runner.app/Runner | grep "colmeia_da1_sync" # nothing shows up.
```

Manually editing the file `Pods-Runner.debug.xcconfig` and including `-force_load ./libcolmeia_dat1_ffi.a` allowed me pass beyond the compilation phase, and load the symbol from Dart.

```
OTHER_LDFLAGS = [...] -force_load "${PODS_ROOT}/../.symlinks/plugins/my_plugin/ios/libs/libcolmeia_dat1_ffi.a"
```

The app crashes right after, but I believe this is something on my code panicking on the FFI side.
I have not investigated how to include the line as part of the `podspec` or the `podfile` yet.

**Comment by hanabi1224** [comment]
@bltavares For static linking, you need to define any dummy function from the lib from .h header. Although it works only in debug build

**Comment by rodydavis** [comment]
Are these docs out of date? https://flutter.dev/docs/development/platform-integration/c-interop

**Comment by dcharkes** [comment]
> Are these docs out of date? https://flutter.dev/docs/development/platform-integration/c-interop

No, not that I'm aware of. The dynamic linking solution is what I use here locally and it works.

Do you have a specific problem?

**Comment by rodydavis** [comment]
No it works for me too! Just didn’t know if there was a bug relating to this issue

**Comment by nmfisher** [comment]
I seem to be hitting this too. 

My main Flutter project references a plugin (https://github.com/nmfisher/flutter_chinese_character_recognition) that invokes a function in a statically linked Rust library (compiled separately) via FFI. 

The plugin itself is bundled as a static framework:

https://github.com/nmfisher/flutter_chinese_character_recognition/blob/2cf35a0b659a591f52dc447f54c4d800e1da62d7/ios/chinese_character_recognition.podspec#L18

and links to the static library via the vendored_libraries config property in the plugin's podspec. 

I also included a dummy method in the plugin to ensure the function wasn't optimized out.

Everything works in debug mode and release mode, both on the simulator and a physical device (iPhone). Also works fine on Android emulator (just waiting to test on a physical Android device).

The issue is only encountered when archiving and submitting to the App Store/TestFlight:

![image](https://user-images.githubusercontent.com/7238578/78920927-b65ec980-7ac6-11ea-8812-f05926ce8669.png)

Have tried 
- adding "s.xcconfig = { 'OTHER_LDFLAGS' => '-all_load' }" to the plugin's podspec:
- removing "use_frameworks!" from the main project's Podfile (caused compilation errors with other plugins)
- unchecking "Strip Dead Code" and "Strip Swift symbols",
- directly linking the main project with the static library in Xcode
- adding a dummy method to the main project's GeneratedPluginRegistrant.m (though I'm not sure if this was overwritten before build or not).
None of these worked.

If I directly dump the symbols from the release Runner build, I can see the library has been linked correctly:
```
nickfisher@Nicks-Mac fluent_academy_app % nm /Users/nickfisher/Library/Developer/Xcode/DerivedData/Runner-chnndanceemyvefanaokyerbrdah/Build/Products/Release-iphoneos/Runner.app/Runner | grep lookup
...
000000010000ad6c T _lookupFFI
```

But trying to do the same for the archive shows nothing:

```
nickfisher@Nicks-Mac fluent_academy_app % nm /Users/nickfisher/Library/Developer/Xcode/Archives/2020-04-09/Runner\ 9-4-20,\ 9.30\ am.xcarchive/Products/Applications/Runner.app/Runner | grep lookup
nickfisher@Nicks-Mac fluent_academy_app % 
```
So I'm 99% sure the "Archive" step is stripping the code, but I can't find anything else in Xcode that might be doing this. Any suggestions?

flutter doctor

```
[✓] Flutter (Channel dev, v1.18.0, on Mac OS X 10.15.3 19D76, locale en-AU)
    • Flutter version 1.18.0 at /Users/nickfisher/Downloads/flutter
    • Framework revision de1e572916 (3 days ago), 2020-04-06 16:15:07 -0700
    • Engine revision df257e59c2
    • Dart version 2.8.0 (build 2.8.0-dev.20.0 1210d27678)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_SDK_ROOT to that location.
      You may also want to add it to your PATH environment variable.


[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.9.1
```

**Comment by devxpy** [comment]
> I've added a walkthrough to the wiki page: [flutter/flutter/wiki/Binding-to-native-code-via-FFI](https://github.com/flutter/flutter/wiki/Binding-to-native-code-via-FFI)
> 
> This illustrates how to add the C/C++ sources directly so they will be compiled for the correct architecture for the end application.

Thanks for the walkthrough.

> Please don't upload `.so` or `.a` files directly to Flutter plugins on Pub: it's a security hazard and it can cause compatibility issues.

If not that, then what's the right way to package `.so` files on pub right now?

**Comment by dcharkes** [comment]
@devxpy right now, uploading `.so` files is the only way. See my update in https://github.com/dart-lang/sdk/issues/36712.

@nmfisher @bltavares The Rust questions are orthogonal are orthogonal to this specific GitHub issue. Feel free to open another GitHub issue or ask on StackOverflow. Please document if you've got the whole chain working with rust so we can add it to the FFI documentation.

**Comment by liang-notes** [comment]
> I've tried to include a static lib as part of the plugin, but I could not make it work on the Simulator either, running with `flutter run --debug`.
> 
> On the plugin `.podspec` freshly generated from the plugin template I've included the following:
> 
> ```ruby
>   s.static_framework = true
>   s.vendored_libraries = "**/*.a"
> ```
> 
> Then I added the compiled archive inside the `my_plugin/ios/libs` folder. After a `pod install` on `my_plugin/example/ios`, I can see that the library was included as part of the linking process:
> 
> <img alt="image" width="264" src="https://user-images.githubusercontent.com/109474/74206748-71035480-4c5b-11ea-906f-bf832cba04a8.png">
> 
> On XCode, navigating to `Pods > Target Support Files > Pods-Runner.debug.cxconfig` I can see that the library has been added to the linking variable:
> 
> <img alt="image" width="687" src="https://user-images.githubusercontent.com/109474/74206791-af007880-4c5b-11ea-91dd-28c47cb67174.png">
> 
> The code compiles, but clicking the button leads to a failed lookup on the symbol. This is the same code that works on Android, so I kept investigating.
> 
> ```
> [VERBOSE-2:dart_isolate.cc(813)] Unhandled exception:
> Invalid argument(s): Failed to lookup symbol (dlsym(RTLD_DEFAULT, colmeia_dat1_sync): symbol not found)
> ```
> 
> The file was generated with `cargo-lipo` from a Rust project. Looking at `libcolmeia_dat1_ffi.a` the symbol is defined:
> 
> ```shell
> $ lipo -info libcolmeia_dat1_ffi.a
> Architectures in the fat file: libcolmeia_dat1_ffi.a are: x86_64 arm64
> 
> $ strings libcolmeia_dat1_ffi.a | grep 'colmeia_da1_sync` # shows up
> $ otool -tV libcolmeia_dat1_ffi.a | grep "colmeia_dat1_sync:" # shows up
> ```
> 
> But looking at the generated frameworks and app, I can't find any of the symbols. I think this is something about how iOS deals with static and dynamic frameworks on the same build. I would expect it to fail during linking phase. That is how far I've investigated.
> 
> ```shell
> otool -tV example/build/ios/Debug-iphonesimulator/Runner.app/Runner | grep "colmeia_da1_sync" # nothing shows up.
> strings  example/build/ios/Debug-iphonesimulator/Runner.app/Runner | grep "colmeia_da1_sync" # nothing shows up.
> ```
> 
> After a lot of search, this [Stackoverflow reply](https://stackoverflow.com/a/7942924) helped a bit more. Manually editing the file `Pods-Runner.debug.xcconfig` and including `-force_load ./libcolmeia_dat1_ffi.a` allowed me pass beyond the compilation phase, and load the symbol from Dart.
> 
> ```
> OTHER_LDFLAGS = [...] -force_load "${PODS_ROOT}/../.symlinks/plugins/my_plugin/ios/libs/libcolmeia_dat1_ffi.a"
> ```
> 
> The app crashes right after, but I believe this is something on my code panicking on the FFI side. ~I have not investigated how to include the line as part of the `podspec` or the `podfile` yet.~
> 
> I've added the following to the `Podspec` [file on the Runner project](https://github.com/bltavares/colmeia/blob/4a3c339532cb03f69d2c1a1532249ac79218662b/colmeia_app/colmeia_native/example/ios/Podfile#L89-L92)



> I've tried to include a static lib as part of the plugin, but I could not make it work on the Simulator either, running with `flutter run --debug`.
> 
> On the plugin `.podspec` freshly generated from the plugin template I've included the following:
> 
> ```ruby
>   s.static_framework = true
>   s.vendored_libraries = "**/*.a"
> ```
> 
> Then I added the compiled archive inside the `my_plugin/ios/libs` folder. After a `pod install` on `my_plugin/example/ios`, I can see that the library was included as part of the linking process:
> 
> <img alt="image" width="264" src="https://user-images.githubusercontent.com/109474/74206748-71035480-4c5b-11ea-906f-bf832cba04a8.png">
> 
> On XCode, navigating to `Pods > Target Support Files > Pods-Runner.debug.cxconfig` I can see that the library has been added to the linking variable:
> 
> <img alt="image" width="687" src="https://user-images.githubusercontent.com/109474/74206791-af007880-4c5b-11ea-91dd-28c47cb67174.png">
> 
> The code compiles, but clicking the button leads to a failed lookup on the symbol. This is the same code that works on Android, so I kept investigating.
> 
> ```
> [VERBOSE-2:dart_isolate.cc(813)] Unhandled exception:
> Invalid argument(s): Failed to lookup symbol (dlsym(RTLD_DEFAULT, colmeia_dat1_sync): symbol not found)
> ```
> 
> The file was generated with `cargo-lipo` from a Rust project. Looking at `libcolmeia_dat1_ffi.a` the symbol is defined:
> 
> ```shell
> $ lipo -info libcolmeia_dat1_ffi.a
> Architectures in the fat file: libcolmeia_dat1_ffi.a are: x86_64 arm64
> 
> $ strings libcolmeia_dat1_ffi.a | grep 'colmeia_da1_sync` # shows up
> $ otool -tV libcolmeia_dat1_ffi.a | grep "colmeia_dat1_sync:" # shows up
> ```
> 
> But looking at the generated frameworks and app, I can't find any of the symbols. I think this is something about how iOS deals with static and dynamic frameworks on the same build. I would expect it to fail during linking phase. That is how far I've investigated.
> 
> ```shell
> otool -tV example/build/ios/Debug-iphonesimulator/Runner.app/Runner | grep "colmeia_da1_sync" # nothing shows up.
> strings  example/build/ios/Debug-iphonesimulator/Runner.app/Runner | grep "colmeia_da1_sync" # nothing shows up.
> ```
> 
> After a lot of search, this [Stackoverflow reply](https://stackoverflow.com/a/7942924) helped a bit more. Manually editing the file `Pods-Runner.debug.xcconfig` and including `-force_load ./libcolmeia_dat1_ffi.a` allowed me pass beyond the compilation phase, and load the symbol from Dart.
> 
> ```
> OTHER_LDFLAGS = [...] -force_load "${PODS_ROOT}/../.symlinks/plugins/my_plugin/ios/libs/libcolmeia_dat1_ffi.a"
> ```
> 
> The app crashes right after, but I believe this is something on my code panicking on the FFI side. ~I have not investigated how to include the line as part of the `podspec` or the `podfile` yet.~
> 
> I've added the following to the `Podspec` [file on the Runner project](https://github.com/bltavares/colmeia/blob/4a3c339532cb03f69d2c1a1532249ac79218662b/colmeia_app/colmeia_native/example/ios/Podfile#L89-L92)

Update the '.a' with -force_load worked for me, I wonder is there any other solution?

**Comment by liang-notes** [comment]
@bltavares [bltavares](https://github.com/bltavares) Hi, I add '-all_load' in the build setting's other_link_flags of  the project. It also worked.

**Comment by eli1stark** [comment]
@dcharkes Documentation can't be found here: https://flutter.dev/docs/development/platform-integration/c-interop and here: https://github.com/flutter/flutter/wiki/Binding-to-native-code-via-FFI. Are there any alternatives?

**Comment by Sunbreak** [comment]
Hope those help

- https://github.com/Sunbreak/native_interop.tour
- https://github.com/Sunbreak/cronet_flutter
- https://github.com/woodemi/quick.flutter

**Comment by GregoryConrad** [comment]
> Update the '.a' with -force_load worked for me, I wonder is there any other solution?

Yes, there is; for iOS and macOS, I'd recommend building an XCFramework and set up your podspec to ship that XCFramework. XCFrameworks support iOS, iOS Simulator, and macOS without lipo-ing everything together (which is no longer recommended). Take a look here: https://github.com/GregoryConrad/mimir/blob/main/packages/flutter_mimir/ios/flutter_mimir.podspec

Same podspec file for iOS & macOS because of using the XCFramework

**Comment by bkonyi** [comment]
@dcharkes I'm assuming this is all covered by the native assets work?

**Comment by dcharkes** [comment]
> @dcharkes I'm assuming this is all covered by the native assets work?

Yes, let's track it in the tracking issue for that:

* https://github.com/flutter/flutter/issues/129757
