### ISSUE TITLE
flutter run: Class '_LocalDirectory' has no instance getter 'isNotEmpty'

### ISSUE THREAD

**Issue by rwozniak** [flutter/flutter#7413]
## Steps to Reproduce

Follow steps from the tutorial (https://flutter.io/getting-started/#creating-your-first-flutter-app).
Cannot run 'myapp' as the compilation returns an error.

## Logs

```
roman$ flutter run
Error detected in application source code:
NoSuchMethodError: Class '_LocalDirectory' has no instance getter 'isNotEmpty'.
Receiver: Instance of '_LocalDirectory'
Tried calling: isNotEmpty
```

```
roman$ flutter run -v
[  +25 ms] /Users/roman/Library/Android/sdk/platform-tools/adb devices -l
[  +11 ms] Exit code 0 from: /Users/roman/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
           033d25a508e53dd8       device usb:336592896X product:hammerhead model:Nexus_5 device:hammerhead
[   +5 ms] idevice_id -h
[   +8 ms] /usr/bin/xcrun simctl list --json devices
[  +83 ms] /Users/roman/Library/Android/sdk/platform-tools/adb -s 033d25a508e53dd8 shell getprop
[ +142 ms] /Users/roman/dev/TOOLS/flutter/bin/cache/artifacts/engine/darwin-x64/sky_snapshot --packages=/Users/roman/dev/PRIV/FLUTTER/myapp/.packages --print-deps /Users/roman/dev/PRIV/FLUTTER/myapp/lib/main.dart
[ +214 ms] Exit code 0 from: /Users/roman/dev/TOOLS/flutter/bin/cache/artifacts/engine/darwin-x64/sky_snapshot --packages=/Users/roman/dev/PRIV/FLUTTER/myapp/.packages --print-deps /Users/roman/dev/PRIV/FLUTTER/myapp/lib/main.dart
[  +10 ms] Error detected in application source code:
[   +3 ms] Exception from flutter run: NoSuchMethodError: Class 'NoSuchMethodError' has no instance method 'trim'.
           Receiver: Instance of 'NoSuchMethodError'
           Tried calling: trim()
           dart:core-patch/object_patch.dart 44                       Object._noSuchMethod
           dart:core-patch/object_patch.dart 47                       Object.noSuchMethod
           package:flutter_tools/src/base/logger.dart 164             VerboseLogger._emit
           package:flutter_tools/src/base/logger.dart 144             VerboseLogger.printError
           package:flutter_tools/src/globals.dart 18                  printError
           package:flutter_tools/src/hot.dart 114                     HotRunner._refreshDartDependencies
           package:flutter_tools/src/hot.dart 146                     HotRunner._run.<async>
           dart:async/future.dart 144                                 Future.Future.microtask.<fn>
           package:stack_trace/src/stack_zone_specification.dart 185  StackZoneSpecification._run
           package:stack_trace/src/stack_zone_specification.dart 97   StackZoneSpecification._registerCallback.<fn>
           package:stack_trace/src/stack_zone_specification.dart 185  StackZoneSpecification._run
           package:stack_trace/src/stack_zone_specification.dart 97   StackZoneSpecification._registerCallback.<fn>
           dart:async/zone.dart 1146                                  _rootRun
           dart:async/zone.dart 1026                                  _CustomZone.run
           dart:async/zone.dart 924                                   _CustomZone.runGuarded
           dart:async/zone.dart 951                                   _CustomZone.bindCallback.<fn>
           package:stack_trace/src/stack_zone_specification.dart 185  StackZoneSpecification._run
           package:stack_trace/src/stack_zone_specification.dart 97   StackZoneSpecification._registerCallback.<fn>
           package:stack_trace/src/stack_zone_specification.dart 185  StackZoneSpecification._run
           package:stack_trace/src/stack_zone_specification.dart 97   StackZoneSpecification._registerCallback.<fn>
           dart:async/zone.dart 1150                                  _rootRun
           dart:async/zone.dart 1026                                  _CustomZone.run
           dart:async/zone.dart 924                                   _CustomZone.runGuarded
           dart:async/zone.dart 951                                   _CustomZone.bindCallback.<fn>
           dart:async/schedule_microtask.dart 41                      _microtaskLoop
           dart:async/schedule_microtask.dart 50                      _startMicrotaskLoop
           dart:isolate-patch/isolate_patch.dart 96                   _runPendingImmediateCallback
           dart:isolate-patch/isolate_patch.dart 149                  _RawReceivePortImpl._handleMessage
           ===== asynchronous gap ===========================
           dart:async/future_impl.dart 22                             _Completer.completeError
           package:flutter_tools/src/hot.dart 239                     HotRunner._run.<async>
           dart:async/future.dart 144                                 Future.Future.microtask.<fn>
           package:stack_trace/src/stack_zone_specification.dart 185  StackZoneSpecification._run
           package:stack_trace/src/stack_zone_specification.dart 97   StackZoneSpecification._registerCallback.<fn>
           package:stack_trace/src/stack_zone_specification.dart 185  StackZoneSpecification._run
           package:stack_trace/src/stack_zone_specification.dart 97   StackZoneSpecification._registerCallback.<fn>
           dart:async/zone.dart 1146                                  _rootRun
           dart:async/zone.dart 1026                                  _CustomZone.run
           dart:async/zone.dart 924                                   _CustomZone.runGuarded
           dart:async/zone.dart 951                                   _CustomZone.bindCallback.<fn>
           package:stack_trace/src/stack_zone_specification.dart 185  StackZoneSpecification._run
           package:stack_trace/src/stack_zone_specification.dart 97   StackZoneSpecification._registerCallback.<fn>
           package:stack_trace/src/stack_zone_specification.dart 185  StackZoneSpecification._run
           package:stack_trace/src/stack_zone_specification.dart 97   StackZoneSpecification._registerCallback.<fn>
           dart:async/zone.dart 1150                                  _rootRun
           dart:async/zone.dart 1026                                  _CustomZone.run
           dart:async/zone.dart 924                                   _CustomZone.runGuarded
           dart:async/zone.dart 951                                   _CustomZone.bindCallback.<fn>
           dart:async/schedule_microtask.dart 41                      _microtaskLoop
           dart:async/schedule_microtask.dart 50                      _startMicrotaskLoop
           dart:isolate-patch/isolate_patch.dart 96                   _runPendingImmediateCallback
           dart:isolate-patch/isolate_patch.dart 149                  _RawReceivePortImpl._handleMessage
           ===== asynchronous gap ===========================
           dart:async/zone.dart 1061                                  _CustomZone.registerCallback
           dart:async/zone.dart 949                                   _CustomZone.bindCallback
           dart:async/schedule_microtask.dart 148                     scheduleMicrotask
           dart:async/future.dart 142                                 Future.Future.microtask
           package:flutter_tools/src/hot.dart                         HotRunner._run
           package:flutter_tools/src/hot.dart 76                      HotRunner.run.<fn>
           package:stack_trace/src/chain.dart 92                      Chain.capture.<fn>
           dart:async/zone.dart 1150                                  _rootRun
           dart:async/zone.dart 1026                                  _CustomZone.run
           dart:async/zone.dart 1503                                  runZoned
           package:stack_trace/src/chain.dart 90                      Chain.capture
           package:flutter_tools/src/hot.dart 75                      HotRunner.run
           package:flutter_tools/src/commands/run.dart 250            RunCommand.runCommand.<async>
           dart:async/future.dart 144                                 Future.Future.microtask.<fn>
           package:stack_trace/src/stack_zone_specification.dart 185  StackZoneSpecification._run
           package:stack_trace/src/stack_zone_specification.dart 97   StackZoneSpecification._registerCallback.<fn>
           dart:async/zone.dart 1146                                  _rootRun
           dart:async/zone.dart 1026                                  _CustomZone.run
           dart:async/zone.dart 924                                   _CustomZone.runGuarded
           dart:async/zone.dart 951                                   _CustomZone.bindCallback.<fn>
           package:stack_trace/src/stack_zone_specification.dart 185  StackZoneSpecification._run
           package:stack_trace/src/stack_zone_specification.dart 97   StackZoneSpecification._registerCallback.<fn>
           dart:async/zone.dart 1150                                  _rootRun
           dart:async/zone.dart 1026                                  _CustomZone.run
           dart:async/zone.dart 924                                   _CustomZone.runGuarded
           dart:async/zone.dart 951                                   _CustomZone.bindCallback.<fn>
           dart:async/schedule_microtask.dart 41                      _microtaskLoop
           dart:async/schedule_microtask.dart 50                      _startMicrotaskLoop
           dart:isolate-patch/isolate_patch.dart 96                   _runPendingImmediateCallback
           dart:isolate-patch/isolate_patch.dart 149                  _RawReceivePortImpl._handleMessage
```

```
roman$ flutter analyze
Analyzing lib/main.dart...
No analyzer warnings! (ran in 6.8s)
```

## Flutter Doctor

```
roman$ flutter doctor
[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/roman/dev/TOOLS/flutter
    • Framework revision 3c7122a797 (27 minutes ago), 2017-01-10 09:30:00
    • Engine revision f13518d7e7
    • Tools Dart version 1.21.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /Users/roman/Library/Android/sdk
    • Platform android-25, build-tools 25.0.2
    • Java(TM) SE Runtime Environment (build 1.8.0_112-b16)

[-] iOS toolchain - develop for iOS devices (Xcode 8.2.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.2.1, Build version 8C1002
    x ideviceinstaller not available; this is used to discover connected iOS devices.
      Install via 'brew install ideviceinstaller'.
    x ios-deploy not available; this is used to deploy to connected iOS devices.
      Install via 'brew install ios-deploy'.

[✓] IntelliJ IDEA Community Edition (version 2016.3.2)
    • Dart plugin version 163.11306
    • Flutter plugin version 0.1.7

[✓] Connected devices
    • Nexus 5 • 033d25a508e53dd8 • android-arm • Android 6.0 (API 23)
```

**Comment by Hixie** [comment]
@tvolkert this might be you

**Comment by tvolkert** [comment]
Looks like the error was introduced in #6668 - we're calling

```
} catch (error) {
  ...
  printError(error);
  ...
}
```

printError requires a `String` arg (we're trying to `trim()` it downstream), yet `error` is an `Error`.

@johnmccutchan

**Comment by Hixie** [comment]
ok, we should just replace it with `printError('$error');`.

**Comment by roman-upnext** [comment]
After pulling recent changes the root cause seems not fixed:

```
flutter run -v
[  +25 ms] /Users/roman/Library/Android/sdk/platform-tools/adb devices -l
[  +12 ms] Exit code 0 from: /Users/roman/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
           033d25a508e53dd8       device usb:336592896X product:hammerhead model:Nexus_5 device:hammerhead
[   +4 ms] idevice_id -h
[   +4 ms] /usr/bin/xcrun simctl list --json devices
[  +81 ms] /Users/roman/Library/Android/sdk/platform-tools/adb -s 033d25a508e53dd8 shell getprop
[ +124 ms] /Users/roman/dev/TOOLS/flutter/bin/cache/artifacts/engine/darwin-x64/sky_snapshot --packages=/Users/roman/dev/PRIV/FLUTTER/myapp/.packages --print-deps /Users/roman/dev/PRIV/FLUTTER/myapp/lib/main.dart
[ +225 ms] Exit code 0 from: /Users/roman/dev/TOOLS/flutter/bin/cache/artifacts/engine/darwin-x64/sky_snapshot --packages=/Users/roman/dev/PRIV/FLUTTER/myapp/.packages --print-deps /Users/roman/dev/PRIV/FLUTTER/myapp/lib/main.dart
[  +10 ms] Error detected in application source code:
[   +1 ms] NoSuchMethodError: Class '_LocalDirectory' has no instance getter 'isNotEmpty'.
           Receiver: Instance of '_LocalDirectory'
           Tried calling: isNotEmpty
[   +8 ms] 'flutter run' took 478ms.

package:flutter_tools/src/base/common.dart 31                     throwToolExit
package:flutter_tools/src/commands/run.dart 255                   RunCommand.runCommand.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/hot.dart 148                            HotRunner._run.<async>
===== asynchronous gap ===========================
dart:async                                                        _Completer.completeError
package:flutter_tools/src/commands/run.dart 257                   RunCommand.runCommand.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/hot.dart 148                            HotRunner._run.<async>
===== asynchronous gap ===========================
dart:async                                                        _asyncThenWrapperHelper
package:flutter_tools/src/commands/run.dart                       RunCommand.runCommand
package:flutter_tools/src/runner/flutter_command.dart 148         FlutterCommand.verifyThenRunCommand.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/dart/pub.dart 67                        pubGet.<async>
===== asynchronous gap ===========================
dart:async                                                        _asyncThenWrapperHelper
package:flutter_tools/src/runner/flutter_command.dart             FlutterCommand.verifyThenRunCommand
package:flutter_tools/src/commands/run.dart 160                   RunCommand.verifyThenRunCommand.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/runner/flutter_command.dart 197         FlutterCommand.findTargetDevice.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/device.dart 72                          DeviceManager.getAllConnectedDevices.<async>
===== asynchronous gap ===========================
dart:async                                                        _asyncThenWrapperHelper
package:flutter_tools/src/commands/run.dart                       RunCommand.verifyThenRunCommand
package:flutter_tools/src/runner/flutter_command.dart 119         FlutterCommand.run
package:args/command_runner.dart 194                              CommandRunner.runCommand.<async>
===== asynchronous gap ===========================
dart:async                                                        Future.Future.microtask
package:args/command_runner.dart                                  CommandRunner.runCommand
package:flutter_tools/src/runner/flutter_command_runner.dart 225  FlutterCommandRunner.runCommand.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/cache.dart 73                           Cache.lock.<async>
===== asynchronous gap ===========================
dart:async                                                        _asyncThenWrapperHelper
package:flutter_tools/src/runner/flutter_command_runner.dart      FlutterCommandRunner.runCommand
package:args/command_runner.dart 109                              CommandRunner.run.<fn>
dart:async                                                        Future.Future.sync
package:args/command_runner.dart 109                              CommandRunner.run
package:flutter_tools/src/runner/flutter_command_runner.dart 151  FlutterCommandRunner.run
package:flutter_tools/executable.dart 124                         main.<async>.<fn>.<fn>.<async>
===== asynchronous gap ===========================
package:stack_trace                                               Chain.capture
package:flutter_tools/executable.dart 123                         main.<async>.<fn>
package:flutter_tools/src/base/context.dart 76                    AppContext._run.<async>


[  +48 ms] exiting with code 1
```

**Comment by tvolkert** [comment]
This should be fixed now.  There was a type error fixed that was causing a catch block to hit which had never been hit before (and which had a bug in it that was fixed by #7416).  Once #7416 landed, the underlying type error was exposed (and fixed in #7422).

**Comment by exts** [comment]
I'm getting this error on windows 10 using flutter version 1.0, have a simple piece of code that 

```
$ flutter --version
Flutter 1.0.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 5391447fae (9 weeks ago) • 2018-11-29 19:41:26 -0800
Engine • revision 7375a0f414
Tools • Dart 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)
```

```
import 'package:test_api/test_api.dart';
import 'package:lesson01/mocks/mock_location.dart';

void main() {
  test('test fetchAny', () {
    final mockLocation = MockLocation.fetchAny();
    expect(mockLocation, isNotNull);
    expect(mockLocation, isNotEmpty);
  });
}
```

```
Testing started at 12:50 AM ...
D:\flutter\bin\flutter.bat --no-color test --machine test\unit
package:test_api                       expect
test\unit\mock_location_test.dart 8:5  main.<fn>

Expected: non-empty
  Actual: <Instance of 'Location'>
NoSuchMethodError: Class 'Location' has no instance getter 'isNotEmpty'.
Receiver: Instance of 'Location'
Tried calling: isNotEmpty at #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      _NotEmpty.matches (package:matcher/src/core_matchers.dart:27:46)
#2      _expect (package:test_api/src/frontend/expect.dart:149:30)
#3      expect (package:test_api/src/frontend/expect.dart:60:3)
#4      main.<anonymous closure> (file:///Z:/Programming/Flutter/fluttercc-lesson1/test/unit/mock_location_test.dart:8:5)
#5      Declarer.test.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:168:27)
<asynchronous suspension>
#6      Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test_api/src/backend/invoker.dart:249:15)
<asynchronous suspension>
#7      _rootRun (dart:async/zone.dart:1124:13)
#8      _CustomZone.run (dart:async/zone.dart:1021:19)
#9      _runZoned (dart:async/zone.dart:1516:10)
#10     runZoned (dart:async/zone.dart:1463:12)
#11     Invoker.waitForOutstandingCallbacks (package:test_api/src/backend/invoker.dart:246:5)
#12     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:166:33)
#13     _rootRun (dart:async/zone.dart:1124:13)
#14     _CustomZone.run (dart:async/zone.dart:1021:19)
#15     _runZoned (dart:async/zone.dart:1516:10)
#16     runZoned (dart:async/zone.dart:1463:12)
#17     Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:165:13)
<asynchronous suspension>
#18     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:399:25)
<asynchronous suspension>
#19     new Future.<anonymous closure> (dart:async/future.dart:176:37)
#20     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
#21     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
#22     _rootRun (dart:async/zone.dart:1120:38)
#23     _CustomZone.run (dart:async/zone.dart:1021:19)
#24     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#25     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#26     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
#27     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
#28     _rootRun (dart:async/zone.dart:1124:13)
#29     _CustomZone.run (dart:async/zone.dart:1021:19)
#30     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#31     Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
#32     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#33     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#34     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

**Comment by zoechi** [comment]
@exts Where does `MockLocation` come from?
The link above `https://flutter.io/getting-started/#creating-your-first-flutter-app` is broken.

**Comment by exts** [comment]
@zoechi it's a class I created

Folder structure

- /lib/mocks
- /lib/mocks/mock_location.dart
- /lib
- /lib/main.dart (flutter app)
- /tests
- /tests/unit
- /tests/unit/mock_location_test.dart

lesson01 = project name.

I have a question, dumb question because I've been following a tutorial that uses this code, `isNotEmpty` is only supposed to work on strings, collections or maps right? Maybe the tutorial I was following was old (because fetchAny returns a class object) and the expected functionality was incorrect or doesn't exist anymore because isNotNull works without issue.

**Comment by zoechi** [comment]
> I've been following a tutorial that uses this code

Where can I find this tutorial?

**Comment by zoechi** [comment]
>  fetchAny returns a class object

That's my suspicion as well, but because I don't know where `MockLocation` comes from I can't tell.
If it is a custom class of yours it's not a Flutter issue and I'd suggest asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by exts** [comment]
It's a paid tutorial and it is a custom class of mine, and my question is very simple one because if `IsNotEmpty` is to only match what I listed in my previous message then the tutorial was using it incorrectly (the tutorial was dated a month before 1.0 came out, so there's a chance it was using that matcher correctly at the time, but the behavior changed at 1.0).

**And if that tutorial _was_ using it incorrectly, that error shouldn't spit that message out, but rather it should say something along the lines of the matcher not of the expected type you're testing against**

**Comment by exts** [comment]
Alright that's a bit more clear on what's going on. so strings, collections and maps have isNotEmpty implemented by default - in order to use that matcher on other classes you need to implement it yourself.

**Comment by zoechi** [comment]
@exts exactly.
