### ISSUE TITLE
FATAL EXCEPTION: flutter-worker-2 java.lang.IncompatibleClassChangeError: Class 'android.content.res.XmlBlock$Parser' does not implement interface 'vd.a'

### ISSUE THREAD

**Issue by Lazizbek97** [flutter/flutter#161478]
### Steps to reproduce

1. Upgraded latest version of Flutter: 3.27.1
2. run the app on android device in release mode
3. Image picker(from gallery), Share images (share_plus: ^10.1.3), image gallery saving (gal: ^2.3.1) all these actions with the packages are crashing and exit from app

### Expected results

It was working on my previous version 3.24.1. It should work as well...

### Actual results

App is crashing and exit from app in only release mode

### Code sample

<details open><summary>Code sample</summary>

```dart
  Future<File?> getSignleImageFromCamera() async {
    try {
      XFile? image = await _picker.pickImage(source: ImageSource.camera);
      if (image == null) return null;

      final File imageTemp = File(image.path);

      return await imageTemp.writeAsBytes(await image.readAsBytes());
    } catch (e) {
      debugPrint('Failed to pick image: $e');
    }
    return null;
  }
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[+21683 ms] E/AndroidRuntime(13041): FATAL EXCEPTION: flutter-worker-2
[        ] E/AndroidRuntime(13041): Process: bundle id, PID: 13041
[        ] E/AndroidRuntime(13041): java.lang.IncompatibleClassChangeError: Class 'android.content.res.XmlBlock$Parser' does not implement interface 'vd.a'
in call to 'java.lang.String vd.a.b()' (declaration of 'p0.h' appears in base.apk)
[        ] E/AndroidRuntime(13041):     at p0.h.e(SourceFile:60)
[        ] E/AndroidRuntime(13041):     at p0.h.c(SourceFile:1)
[        ] E/AndroidRuntime(13041):     at p0.h.d(SourceFile:2)
[        ] E/AndroidRuntime(13041):     at io.flutter.plugins.imagepicker.k.j(SourceFile:87)
[        ] E/AndroidRuntime(13041):     at io.flutter.plugins.imagepicker.t.n(SourceFile:640)
[        ] E/AndroidRuntime(13041):     at t6.v.w(SourceFile:24)
[        ] E/AndroidRuntime(13041):     at rb.c.run(SourceFile:136)
[        ] E/AndroidRuntime(13041):     at rb.j.b(SourceFile:1)
[        ] E/AndroidRuntime(13041):     at rb.i.run(SourceFile:16)
[        ] E/AndroidRuntime(13041):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
[        ] E/AndroidRuntime(13041):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
[        ] E/AndroidRuntime(13041):     at java.lang.Thread.run(Thread.java:764)
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.27.1, on macOS 15.2 24C101 darwin-arm64, locale en-UZ)
    • Flutter version 3.27.1 on channel stable at /Users/lazizbekfayziev/developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 17025dd882 (4 weeks ago), 2024-12-17 03:23:09 +0900
    • Engine revision cb4b5fff73
    • Dart version 3.6.0
    • DevTools version 2.40.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/lazizbekfayziev/Library/Android/sdk
    • Platform android-35, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16C5032a
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] IntelliJ IDEA Ultimate Edition (version 2024.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 78.5.1
    • Dart plugin version 241.15845

[✓] VS Code (version 1.96.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.102.0

[✓] Connected device (4 available)
    • SM N960N (mobile)               • 47365048484e3498      • android-arm64  • Android 9 (API 28)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 15.2 24C101 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 15.2 24C101 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 131.0.6778.265
    ! Error: Browsing on the local area network for iPhone. Ensure the device is unlocked and attached with a cable or
      associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for Lazizbek. Ensure the device is unlocked and attached with a cable or
      associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by Lazizbek97** [comment]
after adding this 2. it worked
`minifyEnabled false
  shrinkResources false`
  
  but if there is any other ways to fix it, would be great

**Comment by darshankawar** [comment]
Based on the error log, it seems similar to https://github.com/flutter/flutter/issues/146266, so please follow-up in it for further updates. You may share your findings in it for better tracking.
Closing this as a duplicate.
