### ISSUE TITLE
`Mac_ios native_platform_view_ui_tests_ios` is failing on every run

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#109880]
```
[native_platform_view_ui_tests_ios] [STDOUT] stdout: /opt/s/w/ir/x/w/recipe_cleanup/tmpr2usjwxr/flutter sdk/dev/integration_tests/ios_platform_view_tests/ios/PlatformViewUITests/PlatformViewUITests.m:26:10: error: no visible @interface for 'XCTestCase' declares the selector 'setup'
[native_platform_view_ui_tests_ios] [STDOUT] stdout:   [super setup];
[native_platform_view_ui_tests_ios] [STDOUT] stdout:    ~~~~~ ^~~~~
[native_platform_view_ui_tests_ios] [STDOUT] stdout: 1 error generated.
```
Caused by https://github.com/flutter/flutter/pull/109720
cc @hellohuanlin
