### ISSUE TITLE
flutter run command fails on Xcode 9.2

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#15909]
The [regular expression](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/ios/simulators.dart#L447) used to parse the sdk major version doesn't work on Xcode 9.2 when run with a simulator.  The `sdkNameAndVersion` is returned as "com.apple.CoreSimulator.SimRuntime.iOS-11-3", which doesn't match anything.

stack trace.
```
Unhandled exception:
NoSuchMethodError: The method 'group' was called on null.
Receiver: null
Tried calling: group(1)
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      IOSSimulator.sdkMajorVersion (package:flutter_tools/src/ios/simulators.dart:449)
<asynchronous suspension>
#2      IOSSimulator.ensureLogsExists (package:flutter_tools/src/ios/simulators.dart:474)
```

**Comment by jonahwilliams** [comment]
Might be due to a change in the simulator and not necessarily the xcode version.  Older version gives me "iOS 11.2" for the sdkNameAndVersion

**Comment by jonahwilliams** [comment]
Fixed by #15918

**Comment by jonahwilliams** [comment]
Or it would be If I had submitted it

**Comment by RoraxHan** [comment]
I've met this error.
I can run on android emulator. but when I try to run on iphone simulator. I got the error like this.
Unhandled exception:
NoSuchMethodError: The method 'group' was called on null.
Receiver: null
Tried calling: group(1)
```
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      IOSSimulator.sdkMajorVersion (package:flutter_tools/src/ios/simulators.dart:448)
<asynchronous suspension>
#2      IOSSimulator.ensureLogsExists (package:flutter_tools/src/ios/simulators.dart:472)
<asynchronous suspension>
#3      _IOSSimulatorLogReader._start (package:flutter_tools/src/ios/simulators.dart:541)
<asynchronous suspension>
#4      _runGuarded (dart:async/stream_controller.dart:804)
#5      _BroadcastStreamController._subscribe (dart:async/broadcast_stream_controller.dart:217)
#6      _ControllerStream._createSubscription (dart:async/stream_controller.dart:817)
#7      _StreamImpl.listen (dart:async/stream_impl.dart:466)
#8      FlutterDevice.startEchoingDeviceLog (package:flutter_tools/src/resident_runner.dart:237)
#9      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:280)
```

How can I fix this?

**Comment by jonahwilliams** [comment]
@RoraxHan I'm rerunning the tests on the PR to fix this for master, I will submit it afterwards.  You would have to switch to the `master`.

**Comment by jonahwilliams** [comment]
The PR has been submitted, please update to master and let me know if you still have this issue
