### ISSUE TITLE
[webview] Build failure due to ThreadedInputConnectionProxyAdapterView filename issue

### ISSUE THREAD

**Issue by nshibu** [flutter/flutter#82803]
```
C:\flutter\.pub-cache\hosted\pub.dartlang.org\webview_flutter-2.0.6\android\src\main\java\io\flutter\plugins\webviewflutter\InputAwareWebView.java:31: error: cannot find symbol
  private ThreadedInputConnectionProxyAdapterView proxyAdapterView;
          ^
  symbol:   class ThreadedInputConnectionProxyAdapterView
  location: class InputAwareWebView
C:\flutter\.pub-cache\hosted\pub.dartlang.org\webview_flutter-2.0.6\android\src\main\java\io\flutter\plugins\webviewflutter\InputAwareWebView.java:112: error: cannot find symbol
        new ThreadedInputConnectionProxyAdapterView(
            ^
  symbol:   class ThreadedInputConnectionProxyAdapterView
  location: class InputAwareWebView
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':webview_flutter:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

```

**Comment by Pherne** [comment]
Could this be a solution? https://github.com/flutter/flutter/issues/82800

**Comment by darshankawar** [comment]
@nshibu 
What flutter version are you on ? It seems compiler can't find the methods listed in the error for `webview_flutter` plugin.
Can you provide `pubspec.yaml` ?

Or you can also try to run `flutter clean` or `flutter pub cache repair` and then `flutter run` to see if it helps.

**Comment by ivtimur** [comment]
I get the same problem

**Comment by nshibu** [comment]
> @nshibu
> What flutter version are you on ? It seems compiler can't find the methods listed in the error for `webview_flutter` plugin.
> Can you provide `pubspec.yaml` ?
> 
> Or you can also try to run `flutter clean` or `flutter pub cache repair` and then `flutter run` to see if it helps.



Flutter 2.0.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 1d9032c7e1 (3 weeks ago) • 2021-04-29 17:37:58 -0700
Engine • revision 05e680e202
Tools • Dart 2.12.3

**Comment by ivtimur** [comment]
I find error, like writed in this issue [82800](https://github.com/flutter/flutter/issues/82800)

**Comment by darshankawar** [comment]
@nshibu 
What command are you running to get this error ? Can you provide steps to replicate this ?

@ivtimur If you switch to 2.0.5, do you still get same issue or no ?

**Comment by ivtimur** [comment]
> @ivtimur If you switch to 2.0.5, do you still get same issue or no ?

I don't know, i just fix this problem and run my app )
You can try to repeat this problem, just install the version 2.0.6

**Comment by rahulquality** [comment]
I get Same issue and nothing working for me 

- [ ] .

Using  latest flutter and latest android studio 

All steps tried  but not able to resolve this even webview_flutter ^2.0.4  not working

**Comment by ivtimur** [comment]
> location: class InputAwareWebView
> D:\Flutter\flutter.pub-cache\hosted\pub.dartlang.org\webview_flutter-2.0.6\android\src\main\java\io\flutter\plugins\webviewflutter\InputAwareWebView.java:112: error: cannot find symbol
> new ThreadedInputConnectionProxyAdapterView(

Look, the error message says that you have version 2.0.6 installed

**Comment by nstrelow** [comment]
My app is working only with 2.0.4 (2.0.5 is not published).

Here is my app (subfolder study_designer), which fails with that error on the newer 2.0.6 release:

https://github.com/hpi-studyu/studyu/tree/dev/study_designer

**Comment by stuartmorgan** [comment]
I looked at the archive for 2.0.6, and the file has the right extension. I suspect this may be a Windows path length issue causing the filename to be truncated somehow.

**Comment by stuartmorgan** [comment]
@jonasfj Has anything changed about the way the zips are created recently? This file has existed for quite a while so I'm not sure why 2.0.6 would be behaving differently than 2.0.4.

**Comment by manpowre** [comment]
`Flutter 2.2.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b22742018b (5 days ago) • 2021-05-14 19:12:57 -0700
Engine • revision a9d88a4d18
Tools • Dart 2.13.0
`
> flutter clean
> flutter pub cache repair (this file gets changed from ThreadedInputConnectionProxyAdapterView.java to ThreadedInputConnectionProxyAdapterView.jav)
> flutter run

Windows 10 path:
E:\flutter\.pub-cache\hosted\pub.dartlang.org\webview_flutter-2.0.6\android\src\main\java\io\flutter\plugins\webviewflutter

`E:\flutter\.pub-cache\hosted\pub.dartlang.org\webview_flutter-2.0.6\android\src\main\java\io\flutter\plugins\webviewflutter\InputAwareWebView.java:31: error: cannot find symbol
  private ThreadedInputConnectionProxyAdapterView proxyAdapterView;
          ^
  symbol:   class ThreadedInputConnectionProxyAdapterView
  location: class InputAwareWebView
E:\flutter\.pub-cache\hosted\pub.dartlang.org\webview_flutter-2.0.6\android\src\main\java\io\flutter\plugins\webviewflutter\InputAwareWebView.java:112: error: cannot find symbol
        new ThreadedInputConnectionProxyAdapterView(
            ^
  symbol:   class ThreadedInputConnectionProxyAdapterView
  location: class InputAwareWebView
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':webview_flutter:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
`

offcourse I change the file ThreadedInputConnectionProxyAdapterView.jav to .java and it works:
flutter run (OK)

**Comment by stuartmorgan** [comment]
Just to be sure that the issue is with the archive, not a change in the unzipping process: can someone with this issue confirm that if you clear your pub cache and then build with the version pinned to 2.0.4 it does work?

**Comment by manpowre** [comment]
Pubspec.yaml: webview_flutter: 2.0.4
> flutter clean
> flutter pub cache repair 
> flutter run

works like a charm (deleter the 2.06 webview in E:\flutter\.pub-cache\hosted\pub.dartlang.org:

Pubspec.yaml: webview_flutter: 2.0.6
> flutter clean
> flutter pub cache repair 
> flutter run

this makes this file ThreadedInputConnectionProxyAdapterView.jav in E:\flutter\.pub-cache\hosted\pub.dartlang.org\webview_flutter-2.0.6\android\src\main\java\io\flutter\plugins\webviewflutter

**Comment by slightfoot** [comment]
@stuartmorgan This just hit me. Downloading the package from pub shows the filename incorrect.
https://storage.googleapis.com/pub-packages/packages/webview_flutter-2.0.6.tar.gz

I assume its a max-path packaging issue. For the moment would a simple class rename and package version push me a good temporary solution until the underlying issue can be resolved?

**Comment by manpowre** [comment]
> 
> 
> @stuartmorgan This just hit me. Downloading the package from pub shows the filename incorrect. (in the actual archive)
> https://storage.googleapis.com/pub-packages/packages/webview_flutter-2.0.6.tar.gz
> 
> I assume its a max-path packaging issue. For the moment would a simple, class rename and package version push, be a good temporary solution until the underlying issue can be resolved?

I have 2.0.4 and 2.0.6 installed in these paths:
> E:\flutter\.pub-cache\hosted\pub.dartlang.org\webview_flutter-2.0.6\android\src\main\java\io\flutter\plugins\webviewflutter\ThreadedInputConnectionProxyAdapterView.jav
> E:\flutter\.pub-cache\hosted\pub.dartlang.org\webview_flutter-2.0.4\android\src\main\java\io\flutter\plugins\webviewflutter\ThreadedInputConnectionProxyAdapterView.java

Wouldnt that be the same issue ?

**Comment by stuartmorgan** [comment]
This is strange. When I said "I looked at the archive for 2.0.6, and the file has the right extension" above, that was based on downloading the archive from pub.dev on my Mac and opening it. I just tried the same thing from my Windows 10 machine, and manually opening it, and it looks correct there too. So I tried making a test app that fetches and opens it via pub thinking it was something about how pub was decompressing it, but it's fine there too (i.e., the file has the right name in the pub cache directory); I can't reproduce this at all.

Maybe this is a CDN issue? @slightfoot what is the exact size of the 2.0.6 archive you download, and what is its MD5 checksum?
I'm seeing:
- 1192378 bytes
- `41965e9defa981ede28f85991ecfc2ea`

**Comment by flutterq** [comment]
[[Solved] Flutter Webview throws compiling error -ThreadedInputConnectionProxyAdapterView location: class InputAwareWebView](https://fluttercorner.com/flutter-webview-throws-compiling-error-threadedinputconnectionproxyadapterview/)

**Comment by stuartmorgan** [comment]
> For the moment would a simple, class rename and package version push, be a good temporary solution until the underlying issue can be resolved?

This file has existed with this name since 2019. Without understanding what the underlying issue *is*, I have no idea if that would actually help.

**Comment by jonasfj** [comment]
This is a problem with long file names... If I download: https://storage.googleapis.com/pub-packages/packages/webview_flutter-2.0.6.tar.gz

And then do:
```
powershell
mkdir extracted_files
cd extracted_files
../flutter\bin\cache\dart-sdk\lib\_internal\pub\asset\7zip\7za.exe x webview_flutter-2.0.6.tar

PS C:\Users\jonasfj\hack> ls .\android\src\main\java\io\flutter\plugins\webviewflutter\


    Directory: C:\Users\jonasfj\hack\android\src\main\java\io\flutter\plugins\webviewflutter


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        4/26/2021   8:42 PM           6816 DisplayListenerProxy.java
-a----        4/26/2021   8:42 PM           1778 FlutterCookieManager.java
-a----        4/26/2021   8:42 PM          15358 FlutterWebView.java
-a----        4/26/2021   8:42 PM          11425 FlutterWebViewClient.java
-a----        4/26/2021   8:42 PM           9407 InputAwareWebView.java
-a----        4/26/2021   8:42 PM           2130 JavaScriptChannel.java
-a----        4/26/2021   8:42 PM           3581 ThreadedInputConnectionProxyAdapterView.jav
-a----        4/26/2021   8:42 PM           1084 WebViewFactory.java
-a----        4/26/2021   8:42 PM           2700 WebViewFlutterPlugin.java
```

This is only a problem on windows, and it might be fixed in the next version as we're moving to use a Dart library for decode tar archives... So if the filename isn't so long that it can't be written by `dart:io`, then it should work fine.

**Comment by stuartmorgan** [comment]
2.0.7 fixes this. It is the same as 2.0.6 other than the version bump, but published from `stable` to avoid https://github.com/dart-lang/pub/issues/3001
