### ISSUE TITLE
NetworkImage will break when updating http package to 0.12

### ISSUE THREAD

**Issue by passsy** [flutter/flutter#11072]
I tried updating to a newer version of the `http` package (not yet released) which supports the new middleware feature to implement an http cache (#10820).

```yml
dependencies:
  flutter:
    sdk: flutter

dependency_overrides:
  http:
    git:
      url: https://github.com/dart-lang/http.git
      ref: 40ccf46720cd128794543e73078c2040de267285
```

```
[✓] Flutter (on Mac OS X 10.12.5 16F73, locale en-DE, channel alpha)
    • Framework revision d36e2f6191 (11 days ago), 2017-06-21 15:09:10 -0700
    • Engine revision b0dee695ec
    • Tools Dart version 1.24.0-dev.6.7
```

I noticed the `http` package has breaking changes breaking the compatibility with the current flutter sdk. Especially for `NetworkImage` and `ImageCache`.

```
══╡ EXCEPTION CAUGHT BY SERVICES ╞══════════════════════════════════════════════════════════════════
The following NoSuchMethodError was thrown resolving a single-frame image stream:
Class 'Response' has no instance getter 'bodyBytes'.
Receiver: Instance of 'Response'
Tried calling: bodyBytes
When the exception was thrown, this was the stack:
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      NetworkImage._loadAsync (package:flutter/src/services/image_provider.dart:435:38)
<asynchronous suspension>
#3      NetworkImage.load (package:flutter/src/services/image_provider.dart:417:7)
#4      ImageProvider.resolve.<anonymous closure>.<anonymous closure> (package:flutter/src/services/image_provider.dart:253:61)
#5      ImageCache.putIfAbsent (package:flutter/src/services/image_cache.dart:82:22)
#6      ImageProvider.resolve.<anonymous closure> (package:flutter/src/services/image_provider.dart:253:38)
```
<details>
<summary>
128 more
</summary>

```
#7      SynchronousFuture.then (package:flutter/src/foundation/synchronous_future.dart:38:29)
#8      ImageProvider.resolve (package:flutter/src/services/image_provider.dart:251:30)
#9      _ImageState._resolveImage (package:flutter/src/widgets/image.dart:286:33)
#10     _ImageState.didChangeDependencies (package:flutter/src/widgets/image.dart:267:5)
#11     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3507:12)
#12     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3366:5)
#13     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750:14)
#14     Element.updateChild (package:flutter/src/widgets/framework.dart:2553:12)
#15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3403:16)
#16     Element.rebuild (package:flutter/src/widgets/framework.dart:3292:5)
#17     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3371:5)
#18     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3366:5)
#19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750:14)
#20     Element.updateChild (package:flutter/src/widgets/framework.dart:2553:12)
#21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3403:16)
#22     Element.rebuild (package:flutter/src/widgets/framework.dart:3292:5)
#23     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3371:5)
#24     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3509:22)
#25     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3366:5)
#26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750:14)
#27     Element.updateChild (package:flutter/src/widgets/framework.dart:2553:12)
#28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3403:16)
#29     Element.rebuild (package:flutter/src/widgets/framework.dart:3292:5)
#30     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3371:5)
#31     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3366:5)
#32     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:3685:16)
#33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750:14)
#34     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4438:32)
#35     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750:14)
#36     Element.updateChild (package:flutter/src/widgets/framework.dart:2553:12)
#37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3403:16)
#38     Element.rebuild (package:flutter/src/widgets/framework.dart:3292:5)
#39     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3371:5)
#40     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3366:5)
#41     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750:14)
#42     Element.updateChild (package:flutter/src/widgets/framework.dart:2553:12)
#43     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3403:16)
#44     Element.rebuild (package:flutter/src/widgets/framework.dart:3292:5)
#45     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3371:5)
#46     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3509:22)
#47     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3366:5)
#48     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750:14)
#49     Element.updateChild (package:flutter/src/widgets/framework.dart:2553:12)
#50     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4333:14)
#51     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750:14)
#52     Element.updateChild (package:flutter/src/widgets/framework.dart:2553:12)
#53     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3403:16)
#54     Element.rebuild (package:flutter/src/widgets/framework.dart:3292:5)
#55     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3371:5)
#56     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3366:5)
#57     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750:14)
#58     Element.updateChild (package:flutter/src/widgets/framework.dart:2553:12)
#59     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4333:14)
#60     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750:14)
#61     Element.updateChild (package:flutter/src/widgets/framework.dart:2553:12)
#62     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3403:16)
#63     Element.rebuild (package:flutter/src/widgets/framework.dart:3292:5)
#64     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3371:5)
#65     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3509:22)
#66     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3366:5)
#67     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750:14)
#68     Element.updateChild (package:flutter/src/widgets/framework.dart:2553:12)
#69     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3403:16)
#70     Element.rebuild (package:flutter/src/widgets/framework.dart:3292:5)
#71     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3371:5)
#72     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3509:22)
#73     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3366:5)
#74     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750:14)
#75     Element.updateChild (package:flutter/src/widgets/framework.dart:2553:12)
#76     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4333:14)
#77     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750:14)
#78     Element.updateChild (package:flutter/src/widgets/framework.dart:2553:12)
#79     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3403:16)
#80     Element.rebuild (package:flutter/src/widgets/framework.dart:3292:5)
#81     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3371:5)
#82     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3366:5)
#83     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750:14)
#84     Element.updateChild (package:flutter/src/widgets/framework.dart:2553:12)
#85     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3403:16)
#86     Element.rebuild (package:flutter/src/widgets/framework.dart:3292:5)
#87     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3371:5)
#88     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3366:5)
#89     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750:14)
#90     Element.updateChild (package:flutter/src/widgets/framework.dart:2553:12)
#91     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4333:14)
#92     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750:14)
#93     Element.updateChild (package:flutter/src/widgets/framework.dart:2553:12)
#94     SliverMultiBoxAdaptorElement.performRebuild (package:flutter/src/widgets/sliver.dart:564:34)
#95     SliverMultiBoxAdaptorElement.update (package:flutter/src/widgets/sliver.dart:537:7)
#96     Element.updateChild (package:flutter/src/widgets/framework.dart:2542:15)
#97     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4066:32)
#98     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4448:17)
#99     _ViewportElement.update (package:flutter/src/widgets/viewport.dart:150:17)
#100    Element.updateChild (package:flutter/src/widgets/framework.dart:2542:15)
#101    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3403:16)
#102    Element.rebuild (package:flutter/src/widgets/framework.dart:3292:5)
#103    ProxyElement.update (package:flutter/src/widgets/framework.dart:3639:5)
#104    Element.updateChild (package:flutter/src/widgets/framework.dart:2542:15)
#105    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4340:14)
#106    Element.updateChild (package:flutter/src/widgets/framework.dart:2542:15)
#107    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4340:14)
#108    Element.updateChild (package:flutter/src/widgets/framework.dart:2542:15)
#109    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4340:14)
#110    Element.updateChild (package:flutter/src/widgets/framework.dart:2542:15)
#111    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3403:16)
#112    Element.rebuild (package:flutter/src/widgets/framework.dart:3292:5)
#113    StatefulElement.update (package:flutter/src/widgets/framework.dart:3528:5)
#114    Element.updateChild (package:flutter/src/widgets/framework.dart:2542:15)
#115    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3403:16)
#116    Element.rebuild (package:flutter/src/widgets/framework.dart:3292:5)
#117    StatefulElement.update (package:flutter/src/widgets/framework.dart:3528:5)
#118    Element.updateChild (package:flutter/src/widgets/framework.dart:2542:15)
#119    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3403:16)
#120    Element.rebuild (package:flutter/src/widgets/framework.dart:3292:5)
#121    ProxyElement.update (package:flutter/src/widgets/framework.dart:3639:5)
#122    Element.updateChild (package:flutter/src/widgets/framework.dart:2542:15)
#123    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3403:16)
#124    Element.rebuild (package:flutter/src/widgets/framework.dart:3292:5)
#125    StatelessElement.update (package:flutter/src/widgets/framework.dart:3453:5)
#126    Element.updateChild (package:flutter/src/widgets/framework.dart:2542:15)
#127    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3403:16)
#128    Element.rebuild (package:flutter/src/widgets/framework.dart:3292:5)
#129    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2142:33)
#130    BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:503:20)
#131    BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:189:5)
#132    BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:688:15)
#133    BindingBase&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:636:9)
#134    _drawFrame (file:///b/build/slave/Mac_Engine/build/src/flutter/lib/ui/hooks.dart:70)
```

</details>

---

**Comment by Hixie** [comment]
Hm, having declared API stability for Flutter is going to be difficult to stick to if our dependencies themselves change their APIs...

cc @eseidel @nex3

**Comment by nex3** [comment]
It's important for us to be able to continue improving packages' APIs. Pub's version solver should help ensure that this doesn't cause too much pain for users.

@passsy It's generally going to be risky to use an unreleased version of a package, especially when other packages depend on it, and *especially* when that version includes breaking changes. It's cool that you want to try out new stuff, but it may be a little early for that with `http`.

**Comment by Hixie** [comment]
A package Flutter depends on is basically equivalent to a package in the dart: namespace, because people need to be able to upgrade the version of the SDK they use without breaking their code. Since Flutter depends on the http package, that puts it in the "can't break API" category (or rather, puts it in the category of "all Flutter apps must use the version the Flutter SDK uses", which can only be versions that are compatible with the version it was using when we declared our intent to keep the API stable).

It's fine if the http package isn't one we can depend on in this way; in that case we will need to find another package that we can use instead (maybe dart:io directly? I'm not sure why we don't use dart:io directly currently; maybe @abarth remembers?).

**Comment by abarth** [comment]
We could use `dart:io` directly.  There are a number of benefits to using the http package (e.g., the ability to replace the client), but they might not be worth the API stability costs.

**Comment by nex3** [comment]
@Hixie If you require that no packages that the SDK uses ever change, maybe depending on packages from the SDK isn't the right way to go. The whole point of a package ecosystem is to make it possible to (safely) make changes over time.

**Comment by Hixie** [comment]
Yeah, we want to minimize our dependencies for this reason (among others).

**Comment by sethladd** [comment]
Friendly ping. Is this still an issue?

**Comment by sethladd** [comment]
I'm going to close as this is pretty old, but if this is still an issue, please reopen.
