### ISSUE TITLE
If you give TextField a TextStyle with only the color set, badness ensues

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#12832]
```
[00052.874] 03959.03982>  EXCEPTION CAUGHT BY WIDGETS LIBRARY 
[00052.881] 03959.03982> The following NoSuchMethodError was thrown building InputDecorator(decoration: InputDecoration(),
[00052.881] 03959.03982> baseStyle: TextStyle(inherit: true, color: Color(0xffffffff)), isFocused: false, isEmpty: true,
[00052.881] 03959.03982> dirty):
[00052.881] 03959.03982> The method '*' was called on null.
[00052.881] 03959.03982> Receiver: null
[00052.881] 03959.03982> Tried calling: *(1.0)
[00052.886] 03959.03982> 
[00052.886] 03959.03982> When the exception was thrown, this was the stack:
[00052.890] 03959.03982> #0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
[00052.890] 03959.03982> #1      InputDecorator.build (package:flutter/src/material/input_decorator.dart:483)
[00052.890] 03959.03982> #2      StatelessElement.build (package:flutter/src/widgets/framework.dart:3627)
[00052.890] 03959.03982> #3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3572)
[00052.890] 03959.03982> #4      Element.rebuild (package:flutter/src/widgets/framework.dart:3473)
```

**Comment by apwilson** [comment]
@Hixie 
@yjbanov

**Comment by apwilson** [comment]
The bug exhibits itself in the wifi_settings app here: https://fuchsia-review.googlesource.com/c/sysui/+/81695  when you tap on a secure network.  I'll try to get a reduced use case at some point.

**Comment by apwilson** [comment]
I discovered if I actually set the font size of the textstyle I gave my text field the issue goes away.

**Comment by yjbanov** [comment]
This might be a potential regression introduced by https://github.com/flutter/flutter/commit/80b820a26d78a0c8d0e3c8ddf7dbb996c9a1548b#diff-0a8c1f8d767d0b3fcfa44f0263486dc3R453.

Related issue: https://github.com/flutter/flutter/issues/12681. I added `InputDecorator` to the list of classes to revise. **tl;dr** currently some widgets that take custom `TextStyle` do not fill in missing properties before they attempt to use them. They assume that your text style is complete (usually you would get a text style from `Theme.of` and patch it using `copyWith` or `merge`).

**Comment by patelkrunal78** [comment]
Maybe This Can Help You [Here](https://icetutor.com/question/flutter-how-to-change-textfield-hint-color)
