### PR TITLE
Relands "Starts using the --source flag to compile the dart registrant. (#98046)"

### LINKED ISSUE #91841: Multiple entry-points in same Dart file is broken
### Steps to reproduce

Create the following Dart program:

```dart
import 'package:flutter/widgets.dart';

@pragma('vm:entry-point')
void main() {
  runApp(ColoredBox(color: Color(0xffcc0000)));
}

@pragma('vm:entry-point')
void entryPoint() {
  runApp(ColoredBox(color: Color(0xff00cc00)));
}
```

... then override `getDartEntrypointFunctionName` in the Android `MainActivity`, like so:

```kotlin
import io.flutter.embedding.android.FlutterActivity

class MainActivity: FlutterActivity() {
  override fun getDartEntrypointFunctionName(): String {
    return "entryPoint"
  }
}
```

... then run the app on an Android device.

### Expected behavior

You expect `entryPoint()` to be run as the program's entry-point, yielding a green screen.

### Actual behavior

The app fails to start, with the following error:

```
E/flutter (16188): [ERROR:flutter/shell/common/shell.cc(103)] Dart Unhandled Exception: NoSuchMethodError: No top-level getter 'entryPoint' declared.
E/flutter (16188): Receiver: top-level
E/flutter (16188): Tried calling: entryPoint, stack trace: #0      NoSuchMethodError._throwNew (dart:core-patch/errors_patch.dart:214:5)
E/flutter (16188): 
E/flutter (16188): [ERROR:flutter/runtime/dart_isolate.cc(727)] Could not resolve main entrypoint function.
E/flutter (16188): [ERROR:flutter/runtime/dart_isolate.cc(195)] Could not run the run main Dart entrypoint.
E/flutter (16188): [ERROR:flutter/runtime/runtime_controller.cc(415)] Could not create root isolate.
E/flutter (16188): [ERROR:flutter/shell/common/shell.cc(588)] Could not launch engine with configuration.
```

## Notes

This scenario has been created in https://github.com/tvolkert/entrypoint

## Culprit

This appears to have been introduced by https://github.com/flutter/flutter/pull/79669

### LINKED ISSUE #98591: Dart plugin registration doesn't run in background isolates
As we've been adopting in-package platform channels in more 1P plugins, which requires Dart plugin registration, we've hit an edge case related to isolates. While plugins don't generally work out of the box in isolates, there are [workarounds](https://pub.dev/packages/flutter_isolate) which, IIUC, run the native plugin registration code in a separate engine instance so that the native side is there. These systems don't know about the new *Dart* plugin registration though, so half of the registration code is missing, and we end up with mismatches like #98473.

@gaaclarke @blasten (since you've both looked at the engine/VM integration part of the Dart plugin registration) is there a way we can automatically run the generated Dart registration in each new isolate, rather than just the primary isolate? Alternately, could we adjust the generated registration such that it provides a referenceable function that things like `flutter_isolate` could call during their isolate setup (similar to the need to call `WidgetsFlutterBinding.ensureInitialized()`)?

### PR DESCRIPTION
**Pull request by gaaclarke**
This lands the original PR in the first commit.  The subsequent commits do the fix to reland this.  What's different now is that we have a file in the framework that will be compiled to point to the location of the dart plugin registrant.  That is loaded and executed in the engine.

This allows us to directly look for the dart plugin registrant instead of hunting for it, thus eliminating the cost of the linear search which caused this to be reverted in the first place.

Engine PR: https://github.com/flutter/engine/pull/32189
Relands: https://github.com/flutter/flutter/pull/98046
The revert: https://github.com/flutter/flutter/pull/100493
Fixes: https://github.com/flutter/flutter/issues/98591
Fixes: https://github.com/flutter/flutter/issues/91841

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by skia-gold** [comment]
Gold has detected about 1 new digest(s) on patchset 2.
View them at https://flutter-gold.skia.org/cl/github/100572

File: packages/flutter_tools/test/general.shard/compile_batch_test.dart [hunk 1]
```diff
@@ -395,7 +395,12 @@ void main() {
           '--no-link-platform',
           '--packages',
           '.packages',
-          '.dart_tools/flutter_build/generated_main.dart',
+          '--source',
+          '.dart_tools/flutter_build/dart_plugin_registrant.dart',
+          '--source',
+          'package:flutter/src/dart_plugin_registrant.dart',
```
Comment (blasten) [inline packages/flutter_tools/test/general.shard/compile_batch_test.dart:401]: is `.dart_tools/flutter_build/dart_plugin_registrant.dart` content different than `package:flutter/src/dart_plugin_registrant.dart`? If different, is it possible to assign a different name?

Comment (gaaclarke) [reply packages/flutter_tools/test/general.shard/compile_batch_test.dart:401]: Yep, the contents are different.  `.dart_tools/flutter_build/dart_plugin_registrant.dart` is where the generated code is.  `package:flutter/src/dart_plugin_registrant.dart` points to where the generated code is.

We could change the name of `.dart_tools/flutter_build/dart_plugin_registrant.dart` easily.  Changing `package:flutter/src/dart_plugin_registrant.dart` would require a change in the engine since that is where it is looking for it.

Comment (blasten) [reply packages/flutter_tools/test/general.shard/compile_batch_test.dart:401]: ok. sg

**Review by blasten — APPROVED** [review]
