### ISSUE TITLE
`flutter test` fails on latest engine (https://github.com/flutter/flutter/pull/15847)

### ISSUE THREAD

**Issue by aam** [flutter/flutter#15849]
```
00:20 +96 ~1 -1: loading C:\projects\flutter sdk\packages\flutter\test\cupertino\scaffold_test.dart
00:21 +96 ~1 -1: C:\projects\flutter sdk\packages\flutter\test\cupertino\refresh_test.dart: UI tests - doesn't invoke anything without user interaction [E]
  NoSuchMethodError: The method '_setExpected' was called on null.
  Receiver: null
  Tried calling: _setExpected(Closure: (Invocation) => dynamic)
  dart:core                             Object.noSuchMethod
  package:mockito/src/mock.dart 318:15  PostExpectation._completeWhen
  package:mockito/src/mock.dart 304:12  PostExpectation.thenReturn
  cupertino\refresh_test.dart 27:30     main.<fn>
  
  'package:flutter_test/src/binding.dart': Failed assertion: line 519 pos 12: 'inTest': is not true.
  dart:core                                     _AssertionError._throwNew
  package:flutter_test/src/binding.dart         TestWidgetsFlutterBinding.postTest
  package:flutter_test/src/binding.dart 680:11  AutomatedTestWidgetsFlutterBinding.postTest
 ```

**Comment by aam** [comment]
This is due to NSM changes. Introduced in 95e9e890a996b9a61ade6cc81830dd7cf295ec9d (https://dart-review.googlesource.com/47621), but still not fixed in af1436931b93e755d38223c487d33a0a1f5eadf5 (https://dart-review.googlesource.com/48023)

@sjindel-google @alexmarkov

**Comment by alexmarkov** [comment]
I didn't see this error when I was running flutter tests today.
aam@, can you reproduce this on Linux? Could you please extract a small sample to reproduce the problem outside of Flutter?

**Comment by aam** [comment]
@alexmarkov wrote
> can you reproduce this on Linux?

Yes, it fails on all platforms: https://travis-ci.org/flutter/flutter/jobs/357231119

**Comment by aam** [comment]
> Could you please extract a small sample to reproduce the problem outside of Flutter?

Hope this helps, https://gist.github.com/aam/133fdc9ffb4a077006b0e688dabd7e17

**Comment by alexmarkov** [comment]
It turns out the failing test was added a couple of days ago (https://github.com/flutter/flutter/commit/feadfd2e40c9214e4886fec1c73ae58f5511b271) and I didn't have that test when I was running Flutter tests.

Maybe, as a workaround, we should fix the test and proceed.

**Comment by srawlins** [comment]
I'm working on a fix. This is a very clever test playing at the edge of Dart 1 semantics 😁 . Mocking method tear-offs is not supported in Dart 2 (https://github.com/dart-lang/mockito/issues/107) so this must be changed.
