### ISSUE TITLE
`podhelper.rb` uses deprecated, recently-removed `exists?` method

### ISSUE THREAD

**Issue by jack7758258** [flutter/flutter#109385]
Automatically signing iOS for device deployment using specified development team
in Xcode project: 89B89GC38P
Running pod install...                                             324ms
CocoaPods' output:
↳

    [!] Invalid `Podfile` file: undefined method `exists?' for File:Class

      return [] unless File.exists? file_path
                           ^^^^^^^^
    Did you mean?  exist?.

     #  from /Users/project/new1/ios/Podfile:38
     #  -------------------------------------------
     #    use_modular_headers!
     >    flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
     #  end
     #  -------------------------------------------

**Comment by stuartmorgan** [comment]
Looks like `exists?` was removed in https://github.com/ruby/ruby/commit/bf97415c02b11a8949f715431aca9eeb6311add2 so the script won't work with very recent versions of Ruby.

/cc @jmagman

**Comment by christopherfujino** [comment]
oh dear

**Comment by jmagman** [comment]
Looks like it was removed in Ruby 3.2, which is still in preview.  Ruby 3.1.2 was the last released version.

**Comment by jmagman** [comment]
@jack7758258 
1. What's the output of `$ ruby -v`
2. If you open path/to/flutter-sdk/packages/flutter_tools/bin/podhelper.rb and change this line:
```diff
- return [] unless File.exists? file_path
+ return [] unless File.exists file_path
```
does the flutter command succeed on your iOS project?

**Comment by jack7758258** [comment]
Error resolved by switching to Ruby3.1.2

**Comment by jmagman** [comment]
> Error resolved by switching to Ruby3.1.2

Can you switch back and validate that the diff works on 3.2?

**Comment by jmagman** [comment]
@jack7758258 alternatively, the fix https://github.com/flutter/flutter/pull/109428 has merged into master.  Can you switch back to Ruby 3.2 preview, check out the [Flutter master channel](https://github.com/flutter/flutter/wiki/Flutter-build-release-channels#how-to-change-channels) and validate that you are able to build your iOS app?  Your validation of the fix would be really helpful!
