### ISSUE TITLE
Multiple commands produce '..Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/Reachability.framework'

### ISSUE THREAD

**Issue by wilburt** [flutter/flutter#43353]
## Steps to Reproduce

-  Add pod 'PusherSwift', '~> 7.1' to **Podile**
- `Flutter build ios --release` completes successfully
- **Xcode -> Product** -> **Run** completes successfully
- **Xcode -> Product** -> **Archive** fails

**Target Platform:** iOS

## Logs

```
 Multiple commands produce '/Users/wilburt/Library/Developer/Xcode/DerivedData/Runner-gpxjtudcfadmwxdlfhcdzelvdgmg/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/Reachability.framework':
1) Target 'Reachability' has create directory command with output '/Users/wilburt/Library/Developer/Xcode/DerivedData/Runner-gpxjtudcfadmwxdlfhcdzelvdgmg/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/Reachability.framework'
2) Target 'ReachabilitySwift' has create directory command with output '/Users/wilburt/Library/Developer/Xcode/DerivedData/Runner-gpxjtudcfadmwxdlfhcdzelvdgmg/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/Reachability.framework'

```

```
Analyzing wilburt_proj...
No issues found! (ran in 4.2s)
```

```
[✓] Flutter (Channel dev, v1.10.14, on Mac OS X 10.14.6 18G103, locale en-GB)
    • Flutter version 1.10.14 at /Users/wilburt/Dev/Flutter/sdk/flutter
    • Framework revision 1946fc4da0 (2 weeks ago), 2019-10-07 15:23:31 -0700
    • Engine revision 1d62160fdb
    • Dart version 2.6.0 (build 2.6.0-dev.1.0 d6c6d12ebf)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at /Users/wilburt/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • ANDROID_HOME = /Users/wilburt/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.7.2

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (2 available)
    • SM J730F      • 192.168.1.71:5555                    • android-arm • Android 9 (API 28)
    • iPhone 11 Pro • D2C80111-1121-4A6F-BCA4-3AC09B3006D5 • ios         • com.apple.CoreSimulator.SimRuntime.iOS-13-1 (simulator)

• No issues found!
```

**Comment by wilburt** [comment]
I found that the issue was that I was using two packages that depend on two separate pods of Reachability. The first package, [flutter_keyboard_visibility](https://github.com/adee42/flutter_keyboard_visibility) depends on [Reachability](https://github.com/tonymillion/Reachability) while the other package, [pusher-websocket-swift](https://github.com/pusher/pusher-websocket-swift) depends on [Reachability.swift](https://github.com/ashleymills/Reachability.swift).

Both pods of Reachability compiles to **Reachability** and there was a conflict. Luckily, I found a [forked version of flutter_keyboard_visibility](https://github.com/MisterJimson/flutter_keyboard_visibility) that doesn't depend on Reachability. 

So that fixed it.

**Comment by alessandrobelli** [comment]
I have the exact same error, I included the version you linked, but when I try to run` flutter build ios `I get:
```
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    In file included from
    /Users/belli/development/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-3.1.0/ios/Classes/FluttertoastPlugin.m:2:
    /Users/belli/development/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-3.1.0/ios/Classes/UIView+Toast.h:328:19:
    warning: empty paragraph passed to '@param' command [-Wdocumentation]
     @param sharedStyle
     ~~~~~~~~~~~~~~~~~^
    /Users/belli/development/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-3.1.0/ios/Classes/UIView+Toast.h:343:25:
    warning: empty paragraph passed to '@param' command [-Wdocumentation]
     @param allowTapToDismiss
     ~~~~~~~~~~~~~~~~~~~~~~~^
    /Users/belli/development/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-3.1.0/ios/Classes/UIView+Toast.h:343:9: warning:
    parameter 'allowTapToDismiss' not found in the function declaration [-Wdocumentation]
     @param allowTapToDismiss
            ^~~~~~~~~~~~~~~~~
    /Users/belli/development/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-3.1.0/ios/Classes/UIView+Toast.h:343:9: note:
    did you mean 'tapToDismissEnabled'?
     @param allowTapToDismiss
            ^~~~~~~~~~~~~~~~~
            tapToDismissEnabled
    /Users/belli/development/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-3.1.0/ios/Classes/UIView+Toast.h:362:20:
    warning: empty paragraph passed to '@param' command [-Wdocumentation]
     @param queueEnabled
     ~~~~~~~~~~~~~~~~~~^
    /Users/belli/development/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-3.1.0/ios/Classes/FluttertoastPlugin.m:19:23:
    warning: unused variable 'viewController' [-Wunused-variable]
        UIViewController *viewController =
                          ^
    /Users/belli/development/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-3.1.0/ios/Classes/FluttertoastPlugin.m:70:21:
    warning: unused variable 'topPadding' [-Wunused-variable]
                CGFloat topPadding = window.safeAreaInsets.top;
                        ^
    /Users/belli/development/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-3.1.0/ios/Classes/FluttertoastPlugin.m:71:21:
    warning: unused variable 'bottomPadding' [-Wunused-variable]
                CGFloat bottomPadding = window.safeAreaInsets.bottom;
                        ^
    /Users/belli/development/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-3.1.0/ios/Classes/FluttertoastPlugin.m:48:19:
    warning: unused variable 'size' [-Wunused-variable]
            NSNumber *size = call.arguments[@"size"];
                      ^
    8 warnings generated.
    In file included from
    /Users/belli/development/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-3.1.0/ios/Classes/FluttertoastPlugin.m:2:
    /Users/belli/development/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-3.1.0/ios/Classes/UIView+Toast.h:328:19:
    warning: empty paragraph passed to '@param' command [-Wdocumentation]
     @param sharedStyle
     ~~~~~~~~~~~~~~~~~^
    /Users/belli/development/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-3.1.0/ios/Classes/UIView+Toast.h:343:25:
    warning: empty paragraph passed to '@param' command [-Wdocumentation]
     @param allowTapToDismiss
     ~~~~~~~~~~~~~~~~~~~~~~~^
    /Users/belli/development/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-3.1.0/ios/Classes/UIView+Toast.h:343:9: warning:
    parameter 'allowTapToDismiss' not found in the function declaration [-Wdocumentation]
     @param allowTapToDismiss
            ^~~~~~~~~~~~~~~~~
    /Users/belli/development/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-3.1.0/ios/Classes/UIView+Toast.h:343:9: note:
    did you mean 'tapToDismissEnabled'?
     @param allowTapToDismiss
            ^~~~~~~~~~~~~~~~~
            tapToDismissEnabled
    /Users/belli/development/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-3.1.0/ios/Classes/UIView+Toast.h:362:20:
    warning: empty paragraph passed to '@param' command [-Wdocumentation]
     @param queueEnabled
     ~~~~~~~~~~~~~~~~~~^
    /Users/belli/development/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-3.1.0/ios/Classes/FluttertoastPlugin.m:19:23:
    warning: unused variable 'viewController' [-Wunused-variable]
        UIViewController *viewController =
                          ^
    /Users/belli/development/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-3.1.0/ios/Classes/FluttertoastPlugin.m:70:21:
    warning: unused variable 'topPadding' [-Wunused-variable]
                CGFloat topPadding = window.safeAreaInsets.top;
                        ^
    /Users/belli/development/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-3.1.0/ios/Classes/FluttertoastPlugin.m:71:21:
    warning: unused variable 'bottomPadding' [-Wunused-variable]
                CGFloat bottomPadding = window.safeAreaInsets.bottom;
                        ^
    /Users/belli/development/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-3.1.0/ios/Classes/FluttertoastPlugin.m:48:19:
    warning: unused variable 'size' [-Wunused-variable]
            NSNumber *size = call.arguments[@"size"];
                      ^
    8 warnings generated.
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Release ===
    Building AOT snapshot in release mode (ios-release)...          
    Building App.framework for arm64...

    Building App.framework for armv7...
    Building AOT snapshot in release mode (ios-release)...             50,5s
    Built to build/aot/.
    warning: parsing line table prologue at offset 0x6f697463 found unsupported version 0x00
    warning: line table parameters mismatch. Cannot emit.
    note: while processing /Users/belli/code/metag/build/aot/armv7/snapshot_assembly.o
    Project /Users/belli/code/metag built and packaged successfully.
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Release ===
    duplicate symbol '_OBJC_CLASS_$_FLTKeyboardVisibilityPlugin' in:
        /Users/belli/code/metag/build/ios/Release-iphoneos/flutter_keyboard_visibility/libflutter_keyboard_visibility.a(KeyboardVisib
        ilityPlugin.o)
        /Users/belli/code/metag/build/ios/Release-iphoneos/keyboard_visibility/libkeyboard_visibility.a(KeyboardVisibilityPlugin.o)
    duplicate symbol '_OBJC_METACLASS_$_FLTKeyboardVisibilityPlugin' in:
        /Users/belli/code/metag/build/ios/Release-iphoneos/flutter_keyboard_visibility/libflutter_keyboard_visibility.a(KeyboardVisib
        ilityPlugin.o)
        /Users/belli/code/metag/build/ios/Release-iphoneos/keyboard_visibility/libkeyboard_visibility.a(KeyboardVisibilityPlugin.o)
    duplicate symbol '_OBJC_IVAR_$_FLTKeyboardVisibilityPlugin._flutterEventSink' in:
        /Users/belli/code/metag/build/ios/Release-iphoneos/flutter_keyboard_visibility/libflutter_keyboard_visibility.a(KeyboardVisib
        ilityPlugin.o)
        /Users/belli/code/metag/build/ios/Release-iphoneos/keyboard_visibility/libkeyboard_visibility.a(KeyboardVisibilityPlugin.o)
    duplicate symbol '_OBJC_IVAR_$_FLTKeyboardVisibilityPlugin._flutterEventListening' in:
        /Users/belli/code/metag/build/ios/Release-iphoneos/flutter_keyboard_visibility/libflutter_keyboard_visibility.a(KeyboardVisib
        ilityPlugin.o)
        /Users/belli/code/metag/build/ios/Release-iphoneos/keyboard_visibility/libkeyboard_visibility.a(KeyboardVisibilityPlugin.o)
    duplicate symbol '_OBJC_IVAR_$_FLTKeyboardVisibilityPlugin._isVisible' in:
        /Users/belli/code/metag/build/ios/Release-iphoneos/flutter_keyboard_visibility/libflutter_keyboard_visibility.a(KeyboardVisib
        ilityPlugin.o)
        /Users/belli/code/metag/build/ios/Release-iphoneos/keyboard_visibility/libkeyboard_visibility.a(KeyboardVisibilityPlugin.o)
    ld: 5 duplicate symbols for architecture armv7
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    duplicate symbol '_OBJC_CLASS_$_FLTKeyboardVisibilityPlugin' in:
        /Users/belli/code/metag/build/ios/Release-iphoneos/flutter_keyboard_visibility/libflutter_keyboard_visibility.a(KeyboardVisib
        ilityPlugin.o)
        /Users/belli/code/metag/build/ios/Release-iphoneos/keyboard_visibility/libkeyboard_visibility.a(KeyboardVisibilityPlugin.o)
    duplicate symbol '_OBJC_METACLASS_$_FLTKeyboardVisibilityPlugin' in:
        /Users/belli/code/metag/build/ios/Release-iphoneos/flutter_keyboard_visibility/libflutter_keyboard_visibility.a(KeyboardVisib
        ilityPlugin.o)
        /Users/belli/code/metag/build/ios/Release-iphoneos/keyboard_visibility/libkeyboard_visibility.a(KeyboardVisibilityPlugin.o)
    duplicate symbol '_OBJC_IVAR_$_FLTKeyboardVisibilityPlugin._flutterEventSink' in:
        /Users/belli/code/metag/build/ios/Release-iphoneos/flutter_keyboard_visibility/libflutter_keyboard_visibility.a(KeyboardVisib
        ilityPlugin.o)
        /Users/belli/code/metag/build/ios/Release-iphoneos/keyboard_visibility/libkeyboard_visibility.a(KeyboardVisibilityPlugin.o)
    duplicate symbol '_OBJC_IVAR_$_FLTKeyboardVisibilityPlugin._flutterEventListening' in:
        /Users/belli/code/metag/build/ios/Release-iphoneos/flutter_keyboard_visibility/libflutter_keyboard_visibility.a(KeyboardVisib
        ilityPlugin.o)
        /Users/belli/code/metag/build/ios/Release-iphoneos/keyboard_visibility/libkeyboard_visibility.a(KeyboardVisibilityPlugin.o)
    duplicate symbol '_OBJC_IVAR_$_FLTKeyboardVisibilityPlugin._isVisible' in:
        /Users/belli/code/metag/build/ios/Release-iphoneos/flutter_keyboard_visibility/libflutter_keyboard_visibility.a(KeyboardVisib
        ilityPlugin.o)
        /Users/belli/code/metag/build/ios/Release-iphoneos/keyboard_visibility/libkeyboard_visibility.a(KeyboardVisibilityPlugin.o)
    ld: 5 duplicate symbols for architecture arm64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
This doesn't happen if I include it.

**Comment by wilburt** [comment]
@alessandrobelli 
Please take the following steps:

- run `flutter clean`
- Delete **Pods** folder and **Podfile.lock** in $PROJECT/ios
-  run `cd ios && pod install`
-  run `flutter build ios`

Please, let me know if this helped.

**Comment by alessandrobelli** [comment]
Same error, I think.
But I noticed from `pod install` that I install also the 5.0 version. Is that the problem? Is there a way to know which package does that?

![image](https://user-images.githubusercontent.com/3796324/67557831-1da1e080-f716-11e9-98da-d229054d5688.png)

```
  ** BUILD FAILED **


Xcode's output:
↳
    In file included from
    /Users/belli/development/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-3.1.0/ios/Classes/FluttertoastPlugin.m:2:
    /Users/belli/development/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-3.1.0/ios/Classes/UIView+Toast.h:328:19:
    warning: empty paragraph passed to '@param' command [-Wdocumentation]
     @param sharedStyle
     ~~~~~~~~~~~~~~~~~^
    /Users/belli/development/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-3.1.0/ios/Classes/UIView+Toast.h:343:25:
    warning: empty paragraph passed to '@param' command [-Wdocumentation]
     @param allowTapToDismiss
     ~~~~~~~~~~~~~~~~~~~~~~~^
    /Users/belli/development/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-3.1.0/ios/Classes/UIView+Toast.h:343:9: warning:
    parameter 'allowTapToDismiss' not found in the function declaration [-Wdocumentation]
     @param allowTapToDismiss
            ^~~~~~~~~~~~~~~~~
    /Users/belli/development/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-3.1.0/ios/Classes/UIView+Toast.h:343:9: note:
    did you mean 'tapToDismissEnabled'?
     @param allowTapToDismiss
            ^~~~~~~~~~~~~~~~~
            tapToDismissEnabled
    /Users/belli/development/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-3.1.0/ios/Classes/UIView+Toast.h:362:20:
    warning: empty paragraph passed to '@param' command [-Wdocumentation]
     @param queueEnabled
     ~~~~~~~~~~~~~~~~~~^
    /Users/belli/development/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-3.1.0/ios/Classes/FluttertoastPlugin.m:19:23:
    warning: unused variable 'viewController' [-Wunused-variable]
        UIViewController *viewController =
                          ^
    /Users/belli/development/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-3.1.0/ios/Classes/FluttertoastPlugin.m:70:21:
    warning: unused variable 'topPadding' [-Wunused-variable]
                CGFloat topPadding = window.safeAreaInsets.top;
                        ^
    /Users/belli/development/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-3.1.0/ios/Classes/FluttertoastPlugin.m:71:21:
    warning: unused variable 'bottomPadding' [-Wunused-variable]
                CGFloat bottomPadding = window.safeAreaInsets.bottom;
                        ^
    /Users/belli/development/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-3.1.0/ios/Classes/FluttertoastPlugin.m:48:19:
    warning: unused variable 'size' [-Wunused-variable]
            NSNumber *size = call.arguments[@"size"];
                      ^
    8 warnings generated.
    In file included from
    /Users/belli/development/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-3.1.0/ios/Classes/UIView+Toast.m:26:
    /Users/belli/development/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-3.1.0/ios/Classes/UIView+Toast.h:328:19:
    warning: empty paragraph passed to '@param' command [-Wdocumentation]
     @param sharedStyle
     ~~~~~~~~~~~~~~~~~^
    /Users/belli/development/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-3.1.0/ios/Classes/UIView+Toast.h:343:25:
    warning: empty paragraph passed to '@param' command [-Wdocumentation]
     @param allowTapToDismiss
     ~~~~~~~~~~~~~~~~~~~~~~~^
    /Users/belli/development/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-3.1.0/ios/Classes/UIView+Toast.h:343:9: warning:
    parameter 'allowTapToDismiss' not found in the function declaration [-Wdocumentation]
     @param allowTapToDismiss
            ^~~~~~~~~~~~~~~~~
    /Users/belli/development/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-3.1.0/ios/Classes/UIView+Toast.h:343:9: note:
    did you mean 'tapToDismissEnabled'?
     @param allowTapToDismiss
            ^~~~~~~~~~~~~~~~~
            tapToDismissEnabled
    /Users/belli/development/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-3.1.0/ios/Classes/UIView+Toast.h:362:20:
    warning: empty paragraph passed to '@param' command [-Wdocumentation]
     @param queueEnabled
     ~~~~~~~~~~~~~~~~~~^
    4 warnings generated.
    In file included from
    /Users/belli/development/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-3.1.0/ios/Classes/FluttertoastPlugin.m:2:
    /Users/belli/development/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-3.1.0/ios/Classes/UIView+Toast.h:328:19:
    warning: empty paragraph passed to '@param' command [-Wdocumentation]
     @param sharedStyle
     ~~~~~~~~~~~~~~~~~^
    /Users/belli/development/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-3.1.0/ios/Classes/UIView+Toast.h:343:25:
    warning: empty paragraph passed to '@param' command [-Wdocumentation]
     @param allowTapToDismiss
     ~~~~~~~~~~~~~~~~~~~~~~~^
    /Users/belli/development/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-3.1.0/ios/Classes/UIView+Toast.h:343:9: warning:
    parameter 'allowTapToDismiss' not found in the function declaration [-Wdocumentation]
     @param allowTapToDismiss
            ^~~~~~~~~~~~~~~~~
    /Users/belli/development/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-3.1.0/ios/Classes/UIView+Toast.h:343:9: note:
    did you mean 'tapToDismissEnabled'?
     @param allowTapToDismiss
            ^~~~~~~~~~~~~~~~~
            tapToDismissEnabled
    /Users/belli/development/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-3.1.0/ios/Classes/UIView+Toast.h:362:20:
    warning: empty paragraph passed to '@param' command [-Wdocumentation]
     @param queueEnabled
     ~~~~~~~~~~~~~~~~~~^
    /Users/belli/development/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-3.1.0/ios/Classes/FluttertoastPlugin.m:19:23:
    warning: unused variable 'viewController' [-Wunused-variable]
        UIViewController *viewController =
                          ^
    /Users/belli/development/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-3.1.0/ios/Classes/FluttertoastPlugin.m:70:21:
    warning: unused variable 'topPadding' [-Wunused-variable]
                CGFloat topPadding = window.safeAreaInsets.top;
                        ^
    /Users/belli/development/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-3.1.0/ios/Classes/FluttertoastPlugin.m:71:21:
    warning: unused variable 'bottomPadding' [-Wunused-variable]
                CGFloat bottomPadding = window.safeAreaInsets.bottom;
                        ^
    /Users/belli/development/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-3.1.0/ios/Classes/FluttertoastPlugin.m:48:19:
    warning: unused variable 'size' [-Wunused-variable]
            NSNumber *size = call.arguments[@"size"];
                      ^
    8 warnings generated.
    In file included from
    /Users/belli/development/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-3.1.0/ios/Classes/UIView+Toast.m:26:
    /Users/belli/development/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-3.1.0/ios/Classes/UIView+Toast.h:328:19:
    warning: empty paragraph passed to '@param' command [-Wdocumentation]
     @param sharedStyle
     ~~~~~~~~~~~~~~~~~^
    /Users/belli/development/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-3.1.0/ios/Classes/UIView+Toast.h:343:25:
    warning: empty paragraph passed to '@param' command [-Wdocumentation]
     @param allowTapToDismiss
     ~~~~~~~~~~~~~~~~~~~~~~~^
    /Users/belli/development/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-3.1.0/ios/Classes/UIView+Toast.h:343:9: warning:
    parameter 'allowTapToDismiss' not found in the function declaration [-Wdocumentation]
     @param allowTapToDismiss
            ^~~~~~~~~~~~~~~~~
    /Users/belli/development/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-3.1.0/ios/Classes/UIView+Toast.h:343:9: note:
    did you mean 'tapToDismissEnabled'?
     @param allowTapToDismiss
            ^~~~~~~~~~~~~~~~~
            tapToDismissEnabled
    /Users/belli/development/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-3.1.0/ios/Classes/UIView+Toast.h:362:20:
    warning: empty paragraph passed to '@param' command [-Wdocumentation]
     @param queueEnabled
     ~~~~~~~~~~~~~~~~~~^
    4 warnings generated.
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Release ===
    Building AOT snapshot in release mode (ios-release)...          
    Building App.framework for arm64...

    Building App.framework for armv7...
    Building AOT snapshot in release mode (ios-release)...             50,9s
    Built to build/aot/.
    warning: parsing line table prologue at offset 0x6f697463 found unsupported version 0x00
    warning: line table parameters mismatch. Cannot emit.
    note: while processing /Users/belli/code/metag/build/aot/armv7/snapshot_assembly.o
    Project /Users/belli/code/metag built and packaged successfully.
    duplicate symbol '_OBJC_CLASS_$_FLTKeyboardVisibilityPlugin' in:
        /Users/belli/code/metag/build/ios/Release-iphoneos/flutter_keyboard_visibility/libflutter_keyboard_visibility.a(KeyboardVisib
        ilityPlugin.o)
        /Users/belli/code/metag/build/ios/Release-iphoneos/keyboard_visibility/libkeyboard_visibility.a(KeyboardVisibilityPlugin.o)
    duplicate symbol '_OBJC_METACLASS_$_FLTKeyboardVisibilityPlugin' in:
        /Users/belli/code/metag/build/ios/Release-iphoneos/flutter_keyboard_visibility/libflutter_keyboard_visibility.a(KeyboardVisib
        ilityPlugin.o)
        /Users/belli/code/metag/build/ios/Release-iphoneos/keyboard_visibility/libkeyboard_visibility.a(KeyboardVisibilityPlugin.o)
    duplicate symbol '_OBJC_IVAR_$_FLTKeyboardVisibilityPlugin._flutterEventSink' in:
        /Users/belli/code/metag/build/ios/Release-iphoneos/flutter_keyboard_visibility/libflutter_keyboard_visibility.a(KeyboardVisib
        ilityPlugin.o)
        /Users/belli/code/metag/build/ios/Release-iphoneos/keyboard_visibility/libkeyboard_visibility.a(KeyboardVisibilityPlugin.o)
    duplicate symbol '_OBJC_IVAR_$_FLTKeyboardVisibilityPlugin._flutterEventListening' in:
        /Users/belli/code/metag/build/ios/Release-iphoneos/flutter_keyboard_visibility/libflutter_keyboard_visibility.a(KeyboardVisib
        ilityPlugin.o)
        /Users/belli/code/metag/build/ios/Release-iphoneos/keyboard_visibility/libkeyboard_visibility.a(KeyboardVisibilityPlugin.o)
    duplicate symbol '_OBJC_IVAR_$_FLTKeyboardVisibilityPlugin._isVisible' in:
        /Users/belli/code/metag/build/ios/Release-iphoneos/flutter_keyboard_visibility/libflutter_keyboard_visibility.a(KeyboardVisib
        ilityPlugin.o)
        /Users/belli/code/metag/build/ios/Release-iphoneos/keyboard_visibility/libkeyboard_visibility.a(KeyboardVisibilityPlugin.o)
    ld: 5 duplicate symbols for architecture arm64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

In addition, if I remove the 0.7.0 version and I build it, I can open in Xcode the Runner.xcworkspace instead of Runner.xcodeproj and successfully archive it.
But then am I doing it right? Am I sending the wrong application?

**Comment by BondarenkoStas** [comment]
@alessandrobelli Interesting notice about Runner.xcworkspace. https://flutter.dev/docs/get-started/install/macos#deploy-to-ios-devices asks to use it, but it's way not straightforward, and there is an issue https://github.com/flutter/flutter/issues/10770. 
Does it work in this way? Also, 0.7.0 is the version of what?

**Comment by wilburt** [comment]
@alessandrobelli  Please, can you confirm that you don't have both **keyboard_visibility** and **flutter_keyboard_visibility** in your pubspec?

**Comment by alessandrobelli** [comment]
@BondarenkoStas sorry 0.7.0 was intended to be **flutter_keyboard_visibility**.

I will now explain to you all the process and how I solved it.
First, I did not include the keyboard_visibility in my pubspec.yaml, not in the last iteration of my app. 
So I had to find which package(s) used it!
I found that I had [flutter_typeahead](https://github.com/AbdulRahmanAlHamali/flutter_typeahead/ ) that depended on keyboard_visibility, and that a later update of it solved the bug written here.
I then updated flutter_typeahead to latest, I performed again

- run `flutter clean`
- Delete Pods folder and Podfile.lock in $PROJECT/ios
- run `cd ios && pod install`
- run `flutter build ios`
- run `flutter run` to the the app

opened Runner.xcodeproj, archive it and the problem now was
![image](https://user-images.githubusercontent.com/3796324/67584715-81480000-f74e-11e9-8e6c-422aa6dca7e2.png)
funny enough. I wrote the issue here: https://github.com/AbdulRahmanAlHamali/flutter_typeahead/pull/125#issuecomment-546360007

Then when I opened Runner.xcworkspace, I successfully archived and sent to app store connect.

**Comment by MisterJimson** [comment]
Just wanted to chime in a say the whole reason I forked `flutter_keyboard_visibility` was to remove this dependency conflict. We have an app that uses our [pusher-websocket-flutter](https://github.com/HomeXLabs/pusher-websocket-flutter) library and `flutter_typeahead ` as well.

**Comment by jmagman** [comment]
Also see https://github.com/flutter/flutter/issues/42707.

**Comment by nickwri** [comment]
> @alessandrobelli
> Please take the following steps:
> 
> * run `flutter clean`
> * Delete **Pods** folder and **Podfile.lock** in $PROJECT/ios
> * run `cd ios && pod install`
> * run `flutter build ios`
> 
> Please, let me know if this helped.

This worked great for me (and my Flutter app) - many thanks.
