### ISSUE TITLE
Engine doesn't build macOS host_debug_unopt on Xcode 13

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#85500]
On Xcode 13 beta 2 (13A5154o) which contains the macOS 12 SDK:
```
$ ./flutter/tools/gn --unoptimized && ninja -C out/host_debug_unopt 
...
ninja: Entering directory `out/host_debug_unopt'
[1/1] Regenerating ninja files
[4594/5483] LINK ./gen_snapshot
FAILED: gen_snapshot 
../../buildtools/mac-x64/clang/bin/clang++ -isysroot /Users/m/Applications/Xcode-13_beta2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk -mmacosx-version-min=10.11.0 -rdynamic -arch x86_64 -nostdlib++ -stdlib=libc++ -Wl,-search_paths_first -L. -Wl,-rpath,@loader_path/. -Wl,-rpath,@loader_path/../../.. -Wl,-pie  -Xlinker -rpath -Xlinker @executable_path/Frameworks -o ./gen_snapshot -Wl,-filelist,./gen_snapshot.rsp  -ldl -lpthread -framework CoreFoundation -framework CoreServices
Undefined symbols for architecture x86_64:
  "dart::FLAG_generate_perf_jitdump", referenced from:
      dart::VirtualMemory::Init() in libdart_vm_precompiler.virtual_memory_posix.o
  "dart::FLAG_generate_perf_events_symbols", referenced from:
      dart::VirtualMemory::Init() in libdart_vm_precompiler.virtual_memory_posix.o
ld: symbol(s) not found for architecture x86_64
clang-13: error: linker command failed with exit code 1 (use -v to see invocation)
[4611/5483] CXX obj/third_party/dart/runtime/vm/libdart_vm_jit.object.o
ninja: build stopped: subcommand failed.
```
Ran on top of PR https://github.com/flutter/buildroot/pull/475 to pick up macOS 12 SDK.  `ios_debug_unopt` built correctly.  `host_debug_unopt` builds on this machine with Xcode 12.5.

**Comment by jmagman** [comment]
Engine team tracked this down to a dart VM issue, closing in favor of https://github.com/dart-lang/sdk/issues/46499.
