### ISSUE TITLE
[camera] Android app build failed after upgrading camera plugin to 0.8.0

### ISSUE THREAD

**Issue by divyanshub024** [flutter/flutter#77388]
## Description 

I'm using Flutter camera plugin `camera: ^0.8.0`

After upgrading Android build is failing.

```
Launching lib/main.dart on Pixel 4a in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     /Users/divyanshubhargava/AndroidStudioProjects/flutter_app/build/flutter_inappwebview/intermediates/library_manifest/debug/AndroidManifest.xml:7:5-11:15: AAPT: error: unexpected element <queries> found in <manifest>.


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 20s
The build failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetifier to solve the incompatibility.
Building plugin camera...
Running Gradle task 'assembleAarRelease'...

/Users/divyanshubhargava/Softwares/flutter/.pub-cache/hosted/pub.dartlang.org/camera-0.8.0/android/src/main/java/io/flutter/plugins/camera/CameraPermissions.java:12: error: package androidx.core.app does not exist
import androidx.core.app.ActivityCompat;
                        ^
/Users/divyanshubhargava/Softwares/flutter/.pub-cache/hosted/pub.dartlang.org/camera-0.8.0/android/src/main/java/io/flutter/plugins/camera/CameraPermissions.java:13: error: package androidx.core.content does not exist
import androidx.core.content.ContextCompat;
                            ^
/Users/divyanshubhargava/Softwares/flutter/.pub-cache/hosted/pub.dartlang.org/camera-0.8.0/android/src/main/java/io/flutter/plugins/camera/CameraZoom.java:10: error: package androidx.core.math does not exist
import androidx.core.math.MathUtils;
                         ^
/Users/divyanshubhargava/Softwares/flutter/.pub-cache/hosted/pub.dartlang.org/camera-0.8.0/android/src/main/java/io/flutter/plugins/camera/CameraPermissions.java:45: error: cannot find symbol
      ActivityCompat.requestPermissions(
      ^
  symbol:   variable ActivityCompat
  location: class CameraPermissions
/Users/divyanshubhargava/Softwares/flutter/.pub-cache/hosted/pub.dartlang.org/camera-0.8.0/android/src/main/java/io/flutter/plugins/camera/CameraPermissions.java:58: error: cannot find symbol
    return ContextCompat.checkSelfPermission(activity, permission.CAMERA)
           ^
  symbol:   variable ContextCompat
  location: class CameraPermissions
/Users/divyanshubhargava/Softwares/flutter/.pub-cache/hosted/pub.dartlang.org/camera-0.8.0/android/src/main/java/io/flutter/plugins/camera/CameraPermissions.java:63: error: cannot find symbol
    return ContextCompat.checkSelfPermission(activity, permission.RECORD_AUDIO)
           ^
  symbol:   variable ContextCompat
  location: class CameraPermissions
/Users/divyanshubhargava/Softwares/flutter/.pub-cache/hosted/pub.dartlang.org/camera-0.8.0/android/src/main/java/io/flutter/plugins/camera/CameraZoom.java:41: error: cannot find symbol
    final float newZoom = MathUtils.clamp(zoom, DEFAULT_ZOOM_FACTOR, this.maxZoom);
                          ^
  symbol:   variable MathUtils
  location: class CameraZoom
7 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

Exception: The plugin camera could not be built due to the issue above.

```

## Flutter doctor

```
divyanshubhargava@divyanshus-MacBook-Pro app % flutter doctor -v
[✓] Flutter (Channel stable, 2.0.1, on macOS 11.2.1 20D74 darwin-x64, locale en-IN)
    • Flutter version 2.0.1 at /Users/divyanshubhargava/Softwares/flutter
    • Framework revision c5a4b4029c (24 hours ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/divyanshubhargava/Library/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/divyanshubhargava/Library/Android/Sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 4.2 Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (2 available)
    • Pixel 4a (mobile) • 0B231JEC220103 • android-arm64  • Android 11 (API 30)
    • Chrome (web)      • chrome         • web-javascript • Google Chrome 88.0.4324.192

! Doctor found issues in 1 category.

```

**Comment by subinsv** [comment]
I had similar issue.

Downgrading inappwebview to version 4.0.0+4 solved the error.
You may try this as an temporary workaround

flutter_inappwebview: 4.0.0+4

**Comment by darshankawar** [comment]
@divyanshub024 
Please see if above solution resolves your issue. If so, it could be an issue with the plugin itself which is 3rd party and you may need to open this issue in dedicated repo : https://github.com/pichillilorenzo/flutter_inappwebview/issues
Closing it from here since it seems to be related to `inappwebview` plugin and not Flutter. If you disagree, write in comments and I'll reopen it.

**Comment by nbbng** [comment]
I had same problem, too.

But, I changed `compileSdkVersion` from 28 to 30 in app/build.gradle, it's work fine for me.

**Comment by vkmaxcooldude** [comment]
You can check [https://github.com/pichillilorenzo/flutter_inappwebview/issues/791](https://github.com/pichillilorenzo/flutter_inappwebview/issues/791) for solution

**Comment by ventr1x** [comment]
This is NOT a 3rd party plugin issue but the camera plugin simply not working with newer Flutter version!
The error is clearly stated. Would be nice to actually read report instead of blindly triaging them into nothingness.

 ```
 location: class CameraPermissions
/Users/*/.pub-cache/hosted/pub.dartlang.org/camera-0.8.1+1/android/src/main/java/io/flutter/plugins/camera/CameraPermissions.java:63: error: cannot find symbol
    return ContextCompat.checkSelfPermission(activity, permission.RECORD_AUDIO)
           ^
  symbol:   variable ContextCompat
  location: class CameraPermissions
/Users/*/.pub-cache/hosted/pub.dartlang.org/camera-0.8.1+1/android/src/main/java/io/flutter/plugins/camera/CameraZoom.java:41: error: cannot find symbol
    final float newZoom = MathUtils.clamp(zoom, DEFAULT_ZOOM_FACTOR, this.maxZoom);
                          ^
  symbol:   variable MathUtils
  location: class CameraZoom
```

I get hit with hit on every Flutter version above 2.0.x.

Btw already set compileSdkVersion at 30.
