### ISSUE TITLE
fatal error: 'Flutter/Flutter.h' file not found

### ISSUE THREAD

**Issue by lukeirvin** [flutter/flutter#90975]
```
Failed to build iOS app
Error output from Xcode build:
↳
    --- xcodebuild: WARNING: Using the first of multiple matching destinations:
    { platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device }
    { platform:iOS Simulator, id:AA0EE6D2-4E24-48C6-B9D6-4F2598B68E4E, OS:15.0, name:iPad (9th generation) }
    { platform:iOS Simulator, id:765C02E6-837E-4443-9073-722162C490DC, OS:15.0, name:iPad Air (4th generation) }
    { platform:iOS Simulator, id:30429B61-93BC-4497-B556-3639373A10D0, OS:15.0, name:iPad Pro (9.7-inch) }
    { platform:iOS Simulator, id:57217E13-F700-4673-9ABF-1866BAE1E435, OS:15.0, name:iPad Pro (11-inch) (3rd generation) }
    { platform:iOS Simulator, id:A85DD0A6-EA0F-480C-9A6F-07966F4FE66B, OS:15.0, name:iPad Pro (12.9-inch) (5th generation) }
    { platform:iOS Simulator, id:1D568B75-852B-42BE-8178-C39E6C515C41, OS:15.0, name:iPad mini (6th generation) }
    { platform:iOS Simulator, id:347466A9-6BA4-4674-94B6-BCB3ACB11F00, OS:15.0, name:iPhone 8 }
    { platform:iOS Simulator, id:F74B444A-2838-4920-91DB-83893719250E, OS:15.0, name:iPhone 8 Plus }
    { platform:iOS Simulator, id:2D4AF847-04A7-463C-A46C-D5D1E200CFDC, OS:15.0, name:iPhone 11 }
    { platform:iOS Simulator, id:BCD3D3BD-6485-4575-AA35-BF9ADEEBB4BD, OS:15.0, name:iPhone 11 Pro }
    { platform:iOS Simulator, id:06DE013F-BF48-4857-B952-BFC2AA1BD304, OS:15.0, name:iPhone 11 Pro Max }
    { platform:iOS Simulator, id:8A06D628-6132-4558-BB65-5598FFAC98DC, OS:15.0, name:iPhone 12 }
    { platform:iOS Simulator, id:885B1C8A-0497-4D95-8A87-447E40AB9238, OS:15.0, name:iPhone 12 Pro }
    { platform:iOS Simulator, id:FF519331-8490-4219-92D0-ED9A08F11976, OS:15.0, name:iPhone 12 Pro Max }
    { platform:iOS Simulator, id:51671583-ED36-4330-839B-401BA09B3996, OS:15.0, name:iPhone 12 mini }
    { platform:iOS Simulator, id:950FC388-6567-40BD-AD31-6CC5A334AC97, OS:15.0, name:iPhone 13 }
    { platform:iOS Simulator, id:562728AB-E0CA-4675-BF75-787299ECE105, OS:15.0, name:iPhone 13 Pro }
    { platform:iOS Simulator, id:CBB3D2FF-97DF-4328-8AD0-7350F83989D1, OS:15.0, name:iPhone 13 Pro Max }
    { platform:iOS Simulator, id:D99FD6E3-C6DC-4F16-8092-83EA0216367F, OS:15.0, name:iPhone 13 mini }
    { platform:iOS Simulator, id:2A06C9C4-9D8C-4C9B-9620-12265131A747, OS:15.0, name:iPhone SE (2nd generation) }
    { platform:iOS Simulator, id:EA2B1A03-78F8-42B2-9818-41FE3F1E833A, OS:15.0, name:iPod touch (7th generation) }
    { platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
    ** BUILD FAILED **
Xcode's output:
↳
    /Users/lukeirvin/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/wakelock-0.5.2/ios/Classes/messages.m:4:9: fatal error: 'Flutter/Flutter.h' file not found
    #import <Flutter/Flutter.h>
            ^~~~~~~~~~~~~~~~~~~
    1 error generated.
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in parallel
```

Running Xcode 13, flutter 2.5.1 on stable, and cocoa pods 1.10.1

Prior to this, I was getting complaints that some pods were on 8.0 and needed to be on 9.0+ so I updated my Podfile to have this:

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
   target.build_configurations.each do |config|
    config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
   end
  end
 end
```

I have tried re-installing Flutter, re-cloning my app, deleting the ios folder, deleting the Flutter folder, cleaning, pod install... anything I have found online. But still getting the above every time. Just on iOS though.

Any guidance would be greatly appreciated.

**Comment by joelsongsouzza** [comment]
After updating my Flutter to 2.5.1, it stopped to working on iOS. 

> Prior to this, I was getting complaints that some pods were on 8.0 and needed to be on 9.0+ so I updated my Podfile to have this:

And I'm getting the same error from pods on 8.0 and 9.0.

`[...] warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.0.99. (in target 'Reachability' from project 'Pods')`

`[...] warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.0.99. (in target 'AppAuth' from project 'Pods')`

`[...] The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.0.99. (in target 'GoogleSignIn' from project 'Pods')`

**Comment by lukeirvin** [comment]
> After updating my Flutter to 2.5.1, it stopped to working on iOS.
> 
> > Prior to this, I was getting complaints that some pods were on 8.0 and needed to be on 9.0+ so I updated my Podfile to have this:
> 
> And I'm getting the same error from pods on 8.0 and 9.0.
> 
> `[...] warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.0.99. (in target 'Reachability' from project 'Pods')`
> 
> `[...] warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.0.99. (in target 'AppAuth' from project 'Pods')`
> 
> `[...] The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.0.99. (in target 'GoogleSignIn' from project 'Pods')`

Correct. I'm getting the same thing. Any suggestions? I've tried everything I've found via Stackoverflow but it's been no luck. A co-worker, though, isn't having these issues and has the same versions on his machine. So this one is very confusing.

**Comment by RaviPenikelapati** [comment]
I'm having a similar issue and made a post as well. Just like @lukeirvin I've tried basically everything and nothing seems to fix the issue. It was a bad idea do try and update everything at once. 

That said, the 'IPHONEOS_DEPLOYMENT_TARGET' error was fixed for me by removing the deployment target in the pod file:
`config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET`

**Comment by lukeirvin** [comment]
> I'm having a similar issue and made a post as well. Just like @lukeirvin I've tried basically everything and nothing seems to fix the issue. It was a bad idea to try and update everything at once.
> 
> That said, the 'IPHONEOS_DEPLOYMENT_TARGET' error was fixed for me by removing the deployment target in the pod file: `config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET`
> 
> Would be great to get some help with the 'Flutter/Flutter.h not found' though. It's been frustrating trying to get it to work

Tried the delete approach, and yes, the same thing on my end. It resolves the Pod 8.0 / needs to be 9.0... issue, but the other still exists.

**Comment by akarabach** [comment]
@lukeirvin  Do you use M1 Mac ?

**Comment by akarabach** [comment]
Steps which helped me:
1. update flutter
2. create a new project outside of the project you are working right now
3. delete ios folder in the project with error `fatal error: 'Flutter/Flutter.h' file not found`
4. copy ios folder from the new project
5. re set-up firebase if you are using it
6. run the project

**Comment by TahaTesser** [comment]
Hi @lukeirvin 
Can you please restore podfile & try the following commands and 
```podfile
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
```
```console
1. pod deintegrate
2. rm ios/Flutter/Flutter.podspec
3. flutter clean
4. flutter pub get
5. pod install
6. flutter run
```

**Comment by lukeirvin** [comment]
> @lukeirvin Do you use M1 Mac ?

No, I do not use a M1 Mac

**Comment by lukeirvin** [comment]
> Hi @lukeirvin Can you please restore podfile & try the following commands and
> 
> ```
> post_install do |installer|
>   installer.pods_project.targets.each do |target|
>     flutter_additional_ios_build_settings(target)
>   end
> end
> ```
> 
> ```
> 1. pod deintegrate
> 2. rm ios/Flutter/Flutter.podspec
> 3. flutter clean
> 4. flutter pub get
> 5. pod install
> 6. flutter run
> ```

So, flutter run will not work as I have dev and prod environments. So just to verify, try this but on the last step, trigger the proper environment file with the proper flavor?

**Comment by lukeirvin** [comment]
> Steps which helped me:
> 
> 1. update flutter
> 2. create a new project outside of the project you are working right now
> 3. delete ios folder in the project with error `fatal error: 'Flutter/Flutter.h' file not found`
> 4. copy ios folder from the new project
> 5. re set-up firebase if you are using it
> 6. run the project

I'm trying this but right now I'm getting this error:

`Exception: The Xcode project does not define custom schemes. You cannot use the --flavor option.`

**Comment by lukeirvin** [comment]
I reset everything with the post above & I am getting the same set of errors...

**Comment by joelsongsouzza** [comment]
@lukeirvin does you use google_sign_in framework? If yes, try updating to version 5.1.1.

Flutter 2.5.0 deprecated iOS 8.0 version, and google_sign_in used this version. In 5.1.1 they added this to changelog:
`Update minimum Flutter SDK to 2.5 and iOS deployment target to 9.0.`

I updated mine, ran flutter clean and worked again.

**Comment by TahaTesser** [comment]
@lukeirvin 
if the issue is specific to your project, please try the command with your flavor.

**Comment by lukeirvin** [comment]
I ended up reformatting my Mac yesterday.

So, once I had everything installed again I cloned my project & still received the same issue, the core one due to updating the version to 9.0+.

I then updated google_sign_in to 5.1.1 & the project worked. I reverted that change & I could still load the project with all the base settings. 

The first thing I did today was trying to load the project but it failed again.

So, I updated google_sign_in to 5.1.1 & now I can run the project.

But, I can only run it via simulator for iOS. If I try to build to my iPhone I get the update issue again.

**Comment by TahaTesser** [comment]
Hi @lukeirvin 
Can you please provide a `flutter run -v <your_flavor>  > run.log` connected to a physical device?

**Comment by josephmangmang** [comment]
Hi, try to remove `build` folder and run 
flutter clean
flutter pub get
pod install
flutter run

**Comment by Mmisiek** [comment]
I have spent a week trying to resolve this issue, I tried all methods possible, still always one of pods will fail with missing Flutter/Flutter.h. The only similarity I see is that pods for those plugins are installed with initial version 0.0.1. Please help ! 

```
    { platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
    ** BUILD FAILED **


Xcode's output:
↳
    In file included from
    /Users/michal/Development/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-6.0.12/ios/Classes/FLTURLLauncherPlugin.m:7:
    /Users/michal/Development/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-6.0.12/ios/Classes/FLTURLLauncherPlugin.h:5:9: fatal error:
    'Flutter/Flutter.h' file not found
    #import <Flutter/Flutter.h>
            ^~~~~~~~~~~~~~~~~~~
    1 error generated.
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in parallel

Could not build the application for the simulator.
```

At diffrent times failing pods:

I```
nstalling path_provider (0.0.1)
Installing shared_preferences (0.0.1)
Installing syncfusion_flutter_pdfviewer (0.0.1)
Installing tau_core (8.3.12)
Installing url_launcher (0.0.1)
Installing video_player (0.0.1)
```

I tried:
1. Remove ios folder 1 flutter create . 1 and copy Runner back etc...
2. Remove build..
3. Remove Flutter\Flutter....
4. All combinations of pod install/upgrade after clean ... 

Nothing works. My project suddenly top to compile for iOS.

**Comment by maheshmnj** [comment]
>    /Users/lukeirvin/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/wakelock-0.5.2/ios/Classes/messages.m:4:9: fatal error: 'Flutter/Flutter.h' file not found
    #import <Flutter/Flutter.h>

@lukeirvin please also try upgrading the wakelock plugin, it seems to be the cause of the build failure,  the latest version is `wakelock: ^0.5.6`.
