### ISSUE TITLE
flutter-desktop-embedding is not working with 2.0.6 in ubuntu

### ISSUE THREAD

**Issue by learncodingforweb** [flutter/flutter#81621]
## Steps to Reproduce

1. Run `flutter create -a java --org com.example provider_pack`.
2. Added plugins desktop plugin
```
name: provider_pack
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  window_size:            #added plugins
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
```

3. Run  'flutter run -d linux'

**Expected results:** 
Application should launch for desktop view in ubuntu

**Actual results:** 

<details>
  <summary>Logs</summary>

```
Launching lib/main.dart on Linux in debug mode...
/home/sukhdeep/project/git/bt/flutter2/ThirdParty/provider_pack/linux/flutter/ephemeral/.plugin_symlinks/window_size/linux/window_size_plugin.cc:80:29: error: unknown type name 'GdkMonitor'
/home/sukhdeep/project/git/bt/flutter2/ThirdParty/provider_pack/linux/flutter/ephemeral/.plugin_symlinks/window_size/linux/window_size_plugin.cc:111:21: error: use of undeclared identifier 'gdk_display_get_n_monitors'
/home/sukhdeep/project/git/bt/flutter2/ThirdParty/provider_pack/linux/flutter/ephemeral/.plugin_symlinks/window_size/linux/window_size_plugin.cc:113:5: error: unknown type name 'GdkMonitor'
/home/sukhdeep/project/git/bt/flutter2/ThirdParty/provider_pack/linux/flutter/ephemeral/.plugin_symlinks/window_size/linux/window_size_plugin.cc:113:27: error: use of undeclared identifier 'gdk_display_get_monitor'; did you mean 'gdk_display_get_screen'?
/home/sukhdeep/project/git/bt/flutter2/ThirdParty/provider_pack/linux/flutter/ephemeral/.plugin_symlinks/window_size/linux/window_size_plugin.cc:139:3: error: unknown type name 'GdkMonitor'
/home/sukhdeep/project/git/bt/flutter2/ThirdParty/provider_pack/linux/flutter/ephemeral/.plugin_symlinks/window_size/linux/window_size_plugin.cc:139:37: error: use of undeclared identifier 'gdk_display_get_primary_monitor'; did you mean 'gdk_screen_get_primary_monitor'?
/home/sukhdeep/project/git/bt/flutter2/ThirdParty/provider_pack/linux/flutter/ephemeral/.plugin_symlinks/window_size/linux/window_size_plugin.cc:139:69: error: cannot initialize a parameter of type 'GdkScreen *' (aka '_GdkScreen *') with an lvalue of type 'GdkDisplay *' (aka '_GdkDisplay *')
/home/sukhdeep/project/git/bt/flutter2/ThirdParty/provider_pack/linux/flutter/ephemeral/.plugin_symlinks/window_size/linux/window_size_plugin.cc:140:20: error: use of undeclared identifier 'gdk_display_get_n_monitors'
/home/sukhdeep/project/git/bt/flutter2/ThirdParty/provider_pack/linux/flutter/ephemeral/.plugin_symlinks/window_size/linux/window_size_plugin.cc:142:5: error: unknown type name 'GdkMonitor'
/home/sukhdeep/project/git/bt/flutter2/ThirdParty/provider_pack/linux/flutter/ephemeral/.plugin_symlinks/window_size/linux/window_size_plugin.cc:142:27: error: use of undeclared identifier 'gdk_display_get_monitor'; did you mean 'gdk_display_get_screen'?
/home/sukhdeep/project/git/bt/flutter2/ThirdParty/provider_pack/linux/flutter/ephemeral/.plugin_symlinks/window_size/linux/window_size_plugin.cc:345:7: error: use of undeclared identifier 'strcmp'
/home/sukhdeep/project/git/bt/flutter2/ThirdParty/provider_pack/linux/flutter/ephemeral/.plugin_symlinks/window_size/linux/window_size_plugin.cc:347:14: error: use of undeclared identifier 'strcmp'
/home/sukhdeep/project/git/bt/flutter2/ThirdParty/provider_pack/linux/flutter/ephemeral/.plugin_symlinks/window_size/linux/window_size_plugin.cc:349:14: error: use of undeclared identifier 'strcmp'
/home/sukhdeep/project/git/bt/flutter2/ThirdParty/provider_pack/linux/flutter/ephemeral/.plugin_symlinks/window_size/linux/window_size_plugin.cc:351:14: error: use of undeclared identifier 'strcmp'
/home/sukhdeep/project/git/bt/flutter2/ThirdParty/provider_pack/linux/flutter/ephemeral/.plugin_symlinks/window_size/linux/window_size_plugin.cc:353:14: error: use of undeclared identifier 'strcmp'
/home/sukhdeep/project/git/bt/flutter2/ThirdParty/provider_pack/linux/flutter/ephemeral/.plugin_symlinks/window_size/linux/window_size_plugin.cc:355:14: error: use of undeclared identifier 'strcmp'
/home/sukhdeep/project/git/bt/flutter2/ThirdParty/provider_pack/linux/flutter/ephemeral/.plugin_symlinks/window_size/linux/window_size_plugin.cc:357:14: error: use of undeclared identifier 'strcmp'
/home/sukhdeep/project/git/bt/flutter2/ThirdParty/provider_pack/linux/flutter/ephemeral/.plugin_symlinks/window_size/linux/window_size_plugin.cc:359:14: error: use of undeclared identifier 'strcmp'
/home/sukhdeep/project/git/bt/flutter2/ThirdParty/provider_pack/linux/flutter/ephemeral/.plugin_symlinks/window_size/linux/window_size_plugin.cc:361:14: error: use of undeclared identifier 'strcmp'
Building Linux application...                                           
Exception: Build process failed
```

```
```

```
```

</details>

**Comment by stuartmorgan** [comment]
flutter-desktop-embedding is a separate project with its own issue tracker; please file issues with it there.
