### ISSUE TITLE
[Regression] Cocoapods shows "undefined method `exists?' for File:Class" error

### ISSUE THREAD

**Issue by sma** [flutter/flutter#147041]
### Steps to reproduce

This bug is back in 

```
$ flutter --version
Flutter 3.22.0-14.0.pre.33 • channel master • https://github.com/flutter/flutter.git
Framework • revision 12d54de962 (2 hours ago) • 2024-04-19 03:10:34 -0400
Engine • revision 25d773ea90
Tools • Dart 3.5.0 (build 3.5.0-76.0.dev) • DevTools 2.35.0-dev.8
```

* https://github.com/flutter/flutter/issues/141167
* https://github.com/flutter/flutter/issues/118295

(I can't reopen my original bug)

It was re-introduced by https://github.com/flutter/flutter/commit/6d19fa3bfa2beee81ee2730dc9aae241b051857c, 12 hours ago.

It's called `exist?` since Ruby 2.2 and the deprecated `exists?` method was removed in Ruby 3.2. And Cocoapods installed by Homebrew uses Ruby 3.3, so it crashes.

### Expected results

it should work

### Actual results

it doesn't

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @sma, can you provide steps to reproduce? 

What version of cocoapods do you have installed? I have cocoapods 1.15.2 installed on my system using the ruby vendored by macOS and I can't reproduce the issue

**Comment by sma** [comment]
> unfortunately we don't have a CI environment with Ruby 3.2

Perhaps writing a check that greps all `*.rb` files for `.exists?` and expects to find nothing might do the trick?

**Comment by stuartmorgan** [comment]
That would be one of the options for a possible lint, yes. The caveat on whether that's worthwhile still applies though.
