### ISSUE TITLE
reflectable not compatible with flutter v0.6.0+

### ISSUE THREAD

**Issue by s-bauer** [flutter/flutter#20881]
### Description
The [reflectable](https://github.com/dart-lang/reflectable) package does not work with flutter v0.6.0, while it does work with v0.5.1.

### Minimal Example
Given the following minimal example: https://github.com/s-bauer/flutter_reflectable_minimal

### Working with v0.5.1

With v0.5.1 it works like expected. I execute the `tools/builder.dart` script using the following command
`flutter packages pub run tools/builder.dart lib/main.dart`

It produces the expected `main.reflectable.dart` output producing the following [OUTPUT](https://gist.github.com/f8b2179af387ae4783c71063166b5772)

### Failing with v0.6.0+

With version v0.6.0 I execute the same command, but this time it fails with the following [OUTPUT](https://gist.github.com/e7b903f06b7c8688ecd95e1d3f79d7c1).
I tested it with version v0.6.0 and  0.6.2-pre.15, maybe the bug even occurred in earlier versions of flutter. I haven't checked that!

\
\
\
\
I have no idea how to further investigate this issue. Can you please look into it and find out what is going wrong here?

**Comment by matanlurey** [comment]
I believe this is a duplicate of https://github.com/dart-lang/build/issues/733 and should be tracked there - the `build_runner` infrastructure currently doesn't have a way to "see" Flutter-engine-only libraries (such as `dart:ui`).

**Comment by s-bauer** [comment]
@matanlurey No, it's not. The "dart:ui" warning is there with both versions. The problem is that since v0.6.0 it also throws the following exception:

```
[SEVERE] ReflectableBuilder on lib/main.dart:

NoSuchMethodError: The getter 'id' was called on null.
Receiver: null
Tried calling: id
```

This is what causing the failure of the reflectable generation!

**Comment by zoechi** [comment]
That's better tracked in https://github.com/dart-lang/reflectable/issues
See also https://github.com/dart-lang/reflectable/issues/144
I don't think there is anything the Flutter team cando.
