### PR TITLE
Audit devicelab log streaming for nullability

### LINKED ISSUE #84819: Some devicelab tests are crashing locally, IosDevice.stopLoggingToSink NoSuchMethodError: The method 'kill' was called on null.
```
dart bin/run.dart -t new_gallery_ios__transition_perf
```
```
ext.cocoonRunTask: (-32000) Server error
NoSuchMethodError: The method 'kill' was called on null.
Receiver: null
Tried calling: kill()
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:63:5)
#1      IosDevice.stopLoggingToSink (package:flutter_devicelab/framework/devices.dart:882:21)
#2      _TaskRunner.run (package:flutter_devicelab/framework/framework.dart:165:24)
<asynchronous suspension>
#3      new _TaskRunner.<anonymous closure> (package:flutter_devicelab/framework/framework.dart:74:33)
<asynchronous suspension>
```
`_loggingProcess` is nullable, regression from https://github.com/flutter/flutter/pull/84008.

### PR DESCRIPTION
**Pull request by jmagman**
Audit some nullability assumptions from https://github.com/flutter/flutter/pull/84008 that aren't right when running tests locally.

1. `hostAgent.dumpDirectory` is now nullable.  Handle that, and move `flutter drive --screenshot` flag logic into `flutterCommandArgs`.
2. Handle null `_loggingProcess` and log `sink` when running tests locally.

Fixes https://github.com/flutter/flutter/issues/84819

### CODE REVIEW

**Review by dnfield — APPROVED** [review]
LGTM
