### ISSUE TITLE
Remove `IMPELLER_OPENGLES_FLIP_DEPRECATED`

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#187517]
https://github.com/flutter/flutter/pull/187316 introduced a macro that helps people transition through the breaking change in https://github.com/flutter/flutter/pull/186556 where opengles fragment shaders no longer need to have special flipping logic.  That macro was important for package developers so they could support `main` and `stable` version of flutter.

Once `IMPELLER_OPENGLES_FLIP_DEPRECATED` is on the stable channel (3.47.0?) it should be removed and its presence in the source code of a shader should be considered a compilation error.

cc @jason-simmons 
cc @chunhtai 
cc @justinmc

**Comment by chunhtai** [comment]
We can only remove it once the material_ui remove the usage, which needs to wait until material_ui bump the minimum flutter sdk to include the impeller changes
