### ISSUE TITLE
Lint: FlutterUmbrellaImport [clang-diagnostic-error] 'Flutter/Flutter.h' file not found

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#93360]
[`FlutterUmbrellaImport`](https://github.com/flutter/engine/blob/cf087516afb930de549e672b37a1e7d70b379931/shell/platform/darwin/ios/framework/Source/FlutterUmbrellaImport.m#L5-L9) is used in the [`copy_and_verify_framework_module` target](https://github.com/flutter/engine/blob/d57627c98fee5da1eb1a85ae29cbd083fbc98c5c/shell/platform/darwin/ios/BUILD.gn#L380), is not included in the engine framework source, and cannot be compiled on its own.

When `clang-tidy` is run on this file, it fails with a `clang-diagnostic-error` (compilation failure).

```
$ dart tools/clang_tidy/bin/main.dart --compile-commands ../out/ios_debug/compile_commands.json --repo . --verbose --lint-all
❗ A clang-tidy job failed to run, aborting:
ProcessRunnerException: Running "../../buildtools/mac-x64/clang/bin/clang-tidy 
...
flutter/shell/platform/darwin/ios/framework/Source/FlutterUmbrellaImport.m:9:9: error: 'Flutter/Flutter.h' file not found [clang-diagnostic-error]
#import <Flutter/Flutter.h>
        ^~~~~~~~~~~~~~~~~~~
:
2 errors generated.
Error while processing /Users/m/Projects/engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterUmbrellaImport.m.
Found compiler error(s).

Lint problems found
```

Unless there's some way to exclude it from `out/ios_debug/compile_commands.json` I don't see a way to avoid the error other than a `FLUTTER_NOLINT`.

**Comment by chinmaygarde** [comment]
Yeah, `FLUTTER_NOLINT` is the way to go.

**Comment by jmagman** [comment]
Fixed in https://github.com/flutter/engine/pull/29623.

**Comment by jmagman** [comment]
https://github.com/flutter/engine/pull/29623 added the `FLUTTER_NOLINT` and a link to this issue.

**Comment by jmagman** [comment]
`FLUTTER_NOLINT` was actually a fine solution, I don't think there's anything else to do here.
