### ISSUE TITLE
[Mac] - Build error on Mac OS with Flutter beta

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter#113575]
I'm trying to build the super_editor example app so that I can verify that another issue is fixed on Beta.

I had to fix a breaking change from Flutter so that I could run the app against Beta. You can run that same code with this branch: https://github.com/superlistapp/super_editor/tree/verifying-beta

When I try to build and run the super_editor example app on Mac, I get the following build error:

```
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:arm64, id:00006001-000C40163609801E }
{ platform:macOS, arch:x86_64, id:00006001-000C40163609801E }
../../../../../.pub-cache/hosted/pub.dartlang.org/file-6.1.2/lib/src/interface/file.dart:15:16: Error: The method 'File.create' has fewer named arguments than those of overridden method 'File.create'.
  Future<File> create({bool recursive = false});
               ^
org-dartlang-sdk:///third_party/dart/sdk/lib/io/file.dart:232:16: Context: This is the overridden method ('create').
  Future<File> create({bool recursive = false, bool exclusive = false});
               ^
../../../../../.pub-cache/hosted/pub.dartlang.org/file-6.1.2/lib/src/interface/file.dart:15:16: Error: The method 'File.create' doesn't have the named parameter 'exclusive' of overridden method 'File.create'.
  Future<File> create({bool recursive = false});
               ^
org-dartlang-sdk:///third_party/dart/sdk/lib/io/file.dart:232:16: Context: This is the overridden method ('create').
  Future<File> create({bool recursive = false, bool exclusive = false});
               ^
../../../../../.pub-cache/hosted/pub.dartlang.org/file-6.1.2/lib/src/forwarding/forwarding_file.dart:22:8: Error: The method 'ForwardingFile.createSync' has fewer named arguments than those of overridden method 'File.createSync'.
  void createSync({bool recursive = false}) =>
       ^
org-dartlang-sdk:///third_party/dart/sdk/lib/io/file.dart:248:8: Context: This is the overridden method ('createSync').
  void createSync({bool recursive = false, bool exclusive = false});
       ^
../../../../../.pub-cache/hosted/pub.dartlang.org/file-6.1.2/lib/src/forwarding/forwarding_file.dart:22:8: Error: The method 'ForwardingFile.createSync' doesn't have the named parameter 'exclusive' of overridden method 'File.createSync'.
  void createSync({bool recursive = false}) =>
       ^
org-dartlang-sdk:///third_party/dart/sdk/lib/io/file.dart:248:8: Context: This is the overridden method ('createSync').
  void createSync({bool recursive = false, bool exclusive = false});
       ^

Command PhaseScriptExecution failed with a nonzero exit code
** BUILD FAILED **

Exception: Build process failed
```

Flutter version:
```
Flutter 3.4.0-34.1.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 71520442d4 (12 days ago) • 2022-10-05 16:38:28 -0500
Engine • revision db0cbb2145
Tools • Dart 2.19.0 (build 2.19.0-255.2.beta) • DevTools 2.18.0
```

**Comment by stuartmorgan** [comment]
You need a newer version of `file`; see the changelog notes for 6.1.3: https://pub.dev/packages/file/changelog

**Comment by matthew-carroll** [comment]
Actionable steps for a resolution would be appreciated over a reference to a declarative statement somewhere else.

"In classes that implement File methods create, createSync now take bool exclusive = true parameter. No functional changes." isn't helpful.

I'm looking at the build failure output that I posted, and I see a lot of references to a pub cache and Dart SDK. What is it that you're expecting me to do to get my build to work again? Everything was fine on 3.3.3, I can't build on 3.3.4, and unless I'm missing something in that mess of a build error, I don't think this failure has to do with my code, does it?

**Comment by stuartmorgan** [comment]
The actionable step is to update the version of the `file` package that you are using, for example by running `flutter pub upgrade`.

> unless I'm missing something in that mess of a build error, I don't think this failure has to do with my code, does it?

No, as indicated in the error messages it's coming from the `file` package (which is not part of the Flutter project, and has its own issue tracker where issues with it can be reported).

**Comment by mraleph** [comment]
FWIW I think @matthew-carroll is right here - the compiler error is really confusing and unactionable, unless you have good enough grasp of Dart/Flutter ecosystem and know that compiler errors confined to dependencies should be resolved by upgrading these dependencies. 

I think there are few pieces here that we could improve to make UX better:

- Errors should not use raw file uris pointing into `.pub_cache`. Instead they should use `package` URIs
- When compilation errors point to `.pub_cache` tooling should suggest updating dependency. 

Consider the output like this: 

```
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:arm64, id:00006001-000C40163609801E }
{ platform:macOS, arch:x86_64, id:00006001-000C40163609801E }

Compilation errors in package 'file' (version 6.1.2):

  package:file/src/interface/file.dart:15:16: Error: The method 'File.create' has fewer named arguments than those of overridden method 'File.create'.
    Future<File> create({bool recursive = false});
                 ^
  Dart SDK: Context: This is the overridden method ('create').
    Future<File> create({bool recursive = false, bool exclusive = false});
                 ^
  package:file/src/interface/file.dart:15:16: Error: The method 'File.create' doesn't have the named parameter 'exclusive' of overridden method 'File.create'.
    Future<File> create({bool recursive = false});
                 ^
  Dart SDK: Context: This is the overridden method ('create').
    Future<File> create({bool recursive = false, bool exclusive = false});
                 ^
  package:file/src/forwarding/forwarding_file.dart:22:8: Error: The method 'ForwardingFile.createSync' has fewer named arguments than those of overridden method 'File.createSync'.
    void createSync({bool recursive = false}) =>
         ^
  Dart SDK: Context: This is the overridden method ('createSync').
    void createSync({bool recursive = false, bool exclusive = false});
         ^
  package:file/src/forwarding/forwarding_file.dart:22:8: Error: The method 'ForwardingFile.createSync' doesn't have the named parameter 'exclusive' of overridden method 'File.createSync'.
    void createSync({bool recursive = false}) =>
         ^
  Dart SDK: Context: This is the overridden method ('createSync').
    void createSync({bool recursive = false, bool exclusive = false});

       ^
The package version currently in use might be incompatible with other 
dependencies or current Flutter SDK version. Try upgrading package file
by running: pub ... 

Command PhaseScriptExecution failed with a nonzero exit code
** BUILD FAILED **

Exception: Build process failed
``` 

or even

```
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:arm64, id:00006001-000C40163609801E }
{ platform:macOS, arch:x86_64, id:00006001-000C40163609801E }

Error: compilation errors occurred when building libraries belonging to package 'file' (version 6.1.2). 
          Run with -v to see them. The package version currently in use might be incompatible with other
          dependencies or current Flutter SDK version. Try upgrading package file by running: pub ... 

Command PhaseScriptExecution failed with a nonzero exit code
** BUILD FAILED **

Exception: Build process failed
``` 

This is much more actionable and user-friendly (especially for new comers) then dumping a bunch of compiler errors on their heads.

**Comment by stuartmorgan** [comment]
> I think there are few pieces here that we could improve to make UX better:
> 
> * Errors should not use raw file uris pointing into `.pub_cache`. Instead they should use `package` URIs
> * When compilation errors point to `.pub_cache` tooling should suggest updating dependency.

These certainly seem worth filing as separate feature requests. (Presumably they should apply to Dart as well as Flutter.)

**Comment by matthew-carroll** [comment]
Those UX improvements sound good to me. 

This case was also a bit more confusing than normal because I implicitly assumed that `flutter upgrade` would include relevant downstream updates. That assumption was wrong.

**Comment by mraleph** [comment]
I have filed an upstream issue against CFE to see if we can make improvements there: https://github.com/dart-lang/sdk/issues/50281
