### ISSUE TITLE
[firebase_crashlytics-0.0.4+8] iOS build error

### ISSUE THREAD

**Issue by sperochon** [flutter/flutter#35635]
Hi,

`flutter build ios`
works well with firebase_crashlytics-0.0.4+**7**

but gives the following error with firebase_crashlytics-0.0.4+**8**

```
    /Users/seb/dev/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_crashlytics-0.0.4+8/ios/Classes/FirebaseCrashlyticsPlugin.m:2:9: fatal error:
    'UserAgent.h' file not found
    #import "UserAgent.h"
            ^~~~~~~~~~~~~
    1 error generated.

```

Thanks!

**Comment by orestesgaolin** [comment]
I have the same problem with `firebase_analytics` in 3.0.3

**Comment by CosmicPangolin** [comment]
I'm getting this quite often on builds since the UserAgent changes in these packages.

**Comment by lidemin** [comment]
@CosmicPangolin you just saved my day. Thanks a lot for sharing.

**Comment by BondarenkoStas** [comment]
Thank you @CosmicPangolin, I think it's safe to close the issue. If you disagree or have any new input, please comment and I will re-open it right away.
