### ISSUE TITLE
Updating Firestore from 0.5.0 to 0.5.1 makes app to crash on start

### ISSUE THREAD

**Issue by Galahand** [flutter/flutter#17572]
## Steps to Reproduce

Everything worked fine with firestore 0.5.0 but when i updated to 0.5.1 the app now crashes on start

## Logs

i get this in logcat:

05-14 13:39:20.904 1957-1957/com.pitahaya.milagritoapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.pitahaya.milagritoapp, PID: 1957
    java.lang.NoSuchMethodError: No virtual method zzbqp()Ljava/lang/String; in class Lcom/google/firebase/FirebaseApp; or its super classes (declaration of 'com.google.firebase.FirebaseApp' appears in /data/app/com.pitahaya.milagritoapp-ItRbWq3xuhq0iQtO1Pozdg==/base.apk)
        at com.google.firebase.auth.FirebaseAuth.zzb(Unknown Source:5)
        at com.google.firebase.auth.FirebaseAuth.getInstance(Unknown Source:4)
        at io.flutter.plugins.firebaseauth.FirebaseAuthPlugin.<init>(FirebaseAuthPlugin.java:47)
        at io.flutter.plugins.firebaseauth.FirebaseAuthPlugin.registerWith(FirebaseAuthPlugin.java:40)
        at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:27)
        at com.pitahaya.milagritoapp.MainActivity.onCreate(MainActivity.java:12)
        at android.app.Activity.performCreate(Activity.java:7009)
        at android.app.Activity.performCreate(Activity.java:7000)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

Flutter doctor:
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v0.4.4-pre.8, on Microsoft Windows [Version 10.0.16299.431], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[√] Android Studio (version 3.1)
[√] VS Code, 64-bit edition (version 1.22.2)
[√] Connected devices (1 available)

• No issues found!

**Comment by zoechi** [comment]
I had a similar issue when run on the Android emulator, but not when run on the phone.
Wiping the emulator fixed it.

**Comment by Galahand** [comment]
Thanks for your answer, i wiped the emulator but the error still appears, it also does on real devices

**Comment by Galahand** [comment]
I updated every other plugin from firebase, and i had to remove the location plugin from the pubspec.yaml to make it work.

It seems that updating these will bring some compatibility issues
