### PR TITLE
[platform_view]fix typo in xcuitest

### LINKED ISSUE #109880: `Mac_ios native_platform_view_ui_tests_ios` is failing on every run
```
[native_platform_view_ui_tests_ios] [STDOUT] stdout: /opt/s/w/ir/x/w/recipe_cleanup/tmpr2usjwxr/flutter sdk/dev/integration_tests/ios_platform_view_tests/ios/PlatformViewUITests/PlatformViewUITests.m:26:10: error: no visible @interface for 'XCTestCase' declares the selector 'setup'
[native_platform_view_ui_tests_ios] [STDOUT] stdout:   [super setup];
[native_platform_view_ui_tests_ios] [STDOUT] stdout:    ~~~~~ ^~~~~
[native_platform_view_ui_tests_ios] [STDOUT] stdout: 1 error generated.
```
Caused by https://github.com/flutter/flutter/pull/109720
cc @hellohuanlin

### PR DESCRIPTION
**Pull request by hellohuanlin**
Oops this is too embarrassing. I was overly confident about last PR. 

*List which issues are fixed by this PR. You must list at least one issue.*
Fixes https://github.com/flutter/flutter/issues/109880

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by jmagman — APPROVED** [review]
LGTM, I also should have caught it 🙂

**Comment by jmagman** [comment]
> It looks like this pull request may not have tests.

Guess https://github.com/flutter/cocoon/pull/2063 hasn't deployed yet.

**Comment by Hixie** [comment]
test-exempt: is a test
