### PR TITLE
Fixes keyboard selects disabled radio

### PR DESCRIPTION
**Pull request by chunhtai**
fixes https://github.com/flutter/flutter/issues/176398

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

**Note**: The Flutter team is currently trialing the use of [Gemini Code Assist for GitHub](https://developers.google.com/gemini-code-assist/docs/review-github-code). Comments from the `gemini-code-assist` bot should not be taken as authoritative feedback from the Flutter team. If you find its comments useful you can update your code accordingly, but if you are unsure or disagree with the feedback, please feel free to wait for a Flutter team member's review for guidance on which automated comments should be addressed.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter/lib/src/widgets/radio_group.dart [hunk 1]
```diff
@@ -170,7 +170,9 @@ class _RadioGroupState<T> extends State<RadioGroup<T>> implements RadioGroupRegi
       return;
     }
     final List<FocusNode> sorted = ReadingOrderTraversalPolicy.sort(
-      _radios.map<FocusNode>((RadioClient<T> radio) => radio.focusNode),
+      _radios
+          .where((RadioClient<T> radio) => radio.enabled)
+          .map<FocusNode>((RadioClient<T> radio) => radio.focusNode),
```
[the remark this answers is not in the document]
Comment (chunhtai) [reply packages/flutter/lib/src/widgets/radio_group.dart:175]: In theory, This is not possible. Otherwise it would have return when it tries to find current focus. so there will be at least one focusable thus enabled radio. Added an assert just in case.

**Review by justinmc — APPROVED** [review]
LGTM 👍 , thanks for jumping on this.

**Comment by gaaclarke** [comment]
reason for revert: this is making the tree red, example: https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_x64%20tool_tests_commands/9129/overview

```
00:13 +0 -2: loading /Volumes/Work/s/w/ir/x/t/flutter_tools.c9CMKx/flutter_tools_create_test.CWr5PZ/flutter_project/test/flutter_project_method_channel_test.dart [E]                                  
  Failed to load "/Volumes/Work/s/w/ir/x/t/flutter_tools.c9CMKx/flutter_tools_create_test.CWr5PZ/flutter_project/test/flutter_project_method_channel_test.dart":
  Compilation failed for testPath=/Volumes/Work/s/w/ir/x/t/flutter_tools.c9CMKx/flutter_tools_create_test.CWr5PZ/flutter_project/test/flutter_project_method_channel_test.dart: ../../../../w/flutter/packages/flutter/lib/src/cupertino/segmented_control.dart:210:7: Error: The non-abstract class '_SegmentButtonState' is missing implementations for these members:
   - RadioClient.enabled
  Try to either
   - provide an implementation,
   - inherit an implementation from a superclass or mixin,
   - mark the class as abstract, or
   - provide a 'noSuchMethod' implementation.
  class _SegmentButtonState<T> extends State<_SegmentButton<T>> with RadioClient<T> {
        ^^^^^^^^^^^^^^^^^^^
  ../../../../w/flutter/packages/flutter/lib/src/widgets/radio_group.dart:280:12: Context: 'RadioClient.enabled' is defined here.
    bool get enabled;
             ^^^^^^^
  ../../../../w/flutter/packages/flutter/lib/src/cupertino/sliding_segmented_control.dart:533:7: Error: The non-abstract class '_SlidingSegmentButtonState' is missing implementations for these members:
   - RadioClient.enabled
  Try to either
   - provide an implementation,
   - inherit an implementation from a superclass or mixin,
   - mark the class as abstract, or
   - provide a 'noSuchMethod' implementation.
  class _SlidingSegmentButtonState<T> extends State<_SlidingSegmentButton<T>> with RadioClient<T> {
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  ../../../../w/flutter/packages/flutter/lib/src/widgets/radio_group.dart:280:12: Context: 'RadioClient.enabled' is defined here.
    bool get enabled;
             ^^^^^^^
```
